### PR TITLE
Convert the existing overlays to use `<dialog>` elements (issue 14698) 

### LINKED ISSUE #14698: Use <dialog> element for the document properties modal
It has been recently released in Firefox:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
and it's available in Safari too:
https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please refer to the individual commit messages for additional details.*

### CODE REVIEW

**Comment by calixteman** [comment]
I tested in windows 11 in using high contrast themes (I selected "Dusk") and there is potentially a regression.

In Firefox nightly, in using http://54.241.84.105:8877/4c5d97f84b91cdd/web/viewer.html: 
image

In Firefox nightly, with the builtin viewer:
image

In edge, in using http://54.241.84.105:8877/4c5d97f84b91cdd/web/viewer.html: 
image

@Snuffleupagus, do you think it's an issue on our side or something wrong with dialog itself or something else ?
@MReschenberg, what is the correct way to display this dialog ?

**Comment by Snuffleupagus** [comment]
> do you think it's an issue on our side or something wrong with dialog itself or something else ?

Given that I didn't really change the CSS all that much, and that the regular `prefers-color-scheme: dark` appear to work, I'd be inclined to assume that it's actually a *platform issue* with the `<dialog>` element here.

**Comment by MReschenberg** [comment]
We should be using the version that respects user-set colors (so the non-black and white one, if you're running Dusk theme). If this happens on all dialogs, it is probably a platform bug -- do we have something on file for that in bugzilla?

**Comment by Snuffleupagus** [comment]
> I tested in windows 11 in using high contrast themes (I selected "Dusk") and there is potentially a regression.

While I'm currently on an older Windows version, I can reproduce similar problems with *dark* high contrast themes in basic `<dialog>` examples as well; see e.g. https://css-tricks.com/some-hands-on-with-the-html-dialog-element/

**Comment by timvandermeij** [comment]
Given that this is an upstream issue, should we just continue with this or do we need to await a bugfix upstream?

**Comment by marco-c** [comment]
I think we should await for a fix upstream. The first step would be to file a bug on Bugzilla. @Snuffleupagus could you do that?

**Comment by calixteman** [comment]
I filed a bug upstream yesterday:
https://bugzilla.mozilla.org/show_bug.cgi?id=1761611

**Comment by Snuffleupagus** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1761611 has already been fixed in Firefox Nightly, and the HTML standard was updated accordingly as well, hence that should no longer block this PR as far as I can tell :-)

/botio-linux preview

**Comment by calixteman** [comment]
In using `Night sky` theme, I noticed that the buttons have a yellow border line (like the text) but in the dialog it's purple.
And in opening the viewer in edge and in mouse-hovering the button, I get:
image
The printing UI in firefox (and in settings UI), switches bg to yellow and fg to black on mouse-hover, I wonder if we should do the same for the dialog in pdf.js, just to be consistent.

**Comment by Snuffleupagus** [comment]
> And in opening the viewer in edge and in mouse-hovering the button, I get:

That sounds a lot like issue #14649, which honestly feels unrelated to this PR.

> [...] I wonder if we should do the same for the dialog in pdf.js, just to be consistent.

In this PR, I've purposely tried to *only* convert the existing overlays while not changing e.g. the look of things.
Any future improvements, or re-designs, would seem more appropriate for follow-up work and we'd probably need an actual design-spec to follow here.

**Review by calixteman — APPROVED** [review]
Looks good to me.
Thank you for doing that.

**Pull request merged**
