### PR TITLE
Remove shadow around each pages (fix issue #15836)

### LINKED ISSUE #15836: Scrolling can be really janky with large pdfs
In playing with zooming on the first page of `pdf.pdf` and the Firefox profiler, I discovered that we spend a lot of time in:
```
imgLoader::LoadImage http://localhost:8888/web/images/shadow.png
```
All the blue areas:
image
are just because of this `shadow.png`.

This image is used:
https://github.com/mozilla/pdf.js/blob/826c358b3aefdddac7914c28462f4db5876ba8ca/web/pdf_viewer.css#L68

If I remove the `var` and just inline the border definition,I get:
image

I think we could just use a box shadow or something like that in order to avoid this issue.
At least with the dark background, we could just remove the shadow which is useless (or maybe it's just my eyes):
image
and on a white background, maybe a black or box-shadow would be enough.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Review by Snuffleupagus — COMMENTED** [review]
I believe that you need to update the colour values of this variable for consistency (but *not* the transparency component): https://github.com/mozilla/pdf.js/blob/1ab711e2ac5c2c4b9ae873d9f1e3454df9a9f899/web/viewer.css#L40

Also, please remove this now unnecessary line as well: https://github.com/mozilla/pdf.js/blob/1ab711e2ac5c2c4b9ae873d9f1e3454df9a9f899/gulpfile.js#L989

**Comment by Snuffleupagus** [comment]
We probably need to update the GeckoView viewer as well, since it uses the same values: https://github.com/mozilla/pdf.js/blob/dd96ee1512a933c3ec3bd16a635a8efeef2cb850/web/viewer-geckoview.css#L26

**Comment by timvandermeij** [comment]
I think we need some UI/UX feedback here, but for my feeling at least the background is too dark now in the light theme. I do agree that we might not need the shadow, especially if it's hurting performance, but in that case maybe a slightly better border color/width or background color should be chosen. Sadly I can't really do suggestions for which colors would be "friendlier" to the eye so to say since I don't have the required UI/UX skills.

**Comment by Snuffleupagus** [comment]
> but for my feeling at least the background is too dark now in the light theme.

To me it actually looks fairly OK like that, but there's obviously going to be a fair amount of subjectivity involved in picking a colour value :-)
Not that it necessarily means much here, but the reason that I suggested just using a slightly darker background-color is that in Adobe Reader the light-theme looks like this:
background

> but in that case maybe a slightly better border color/width

The clear advantage of not messing with e.g. the border-width, and just tweak the background-color, is that we don't have to worry about updating lots of `margin` related CSS properties (since that'd be annoying to test/review).

**Comment by timvandermeij** [comment]
I agree that the contrast between the page and the background in Adobe Reader is good; perhaps that means that the current value should indeed be darkened a little. There is definitely subjectivity involved here, but the current value, to me at least, doesn't provide enough contrast between the background and the page. Let's see what a slightly darker color looks like.

**Review by timvandermeij — COMMENTED** [review]
I agree that the contrast between the page and the background in Adobe Reader is good; perhaps that means that the current value should indeed be darkened a little. There is definitely subjectivity involved here, but the current value, to me at least, doesn't provide enough contrast between the background and the page. Let's see what a slightly darker color looks like.

**Comment by Snuffleupagus** [comment]
I do wonder if we could maybe pick a colour value somewhere between the two previews above?
(Based on a quick look, it seems to me that picking a significantly darker body-colour value might require follow-up tweaks to a bunch of other colours as well.)

**Comment by Snuffleupagus** [comment]
Looking at the sidebar, I do think that we perhaps also want to change https://github.com/mozilla/pdf.js/blob/1e3e2defe43e58d59d438386602610854170b0bf/web/viewer.css#L284 into `background-color: rgba(0, 0, 0, 0.05);` instead to avoid it becoming too dark.

---

Anyway, I'm fine with these changes; however it probably makes sense to have @timvandermeij sign-off on this as well given https://github.com/mozilla/pdf.js/pull/15850#pullrequestreview-1222021074.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good to me now. For the dark theme I agree that there is no change, and for the light theme it takes some getting used to, but in general I agree that this is better. Thanks!

**Pull request merged**
