### PR TITLE
only add a scrollbar padding if really needed

### PR DESCRIPTION
**Pull request by nschloe**
Fixes issue #5559.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
I'm sorry to say that this isn't a particularly good solution. This patch causes basically the same issue as I described in https://github.com/mozilla/pdf.js/issues/5559#issuecomment-77150282, but for `page-width`, namely:
> Also, in the standard viewer, using full-width as implemented in that PR would cause a horizontal scrollbar to be displayed.

**Comment by nschloe** [comment]
Hm, too bad. And I don't quite understand: The only thing that's changed here is the `hPadding`, how does this influence the display of a scroll bar? I assumed a scroll bar is shown if
```
this.container.scrollWidth > this.container.clientWidth
```
(the condition in `get isHorizontalScrollbarEnabled()`).

**Comment by Snuffleupagus** [comment]
Please look at the CSS class for the pages: https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.css#L21-L32. Here you can see that there is a border "shadow" added around the pages, which `SCROLLBAR_PADDING` helps account for (it also adds a little bit of vertical separation between the pages and the viewer edges in `page-width` zoom).

With this patch you adjust the width of the page, *excluding* the border, to fit the width of the viewer. Hence there is simply no room for the page border, and the viewer displays the horizontal scrollbar as a result.

Since this won't work for the standard viewer (i.e. the one we use in Firefox), I'm closing this PR.

**Comment by nschloe** [comment]
Aha, so the padding is actually a `BORDERSHADOW_PADDING`? (Renaming the variable would arguably increase the clarity of code here.)

**Pull request closed without merging**
