### PR TITLE
Prevent external links from "replacing" the viewer when it's embedded (bug 976541)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
A tentative patch, that fixes https://bugzilla.mozilla.org/show_bug.cgi?id=976541.

To test this, install the Firefox extension, and visit e.g. http://www.cs.tut.fi/~jkorpela/html/iframe-pdf.html.

### CODE REVIEW

**Comment by timvandermeij** [comment]
While I think that opening links in a new tab/window is always desirable, would it perhaps make more sense to use `target="_parent"` instead as that also prevents the link from being opened in the iframe, yet PDF.js then also behaves like the regular Firefox viewer where the link also opens in the same tab? Of course, when the preference for always opening in a new window/tab is enabled, it should behave like your current patch. What do you think?

**Comment by Snuffleupagus** [comment]
As I said above, this is a tentative patch, and I'm really not sure if it's the best solution :-)
However, since the issue that this patch tries to address is somewhat of an edge-case, I figured I'd just submit a simple patch that builds upon PR #5758 first (instead of adding a bunch of new code).

One issue that I see with `_parent`, besides needing to add more code and another property on the `PDFJS` object, is in the edge-edge case where the viewer is placed in an `iframe` inside another `iframe`.
In cases like these `_blank`, or perhaps `_top` (but that requires more added code), probably makes the most sense.

**Comment by Snuffleupagus** [comment]
When thinking more about this, it seems that the best solution *might* be to just replace `PDFJS.openExternalLinksInNewWindow` with a parameter that allow us to explicitly specify the `target` attribute. E.g. something like this: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:api-externalLinkTarget.

@timvandermeij Would that enable behaviour more in-line with what you were suggesting?

**Comment by timvandermeij** [comment]
That does seem like a better solution to me! It also gives some more freedom for forks to implement custom behavior without having to add hacks for that.

**Pull request closed without merging**
