### PR TITLE
Replace unnecessary `bind(this)` and `var self = this` statements with arrow functions in remaining `src/core/` files

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Smaller diff with https://github.com/mozilla/pdf.js/pull/8357/files?w=1.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/pdf.js/8357)

### CODE REVIEW

**Review by yurydelendik — APPROVED** [review]
Looks good. But I think (as in #8358) we shall start using params destructuring when array is arg, especially for Promise.all, e.g.

```
        var dataPromises = Promise.all([contentStreamPromise, resourcesPromise]); 
        dataPromises.then(([contentStream]) => {
```

(at least for the affected code above)

**Comment by Snuffleupagus** [comment]
Thank you for the review!

Here's an interdiff of the changes, in case that's helpful (since Reviewable didn't want to create one).
```diff
diff --git a/src/core/document.js b/src/core/document.js
index a35a0a75..c338f704 100644
--- a/src/core/document.js
+++ b/src/core/document.js
@@ -256,8 +256,7 @@ var Page = (function PageClosure() {
                                                   this.evaluatorOptions);
 
       var dataPromises = Promise.all([contentStreamPromise, resourcesPromise]);
-      var pageListPromise = dataPromises.then((data) => {
-        var [contentStream] = data;
+      var pageListPromise = dataPromises.then(([contentStream]) => {
         var opList = new OperatorList(intent, handler, this.pageIndex);
 
         handler.send('StartRenderPage', {
@@ -274,9 +273,8 @@ var Page = (function PageClosure() {
       // Fetch the page's annotations and add their operator lists to the
       // page's operator list to render them.
       var annotationsPromise = pdfManager.ensure(this, 'annotations');
-      return Promise.all([pageListPromise, annotationsPromise]).then((data) => {
-        var [pageOpList, annotations] = data;
-
+      return Promise.all([pageListPromise, annotationsPromise]).then(
+          function ([pageOpList, annotations]) {
         if (annotations.length === 0) {
           pageOpList.flush(true);
           return pageOpList;
@@ -317,8 +315,7 @@ var Page = (function PageClosure() {
       ]);
 
       var dataPromises = Promise.all([contentStreamPromise, resourcesPromise]);
-      return dataPromises.then((data) => {
-        var [contentStream] = data;
+      return dataPromises.then(([contentStream]) => {
         var partialEvaluator = new PartialEvaluator(pdfManager, this.xref,
                                                     handler, this.pageIndex,
                                                     this.idFactory,
diff --git a/src/core/obj.js b/src/core/obj.js
index d58bffbe..18d017a6 100644
--- a/src/core/obj.js
+++ b/src/core/obj.js
@@ -441,8 +441,8 @@ var Catalog = (function CatalogClosure() {
 
     getPage: function Catalog_getPage(pageIndex) {
       if (!(pageIndex in this.pagePromises)) {
-        this.pagePromises[pageIndex] = this.getPageDict(pageIndex).then((a) => {
-          var [dict, ref] = a;
+        this.pagePromises[pageIndex] = this.getPageDict(pageIndex).then(
+            ([dict, ref]) => {
           return this.pageFactory.createPage(pageIndex, dict, ref,
                                              this.fontCache,
                                              this.builtInCMapCache);

```

**Comment by yurydelendik** [comment]
Thank you for the patch.

**Comment by timvandermeij** [comment]
Nice work! I didn't really have experience with parameter destructuring, but it looks much shorter and more readable.

**Pull request merged**
