### PR TITLE
[Editing] Disable buttons until the first page is rendered

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Sorry, but I don't understand how this patch actually implements what the commit says (i.e. "Disable buttons until the first page is rendered")?
If you actually want to do this, then I believe that you want to remove https://github.com/mozilla/pdf.js/blob/589f72e32570dba402ea49d9382944a8f0da07a4/web/base_viewer.js#L730-L734 and instead add
```javascript
if (this.#annotationEditorUIManager) {
  // Ensure that the Editor buttons, in the toolbar, are updated.
  this.eventBus.dispatch("annotationeditormodechanged", {
    source: this,
    mode: this.#annotationEditorMode,
  });
}
```
*after* the following line https://github.com/mozilla/pdf.js/blob/589f72e32570dba402ea49d9382944a8f0da07a4/web/base_viewer.js#L818

**Comment by Snuffleupagus** [comment]
I don't believe that you need the changes in the `web/toolbar.js` file now, since the buttons should already be *disabled by default* and you now simply delay their enabling.

**Comment by calixteman** [comment]
Strange...
It works as you expect it in Chrome but not in Firefox (with local server).
I added a
```js
console.log("getViewerConfiguration", document.getElementById("editorFreeText").hasAttribute("disabled"))
```
in `viewer.js::getViewerConfiguration` and in Chrome I get a `true` when I get a `false` in Firefox.

So it isn't the most strange thing here...
I had a pending nightly update, hence I restart Firefox and everything is working fine now, I mean it works as expected.

**Comment by calixteman** [comment]
And I've the same bug again....
`console.log("getViewerConfiguration", document.getElementById("editorFreeText").hasAttribute("disabled"))` is showing a `false` in Firefox.

**Comment by Snuffleupagus** [comment]
Isn't that just the soft- vs hard-reload thing again, i.e. <kbd>F5</kbd> vs <kbd>Ctrl + F5</kbd>?
Hence that shouldn't affect the Firefox built-in viewer, and there's probably a bunch of other HTML-state in the viewer that behaves the same way already (so nothing that we need to special-case here as far as I'm concerned).

**Comment by calixteman** [comment]
Yep it's exactly the issue I hit.

**Review by Snuffleupagus — APPROVED** [review]

**Pull request merged**
