### PR TITLE
Add a helper method to reduce duplication in `StampEditor.#getBitmap`

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Currently we're repeating virtually the same code *four times* when fetching the bitmap-data, which seems unnecessary.

Also, ensure that the `#bitmapPromise` is always `null`ed by moving that into the `StampEditor.#getBitmapDone` method.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
After looking at this code, there's one question that I'm not sure of: In the following code, aren't we nulling `this.#bitmapPromise` too soon?
https://github.com/mozilla/pdf.js/blob/c72cb5436def2d6f2e703447c8b901e92b4dd403/src/display/editor/stamp.js#L168-L177

In other branches in this method we keep the Promise around until the `ImageManager`-instance has returned data, see e.g.
https://github.com/mozilla/pdf.js/blob/c72cb5436def2d6f2e703447c8b901e92b4dd403/src/display/editor/stamp.js#L118-L121

**Comment by calixteman** [comment]
After having a quick look, I think it should be fine to set the nullity in `#getBitmapDone`.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
