### PR TITLE
Fix nodejs core module :  ignore url module for web browser

### PR DESCRIPTION
**Pull request by mgrigis**

### CODE REVIEW

**Comment by timvandermeij** [comment]
Could you elaborate about what this fixes exactly? There is no issue associated with this PR, so it's a bit unclear why this change is necessary. Is something broken now?

**Comment by mgrigis** [comment]
we try to integrate the library in an ember application, and we cannot to this due to the url module dependency (part of core nodejs). The solution was to exclude it  like other nodejs core module.

Maybe it can be done in a different way.

**Comment by mgrigis** [comment]
> Could you elaborate about what this fixes exactly? There is no issue associated with this PR, so it's a bit unclear why this change is necessary. Is something broken now?

we try to integrate the library in an ember application, and we cannot to this due to the url module dependency (part of core nodejs). The solution was to exclude it like other nodejs core module.

Maybe it can be done in a different way.

**Comment by timvandermeij** [comment]
@Snuffleupagus I think this is safe, but I can't fully oversee this. What do you think?

**Comment by Snuffleupagus** [comment]
> @Snuffleupagus I think this is safe, but I can't fully oversee this. What do you think?

Based on https://github.com/mozilla/pdf.js/blob/6763e1680482b4e91d853445dfd3d9c0f82936e9/src/display/node_stream.js#L17-L20 and https://github.com/mozilla/pdf.js/blob/6763e1680482b4e91d853445dfd3d9c0f82936e9/src/display/svg.js#L136 it seems to me that `url` was simply left out of that list; so it looks OK as far as I can tell :-)

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thanks!

**Pull request merged**
