### PR TITLE
Remove empty, top-level, nodes in the Babel plugin

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Looking at the *built* files you'll notice some lines containing nothing more than a semicolon. This is the result of (mostly top-level) `if`-statements, which include `PDFJSDev`-checks, that evalute to `false` during Babel parsing.

This has always annoyed me a bit, and looking at Babel plugin it seems that we can fix this simply by *removing* the relevant nodes.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Hey don't feel blocked on me in any way, but just fyi I plan to review these Babel-related PRs by Monday.

**Review by timvandermeij — APPROVED** [review]
Looks good to me, but let's await @nicolo-ribaudo's review as well before merging this. Thanks!

**Review by nicolo-ribaudo — APPROVED** [review]

**Pull request merged**
