### PR TITLE
Don't map glyphs to certain problematic Thai/Lao Unicode locations (issue 5994)

### LINKED ISSUE #5994: Two Words Not Positioned Correctly in Nastaleeq Font
Link to example PDF: https://drive.google.com/file/d/0B9loCyDBc62ZaXpxVXp0TFBpaEE/view?usp=sharing (Rendered correctly by Google Viewer)
Location in File: Page 347 (but also on other pages with the same two words)
Screenshot: 
Bad:
bad
Good:
good
Browser Version: 37.0.2
Operating system: Ubuntu 14.04 LTS 64-bit
PDF.js version: Test version found here: http://107.21.233.14:8877/5839ed92a0d8a84/web/viewer.html
JavaScript Console Warning/Error Messages: "#thumb_page_title is undefined."
 "#page_scale_percent is undefined." (Don't think these relate)
PDF Creator: LaTex

This Urdu PDF is rendered almost entirely correct, but there are some small defects. The two words circled in red are pushed towards the left in all instances found throughout the PDF. The default Ubuntu PDF reader (Evince - probably other readers too) renders it correctly, and if I print to file there, PDF.js renders it correctly too. However, the resulting PDF is three times as big as the original, so I would like to find the problem. Thanks in advance for any solutions.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
~~_This patch depends on PR #5990._~~

According to https://dxr.mozilla.org/mozilla-central/source/gfx/harfbuzz/src/hb-ot-shape-fallback.cc#38, certain Thai/Lao characters are treated as special by the font shaping code in Firefox.
Further down in that file, https://dxr.mozilla.org/mozilla-central/source/gfx/harfbuzz/src/hb-ot-shape-fallback.cc#216, the vertical position of glyphs is modified, which should thus explain why some glyphs end up in the wrong position in the PDF file.

Fixes #5994.

~~**TODO:** Add a reduced test-case (once I manage to create one that works).~~

### CODE REVIEW

**Comment by timvandermeij** [comment]
Triggering lint because of a temporary Travis failure.

/botio lint

**Comment by Snuffleupagus** [comment]
*Rebased to fix a merge conflict in `.gitignore`, no other code changes were made.*

**Pull request merged**
