### PR TITLE
Update packages and translations 

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Given the upcoming release, and that some of the packages have major updates, I've `diff`ed the output of `gulp mozcentral`, `gulp generic`, and `gulp generic-legacy` to compare the `master`-branch and this patch.
With the exception of lots of white-space changes, primarily fewer newlines in the built-files, nothing looked immediately wrong. Most likely the updated `acorn` package explains the difference here, and this leads to *slightly* smaller files which can't hurt.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
*Please note:* I reverted the Puppeteer update, since that one caused problems and apparently require other changes as well.
I don't know if/when I'll have time to look into this, so someone else is most welcome to do that :-)

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you!

**Pull request merged**
