### PR TITLE
Assign the `quantizationTables` after parsing the entire JPEG image, to prevent issues when the DQT (Define Quantization Tables) marker is encountered after SOF{n} (Start of Frame) markers (issue 7406)

### LINKED ISSUE #7406: Images not rendering due to quantizationTables missing at rendering phase
Link to PDF file (or attach file here):

Configuration:
[broken-image.pdf](https://github.com/mozilla/pdf.js/files/311002/broken-image.pdf)

- Web browser and its version:Chrome 51
- Operating system and its version:OSX 10.10.5
- PDF.js version:1.5.294
- Is an extension:No

Steps to reproduce the problem:
1. Open PDF
2. Observe no images appearing

What is the expected behavior? (add screenshot)
Images appearing (they are appearing in OSX Preview, Adobe Acrobat, Chrome PDFium)

What went wrong? (add screenshot)
This seems related to reading the quantizationTables in the parse function of JpegImage. It looks like the quantizationTables are parsed after they are used which is causing them to be empty. Could this be a matter of rendering order for these tables?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This is a tentative patch that fixes #7406.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Now with a reduced test-case :-)

/botio test

**Comment by Snuffleupagus** [comment]
*The PR was rebased to master, and a comment adjusted, however no functional changes were made.*

**Comment by timvandermeij** [comment]
@yurydelendik Could you review this patch?

**Comment by timvandermeij** [comment]
Thank you!

**Pull request merged**
