### PR TITLE
Fix #selectEditors typo in the AnnotationEditorUIManager.unselectAll method

### PR DESCRIPTION
**Pull request by nmtigor**
…method

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
As mentioned in https://github.com/mozilla/pdf.js/pull/15469#issuecomment-1252092966, this seems like the sort of change that'd benefit from a test-case.

**Comment by calixteman** [comment]
It's a typo... I added the check just in order to avoid to trigger an event:
https://github.com/mozilla/pdf.js/blob/09b54a8c9e36799bb038f4bcf9f7b1ca034c017c/src/display/editor/tools.js#L1008

And it should already been covered by either integration tests in this repo and/or in mochitests in m-c.

**Review by Snuffleupagus — APPROVED** [review]
Thank you!

**Pull request merged**
