### PR TITLE
Testing new windows bot.

### PR DESCRIPTION
**Pull request by brendandahl**
Old bot is on old windows server version that will soon only support firefox 52. This is a new(faster) instance.

### CODE REVIEW

**Comment by brendandahl** [comment]
Open those ports!
/botio-windows-new lint

**Comment by brendandahl** [comment]
And the firewall...
/botio-windows-new lint

**Comment by brendandahl** [comment]
Older version of node:
/botio-windows-new lint

**Comment by brendandahl** [comment]
Note: I copied the references images from the old bot to see some changes.

**Comment by brendandahl** [comment]
Finally! Now let's see if the tests are repeatable.
/botio-windows-new makeref

**Comment by Snuffleupagus** [comment]
The unit-test failure in https://github.com/mozilla/pdf.js/pull/8012#issuecomment-276433872 suggests to me that the bot isn't use the updated PDF file found in PR #7868.

**Comment by brendandahl** [comment]
> The unit-test failure in #8012 (comment) suggests to me that the bot isn't using the updated PDF file found in PR #7868.

Strange, I though I copied the pdfs over from the old bot, but it seems to have re-downloaded them.

**Comment by timvandermeij** [comment]
Nice work on this so far! It definitely appears to be faster.

**Comment by brendandahl** [comment]
The previous test vs the old bot refs should be disregarded. Turns out shelljs has updated the behavior of 'cp' to match real 'cp', it use to previously always do a '-n' option. The pdf-cache has old files, which on the new bot were being copied over the new ones. I've added the '-n' option.

/botio-windows-new test

**Comment by brendandahl** [comment]
New bot is being used by default now. @Snuffleupagus @timvandermeij let me know if you have issues.

**Comment by timvandermeij** [comment]
Thank you for working on this!

**Comment by timvandermeij** [comment]
The Windows bot changes are system font rendering improvements. Overall the glyph rendering is more consistent now and more corresponding to how PDF viewers render the PDFs on e.g., Linux as well.

/botio-windows makeref

**Pull request closed without merging**
