### PR TITLE
Enable the `import/no-cycle` ESLint plugin rule

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Having cyclical imports is obviously not a good idea, and this ESLint plugin rule can help detect those; please see https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@calixteman Do you have any ideas/opinions on how to best break the dependency cycles in the `xfa/`-code, without having to move loads of code?
See https://github.com/mozilla/pdf.js/actions/runs/5155612716/jobs/9285509966?pr=16515#step:6:54

**Comment by calixteman** [comment]
We could move the symbols `$...` used in som.js into a separate file which can be then imported by both files.
Then we can add a flag in both classes XFAObject and XFAObjectArray (e.g. isXfaObject and isXFAObjectArray) to avoid the use of `instanceof` in `som.js`.
And to fix the XmlObject issue, since `createNodes` is not really related to the som stuff we could move it in XFAObject as a method and then in `som.js` replace the use of `createNodes(root, path)` by `root.createNodes(path)`.

**Review by timvandermeij — APPROVED** [review]
Looks good to me, with a rebase. Thanks!

**Pull request merged**
