### PR TITLE
Fix the intermittent integration test failure when an highlight is hovered

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by timvandermeij** [comment]
If it helps, the earliest occurrence I could find of this test failure is https://github.com/mozilla/pdf.js/pull/18698#issuecomment-2336406803, so perhaps that patch introduced a regression (other than #18716)?

**Comment by calixteman** [comment]
@timvandermeij yep I noticed that but as far as I can tell it seems unrelated.
My main problem is that I can't reproduce the bug neither on Ubuntu through WSL2 on Windows 11 nor on Windows 11 and nor on Mac.

**Comment by timvandermeij** [comment]
Closing since this is fixed by #18860 now.

**Pull request closed without merging**
