### PR TITLE
Make the text layer invariant

### PR DESCRIPTION
**Pull request by calixteman**
This way we don't have to update the text layer on rescale.
But rescale it in case of resolution change which should be pretty rare so
in term of performance it's impactless.

### CODE REVIEW

**Comment by calixteman** [comment]
@Snuffleupagus did you have time to have a look on this PR ?
It should improve zooming on the pdf  in #15844.

**Comment by Snuffleupagus** [comment]
> did you have time to have a look on this PR ?

Sorry, I've not found the time yet. From a brief look, I'm finding some of the "refreshTextLayer"-changes throughout the viewer a bit "hacky" and difficult to follow unfortunately.
Also, how relevant would these changes be if your suggestion in https://github.com/mozilla/pdf.js/issues/15844#issuecomment-1355162706 was implemented?

Hopefully I'll have time to review #15812 during the weekend, but I probably won't have time I'll get to this as one well (given its size/scope).

**Comment by calixteman** [comment]
> > did you have time to have a look on this PR ?
> 
> Sorry, I've not found the time yet. From a brief look, I'm finding some of the "refreshTextLayer"-changes throughout the viewer a bit "hacky" and difficult to follow unfortunately. 

The `refreshTextLayer` thing is only triggered by a change of `devicePixelRatio`. If you've some ideas to improve that stuff, they're of course welcomed.

> Also, how relevant would these changes be if your suggestion in [#15844 (comment)](https://github.com/mozilla/pdf.js/issues/15844#issuecomment-1355162706) was implemented?
> 

With this patch we won't have to update the text layer anymore: it'll be really constant (except in the case of the `devicePixelRatio` thing). So it'll take exactly the same time as now to build but the rescaling will be completely handled by the browser.
And the idea about having the measurements in the worker would just help to potentially improve the time spent in the text layer creation. 


> Hopefully I'll have time to review #15812 during the weekend, but I probably won't have time to get to this as one well (given its size/scope).

**Comment by calixteman** [comment]
I've a patch which will be better than this one.

**Pull request closed without merging**
