### PR TITLE
Various clean-up and improvements related to `pdf.sandbox.js` building, and the related default-viewer functionality

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Unfortunately this PR became quite a bit larger than originally anticipated, but as I began looking at all of this code a number of things (also in the viewer) looked strange/inconsistent.

I've tried to split this into a fair number of separate commits, to make reviewing easier, but there's a lot of "moving parts" here. To prevent more PRs landing, creating even more things to clean-up, I'm hoping that this (time permitting of course) can land as soon as possible to improve the overall structure of this code (especially in the viewer).

/cc @timvandermeij Would you possibly have time to review this?

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice work! Quite a big patch indeed, but it's good to have this cleaned up a bit.

**Pull request merged**
