### PR TITLE
Fix invalid `XUID` entries in CFF fonts

### LINKED ISSUE #12399: Some text is not displayed in pdf.js, but display in foxit or chrome viewer
Some text of specified PDF is not displayed in pdf.js, but display in foxit or chrome embeded viewer.
[display_bug.pdf](https://github.com/mozilla/pdf.js/files/5252466/display_bug.pdf)

Configuration:
- Google chrome 85.0.4183.102
- PDF.js 2.6.347

Steps to reproduce the problem:
1. Open attached PDF in pdf.js [web viewer](https://mozilla.github.io/pdf.js/web/viewer.html)

comparison

### PR DESCRIPTION
**Pull request by janpe2**
Fixes #12399

In CFF fonts, entry `XUID` should be an array that has no more than 16 elements. In the issue, the length is 20, which causes the fonts to fail. See Appendix B, "Implementation Limits" in PostScript Language Reference Manual
https://web.archive.org/web/20170218093716/https://www.adobe.com/products/postscript/pdfs/PLRM.pdf

Actually entries `XUID` and `UniqueID` are altogether obsolete.
https://blogs.adobe.com/CCJKType/2016/06/no-more-xuid-arrays.html

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
r=me, with passing tests :-)

Thank you for debugging and fixing this!

**Comment by janpe2** [comment]
What's going on in some Chrome tests on Linux? For example, tests `chrome-tracemonkey-eq-page11` and `chrome-issue7303-page2` have some graphics missing in the reference image and different graphics missing in the test result.
kuva
kuva

**Comment by brendandahl** [comment]
May be new intermittent failures...
/botio-linux test

**Comment by timvandermeij** [comment]
Chrome is all over the place in terms of intermittents unfortunately. I hoped the upgrade to the most recent Chrome (with the upgrade of Puppeteer from one or two days ago) would solve it, but it hasn't improved unfortunately :-(

It's not related to your patch though as it already happened in another PR too, so for this PR we can ignore this. It's tracked in #12123.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you!

/botio makeref

**Pull request merged**
