### PR TITLE
Move `EOF`/`isEOF` from core/parser.js to core/primitives.js

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Given the nature of `EOF` and `isEOF`, it seems to me that they really ought to be placed in `core/primitives.js` instead.

In general, it doesn't seem great to have to depend on the entire `core/parser.js` file for such simple primitives/helper functions.
In particular, while `core/ps_parser.js` is completely separate from `core/parser.js` with regards to its function, it still depends on the latter for just *one* primitive.

Note that compared to e.g. PR #7389, this will not reduce the number of dependencies for `core/ps_parser`, however the new dependency IMHO makes more sense.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
The Windows failures look like fallout from the recent Firefox 53 update on the bots, and https://github.com/mozilla/pdf.js/pull/7898#issue-195941655 ought to explain the changes in the `forms` test cases.

**Comment by timvandermeij** [comment]
Looks good, thanks!

**Pull request merged**
