### PR TITLE
[JS] Use heap allocation when initializing quickjs sandbox

### PR DESCRIPTION
**Pull request by calixteman**
- In case of large string the sandbox initialization failed because of an OOM
    * so allocate a new string in the heap
    * and free it after use.
  - it requires a quickjs update since we need to export some symbols (stringToNewUTF8 and free).

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Do you have an example of a PDF document, that you can share, which triggers this behaviour?

**Comment by calixteman** [comment]
Sure, the pdf attached to this issue:
https://github.com/mozilla/pdf.js/issues/12593
contains a lot of JS and the final string (sent to the sandbox) is around 6Mb.

**Review by Snuffleupagus — APPROVED** [review]
r=me, since sandbox initialization now works in the GENERIC viewer.

**Pull request merged**
