### PR TITLE
Hide the loading bar when closing the viewer

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
It's maybe a fix for:
https://treeherder.mozilla.org/jobs?repo=try&revision=320f861565326918b74226e4a510eafd9288815d&selectedTaskRun=By61aiQRQyqjld2EbYQ4VQ.0

**Comment by Snuffleupagus** [comment]
> It's maybe a fix for: https://treeherder.mozilla.org/jobs?repo=try&revision=320f861565326918b74226e4a510eafd9288815d&selectedTaskRun=By61aiQRQyqjld2EbYQ4VQ.0

Sorry, but I don't understand how this patch could help!?
The test-case mentioned in the logs waits for "documentloaded", [according to this code](https://searchfox.org/mozilla-central/rev/3f193a8bb0759058c2f9a9d7761ad73bc6ffd4b1/dom/security/test/csp/browser_pdfjs_not_subject_to_csp.js#12-25), and that event is dispatched *after* the loadingBar has already been hidden:
https://github.com/mozilla/pdf.js/blob/b58c24ab099c4bd4cefa5139669708227dd9641a/web/app.js#L1224-L1228

**Comment by calixteman** [comment]
Yep correct.

**Pull request closed without merging**
