### PR TITLE
Add localization support for the `annotationLayer` reference tests (issue 10791)

### LINKED ISSUE #10791: Incorporate localization into the reference tests
The annotation reference tests now show the date/time placeholder, but since localization is not active we don't see the actual date/time string. It would be nice to be able to have this in the reference images.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #10791

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Note that I was somewhat surprised by the small size of this patch, and I'd guess that a number of changes/improvements over the years (in both the viewer and test-suite) have made this almost trivial to fix now.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice, this is indeed simpler than I expected it to be before. Thank you for fixing this!

**Pull request merged**
