### PR TITLE
XFA - Improve text layout

### PR DESCRIPTION
**Pull request by calixteman**
- support paragraph margins, line height, letter spacing, ...
  - compute missing dimensions from fields based almost on the dimensions of caption contents.

### CODE REVIEW

**Comment by calixteman** [comment]
It's expected to have a lot of test failures.
Overall, the rendering looks better (there is one exception in an Italian document where some different texts are not correctly vertically aligned: it's a matter of one pixel and I'll investigate that later).

/botio  test

**Review by marco-c — APPROVED** [review]

**Comment by Snuffleupagus** [comment]
This might be a known issue, but looking at e.g. `xfa_bug17176688_3` and comparing with Adobe Reader some of the changes with this patch are improvements and others are regressions.

**Comment by marco-c** [comment]
> This might be a known issue, but looking at e.g. `xfa_bug17176688_3` and comparing with Adobe Reader some of the changes with this patch are improvements and others are regressions.

Most of the changes there looked irrelevant to me, do you have an example of a regression?

**Comment by calixteman** [comment]
I know we've still some issues with line height.

**Comment by Snuffleupagus** [comment]
> Most of the changes there looked irrelevant to me, do you have an example of a regression?

One example: Compare the *bottom* of the first page and the *top* of the second page, in PDF.js and Adobe Reader.

(If necessary I can attach screen-shots later, but based on https://github.com/mozilla/pdf.js/pull/13653#issuecomment-874068427 I guess this is indeed a know issue.)

**Comment by calixteman** [comment]
sadly we had an intermittent failure here...
The message `TEST-UNEXPECTED-FAIL | test failed firefox has not responded in 120s` likely means that firefox crashed, is it correct ?
In comparing logs from the two bots, I've the impress the first test not appearing is `xfa_bug1716980` which could be the one which led to the issue.
Unfortunately I don't manage to reproduce locally.

**Comment by Snuffleupagus** [comment]
> The message `TEST-UNEXPECTED-FAIL | test failed firefox has not responded in 120s` likely means that firefox crashed, is it correct ?

Possibly it *could* also mean that the browser hangs, but I also don't really know :-(

This type of error looks *very* similar, or even identical, to the intermittent ones that made me abandon PR #13649.

> In comparing logs from the two bots, I've the impress the first test not appearing is `xfa_bug1716980` which could be the one which led to the issue.

In the PR mentioned above, initially the failures occurred for another test-case; hence I'm not sure if the problem is with a specific file. However, it seems to me that it's the XFA test-cases which are (intermittently) affected by this. This is pure speculation on my part, but I cannot help wonder if *maybe* there's cases where some of the image resources somehow fail to load (without an error being throw), causing the `resolveImages` helper (in `test/driver.js`) to never resolve!?

> Unfortunately I don't manage to reproduce locally.

Me neither, and I really tried in PR #13649.
I wonder if adding more logging around the `resolveImages`, for the `enableXfa` case, could maybe help?

**Pull request merged**
