### PR TITLE
[Editor] Avoid to focus an existing editor when enabling the layer

### LINKED ISSUE #18911: [Bug]: Page snapping/scrolling issue when activating annotation editor in a pdf with annotations on multiple pages.
### Attach (recommended) or Link to PDF file

[b79facae-9204-424f-879a-dda7724d6c20.pdf](https://github.com/user-attachments/files/17401384/b79facae-9204-424f-879a-dda7724d6c20.pdf)

### Web browser and its version

Mozilla Firefox

### Operating system and its version

Windows 10

### PDF.js version

4.7.76

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached pdf in the demo browser.
2. Activate the annotation editor through the pdf.js toolbar.
3. Begin to scroll to page 2.

### What is the expected behavior?

Scrolling should continue naturally.

### What went wrong?

Instead, as soon as page 2 becomes visible, a cascading effect begins where the viewer rapidly snaps through all of your pages that contain annotations.  In the attached pdf, a minor scroll will take you from page 2 to page 5.

### Link to a viewer

_No response_

### Additional context

This issue only occurs when you have not previously scrolled to the other pages.

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #18911.

### CODE REVIEW

**Comment by calixteman** [comment]
Unfortunately, the puppeteer update brought some Chrome-only new more-or-less intermittent issues... :(

**Review by Snuffleupagus — APPROVED** [review]
r=me, assuming that you're sure that the test failures are unrelated to this patch; thank you.

**Comment by calixteman** [comment]
> r=me, assuming that you're sure that the test failures are unrelated to this patch; thank you.

I thought it was Chrome-only because only CDP was appearing in the backtraces, but in fact the two tests about existing annotations are just failing. I don't why we didn't get an error from the test in Firefox or maybe because the timeout exception for Chrome avoided the one for Firefox.

**Comment by calixteman** [comment]
@Snuffleupagus I made few changes, are you still ok ?

**Review by Snuffleupagus — APPROVED** [review]

**Pull request merged**
