### PR TITLE
Fix glyph at index zero in CIDFontType2 that has a CIDToGIDMap stream

### LINKED ISSUE #10519: Missing letters
Attach (recommended) or Link to PDF file here:
[Dar_smlouva.pdf](https://github.com/mozilla/pdf.js/files/2826984/Dar_smlouva.pdf)
Configuration:
- Web browser and its version: Chrome 71.0.3578.98 64bit (bug appears on IE,Edge and Firefox too)
- Operating system and its version: Windows 10 Pro 1809
- PDF.js version:  master (2.1.237)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open attached file
2. See missing letters

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
Missing letters 'D' (twice) and 'B'
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

### PR DESCRIPTION
**Pull request by janpe2**
Fixes #10519

See the description of the problem in https://github.com/mozilla/pdf.js/issues/10519#issuecomment-488102668

@Snuffleupagus Thank you for the idea (https://github.com/mozilla/pdf.js/issues/10519#issuecomment-488134023) to use `ToUnicode` in deciding when glyph index zero is necessary or not.

I also found out that when the glyph index zero is duplicated, we must set its left sidebearing (LSB) in the `hmtx` table. Currently just zeros are appended as LSB values, which makes the glyph positioned too far to the left. Because of this change in `core/fonts.js` some characters move also in regression test "issue3427". Now the glyphs are actually in correct positions. (See 'C' in the bold font and 'P' in the regular font in "issue3427".)

### CODE REVIEW

**Review by brendandahl — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you!

**Comment by termux-io** [comment]
https://patch-diff.githubusercontent.com/raw/mozilla/pdf.js/pull/10725.patch

**Pull request merged**
