### PR TITLE
prevent viewer from zooming on cmd+mousewheel (bug 1018932)

### PR DESCRIPTION
**Pull request by ghost**
As reported in [bug 1018932](https://bugzilla.mozilla.org/show_bug.cgi?id=1018932), the viewer toolbar resizes with the content when zooming with cmd+mousewheel.

This pull request adds a condition to the mousewheel handler to check if the [metakey](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey) is pressed, in which case toolbar zoom is prevented.

### CODE REVIEW

**Comment by browtayl** [comment]
Please note that this is my first contribution to a Mozilla project, so style or workflow feedback is appreciated.

**Comment by Snuffleupagus** [comment]
@browtayl Please squash the commits, see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits.

**Comment by browtayl** [comment]
@Snuffleupagus squashed.

**Comment by timvandermeij** [comment]
Thank you for the patch!

**Pull request merged**
