### PR TITLE
Correct type for some chars between 0x600 and 0x6ff

### PR DESCRIPTION
**Pull request by adrianheine**

### CODE REVIEW

**Comment by timvandermeij** [comment]
How do we verify this change? Is there a specification for this?

**Comment by timvandermeij** [comment]
The specification for this is here: ftp://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt

@adrianheine It appears that the beginning of the block also contains errors when comparing our code to the specification above. Do you agree?

**Comment by adrianheine** [comment]
I don't know much about this. Since the first items are combining marks, I suppose their directionality doesn't matter too much?

**Comment by adrianheine** [comment]
I updated my commit to fix all 0600–06ff items, but feel free to favor your commit since it fixes all of them.

**Comment by timvandermeij** [comment]
Closing as fixed in #7846. Thank you for bringing this to our attention!

**Pull request closed without merging**
