### PR TITLE
Extend `getGlyphMapForStandardFonts` with additional entries (issue 15977)

### LINKED ISSUE #15977: Wrong glyph is rendered with a missing font
Attach (recommended) or Link to PDF file here:
[01_0000023031_v4(1).pdf](https://github.com/mozilla/pdf.js/files/10534847/01_0000023031_v4.1.pdf)

I found the pdf in https://bugs.ghostscript.com/show_bug.cgi?id=706359

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. Open the pdf and have a look on line 5: the `Ó` is rendered as a `Ï ` (there is a similar issue in the text layer). 

What is the expected behavior? (Acrobat)
image

What went wrong? (Firefox)
image

It's correctly rendered in Chrome.

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

**Comment by calixteman** [comment]
I know I'm a bit stubborn sometimes and I already asked the question (https://github.com/mozilla/pdf.js/pull/15034#discussion_r895469505), but I think we should fill the gaps without waiting for bugs.
Based on the pdf you added in this PR, I created this pdf:
[0000_11C4.pdf](https://github.com/mozilla/pdf.js/files/10536089/0000_11C4.pdf)
with all chars code from 0000 to 11C4.
If the final map is too big we can still save it in a binary format (and even compress it since we have stuff to uncompress data).
I have the impress that Chrome is rendering correctly this file (when I compare to Acrobat).

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by Snuffleupagus** [comment]
> I know I'm a bit stubborn sometimes and I already asked the question ([#15034 (comment)](https://github.com/mozilla/pdf.js/pull/15034#discussion_r895469505)), but I think we should fill the gaps without waiting for bugs.

Maybe, but in that case we probably need to generate the list from a suitable font file since doing that manually doesn't scale beyond a handful of entries at a time.

> Based on the pdf you added in this PR, I created this pdf:
> [0000_11C4.pdf](https://github.com/mozilla/pdf.js/files/10536089/0000_11C4.pdf)

*Just a FYI, if you end up submitting a patch with that file included:* That PDF document is corrupt, so you'd probably want to run it through a suitable tool to fix that. (Unless you want to test PDF corruption, it's always nicer if the document is actually valid.)

> If the final map is too big we can still save it in a binary format (and even compress it since we have stuff to uncompress data).
> I have the impress that Chrome is rendering correctly this file (when I compare to Acrobat).

I don't think the size will be that much of a problem, and note it's already being *lazily* initialized, so I'd suggest that we don't increase the complexity here.

**Pull request merged**
