### PR TITLE
Convert examples/text-only/pdf2svg.js to await/async 

### PR DESCRIPTION
**Pull request by adenicole**
This is my first pull request.

### CODE REVIEW

**Review by calixteman — CHANGES_REQUESTED** [review]
You're adding the function `pageLoaded` but it isn't called anywhere so it's useless.

**Comment by calixteman** [comment]
> > You're adding the function `pageLoaded` but it isn't called anywhere so it's useless.
> 
> Isn't the problem actually that the patch adds a _new_ function, rather than simply replacing the old one (as intended)?
> 

Oh! I've been confused because of the github UI.

> Furthermore, was this successfully tested locally? There's also a number of linting failures, please remember to run `gulp lint` and fix all the reported problems. Finally, please squash the commits; see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
As mentioned in https://github.com/mozilla/pdf.js/pull/14141#issuecomment-943489131:
 - Please confirm that you've successfully tested this locally.
 - Please squash the commits, since we don't allow either fixup (or merge) commits to land; see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits

**Comment by Snuffleupagus** [comment]
The *second* sentence of the commit message, or at least the "and corrected lint errors"-part, doesn't seem appropriate here since it suggests that there were lint errors in the old code which isn't actually the case.

**Comment by adenicole** [comment]
> The _second_ sentence of the commit message, or at least the "and corrected lint errors"-part, doesn't seem appropriate here since it suggests that there were lint errors in the old code which isn't actually the case.

Oh, my bad! Fixed the commit message. 🙂

**Review by Snuffleupagus — APPROVED** [review]
*For future reference:* As outlined in https://github.com/mozilla/pdf.js/wiki/Contributing, you want to use feature branches rather than working directly against the "master" branch (since that makes working on more than thing at a time really difficult and causes e.g. rebasing to become more difficult).

r=me, thank you.

**Pull request merged**
