### PR TITLE
Prevent errors in `AnnotationEditorUIManager.destroy` if the `altTextManager` is undefined

### PR DESCRIPTION
**Pull request by pulsejet**
Fixes a crash when loading a document in PDFSlick

### CODE REVIEW

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
I've tweaked the PR title to be slightly more specific about the change made in the patch, so can you please update the *commit message* accordingly?

**Comment by pulsejet** [comment]
Done

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Pull request merged**
