### PR TITLE
Attempt to combine text runs positioned with `setTextMatrix`

### LINKED ISSUE #4626: Poor performance on a pdf document
This PDF document:
http://lex-2008.github.io/pdf.js/print.pdf
has poor performance when scrolling.

as @chriskr noticed, this is probably related to text layer. Setting
````
.textLayer {display: none;}
````
increases performance.

To reproduce the issue:
1. Open attached document
2. Scroll it to the bottom
Pass if scrolling performance is acceptable.

The file in question is a pdf printout of a http://habrahabr.ru/post/160035/ page, sent to me by a friend. Not sure how it was generated.

### LINKED ISSUE #6962: Letters getting rendered each in their own <div> tags, which slows down rendering
Files from the EDGAR SEC database seem to result in each letter rendered in its own `<div>` tag, which can make the rendering and responsiveness of the front end slow, and also makes the copy paste results unusable.

Example PDF is attached here:
[EXXI_-_Credit_Agreement_w_Amends_1-9_and_Waiver.pdf](https://github.com/mozilla/pdf.js/files/122238/EXXI_-_Credit_Agreement_w_Amends_1-9_and_Waiver.pdf)

Screenshot:
https://www.evernote.com/l/AApmrxRAYp5BaYELMMHikzDhSqRylAKK1QQ

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #6962. 
Fixes #4626.
... and probably more issues/bugs, but those are the ones that I managed to find quickly.

### CODE REVIEW

**Comment by yurydelendik** [comment]
Looks good (Land if testing will pass or be better).

/botio test

**Comment by timvandermeij** [comment]
Awesome work! This patch also greatly improves scrolling performance for the mentioned PDFs.

**Pull request merged**
