### PR TITLE
[api-minor] Always allow e.g. rendering to continue even if there are errors, and add a `stopAtErrors` parameter to `getDocument` to opt-out of this behaviour (issue 6342, issue 3795, bug 1130815)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Other PDF readers, e.g. Adobe Reader and PDFium (in Chrome), will attempt to render as much of a page as possible even if there are errors present.
Currently we just bail as soon the first error is hit, which means that we'll usually not render anything in these cases and just display a blank page instead.

*NOTE:* This patch changes the default behaviour of the PDF.js API to always attempt to recover as much data as possible, even when encountering errors during e.g. `getOperatorList`/`getTextContent`, which thus improve our handling of corrupt PDF files and allow the default viewer to handle errors slightly more gracefully.
In the event that an API consumer wishes to use the old behaviour, where we stop parsing as soon as an error is encountered, the `stopAtErrors` parameter can be set at `getDocument`.

Fixes, inasmuch it's possible since the PDF files are corrupt, e.g. issue #6342, issue #3795, and [bug 1130815](https://bugzilla.mozilla.org/show_bug.cgi?id=1130815) (and probably others too).

*Note:* Slightly smaller diff with https://github.com/mozilla/pdf.js/pull/8240/files?w=1.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/pdf.js/8240)

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
*Updated to fix a merge conflict in `test/pdfs/.gitignore`, no actual code changes were made.*

**Review by yurydelendik — APPROVED** [review]
Looks good. Logic around clone of PartialEvaluator looks complicated though. Any future refactoring there will be nice to have.

**Pull request merged**
