### PR TITLE
Enable the `no-empty-pattern`/`no-floating-decimal`/`no-self-compare`/`no-delete-var`/`no-new-object` ESLint rules

### PR DESCRIPTION
**Pull request by Snuffleupagus**
The following rules required no code changes:
http://eslint.org/docs/rules/no-empty-pattern
http://eslint.org/docs/rules/no-floating-decimal
http://eslint.org/docs/rules/no-delete-var
http://eslint.org/docs/rules/no-new-object

There was just one change needed in order to enable:
http://eslint.org/docs/rules/no-self-compare; which I think helps readability a lot, since that comparison makes no sense until you realize that we push `NaN` onto the `stack` in some cases *and* furthermore that `NaN !== NaN`.

### CODE REVIEW

**Review by yurydelendik — APPROVED** [review]

**Comment by yurydelendik** [comment]
Thank you for the patch

**Comment by timvandermeij** [comment]
Thank you! I agree that that comparison made no sense at all to me until you explained it, so I'm glad this change was made.

**Comment by timvandermeij** [comment]
Question: where does `isNaN` actually come from? Shouldn't it have been imported?

**Comment by Snuffleupagus** [comment]
> Question: where does isNaN actually come from? Shouldn't it have been imported?

That's a function that's built-in to all browsers, so no need to import anything; also see e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN.

**Comment by yurydelendik** [comment]
or http://www.ecma-international.org/ecma-262/5.1/#sec-15.1.2.4

**Comment by timvandermeij** [comment]
You're right. I was confused because we also have `isInt` and similar functions that we implement ourselves as utility functions. Sorry for the noise.

**Pull request merged**
