### PR TITLE
Extract correct PDF format version from the catalog

### PR DESCRIPTION
**Pull request by mcorb**
The 'Version' field of the most recent document catalog, if present, is
intended to supersede the value in the file prologue.

This is significant for incrementally-built PDF documents and generators that
emit a low version in the prologue and later apply a format version based on
PDF features used, such as Apple's CoreGraphics/Quartz PDF backend.

Fixes the internal version variable, as well as the PDFFormatVersion reported
by the API and consumed by viewers.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Could you squash the commits into one commit (see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits)? Also, do you have an example of such a PDF file?

**Comment by mcorb** [comment]
Fix and test case are now squashed into one commit and rebased.

**Comment by yurydelendik** [comment]
Thank you for the patch.

**Pull request merged**
