### PR TITLE
Support parsing encrypted documents in `XRef.indexObjects` (issue 15893)

### LINKED ISSUE #15893: Password protected PDF file seems blank
Configuration:
- Mozilla Firefox 108.1 from PPA
- Ubuntu 22.04.1
- PDF.js version: I don't know
- Is a browser extension: No

Steps to reproduce the problem:
1. Download (removed) file.
2. Try to open with Firefox

What is the expected behavior?  Show the password protected file.
What went wrong? Showed two blank pages without any indication about the password protection.

I have tested with some application:
- Chrome: Requested pasword and viewed the file mean OK.
- KOReader: OK.
- Ongoogled Chromium: OK.
- Sioyek: OK.
- Master PDF Editor: OK.
- Firefox: Failed.
- Okular: Failed.
- LibreOffice: Failed.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please note:* The reduced test-case is *not* a perfect reproduction of the original PDF document, since this one fails to open in e.g. Adobe Reader, but I do believe that it captures the most important points here.

For corrupt *and* encrypted PDF documents, it's possible that only some trailer dictionaries actually contain an /Encrypt-entry. Previously we'd could easily miss that, since we generally pick the first not obviously corrupt trailer dictionary, and the solution implemented here is to simply pre-parse all trailer dictionaries to see if there's any /Encrypt-entries.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@calixteman Review ping, since I managed to come up with a reduced test-case that mostly captures the details of the original document.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you for the test case.

**Pull request merged**
