### PR TITLE
Remove the superfluous `PDFJS.disableFontFace = false;` statement at the top of font_loader.js (issue 6742)

### LINKED ISSUE #6742: PDFJS.disableFontFace value is overwritten by font loader without any mercy
In the [font_loader.js](https://github.com/mozilla/pdf.js/blob/master/src/display/font_loader.js#L20) the PDFJS.disableFontFace is set to false. This overrides the work done in [api.js](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L53) and makes it problematic for a user of PDF.js to decide this value for himself.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #6742.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Looks good to me, though I also really wonder why it was there in the first place if it is an API option...

**Comment by Snuffleupagus** [comment]
> Looks good to me, though I also really wonder why it was there in the first place if it is an API option...

Probably for "historical reasons", please see https://github.com/mozilla/pdf.js/issues/6742#issuecomment-163922610 for some background.

**Comment by yurydelendik** [comment]
Thank you

**Pull request merged**
