### PR TITLE
Create absolute filter-URLs when needed in `DOMFilterFactory` (issue 18406)

### LINKED ISSUE #18406: [Bug]: Adding a `<base href>` tag to a page containing a pdfjs viewer breaks transparancy filters in Firefox.
### Attach (recommended) or Link to PDF file

https://github.com/mozilla/pdf.js/files/11229069/test.pdf

### Web browser and its version

Firefox 127.0.2

### Operating system and its version

Mac and Windows

### PDF.js version

4.5 (master)

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

0. Running local copy of pdfjs using `npx gulp server`
1. Add `<base href="." />` to `viewer.html`
2. Open test.pdf

### What is the expected behavior?

The PDF should render the same regardless of `<base href>`

image

### What went wrong?

When rendering a pdf in Firefox when a `<base href>` is defined the drop shadow is not rendered correctly.

image

### Link to a viewer

_No response_

### Additional context

This issue was discovered and discussed here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2363

We tested accross multiple browsers, OSs, sites, and PDFs.  The issue was eventually narrowed down to pdfjs v4.3-v4.5 in Firefox when the site defines a `<base href>`.  Many SPAs require a base href to be defined.  This issue was not seen in other browsers nor in pdfjs v.4.2.  It was seen in Firefox regardless of OS.

Additional note: Relatively certain this issue is SVG IRI references in `display_utils.js`.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This functionality is purposely limited to development mode and GENERIC builds, since it's unnecessary in e.g. the *built-in* Firefox PDF Viewer, and will only be used when a `<base>`-element is actually present.

*Please note:* We also have tests in mozilla-central that will *indirectly* ensure that relative filter-URLs work as intended in the Firefox PDF Viewer, see https://searchfox.org/mozilla-central/source/toolkit/components/pdfjs/test/browser_pdfjs_filters.js

---

To test that the issue is fixed, the following code can be used:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <base href=".">
  <title>base href (issue 18406)</title>
</head>
<body>

<ul>
  <li>Place this code in a file, named `base_href.html`, in the root of the PDF.js repository</li>
  <li>Run <pre>npx gulp dist-install</pre></li>
  <li>Run <pre>npx gulp server</pre></li>
  <li>Open <a href="http://localhost:8888/base_href.html">http://localhost:8888/base_href.html</a> in a browser</li>
  <li>Compare rendering with <a href="http://localhost:8888/web/viewer.html?file=/test/pdfs/issue16287.pdf">http://localhost:8888/web/viewer.html?file=/test/pdfs/issue16287.pdf</a></li>
</ul>

<canvas id="the-canvas" style="border: 1px solid black; direction: ltr;"></canvas>

<script src="/node_modules/pdfjs-dist/build/pdf.mjs" type="module"></script>

<script id="script" type="module">
  //
  // If absolute URL from the remote server is provided, configure the CORS
  // header on that server.
  //
  const url = '/test/pdfs/issue16287.pdf';

  //
  // The workerSrc property shall be specified.
  //
  pdfjsLib.GlobalWorkerOptions.workerSrc =
    '/node_modules/pdfjs-dist/build/pdf.worker.mjs';

  //
  // Asynchronous download PDF
  //
  const loadingTask = pdfjsLib.getDocument(url);
  const pdf = await loadingTask.promise;
  //
  // Fetch the first page
  //
  const page = await pdf.getPage(1);
  const scale = 1.5;
  const viewport = page.getViewport({ scale });
  // Support HiDPI-screens.
  const outputScale = window.devicePixelRatio || 1;

  //
  // Prepare canvas using PDF page dimensions
  //
  const canvas = document.getElementById("the-canvas");
  const context = canvas.getContext("2d");

  canvas.width = Math.floor(viewport.width * outputScale);
  canvas.height = Math.floor(viewport.height * outputScale);
  canvas.style.width = Math.floor(viewport.width) + "px";
  canvas.style.height = Math.floor(viewport.height) + "px";

  const transform = outputScale !== 1
    ? [outputScale, 0, 0, outputScale, 0, 0]
    : null;

  //
  // Render PDF page into canvas context
  //
  const renderContext = {
    canvasContext: context,
    transform,
    viewport,
  };
  page.render(renderContext);
</script>

</body>
</html>
```

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@calixteman How do you feel about this, do you think this is something that we should support?

**Comment by calixteman** [comment]
From an api pov, I think it isn't that bad to try to be environment agnostic: it makes the pdfjs integration easier especially in such a case it's very uneasy to make the link between a rendering issue and the presence of `<base>`.
That said, I'd prefer having a test here or at least we should have a very basic html file (attached to the original bug) to reproduce the issue in order to have something to manually test if someone wants to touch this part of the code.
I think I already wrote something about that in the past, but I think we should have a kind of mix of integration and reference test: we could load a html in an integration test, get an image either from a canvas or from a screenshot and compare it with a reference.

**Comment by Snuffleupagus** [comment]
> That said, I'd prefer having a test here or at least we should have a very basic html file (attached to the original bug) to reproduce the issue in order to have something to manually test if someone wants to touch this part of the code.

I've create a basic standalone test-case, please see https://github.com/mozilla/pdf.js/pull/18417#issue-2400068998.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
