### PR TITLE
A couple of improvements of `getDestination` (unit-test included)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
_Please refer to the individual commit messages._

### CODE REVIEW

**Comment by timvandermeij** [comment]
Do you happen to have one or more PDF files that can be used for testing this? It looks good, but especially the second commit would be good to test with a file that has named destinations in a Dict.

**Comment by Snuffleupagus** [comment]
> Do you happen to have one or more PDF files that can be used for testing this? It looks good, but especially the second commit would be good to test with a file that has named destinations in a Dict.

Apart from `basicapi.pdf`, which is already covered by existing (and added) tests, there's e.g. `hmm.pdf`.

**Comment by timvandermeij** [comment]
Nice work, thank you!

**Pull request merged**
