### PR TITLE
XFA - Create a new page in case of overflow

### LINKED ISSUE #14071: XFA - Overflow is not rendered on the next page
Attach (recommended) or Link to PDF file here:
https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/eimm5669e.pdf
[eimm5669e.pdf](https://github.com/mozilla/pdf.js/files/7225677/eimm5669e.2.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Linux Debian

Steps to reproduce the problem:
1. Look at the bottom of page 2

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix #14071;
  - a subform is overflowing and the the target in case of overflow is itself. In this case we must create a new page.

### CODE REVIEW

**Comment by marco-c** [comment]
The contents of the "Badge details" section disappeared in `firefox-xfa_bug1717668_2-page1`.

**Comment by calixteman** [comment]
> The contents of the "Badge details" section disappeared in `firefox-xfa_bug1717668_2-page1`.

Yeah I checked locally and before the patch this stuff was duplicated on page 1 and 2. With the patch it's only on page 2.
Anyway this stuff should appear/disappear thanks to some JS actions so it's pretty impossible to know what it's really correct here.

**Pull request merged**
