### PR TITLE
[Editor] Simplify the strings for the tools in the UI

### LINKED ISSUE #15216: Area to set line thickness is not large enough
In Firefox nightly (french version):
image

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
How wide can these containers potentially become, for the locale with the *longest* l10n strings?
Because if it *significantly more* than the intended width, i.e. `220 px`, then we probably need to implement wrapping of these toolbar-elements (similar to e.g. secondaryToolbar).

**Comment by calixteman** [comment]
I think we just remove the first word: "Line" or "Font", they're a bit redundant with what the tool is supposed to do.
Or we could have something like:

| Line thickness...................................|
|    -o-----------------------------.|
| ...............................................................|
| Line color...........................................|
...

**Comment by Snuffleupagus** [comment]
> I think we just remove the first word: "Line" or "Font", they're a bit redundant with what the tool is supposed to do.

I really like that idea!

**Pull request merged**
