### PR TITLE
[api-major] Remove the `enhanceTextSelection` functionality (PR 15145 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
For the `gulp mozcentral` command, this reduces the size of the *built* `pdf.js` file by `> 10` kB.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
*Please note:* I'm assuming that we're *not* planning on any more releases from the `2`-branch, since otherwise we probably need to hold off on landing this.

**Comment by timvandermeij** [comment]
I was thinking to do one final 2.x release, mainly to incorporate the CSS fixes that somewhat "broke" in the current release. That way we provide users with that fix without requiring them to also upgrade to a new major version. After the release we can then merge the `[api-major]` patches. Is that OK?

**Comment by Snuffleupagus** [comment]
> I was thinking to do one final 2.x release in a few days, mainly to incorporate the editor CSS fix that somewhat "broke" in the current release. That way we provide users with that fix without requiring them to also upgrade to a new major version.

That sounds like a good idea to me!

> Once that release is done we can merge the `[api-major]` patches and release PDF.js 3.0. Is that OK?

That sounds perfect :-)
However we might want to wait with releasing version `3` until editing is enabled *by default*, since it got pushed to Firefox 106 (see e.g. [bug 1784272](https://bugzilla.mozilla.org/show_bug.cgi?id=1784272) and [bug 1785248](https://bugzilla.mozilla.org/show_bug.cgi?id=1785248)), so that we have a "significant" new feature in the version `3` release!?

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for working on this!

**Pull request merged**
