### PR TITLE
Add SehyunPark to AUTHORS

### PR DESCRIPTION
**Pull request by SehyunPark**
Add SehyunPark to AUTHORS

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
"Update AUTHORS" isn't a great commit message, a better one would probably be e.g. "Add SehyunPark to AUTHORS".

**Comment by SehyunPark** [comment]
edited! :) Thank you

**Comment by Snuffleupagus** [comment]
What you edited is *only* the PR title, the *commit message* itself should be updated as well.
Please avoid using the GitHub web interface, and follow https://github.com/mozilla/pdf.js/wiki/Contributing instead.

**Comment by SehyunPark** [comment]
Ok, thanks for the kind explanation
Closed and I'll do this through linux.

**Pull request closed without merging**
