### PR TITLE
[api-minor] Don't render highlight/underline/squiggly/strikeout annotations that doesn't have popup

### LINKED ISSUE #6838: Text selection and pointer cursor for annotations without Popup annotation
*Originally reported by @xlc*

The file at https://drive.google.com/uc?export=download&id=0B6YhVF9p-y2AMmlnaURWSjZKNlk has annotations with no associated Popup annotations, so displaying a pointer cursor is not useful. Text selection on the div is also not possible.

### PR DESCRIPTION
**Pull request by xlc**
Fixes #6838

### CODE REVIEW

**Comment by timvandermeij** [comment]
Thank you! Let's do this for now, but there is an underlying issue that I would like to fix, for which I will open separate issues.

**Comment by Snuffleupagus** [comment]
Given that PR #6780 added support for annotation regression testing, it would have been a very good idea to include a test-case in this PR.
So, can someone please create a follow-up that adds a test-case for this!?

**Pull request merged**
