### PR TITLE
[editor] Disable editing while PresentationMode is active

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
> Might not be too bad to support it (e.g. if you're doing a presentation and you want to highlight some area of the presentation), but definitely requires a better UX.

Given that we *purposely* don't have any toolbars (or other UI) visible in PresentationMode, there'd be no way to e.g. change any of the editing-parameters without leaving PresentationMode first.
Furthermore, considering how PresentationMode is implemented there's bound to be a number of assumptions (in both the JS and CSS code) that basically depends on it being a *very simple* mode without e.g. any toolbars. Changing that would probably not be entirely simple, since there's going to be lots of edge-cases, which is why I think this patch makes sense here.

**Comment by marco-c** [comment]
Oh yes, it makes perfect sense to disable it for now. Mine was just an idea for a future feature :)

**Comment by Snuffleupagus** [comment]
Note that there's also the "browser fullscreen"-mode, which can be toggled with <kbd>F11</kbd> (at least on Windows), that allows the regular PDF.js viewer (or any web-page really) to occupy the *entire* screen.

**Review by calixteman — APPROVED** [review]
LGTM.

**Pull request merged**
