### PR TITLE
Clean up npm dependencies and add `license` property

### PR DESCRIPTION
**Pull request by TimothyGu**
underscore and moment were not used anywhere

### CODE REVIEW

**Comment by timvandermeij** [comment]
Looks good, but we need to revert the change here regarding ShellJS. It was put specifically on the current version because of https://github.com/mozilla/pdf.js/pull/5912#issuecomment-103101024.

**Comment by TimothyGu** [comment]
@timvandermeij, just to make sure, does the commit mentioned in that comment (arturadib/shelljs#207) actually affect us? If it does, I'll revert to 0.4.0. If not, #6030 is TBH unnecessary since ShellJS breaking changes get a minor bump, and npm doesn't consider minor bumps valid for `~` operator. (In other words, `0.5.0` would never be installed to match `~0.4.0`.)

**Comment by timvandermeij** [comment]
I tihnkl not, but let's ask @yurydelendik for his opinion.

**Comment by TimothyGu** [comment]
@yurydelendik ping

**Comment by timvandermeij** [comment]
@yurydelendik is currently on vacation, but to make landing this patch easier I propose to keep just the moment/underscore removal and the license change. Let's not fiddle with the package versions too much for now as we need to carefully verify that no problems occur with that, which can be done in a follow-up PR.

**Comment by yurydelendik** [comment]
looks good (if we don't break any build functionality -- please rebase and test using botio's preview).

**Comment by existentialism** [comment]
It may be worth updating to the release version of jsdoc 3.3.3 as well.

**Comment by yurydelendik** [comment]
@existentialism sure, but it's out of scope of this PR

**Comment by yurydelendik** [comment]
Merged by c27d3125bfc55bc4695c1e873db2f88c2804a2b4

Thank you for the patch.

**Pull request closed without merging**
