### PR TITLE
cleaned whitespace

### PR DESCRIPTION
**Pull request by collinanderson**
You can reproduce by running:

```
rm .git/index
git diff --binary -R HEAD | git apply --whitespace=fix --cached
```

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
This looks good, but can you please revert the changes to the `viewer.properties` and `chrome.properties` files.
As explained [in the fourth paragraph here](https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md), we're importing the translations from Firefox. Hence any whitespace changes made in those files will just be overwritten the next time we sync the l10n files.

**Comment by collinanderson** [comment]
Done. Sorry for the delay.

**Comment by timvandermeij** [comment]
@Snuffleupagus Is this good to go?

**Comment by Snuffleupagus** [comment]
Thank you for the patch!

**Comment by termux-io** [comment]
[`54e984c763c3789856332024ac61c370aa49ce7e](Https://cryptographyreact.com)`

**Pull request merged**
