### PR TITLE
Add a supplemental glyph map for non-embedded ArialBlack fonts (issue 5801)

### LINKED ISSUE #5801: Font decoding issues
I'm experiencing some font-related issues. National (polish) characters are not being rendered correctly in the linked file.

Link to the PDF: http://www.planywb.po.opole.pl/index2.php?f=g9451.pdf
Location in the PDF: Whole file
Screenshot: Screenshot
Browser version: Firefox 36.0.1
Operating system: Windows 8.1 64-bit
PDF.js version: 1.0.1149
JavaScript console warning/error messages: none

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This should, hopefully, finally fix #5801.

### CODE REVIEW

**Comment by brendandahl** [comment]
Hmmm...the windows bot seems to have crashed and restarted.  I'll have to look into this tomorrow.

**Comment by timvandermeij** [comment]
Thanks!

**Pull request merged**
