### PR TITLE
Map missing glyphs to the notdef glyph for TrueType (3, 1) fonts (issue 6068)

### LINKED ISSUE #6068: Embedded font displays as gibberish
I have made a document using Scribus 1.5.0svn with only the text "Arial Regular" in it, which has the Arial Regular font. I have made sure that it is embedded when exporting the PDF. While it is fine in Adobe Acrobat, it appears as gibberish in PDF.js using Windows 7 x64 and Firefox 38.0.1.

Here the comparison, with PDF.js on the left and Adobe Acrobat on the right:

naamloos

A minimal testcase (download an rename .png to .pdf):

testcase

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #6068.

The most notable issue with the font in question is that the `differences` array contains lots of strange entries (of the type `uniXXXX`, instead of proper glyph names).

### CODE REVIEW

**Comment by timvandermeij** [comment]
This fixes the issues I had with that file. Thank you for the quick turnaround on this!

**Comment by timvandermeij** [comment]
@brendandahl Good to go?

**Comment by Snuffleupagus** [comment]
This patch also, partially, fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1132849.
With this patch, the right glyphs are now rendered. *However*, compared to Adobe Reader, they still don't look entirely correct:

Some quick bisecting suggests that the "look" of the glyphs were *much* closer to the rendering of Adobe Reader, obviously ignoring the fact that we didn't render the correct glyphs, prior to PR #4259 and more specifically commit https://github.com/mozilla/pdf.js/commit/b5b94a4af389ef387570cf22662d9fc6bd41417a.

**Comment by brendandahl** [comment]
r+

**Comment by Snuffleupagus** [comment]
Thanks for the review!

/botio makeref

**Pull request merged**
