### PR TITLE
Apply padding on <select>, not the button

### PR DESCRIPTION
**Pull request by TimothyGu**
Fixes clicking the edge of the zoom selection dropdown button.

### CODE REVIEW

**Comment by timvandermeij** [comment]
The dropdown is now too close to the loading bar. Maybe it's because the top padding is increased?

After you have adjusted that, could you squash the commits into one? See https://github.com/mozilla/pdf.js/wiki/Squashing-Commits on how to do that easily.

**Comment by TimothyGu** [comment]
> The dropdown is now too close to the loading bar. Maybe it's because the top padding is increased?

This is an intentional change. IMO it looks really odd to have the +/- buttons fairly big and centered vertically, then have the dropdown right next to it not aligned with the buttons:

image

> After you have adjusted that, could you squash the commits into one?

Absolutely. I intentionally used separate commits since they technically are separate changes.

**Comment by Snuffleupagus** [comment]
> This is an intentional change. IMO it looks really odd to have the +/- buttons fairly big and centered vertically, then have the dropdown right next to it not aligned with the buttons:

As @timvandermeij alluded to above, this PR unfortunately "breaks" in Firefox.
Given that the primary use-case for the default viewer is to be the UI for the built-in PDF viewer in Firefox, we cannot accept a PR that regresses Firefox (even if it would happen to fix something in other browsers). This is what the latest version of this PR looks like in Firefox 41:
broken_zoom

**Comment by TimothyGu** [comment]
@Snuffleupagus I totally understand. However I cannot reproduce your issue locally on Firefox 38.0 as bundled with Ubuntu. Testing Windows right now.

But regardless I reverted the controversial padding change so it should be as it was.

**Comment by TimothyGu** [comment]
Ping; any further comments?

**Comment by timvandermeij** [comment]
Thank you for the patch!

**Pull request merged**
