### PR TITLE
Prevent the `debugger` from breaking on unbalanced save/restore OPS (issue 15767)

### LINKED ISSUE #15767: A pdf is correctly rendered but the debugger is broken
Attach (recommended) or Link to PDF file here:
https://gitlab.freedesktop.org/poppler/poppler/uploads/104f83e831aab40e4c8e60158f44149c/test.pdf

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

I get the following exception:
```
Uncaught (in promise) RangeError: repeat count must be non-negative
    updateOperatorList resource://pdf.js/web/debugger.js:370
    operatorListChanged resource://pdf.js/build/pdf.js:2698
    _renderPageChunk resource://pdf.js/build/pdf.js:1657
    pump resource://pdf.js/build/pdf.js:1689
    promise callback*pump resource://pdf.js/build/pdf.js:1678
    _pumpOperatorList resource://pdf.js/build/pdf.js:1712
    render resource://pdf.js/build/pdf.js:1445
    paintOnCanvas resource://pdf.js/web/viewer.js:10371
    draw resource://pdf.js/web/viewer.js:10235
    renderView resource://pdf.js/web/viewer.js:6609
    forceRendering resource://pdf.js/web/viewer.js:8950
    promise callback*forceRendering resource://pdf.js/web/viewer.js:8949
    renderHighestPriority resource://pdf.js/web/viewer.js:6539
    update resource://pdf.js/web/viewer.js:8812
    webViewerScaleChanging resource://pdf.js/web/viewer.js:2943
    dispatch resource://pdf.js/web/viewer.js:3376
    _setScaleUpdatePages resource://pdf.js/web/viewer.js:8607
    _setScale resource://pdf.js/web/viewer.js:8664
    set currentScaleValue resource://pdf.js/web/viewer.js:8164
    setInitialView resource://pdf.js/web/viewer.js:2406
    load resource://pdf.js/web/viewer.js:2076
    promise callback*__webpack_modules__</load/< resource://pdf.js/web/viewer.js:2042
    promise callback*load resource://pdf.js/web/viewer.js:2039
    open resource://pdf.js/web/viewer.js:1860
    promise callback*open resource://pdf.js/web/viewer.js:1859
    onOpenWithTransport resource://pdf.js/web/viewer.js:1707
    windowMessage resource://pdf.js/web/viewer.js:12021
    initPassiveLoading resource://pdf.js/web/viewer.js:12005
    initPassiveLoading resource://pdf.js/web/viewer.js:1705
    webViewerInitialized resource://pdf.js/web/viewer.js:2689
    promise callback*run resource://pdf.js/web/viewer.js:1650
    webViewerLoad resource://pdf.js/web/viewer.js:12651
    EventListener.handleEvent* resource://pdf.js/web/viewer.js:12657
    <anonymous> resource://pdf.js/web/viewer.js:12659
    <anonymous> resource://pdf.js/web/viewer.js:12661
```

The pdf itself is broken: it doens't render in neither Evince nor Acrobat.

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

**Comment by calixteman** [comment]
How to test the debugger in the above viewer ?

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by Snuffleupagus** [comment]
Also, to access the debugging tools in the Firefox PDF Viewer there's the `pdfjs.pdfBugEnabled` preference; please find some additional details at https://github.com/mozilla/pdf.js/wiki/Debugging-pdf.js

**Pull request merged**
