### PR TITLE
Replace the linked test-case for `intelisa.pdf`

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Re: PR #972.

Originally this was added as a `load` test in commit https://github.com/mozilla/pdf.js/commit/6ca1c4cf8346d789d952388602d35c3bdcadbcc7, which appears to have been pushed directly to `master` without any real information about why the test was added.

Later, as part of PR #972, it was changed to an `eq` test covering the first _100_ pages. To me this seems very excessive, since the first page would have sufficed as a test.

Hence this PR, which replaces the linked test with a reduced one instead. Obviously there's a small possibility that the current test also covers some other aspect of e.g. the font rendering. However, given that our test-coverage has improved vastly in the four years since this was added, I do think that it's worth the small risk that simplifying this test carries.

### CODE REVIEW

**Comment by yurydelendik** [comment]
I think this is one of the files that test PDF.js ability to handle large files (along with pdf specs).

**Comment by Snuffleupagus** [comment]
> I think this is one of the files that test PDF.js ability to handle large files (along with pdf specs).

OK, but how many of those do we actually need?
I think that we actually have a number of longer/larger files, even with this one removed; one such example is `ecma262.pdf`.

**Comment by yurydelendik** [comment]
>  but how many of those do we actually need?

Not sure. I'm okay with several of they cover different pdf structures, e.g. encrypted or not, with different types of xrefs, with outline, etc.

/cc @brendandahl

**Comment by Snuffleupagus** [comment]
Do we need it to be an `eq` test though, since I'm not sure what good it does comparing snap-shots for 100 pages like we're currently doing?
Would it suffice to convert the the linked test back to a `load` test, and then add the `eq` test in this PR for the actual rendering issue?

**Comment by yurydelendik** [comment]
I don't think we shall change anything about the intelisa.pdf test. Let's add reduced test as a new one.

**Comment by Snuffleupagus** [comment]
> Let's add reduced test as a new one.

Is the updated patch more to your liking?

**Comment by yurydelendik** [comment]
looking for @brendandahl 's feedback :)

**Comment by brendandahl** [comment]
Back when I was doing more font work, intelisa use to to fail in interesting ways. We hopefully have enough tests to cover it now, but in an ideal world we'd have a reduced test case with all of the unique fonts. I'm not sure how many there are so it could be a lot of work.

**Comment by brendandahl** [comment]
Looks like there are 21 unique fonts. Hmm...

**Comment by brendandahl** [comment]
Maybe we could expand the maker util to generate a pdf with all fonts and all the characters that have glyphs?

**Comment by Snuffleupagus** [comment]
> Looks like there are 21 unique fonts.

It seems that only 11 of these actually contain font files, while the rest of them are "standard" non-embedded fonts.
@brendandahl Does a reduced test-case need to include *all* fonts, or would it suffice if it included just the ones with font files? If the latter is OK, I doesn't seem *too* hard to create a reduced test-case for this.

**Comment by brendandahl** [comment]
> @brendandahl Does a reduced test-case need to include all fonts, or would it suffice if it included just the ones with font files?

I think it would be okay to just test the included ones. 

BTW, I started on a tool to generate a pdf with all the chars used in a pdf, but it's going to a be a bit more work than I expected and I doubt I'll have time to finish it up in the next few weeks.

**Comment by Snuffleupagus** [comment]
Closing in favour of PR #6842, since that one means a lot less work :-)

**Pull request closed without merging**
