### PR TITLE
Sig verify support

### PR DESCRIPTION
**Pull request by xbqian**

### CODE REVIEW

**Comment by timvandermeij** [comment]
This PR cannot be merged due to merge conflicts. Please resolve those and squash all commits into one commit (see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits).

**Comment by Snuffleupagus** [comment]
> This PR cannot be merged due to merge conflicts. Please resolve those and squash all commits into one commit (see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits).
> 
> Furthermore, the test files also need to be added to test/test_manifest.json to actually be included in the test runs. However, to test that signature verification works, we will need a set of unit tests as well.

It seems that this PR is based on a *very* out-dated version of PDF.js.

Besides the above, it's also worth noting that this PR is currently relying on `submodules` to include *a huge* amount of external code (with licenses that may not be compatible with Apache 2.0), which is not something that we're currently using except for (font) testing.
Most likely this use of `submodules` might need to be changed, and there's also the question if the PDF use-case really necessitates this much code (it may be preferred to use a a "clean-room" implementation with just the parts necessary for PDF files), since e.g. trying to review all of this isn't exactly going to be easy.

**Comment by timvandermeij** [comment]
I'm going to close this PR as it's far from being mergeable due to the issues mentioned above. Especially the licensing of the extenal code is problematic, so this needs to be redone using a clean-room implementation.

**Comment by yurydelendik** [comment]
@xbqian can you introduce a service for GlobalSign apis without link to the actual modules: we can stub it for standard version, but if it will be modified (e.g. by loading additional modules), the extended service will contain third-party code (probably in the different fork or library). I'll re-open the PR in case if somebody wants to do that.

**Review by yurydelendik — CHANGES_REQUESTED** [review]
Remove submodues and wrap all "org.pkijs." member into a class, atm it can be a singelton. No loading on the external js or references to "pkijs" can be present (e.g. `loadPkiJs` can be just `init` in the stub class). 

The concrete implementation (which will be located in the different repo) will override stub. The unit tests will provide their own stub for testing.

**Comment by timvandermeij** [comment]
Perhaps there exist other libraries that are compatible with our license that we can use. I don't really see how we can support this feature properly without using a library. If we abstract away from the library, custom solutions can add it and use it, but we will not be able to provide the feature in PDF.js itself, which is unfortunate.

**Comment by zambonin** [comment]
> It seems that this PR is based on a very out-dated version of PDF.js.

I have addressed this issue on my branch with some small changes. I understand that the use of submodules is not exactly desired, and will try to implement @yurydelendik's suggestion, creating an adapter pattern. 

Probably will take some time and it may be rough around the edges, but I will give it a shot.

> Perhaps there exist other libraries that are compatible with our license that we can use?

BSD 3-clause and Apache 2.0 are compatible, so ASN1.js and PKI.js could be used as a backend for the signature verification.

**Comment by johnlamericain** [comment]
What is the status of Digital signatures in PDF.js?

**Comment by rmhrisk** [comment]
@timvandermeij is the library with license issues PKIjs?

**Comment by timvandermeij** [comment]
I think it's not so much a licensing problem anymore as the licenses appear to be compatible, but more that a large amount of code is imported (using submodules) of which only a small fraction appears to be used. In those cases we prefer an implementation that only imports the necessary parts of the library (both for review and code size).

**Comment by johnlamericain** [comment]
Any lead on this tasks? Is it plan to do soon?

**Comment by rmhrisk** [comment]
@timvandermeij the ES6 version of PKIjs is more modular; if the patch was re-written with that it would carry less of a weight with it. It also uses rollup as its module builder which uses tree shaking which helps some. That said quite a bit of PKIjs will be needed for this scenario to work well.

**Comment by lexcorp** [comment]
What are the conflicts that need to be resolved?

I tried the version of Gustavo Zambonin https://github.com/zambonin/pdf.js/commit/1a8c4ff225aec9e6577097b52955d3201deaa30f, but I get this error:

pdf.worker.js:4242 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.
at Promise.resolve.then.then.reason (http://localhost/pdfjsdemo/build/pdf.worker.js:4242:16)
Promise.resolve.then.then.reason @ pdf.worker.js:4242

**Comment by lexcorp** [comment]
What are the conflicts that need to be resolved?

I tried the version of Gustavo Zambonin https://github.com/zambonin/pdf.js/commit/1a8c4ff225aec9e6577097b52955d3201deaa30f, but I get this error:

pdf.worker.js:4242 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.
at Promise.resolve.then.then.reason (http://localhost/pdfjsdemo/build/pdf.worker.js:4242:16)
Promise.resolve.then.then.reason @ pdf.worker.js:4242

**Comment by zambonin** [comment]
I have not been able to solve the error mentioned above, perhaps it's the first step to broaden support for different types of signatures. Simple certificates from Adobe work even with that error, though.

Unfortunately, I was asked to focus on other tasks. However, I'll try to update my branch with newer versions of PKIjs and pdf.js whenever possible.

**Comment by timvandermeij** [comment]
I'm closing this PR because it cannot be merged in the current state and nobody is actively working on this. Tracking issue #1076 remains open and, since this PR is linked to is, people can use this PR as a basis for a new PR.

**Pull request closed without merging**
