### PR TITLE
Implement text rendering modes in SVG backend

### LINKED ISSUE #7017: Unable to get cMap - nullAdobe-Japan1-UCS2 - console errors
Hello,

I'm using pdf.js, with the SVG, for a pdf with a lot of line and I have this error in my console : 

`Error: Unable to get cMap at: nullAdobe-Japan1-UCS2 util.js:258:5
createBuiltInCMap@http://localhost:8888/src/core/cmap.js:992:7
CMapFactoryClosure/<.create@http://localhost:8888/src/core/cmap.js:1003:16
Font_buildToUnicode@http://localhost:8888/src/core/fonts.js:2726:24
Font@http://localhost:8888/src/core/fonts.js:499:45
PartialEvaluator_translateFont@http://localhost:8888/src/core/evaluator.js:2066:14
PartialEvaluator_loadFont@http://localhost:8888/src/core/evaluator.js:655:1
PartialEvaluator_handleSetFont@http://localhost:8888/src/core/evaluator.js:424:14
next@http://localhost:8888/src/core/evaluator.js:826:22
next/<@http://localhost:8888/src/core/evaluator.js:831:19
 util.js:259:1
Warning: Error during font loading: Unable to get cMap at: nullAdobe-Japan1-UCS2`

I have seen that there is a similar issue in 2014 and it looks like it was closed but it seems that there is this issue again. 
I don't know if it is the cause of this but there is this strange print of the document, Japan print. I hope that It will help you to improve your lib.

strange

Update 1 : Ok it seems that there is a OCR on my pdf but is this normal that pdf.js display these characters ?

### LINKED ISSUE #9647: SVG renderer does not implement setTextRenderMode, beginAnnotations and endAnnotations
Attach (recommended) or Link to PDF file here: http://cs.brown.edu/~sk/Publications/Papers/Published/lepk-verif-ext-pbm/paper.pdf

Configuration:
- Web browser and its version: Firefox latest
- Operating system and its version: Ubuntu 16.0
- PDF.js version: 2.0.487
- Is a browser extension: no

Steps to reproduce the problem:
Render the file with SVG versus canvas.

Most of the pages come up with solid blocks of color, rather than text.  The console is full of many messages, 
```
19:39:21.887 Warning: Unimplemented operator beginAnnotations
pdf.min.self.js:1:2288
19:39:21.888 Warning: Unimplemented operator endAnnotations
pdf.min.self.js:1:2288
19:39:22.066 Warning: Unimplemented operator setTextRenderingMode
```
which makes sense, since the text rendering mode clearly affects the coloring of the page.  (I know that particular PDF uses rendering modes to implement optional content groups, which seem to work properly in the canvas output.)  I have no idea what the beginAnnotations and endAnnotations are used for.

### LINKED ISSUE #9999: Both text and path are rendered overlapping each other in SVG mode
Attach (recommended) or Link to PDF file here:
[TEST.PDF](https://github.com/mozilla/pdf.js/files/2311069/TEST.PDF)

Configuration:
- Web browser and its version: Crome 68, Firefox 61.0.2, reproduces on others as well
- Operating system and its version: Os X 10.13, reproduces on others as well
- PDF.js version: pdfjs-dist: 2.0.489
- Is a browser extension: no

Steps to reproduce the problem:
Just the basic svg configuration should be taken into account:
```
import pdfjs from 'pdfjs-dist';

pdfjs
  .getDocument(url)
  .then(pdf => pdf.getPage(1))
  .then(page => {
    const viewport = page.getViewport(1);
    // Get div#the-svg
    const container = document.getElementById('the-svg');

    // Set dimensions
    container.style.width = `${viewport.width}px`;
    container.style.height = `${viewport.height}px`;

    // SVG rendering by PDF.js
    page
      .getOperatorList()
      .then(opList => {
        const svgGfx = new pdfjs.SVGGraphics(page.commonObjs, page.objs);
        return svgGfx.getSVG(opList, viewport);
      })
      .then(svg => {
        container.appendChild(svg);
      });
  });
```

What is the expected behavior? (add screenshot)
screen shot 2018-08-22 at 17 43 03
If to open the document with Chrome.

What went wrong? (add screenshot)
screen shot 2018-08-22 at 17 42 00
If to render the pdf document with pdf.js

So it seems both text and path are rendered at the same time overlapping each other.

Are there any ideas on why could that happen?

### PR DESCRIPTION
**Pull request by janpe2**
This implements the operator `Tr` in the SVG backend.

Fixes #7017 [(comment)](https://github.com/mozilla/pdf.js/issues/7017#issuecomment-189628309)
Fixes #9647
Fixes #9999

### CODE REVIEW

**Comment by janpe2** [comment]
Firefox seems to have a problem when SVG `<text>` elements are used as child nodes of `<clipPath>`. If the texts have `fill="none"`, Firefox generates an empty clipping path that hides all graphics. The SVG Recommendation says that the fill and stroke attributes should not affect the generated clipping path. As a workaround I have used `fill="transparent"` instead of `fill="none"` when `Tr` specifies that glyphs should be used as a clipping path and not filled.

**Review by timvandermeij — COMMENTED** [review]
Looks good! Some minor comments, but I'm glad that work is being done to improve the SVG back-end.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Great work! I tested this locally since we don't have reference tests for the SVG back-end and this works just fine.

**Comment by valerii-cognite** [comment]
Good job! Any estimates on when it is going to be a part of a new release?

**Comment by timvandermeij** [comment]
No exact date yet, but we have been talking about making a release really soon now that we have most patches merged.

**Pull request merged**
