### PR TITLE
Revert "Merge pull request #6698 from yurydelendik/rm-UnsupportedMana…

### PR DESCRIPTION
**Pull request by brendandahl**
…ger"

This reverts commit 376788f2b22d96fb14b71db86fa500bc44f18c22, reversing
changes made to 5f56a20b34848b4e9f09fd479582d3a84cbe7fb5.

### CODE REVIEW

**Comment by yurydelendik** [comment]
Notice that test images here and at https://github.com/mozilla/pdf.js/pull/6714#issuecomment-161470061 shows correct images, but references are incorrect (probably made by https://github.com/mozilla/pdf.js/pull/6695#issuecomment-161034633 command).

**Comment by brendandahl** [comment]
/botio makeref
we'll just hope the makeref gets the correct results this time

**Comment by yurydelendik** [comment]
it was fine at https://github.com/mozilla/pdf.js/pull/6711#issuecomment-161746971

**Pull request closed without merging**
