### PR TITLE
Add the `pdkids` PDF document to the repository

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Given that the sub-title of that document is "Public domain texts for young people." and that the images have clear sources at the end of the document, it should (hopefully) be OK to add it to the repository rather than relying on a linked test-case.

### CODE REVIEW

**Comment by marco-c** [comment]
@calixteman and I were talking about this, maybe we could store the PDFs in a separate repo. This would avoid slowing things down in the main pdf.js repo by having fewer binary files.

**Comment by Snuffleupagus** [comment]
> @calixteman and I were talking about this, maybe we could store the PDFs in a separate repo. This would avoid slowing things down in the main pdf.js repo by having fewer binary files.

A few observations/questions:
 - The reason that we have linked test-cases is because historically we didn't want to deal with any potential legal issues of re-distributing third-party PDFs.
 - If we have a separate repository, could that make it more difficult for users to get the test-suite setup and running locally?
 - Ideally we'd only have reduced test-cases for the PDFs, but unfortunately it's often difficult to re-create all the brokenness found in real-world PDFs manually.

---

In any case, replacing a linked test-case as this PR does seems generally desirable regardless of any other (future) changes.

**Comment by marco-c** [comment]
Yes, it's something to consider for later, this PR looks good as it is.

**Comment by Snuffleupagus** [comment]
> Yes, it's something to consider for later, this PR looks good as it is.

Given that this PR contains a small test-only change, I'll consider that as approval to just land this :-)

**Pull request merged**
