### PR TITLE
Implement support for Highlight annotations

### LINKED ISSUE #5018: Sticky notes not viewable
Hi Guys. The sticky notes on pages 2 and 4 of this PDF are not viewable in Mozilla Firefox. Can you please take a look? Here is the file: 

http://www11.zippyshare.com/v/20982896/file.html

### PR DESCRIPTION
**Pull request by timvandermeij**
Fixes #5018.

Highlight annotations are basically nothing more than the already implemented Text annotations. Therefore a Highlight annotation can be represented as a Text annotation according to the PDF specification at https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf#page=633&zoom=auto,-306,268.

Note that for the issue mentioned in this PR the annotations itself are fixed with this PR, but the annotation content is rotated. This is a separate issue (due to the transform on `annotText` that also affects child elements such as the annotation content) and I think it also related to #3826. This should be filed as a follow-up issue.

### CODE REVIEW

**Comment by PaBLoX-CL** [comment]
Any news?

**Comment by timvandermeij** [comment]
No news yet, someone has to review #5585 before I can continue with my work on the annotation layer.

**Comment by hjalet** [comment]
@timvandermeij Will the work you do on the annotation layer fix the issue described in #3826?
We experience the same issue with PDFs including highlighting (it is rotated).
Highlighting is very important in our use case.

**Comment by timvandermeij** [comment]
No, my work is more focused on refactoring. This is a bugfix, so I'm not currently working on that.

**Pull request closed without merging**
