### PR TITLE
Fix (or not) windows integration test

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by timvandermeij** [comment]
Hm, looking at the test results I sadly don't see too much improvement. Is this something that can be fixed here or should we take a different approach for attacking the integration test errors?

**Comment by Snuffleupagus** [comment]
@calixteman Ping, do we still need this PR or can it be closed?

**Comment by timvandermeij** [comment]
Closing since I don't think this will fix the problems: I didn't see a change in https://github.com/mozilla/pdf.js/pull/15848#issuecomment-1374466465 and this introduces more timeouts which I think are the source of the flakiness we experience with the integration tests; please see https://github.com/mozilla/pdf.js/issues/16930#issuecomment-1712870119.

In short, we should probably take a step back here and instead go for a solution that checks the presence of elements without fixed timeouts.

**Pull request closed without merging**
