### PR TITLE
Compute correctly the bounding box of a transformed rectangle (fixes #17065)

### LINKED ISSUE #17065: Pattern: applying a transform breaks the pattern
Attach (recommended) or Link to PDF file here: [test.pdf](https://github.com/mozilla/pdf.js/files/12795741/test.pdf)

Configuration:
- Web browser and its version: Firefox 118.0.1 (64-bit)
- Operating system and its version: Windows 10 22H2 19045.3448
- PDF.js version: 3.10.86 [c72cb5436]
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the PDF in Firefox
2. Compare with a version in Chrome/mupdf

What is the expected behavior? (add screenshot)
It should show four distorted rectangles each with a single contiguous color gradient from red to blue to green to purple (the red part is clipped). The file has been tested in the following viewers: Acrobat, mupdf, evince, XPDF, Chrome, SummatraPDF, and the Apple one and works in all of them.

image

What went wrong? (add screenshot)
For the two rectangles on which a skew & rotation is applied, the pattern does not appear:
image

Hope this is complete, thanks in advance,

Dherse :)

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
Interesting, this patch is fixing some issues in issue16127.pdf.
And I don't really see any real visible differences in issue6961.pdf.

**Review by Snuffleupagus — APPROVED** [review]
Really nice find; please rebase this on `master` before landing (such that makeref covers the other recently landed PR as well).

r=me, thank you!

**Pull request merged**
