### PR TITLE
(Don't Merge)

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
Likely a temp failure on github's side.
/botio makeref

**Comment by Snuffleupagus** [comment]
> Likely a temp failure on github's side.

The thing that failed was the `browsertest` command, so I'm not sure that if this actually tested the right thing!?

**Comment by calixteman** [comment]
If I understood correctly `html_url` is a property of the payload from a gh request.
So it should be fine with whatever command.
But I'll test with `browsertest` to be sure.

**Comment by Snuffleupagus** [comment]
Unfortunately the issue still remains, given that when opening http://54.193.163.58:8877/641ecf2f433b128/reftest-analyzer.html#web=eq.log you cannot actually click on the "firefox-annotation-text-widget-forms-page1"-line and it's thus impossible to review the ref-test failures on Windows.

**Comment by Snuffleupagus** [comment]
It seems that *something* goes wrong in the following code, but only on the Windows bot:
https://github.com/mozilla/pdf.js/blob/60e9065bf6d32d35a20e2efffa612275ac6079f1/test/resources/reftest-analyzer.js#L284-L295

**Comment by calixteman** [comment]
I don't know what the issue is, but at least I can reproduce locally.
I ran a `makeref` and then a `browsertest` and I got a lot of `TEST-UNEXPECTED-FAIL`....
Most of the links in the analyzers are ok but few of them are wrong.

**Comment by calixteman** [comment]
I think understand what the issue is.
 - the regexp here: https://github.com/mozilla/pdf.js/blob/60e9065bf6d32d35a20e2efffa612275ac6079f1/test/resources/reftest-analyzer.js#L228 catch only integer `outputScale`
 - with my setup the `outputScale` is 1.5 and is set by: https://github.com/mozilla/pdf.js/blob/60e9065bf6d32d35a20e2efffa612275ac6079f1/test/driver.js#L615

So it's why it's failing locally.
When I connected to the VM in using a remote desktop connection, I think (I'm not sure at all) that the remote windows changed its resolution to fit mine, hence the bug...
So the first fix is to fix the regexp and I wonder if we should use `window.devicePixelRatio` in order to avoid any issue.
I checked the options to connect to the vm and I didn't find anything to fix the remote screen resolution, so I guess that each time I connect it we could have potential issues due to a different outputScale.

**Comment by calixteman** [comment]
So the penultimate `/botio-windows browsertest` failed because of a `html_url`, I just restarted the process and the last command is ok...

**Pull request closed without merging**
