### PR TITLE
Handle errors gracefully, in `PartialEvaluator.translateFont`, when fetching the font file (issue 9462)

### LINKED ISSUE #9462: First page is mixed with the last page
Could you take a look on this file. The first page is mixed with the last page.

[cb7e7bd2362328f37fe97dc8dff151a3.pdf](https://github.com/mozilla/pdf.js/files/1706865/cb7e7bd2362328f37fe97dc8dff151a3.pdf)

Configuration:
- Firefox Nightly 60
- Windows 7

### PR DESCRIPTION
**Pull request by Snuffleupagus**
The *third* page of the referenced PDF document currently fails to render completely, since one of its font files fail to load.
Since that error isn't handled, a large part of the text is thus missing which looks quite bad. By "replacing" the font data with an *empty* stream, we'll thus be able to fallback to rendering the text with a standard font (instead of using `ErrorFont`). While there's obviously no guarantee that things will look perfect, actually rendering the text at all should be an improvement in general.

Also, print a warning in `PartialEvaluator.loadFont` when the `PartialEvaluator.translateFont` method rejects, since that'd have helped debug/fix the issue faster.

Fixes #9462

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
*Oh great*, this fails both on the bots and *locally* in Google Chrome even when testing against the `master` branch (but not if the document is loaded/rendered "in order").
This all suggests a (somewhat) serious bug in Google Chrome, since the rejected Promise from `PartialEvaluator.translateFont` *somehow* isn't caught by https://github.com/mozilla/pdf.js/blob/a392082e302366a25a17d1ba35551a2acd9e5195/src/core/evaluator.js#L1153-L1182 and we thus end up propagating the error to the main-thread.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for fixing this!

/botio makeref

**Pull request merged**
