### PR TITLE
Update refs for ff27.

### PR DESCRIPTION
**Pull request by brendandahl**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Let's see if that actually makes `issue6113.pdf` behaving nicely in Firefox on Linux.

/botio-linux test

**Comment by yurydelendik** [comment]
45->46

/botio makeref

**Comment by Snuffleupagus** [comment]
Apparently the update to Firefox 50 causes intermittent failures, at least on Linux :-(

**Comment by timvandermeij** [comment]
Oh no :(

Is there already an upstream bug for it? It not, we should file it and perhaps keep the bots on 49.

/cc @yurydelendik @brendandahl

**Comment by Snuffleupagus** [comment]
> Is there already an upstream bug for it?

Perhaps https://bugzilla.mozilla.org/show_bug.cgi?id=1243938 could be relevant here, if the canvas rendering is done with Skia.
(Note that using the test-cases attached to that bug, I'm however *not* able to reproduce the problem locally, so I'm unfortunately not convinced that the bug is relevant here.)

**Comment by Snuffleupagus** [comment]
As mentioned on IRC, running [mozregression](http://mozilla.github.io/mozregression/) (on Windows) gave me the following range: https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=950a962b75eae61cb9f0c5638b6b362427f7ebe6&tochange=fc5b4f286716bf47199435415f945695c1c20d0b.
Given the commit message and the actual code this seems like a fairly reasonable regression range, but I'd be great if someone else could confirm that it's accurate.

**Comment by Snuffleupagus** [comment]
The regression tracked in https://github.com/mozilla/pdf.js/issues/8165 has now been fixed :-)

/botio-windows makeref

**Pull request closed without merging**
