### PR TITLE
Fix inverted 1-bit images in SVG backend

### LINKED ISSUE #8612: SVG render CCITTFaxDecode outputs negative colors
Link to PDF file (or attach file here): [issue-CCITTFaxDecode.PDF](https://github.com/mozilla/pdf.js/files/1124473/issue-CCITTFaxDecode.PDF)

Configuration:
- Web browser and its version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- Operating system and its version: macOS Sierra Version 10.12.4
- PDF.js version: 1.8.514
- Is an extension: False

Steps to reproduce the problem:
```bash
# 1. Clone the mozilla/pdf.js repository
$ git clone git@github.com:mozilla/pdf.js.git
$ cd pdf.js

# 2. Install dependencies
$ npm install

# 3. Download the PDF to the /web directory
$ curl -L https://github.com/mozilla/pdf.js/files/1124473/issue-CCITTFaxDecode.PDF > web/issue-CCITTFaxDecode.PDF 

# 4. Serve pdf.js
$ gulp server
```

5. Open Local Canvas Viewer: http://localhost:8888/web/viewer.html?file=issue-CCITTFaxDecode.PDF
6. Open Local SVG Viewer: http://localhost:8888/examples/svgviewer/index.html?file=..%2F..%2Fweb%2Fissue-CCITTFaxDecode.PDF

What is the expected behavior? (add screenshot)
canvas_success

What went wrong? (add screenshot)
svg_fail

Beginning of file
```pdf
%PDF-1.4
1 0 obj
<</Length 44>>stream
q 588.480000 0 0 833.280000 0 0 cm /Iff Do Q
endstream
endobj
2 0 obj
<</Type /XObject /Subtype /Image /Name /Iff /Width 2452 /Height 3472 
/BitsPerComponent 1 /ColorSpace /DeviceGray /Filter /CCITTFaxDecode 
/DecodeParms << /K -1 /Columns 2452 /BlackIs1 false>>/Length 14146 >> 
stream
```
Or if you prefer hex
```hex
00000000:  2550 4446 2d31 2e34 0d31 2030 206f 626a 0d3c 3c2f 4c65 6e67  :%PDF-1.4.1 0 obj.<</Leng
00000018:  7468 2034 343e 3e73 7472 6561 6d0d 0a71 2035 3838 2e34 3830  :th 44>>stream..q 588.480
00000030:  3030 3020 3020 3020 3833 332e 3238 3030 3030 2030 2030 2063  :000 0 0 833.280000 0 0 c
00000048:  6d20 2f49 6666 2044 6f20 510d 656e 6473 7472 6561 6d0d 656e  :m /Iff Do Q.endstream.en
00000060:  646f 626a 0d32 2030 206f 626a 0d3c 3c2f 5479 7065 202f 584f  :dobj.2 0 obj.<</Type /XO
00000078:  626a 6563 7420 2f53 7562 7479 7065 202f 496d 6167 6520 2f4e  :bject /Subtype /Image /N
00000090:  616d 6520 2f49 6666 202f 5769 6474 6820 3234 3532 202f 4865  :ame /Iff /Width 2452 /He
000000a8:  6967 6874 2033 3437 3220 0d2f 4269 7473 5065 7243 6f6d 706f  :ight 3472 ./BitsPerCompo
000000c0:  6e65 6e74 2031 202f 436f 6c6f 7253 7061 6365 202f 4465 7669  :nent 1 /ColorSpace /Devi
000000d8:  6365 4772 6179 202f 4669 6c74 6572 202f 4343 4954 5446 6178  :ceGray /Filter /CCITTFax
000000f0:  4465 636f 6465 200d 2f44 6563 6f64 6550 6172 6d73 203c 3c20  :Decode ./DecodeParms << 
00000108:  2f4b 202d 3120 2f43 6f6c 756d 6e73 2032 3435 3220 2f42 6c61  :/K -1 /Columns 2452 /Bla
00000120:  636b 4973 3120 6661 6c73 653e 3e2f 4c65 6e67 7468 2031 3431  :ckIs1 false>>/Length 141
00000138:  3436 203e 3e20 0d73 7472 6561 6d0d 0aff ffff ffff ffff ffff  :46 >> .stream...........
```

### PR DESCRIPTION
**Pull request by janpe2**
Fixes #8612

When the SVG backend converts images to PNG, it inverts the colors of all 1-bit grayscale images (`ImageKind.GRAYSCALE_1BPP`). That is incorrect. Only image masks must be inverted.

Enable the SVG backend and open my test file:
[images_1bit_grayscale.pdf](https://github.com/mozilla/pdf.js/files/1511194/images_1bit_grayscale.pdf)
This PDF contains many kinds of 1-bit grayscale images.

Inline images seem to work also without my patch because their pixel data format is `ImageKind.RGBA_32BPP` even when the PDF image is 1-bit grayscale.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
> images_1bit_grayscale.pdf
> This PDF contains many kinds of 1-bit grayscale images.

Even though we currently don't have (reference) tests for the SVG backend, since you've created a nice reduced test-case I'd nonetheless suggest adding that file as a new `eq` test :-)

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for fixing this!

**Pull request merged**
