### PR TITLE
Update dependencies and translations to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
What happened with the Firefox ref-tests on Windows, since there seem to be movement in every single test!?
Has something been changed on the bot, since I don't understand how this patch could "cause" this?

**Comment by timvandermeij** [comment]
It looks like this started two days ago already in https://github.com/mozilla/pdf.js/pull/18918#issuecomment-2423015380, so indeed it doesn't seem related to this patch. Five days ago in https://github.com/mozilla/pdf.js/pull/18905 there were no issues yet, which was the last successful run I could find, and in all cases we used Firefox 133.0.

**Comment by timvandermeij** [comment]
I have created #18928 to track the bot issues found above because they also happened on a dummy PR, which shows that they are not caused by this PR. In the interest of preparing for the next release (and because I plan to do more with the dependencies, and keeping `package-lock.json` rebased is a bit of a pain) I'd therefore propose to move on with this PR as-is, unless there are objections of course.

**Review by Snuffleupagus — APPROVED** [review]
> [...] In the interest of preparing for the next release (and because I plan to do more with the dependencies, and keeping `package-lock.json` rebased is a bit of a pain) I'd therefore propose to move on with this PR as-is, unless there are objections of course.

That seems OK, as far as I'm concerned.

r=me, thank you.

**Comment by calixteman** [comment]
> What happened with the Firefox ref-tests on Windows, since there seem to be movement in every single test!? Has something been changed on the bot, since I don't understand how this patch could "cause" this?
> 
> /cc @calixteman

See my answer: https://github.com/mozilla/pdf.js/issues/18928#issuecomment-2425146808

**Pull request merged**
