### PR TITLE
Improve UI design (Change some colors)

### PR DESCRIPTION
**Pull request by shge**
Since the colors and gradations were a little outdated, I made some changes to the UI design. 😃

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Just making the entire default viewer, which is shipping in Firefox, essentially black really isn't an improvement at all. There's a number of issues such as e.g. the main toolbar being indistinguishable from the rest of the viewer, and generally a fairly incomplete attempt at changing the styling in any coherent way.

For a custom implementation you're obviously free to do whatever you want, but I don't think this is something that belongs in the main PDF.js library.

**Comment by shge** [comment]
@Snuffleupagus 
Okay, I will change only selection colors.

**Comment by Snuffleupagus** [comment]
> Okay, I will change only selection colors.

That's already tracked in issue #9184, and it's not really clear if/how any changes should actually be made here (since there's a degree of subjectivity involved).
As for these particular changes, they are not an improvement since for one they make the actual text *less* clear when it's selected (probably caused by the change in opacity).

**Comment by timvandermeij** [comment]
I agree with the above. The only thing we may consider is #9702, but the designers from Firefox should come up with a design first.

**Pull request closed without merging**
