### PR TITLE
[api-minor] Add support for URLs in the document outline

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Re: issue #5089.
(Note that since there are other outline features that we currently don't support, e.g. bold/italic text and custom colours, I thus think we can keep the referenced issue open.)

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Note that it isn't too common for PDF files to include URLs in the outline, but as the referenced issue demonstrates, it does happen in practice. Given that this patch validates the URL, only absolute ones are allowed, it shouldn't really be more unsafe than normal LinkAnnotations.
 
@timvandermeij Is this something that you'd be comfortable reviewing?

**Comment by timvandermeij** [comment]
Thank you for fixing this!

**Pull request merged**
