### PR TITLE
Add translation for central Kurdish(ckb) language

### PR DESCRIPTION
**Pull request by allekok**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
As outlined in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, this unfortunately cannot be accepted since translations are imported from Firefox:
> Note that the translations for PDF.js in the l10n folder are synchronized with the Nightly channel of Mozilla Firefox. This means that we will only accept pull requests that add strings currently missing in the Nightly channel, but keep in mind that the changes will be overwritten when we synchronize again.

**Comment by allekok** [comment]
I didn't know that. This part of documentation is not so clear.

**Comment by allekok** [comment]
Should I close this PR?

**Comment by timvandermeij** [comment]
The documentation is now updated to be more clear about this. I'll close this PR, but please feel free to send the contents of this PR to the upstream maintainers. You can find their contact information at https://wiki.mozilla.org/L10n:Teams:ku. If that is completed, we will import the changes here as well. Thanks!

**Comment by allekok** [comment]
Ok, thanks.

**Pull request closed without merging**
