### PR TITLE
Update dependencies and translations to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
It seems that the `integrationtest` failed at the same exact point on both Linux *and* Windows, hopefully that's just really bad luck and not something broken by the Puppeteer update.

/botio integrationtest

**Comment by timvandermeij** [comment]
Yikes, that same test times out fails locally as well. I'll have a look at what's wrong with it; it could be a pre-existing issue in the test that only surfaces now for some reason. I didn't find anything particularly interesting between Puppeteer 21.5.0 and 21.5.1, but apparently something changed to make it show up.

**Comment by timvandermeij** [comment]
I looked into this and could already reproduce this locally with master. I have made https://github.com/mozilla/pdf.js/pull/17261 to check this further and it's indeed already failing on master, so it's not related to this PR. I'll check if I can find where this started failing because it must have been a very recent change given that the integration tests passed two days ago.

**Comment by timvandermeij** [comment]
I have bisected it and created #17262 to track the integration test problem which indeed turned out to be pre-existing issue.

**Review by Snuffleupagus — APPROVED** [review]
r=me, this should be fine to land as-is since the `integrationtest` failure is unrelated; thank you!

**Pull request merged**
