### PR TITLE
Update jpx decoder

### PR DESCRIPTION
**Pull request by calixteman**
The decoder has been updated to reduce the number of copies after having decoded an image:
https://github.com/mozilla/pdf.js.openjpeg/commit/b4ba3b3090347e5efe663f60d61e49f278bfc283

### CODE REVIEW

**Comment by timvandermeij** [comment]
The reference test image difference seem to be limited to the known intermittents, but one error is reported (see below) and that one seems new given that I haven't seen it in earlier runs. Could that be a regression of this patch, or is it a new intermittent?

```
TEST-UNEXPECTED-FAIL | test failed pr12564 | in chrome | page1 round 1 | render : Error: Requesting object that isn't resolved yet img_p0_15.
```

**Comment by calixteman** [comment]
> The reference test image difference seem to be limited to the known intermittents, but one error is reported (see below) and that one seems new given that I haven't seen it in earlier runs. Could that be a regression of this patch, or is it a new intermittent?
> 
> ```
> TEST-UNEXPECTED-FAIL | test failed pr12564 | in chrome | page1 round 1 | render : Error: Requesting object that isn't resolved yet img_p0_15.
> ```

I don't manage to have an issue while I'm loading this pdf. 
In considering that there is no jpeg2000 image in this pdf, I'd say it's a new intermittent.

**Comment by timvandermeij** [comment]
> I don't manage to have an issue while I'm loading this pdf. In considering that there is no jpeg2000 image in this pdf, I'd say it's a new intermittent.

Thanks for checking! Let's try again in that case and see if it disappears, but given that the Windows bot also didn't fail on this it does look like an intermittent:

/botio-linux browsertest

**Comment by Snuffleupagus** [comment]
> The reference test image difference seem to be limited to the known intermittents, but one error is reported (see below) and that one seems new given that I haven't seen it in earlier runs. Could that be a regression of this patch, or is it a new intermittent?
> 
> ```
> TEST-UNEXPECTED-FAIL | test failed pr12564 | in chrome | page1 round 1 | render : Error: Requesting object that isn't resolved yet img_p0_15.
> ```

We saw that one fail in PR #18167, where I was a bit worried about the changes there somehow causing it. (Since the image in question should be using a /FlateDecode filter.)

> I don't manage to have an issue while I'm loading this pdf.

Well, if this is intermittently failing it might be quite difficult to reproduce (reliably) locally unfortunately...

**Comment by timvandermeij** [comment]
> We saw that one fail in PR https://github.com/mozilla/pdf.js/pull/18167, where I was a bit worried about the changes there somehow causing it. (Since the image in question should be using a /FlateDecode filter.)

That's good to know. Unfortunately then it's apparently so intermittent that we haven't seen it in two weeks time, and I'd also not really have an idea how to reproduce it locally other than perhaps trying to repeatedly open/close the file until it  happens.

However, the run above indeed confirmed that it's not caused by this particular PR, so I'll make a follow-up issue for it.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thanks!

**Pull request merged**
