### PR TITLE
Restore the header size limit of 80 KB

### LINKED ISSUE #10849: Downloading error while running gulp makeref
Attach (recommended) or Link to PDF file here:

PDF link found in test/pdfs/issue6360.pdf.link

Configuration:
- Web browser and its version: N/A
- Operating system and its version: Ubuntu 18.04.2 LTS
- PDF.js version: Master
- Is a browser extension: No

Steps to reproduce the problem:
1. Fork repository and follow instructions to install local version from pdf.js/README.md.
2. Run gulp makeref.

What is the expected behavior? (add screenshot)

All pdfs succesfully downloaded.

What went wrong? (add screenshot)
image

When I took a look at the file issue6360.pdf.error, it states:
`Error: parse error`

When I took a look at the output of gulp makeref, this came up for the pdf in question: 
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

### PR DESCRIPTION
**Pull request by timvandermeij**
Fixes #10849.

### CODE REVIEW

**Comment by timvandermeij** [comment]
The bots run Node.js 10.14.1 and should be updated to use Node.js 10.15.0 since the command line argument used here is backported to that version in the 10.x range. Preferably we update to 10.16.0 though since that is the latest LTS version of Node.js.

/cc @brendandahl @yurydelendik for doing this on both bots

**Comment by brendandahl** [comment]
./botio test

**Comment by timvandermeij** [comment]
Thank you @brendandahl! @Snuffleupagus Could you perhaps review this?

**Review by Snuffleupagus — APPROVED** [review]

**Pull request merged**
