### PR TITLE
Printing refactor split from 7721

### LINKED ISSUE #7720: Print before document is ready causes an alert dialog + print overlay is stuck
1. Visit https://mozilla.github.io/pdf.js/web/viewer.html
2. Issue a print request before it is ready.
3. An alert dialog appears, "Warning: The PDF is not fully loaded for printing", close it.
4. A print dialog appears, close it.

Expected: PDF viewer returns to normal state

Actual: The print overlay is stuck at being open and does not go away.

The console contains the following errors:
viewer.js:9639 Expected print service to be initialized.
viewer.js:9641 Uncaught TypeError: Cannot read property 'renderPages' of null

### PR DESCRIPTION
**Pull request by Rob--W**
This PR contains all reviewed commits from #7721 (without changes) and fixes #7720.
Maybe the complex OOP printing patch from the other PR is not needed if Chrome fixes the underlying bug before Chrome-with-the-bug reaches the stable channel.

### CODE REVIEW

**Comment by Rob--W** [comment]
@yurydelendik You've already reviewed the patches, please merge if you think that it's OK to merge.

Only the first two patches are necessary to fix #7720, the other two only make it easier to extend the PDF printing logic later, if wanted.

**Comment by yurydelendik** [comment]
Thank you for the patch

**Pull request merged**
