### PR TITLE
Better thumbnail image scaling

### PR DESCRIPTION
**Pull request by fkaelberer**
`ctx.drawImage()` does a bad job scaling large image onto a small canvas (results are very noisy/blocky). Therefore, images are scaled down by factor 2 several times before the image is scaled to thumbnail canvas size. 

This PR changes the order of scaling factors: It first scales by a fractional value, and then scales down by 2 several times. Scaling by fractional numbers usually introduces more artifacts (e.g. blurryness) than scaling by powers of 2. The resulting image quality is higher because the artifacts of fractional scaling are introduced in the first scaling step, and then than vanish when downsampling by exact powers of 2 afterwards. 

The following animated gif toggles the thumbnail images which are generated with new and old code from the tracemonkey paper at 70%, 100%, 180% and 300% zoom.
output_ghu1jf

### CODE REVIEW

**Comment by timvandermeij** [comment]
@fkaelberer That looks much, much better. I have only found that it isn't applied to all thumbnails, but mostly only for the currently active page and maybe the next one. See the screenshot I took below. You can see that the first two are very nice, but the other two are rather dark. If I go to that page and reload the viewer, then that thumbnail is nice and the other ones are darker. Any idea what causes that?

naamloos

**Comment by Snuffleupagus** [comment]
@timvandermeij That issue is already present in master. The difference should be that the first two thumbnails are created using the page canvas, while the others are actually rendered.

**Comment by yurydelendik** [comment]
> That issue is already present in master. The difference should be that the first two thumbnails are created using the page canvas, while the others are actually rendered.

Correct, in the future we can try rendering on the canvas 2x larger and scale down to the target size.

**Comment by timvandermeij** [comment]
In that case ignore my comment. Sorry for the noise!

**Comment by CodingFabian** [comment]
this can be merged right? The thumbnail looks indeed better and the PR does not change anything besides the manual downscaling order.

**Comment by timvandermeij** [comment]
Also fixes http://kennemerlyceum.nl/attachments/article/4/Gymnasiumfolder.pdf. The second thumbnail is stretched in the current master, but fixed with this PR.

**Comment by timvandermeij** [comment]
Regressions have been fixed.

/botio-linux preview

**Comment by timvandermeij** [comment]
Really nice, thank you!

**Pull request merged**
