### PR TITLE
Added masks & gradients support, and group hierarchy management in SVG

### PR DESCRIPTION
**Pull request by fr33z00**
Hi all.
In order to have a better PDF to SVG conversion for one of our projects, I forked the repo and improved the SVG graphic rendering on some points (gradients support, path filling, masking, and groups hierarchy).
The tracemonkey file renders correctly (or at least better on the p.11 graph), as far as I checked.

The modifications do not respect the initial authors way of making groups, so a merge may not be acceptable, however, it could help or inspire people working on it.

I noticed that shadingFill ( = gradients) do not render exactly as on canvas (or desktop apps like evince) and couldn't figure out how to improve this, but the result looks pretty similar to what inkscape produces. See the example page below:

source:
[page1.pdf](https://github.com/mozilla/pdf.js/files/2460333/page1.pdf)

canvas rendering:
pdf2canvas

svg rendering:
pdf2svg

inkscape conversion  (do not pay attention to fonts):
pdf2svg_inkscape

### CODE REVIEW

**Comment by timvandermeij** [comment]
Nice work; thank you for upstreaming your changes! I'm positive we can merge most parts of this if we split it up into multiple smaller pull requests, one per feature, and make it adhere to the current code structure.

**Comment by fr33z00** [comment]
Tim,
The way the official code structure creates group doesn't stick to the PDF ops tree which explicitly requests groups creation before feeling them. I had no background on PDF documents internal stuff, no background on the pdf.js structure, and, of course, not much time to spend on this. I just couldn't, and still can't, figure out how to combine the operations needed to create a mask or a gradient with the postponed group creation and transform matrix application.
That's why I proposed my code as an inspiration.

**Comment by fr33z00** [comment]
Tim (or anyone else), 
I improved my proposal on SVG, adding patterns & blend mode support, and fixing different things like clipping & transform matrix.
This leads to a perfect rendering of the tracemonkey file, as well as of my test file (see the screenshots below), and many other files I tried.
I now believe the way I used to build groups hierarchy is the only possible one. Thus, this pull request may now be considered as such.

SVG rendering (now comparable to my first post canvas rendering thanks to blend mode support)
screenshot_2018-11-07_pdf-example

tracemonkey page 11 (gradients fill)
screenshot_2018-11-07 tracemonkey

tracemonkey page 13 figure (patterns)
screenshot_2018-11-07 tracemonkey_patterns

**Comment by timvandermeij** [comment]
Is there any way that this can be split into multiple smaller pull requests? It looks like this patch contains quite a bit of different functionality, which makes it hard to review. However, we are interested in merging this, so if you can make a pull request per functionality then this is much more likely to be merged.

**Comment by fr33z00** [comment]
Ok, I'll try to split it in a series. However, the first one will be somehow "massive", because, how I already said, the change from post created groups to pre created cannot be splitted. And much of the work relies on that.
I then close this request and will start the series.

**Comment by timvandermeij** [comment]
Sounds good! Even though the patch may be a bit larger, that's not a problem if it's one self-contained feature, so that should be fine.

**Pull request closed without merging**
