### PR TITLE
Fix Typo:XFATemplate class Para Styling paddingight => paddingRight

### PR DESCRIPTION
**Pull request by Bomberus**

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by Snuffleupagus** [comment]
*Nit:* This should probably have a better *commit message* than just `Fixed Typo` since that's pretty non-descriptive!?

**Comment by calixteman** [comment]
> _Nit:_ This should probably have a better _commit message_ than just `Fixed Typo` since that's pretty non-descriptive!?

Sorry about that: I just focused on the patch itself. @Bomberus ^^

**Comment by Bomberus** [comment]
Hi @calixteman,
commit message and title should now be more descriptive.

**Comment by Snuffleupagus** [comment]
Looking at the ref-tests there appears to be some actual regressions, e.g. in `xfa_bug1718670_1-page3` and `xfa_bug1717668_4-page12`.

**Pull request closed without merging**
