### PR TITLE
Cleanup PdfJsTelemetry addon stub

### PR DESCRIPTION
**Pull request by georgf**
This is a follow-up to #8239, renaming the PdfJsTelemetry-addon.jsm file and removing left-overs.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Unless I'm mistaken, it looks like the old `extensions/firefox/content/PdfJsTelemetry-addon.jsm` file isn't actually being removed in this PR (only a new file is added). Hence I'd suggest using the `git mv` command to rename the existing file, since this has the added bonus of retaining the commit history for the file.

**Comment by georgf** [comment]
I used `git mv`, is anything broken?

**Comment by Snuffleupagus** [comment]
> I used git mv, is anything broken?

Well, not "broken" as such, but as mentioned it looks like the old `PdfJsTelemetry-addon.jsm` file isn't actually being removed in the patch!?

**Comment by timvandermeij** [comment]
Indeed, something appears to have gone wrong. If you look at the diff at https://github.com/mozilla/pdf.js/pull/8254/files, `PdfJsTelemetry-stub.jsm` is created, but `PdfJsTelemetry-addon.jsm` still exists as well, while that one should have been removed.

**Comment by Snuffleupagus** [comment]
Landed in PR #8275 (obviously keeping the author information correct), thank you for the patch!

**Pull request closed without merging**
