### PR TITLE
Disable XFA tests because of timeouts with Firefox (issue 17311)

### LINKED ISSUE #17311: Disable XFA reference tests because of timeouts
We just switched to firefox 122.0a1 on the bots and they're consistently failing with some xfa files.
It's very likely a Firefox regression.
It started when making refs:
https://github.com/mozilla/pdf.js/pull/17291#issuecomment-1820584575

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Review by Snuffleupagus — DISMISSED** [review]

**Comment by Snuffleupagus** [comment]
Looking at the logs above it's not just the reference tests that are "broken" now, but it seems that we also get a few new unit-test failures as well :-(

**Comment by calixteman** [comment]
I filed a bug for Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1865917

**Comment by calixteman** [comment]
@Snuffleupagus, in waiting for [bug 1865774](https://bugzilla.mozilla.org/show_bug.cgi?id=1865774) to be fixed, I removed nightly 122.0a1 from the bots and replace them by 121.0a1 from the 13th of November (https://archive.mozilla.org/pub/firefox/nightly/2023/11/2023-11-13-09-15-05-mozilla-central/). It's the best I can do for the moment.

**Pull request closed without merging**
