### PR TITLE
Enable dumpio when running the tests in order to have some useful debug data

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
It could help to figure out what's wrong in #18259.

**Comment by timvandermeij** [comment]
Hm, I'm a bit on the fence about this because while it might be useful it also generates _a lot_ of log spam for especially the integration tests.

I'd feel better about this if we could at least solve that problem first:

- Preferably we fix those logs altogether, because for example logs like `JavaScript error: http://127.0.0.1:62573/build/generic/web/viewer.mjs, line 3023: Error: Not implemented: #createBundleFallback` already don't look particularly good.
- If that is difficult, we might also opt to only enable `dumpio` for the reference tests and not for the unit/integration tests, at least for the time being until we figured out what's going on for #18259 (and maybe after that disable it again).

**Comment by calixteman** [comment]
Yes there's some noise :(, especially those exceptions we've because of DecompressionStream (I must file a bug about that).
We should try to fix the createBundleFallback one.
That said in considering that it helped to fix one bug (in integration tests) and it's the best idea I've for the moment to be able to potentially catch something from this intermittent failure, I'd say we should do it.

**Comment by timvandermeij** [comment]
> It could help to figure out what's wrong in https://github.com/mozilla/pdf.js/issues/18259.

Unfortunately I found out that this patch won't help with that particular issue; see https://github.com/mozilla/pdf.js/issues/18259#issuecomment-2173874135.

I'm still somewhat in favor of doing this, but ideally once the integration test logs are cleaned up at least a little bit, to avoid the logs becoming unwieldy to read through. I'll create dedicated issues for the most important/spammy ones because this patch _did_ nicely surface those issues, so that in itself is really good.

**Comment by timvandermeij** [comment]
I have created the two issues above for the most important log spam problems here. I think once those are resolved we should be in a state where we can enable `dumpio: true` since, now that we have seen this, might also help with future patches because it'll surface new logs instead of them going by unnoticed as was the case until this PR.

**Comment by Snuffleupagus** [comment]
Can we perhaps revisit this one now, given the PRs that landed earlier today?

**Comment by timvandermeij** [comment]
Yes, overall the logs should be in a much better state now that the two mentioned issues have been fixed. @calixteman Could you rebase this patch and trigger a new test run to verify that the logs should be in a good enough state now that we can enable this?

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
This has _clearly_ proven its value, and the logs are much more under control now. Good idea to enable this! I'll create a meta-issue to clean up the logs further, but it's not blocking landing this anymore.

**Pull request merged**
