### PR TITLE
Update npm packages

### PR DESCRIPTION
**Pull request by Snuffleupagus**
- Update npm packages

 - Fix (some) vulnerabilities reported by `npm audit`

   This was done automatically, using the `npm audit fix` command.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
I wonder if the Windows bot just needs a reboot, or if it's perhaps out of storage space?

**Comment by timvandermeij** [comment]
@brendandahl @yurydelendik Could one of you kick the Windows bot?

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good! I'll open a separate issue for the Windows bot.

**Pull request merged**
