### PR TITLE
XFA - Fix layout issues

### LINKED ISSUE #13567: xfa_imm1344e-page1 regression after #13554
This issue is tracking the regression mentioned in https://github.com/mozilla/pdf.js/pull/13554#issuecomment-861661644.

### PR DESCRIPTION
**Pull request by calixteman**
- PR #13554 is buggy, so this patch aims to fix bugs.
  - check if a component fits into its parent in taking into account the parent layout.
  - introduce method isSplittable for template nodes to know if a component can be splitted in case of overflow.

### CODE REVIEW

**Comment by calixteman** [comment]
Something is wrong on `firefox-xfa_imm1295e-page3`.

**Review by marco-c — APPROVED** [review]
Can you make sure the differences in `firefox-xfa_annual_voting_survey` are expected?
And can you double check the differences in `firefox-xfa_imm1295e-page2`?

**Pull request merged**
