### PR TITLE
Try to skip mapping of missing TrueType and CIDFontType2 glyphs

### LINKED ISSUE #3652: font show error
pdf show error

pdf file
http://pan.baidu.com/share/link?shareid=2977317873&uk=1543899842

### LINKED ISSUE #5202: Astral code points are garbled
Characters in Unicode supplementary planes (such as 𠮟, 𩸽 and 𠀋) are garbled. To copy and paste them also brings garbled results.

[Test PDF](https://pdf.yt/d/YXXjGX-Pu5LP-DAr)
[XeLaTeX source code](https://gist.github.com/mandel59/92bef891c8bb763d73e8)

Expected:

Actual:

Environment: OS X 10.9.4, Firefox 31.0, PDF.js in mozilla/pdf.js master

### LINKED ISSUE #5664: rendered with vertical glyphs incorrectly
Some of characters in this pdf are garbled: [グローバル社会における郵便・信書便事業の制度設計等](http://www.soumu.go.jp/yusei/seido_minaoshi/pdf/070822_1_si1.pdf)

PDF.js (Firefox 35.0):

Preview (OS X):

### LINKED ISSUE #5681: In lastest pdf.js version, Some characters(Korean character) is not rendered
Some characters do not display correctly in the PDF.

It is rendered normally in other PDF readers, including Adobe Reader,

but in pdf.js does not look normal on chrome and IE 10 browser.

In my opinion, It is related to the embedding true type font file.

Screen Capture

https://www.dropbox.com/s/t7t0b991xztdb1o/AdobeVsPDFJS.jpg?dl=0

PDF File URL

https://www.dropbox.com/s/dw6n8tb8lim1ty6/example.pdf?dl=0

### LINKED ISSUE #5704: Ø (LATIN CAPITAL LETTER O WITH STROKE) doesn't appear
In this PDF: http://www.jazzbooks.com/mm5/download/FREE-nomenclature.pdf
the character Ø (U+00D8, LATIN CAPITAL LETTER O WITH STROKE) doesn't appear. Issue occurs on both Windows and Mac. Screenshots from http://mozilla.github.io/pdf.js/web/viewer.html and Adobe Reader:
pdfjs
adobereader

### PR DESCRIPTION
**Pull request by Snuffleupagus**
_This PR is based on a patch written by @brendandahl._

The first patch fixed most of the issues, and needed only a very minor adjustment to work correctly for fonts with a `CIDToGIDMap`.
However in some browsers (e.g. the release version of Firefox), the first patch caused a lot of `notdef` glyphs to appear in a number of the test files.
After quite a bit of debugging, I found that this was usually an issue with the way that the `space` character was mapped. In the problematic PDF files, `space` was usually mapped to various (low) control charCodes.

Since the `space` glyph (obviously) doesn't need any glyph data, and is thus empty, this causes it to be added to `missingGlyphs` by [`sanitizeGlyphLocations()`](https://github.com/mozilla/pdf.js/blob/master/src/core/fonts.js#L3489).
To work around this, I'm proposing that we also look at `toUnicode` when building the `charCodeToGlyphId` map. If the charCode exists in `toUnicode` the glyph is most likely needed, even if it's empty, hence we add it to the `charCodeToGlyphId` map. This lets [`adjustMapping()`](https://github.com/mozilla/pdf.js/blob/master/src/core/fonts.js#L2662), if necessary, move the charCode to the Private Use Area and thus fixing the issues with `notdef` being displayed.

I hope that this approach is reasonable (it passes all tests locally)!

Fixes #5202.
Fixes #5584.
Fixes #3652.
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1122998.
Fixes #5664.
Fixes #5681.
Fixes #5704.
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=893730.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
As far as I'm concerned, the test "failures" on Linux seem to be two kinds:
* Changes that are almost imperceivable to the naked eye.
* Changes that make the text render better.

/botio-linux preview

**Comment by Snuffleupagus** [comment]
@brendandahl @yurydelendik The list of regressions that will be fixed by this PR keeps growing, does anyone of you have time to review this?

**Comment by Snuffleupagus** [comment]
As far as I'm concerned, the test "failures" on Linux seem to be of two kinds:
 - Changes that are almost imperceivable to the naked eye.
 - Changes that make the text render better.

/botio-linux preview

**Comment by brendandahl** [comment]
Thanks for picking this up!

**Pull request merged**
