### PR TITLE
Fix for IE highlight bug due to lack of blending mode support

### PR DESCRIPTION
**Pull request by lochstar**
Issue discussed here: https://github.com/mozilla/pdf.js/issues/5264

### CODE REVIEW

**Comment by timvandermeij** [comment]
To be honest, this looks a bit like a hack to me. Why does this work exactly? Why the value 0.4? If there is a reasoning for this, we need to move this to `compatibility.js` as we do not like to have browser-specific code in the core.

**Comment by yurydelendik** [comment]
The proposed solution create a canvas for every annotation, it's waste of the memory -- the feature detection has to be done only once. The logic behind is not clear. If you are trying to polyfill ie canvas blend mode, please as the code to the web/compatibility.js -- the workarounds shall not be a part of the production code.

**Comment by lochstar** [comment]
Thanks for the feedback. A polyfill for compatibility.js makes a lot more sense.

**Comment by timvandermeij** [comment]
I'm closing this as it is not mergeable in the current state. However, @lochstar, if you are interested in making a polyfill for canvas blend mode for IE, then we are happy to review that pull request. Thank you!

**Pull request closed without merging**
