### PR TITLE
Update dependencies and translations to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
What's wrong with the latest Puppeteer version, since it seems that you "reverted" the version slightly?

**Comment by timvandermeij** [comment]
The slightly newer version didn't work on the bots because user contexts were implemented for the Webdriver BiDi implementation that we use for Firefox (see https://github.com/puppeteer/puppeteer/pull/11784), however on the Firefox side that was actually implemented quite recently in https://phabricator.services.mozilla.com/D198992. The Nightly version we have cached on the bots was from before that patch landed (because it's cached on version number and that stays at 124.0a1 until a new alpha version is created), so I decided to go back one version so we didn't have to await the version number to change.

However, I just figured now that we can also just purge the cached Nightly version for Linux and Windows from both bots. @calixteman Is that something you could do? If so, during the weekend I can redo this patch with a more recent Puppeteer version (and more recent translations if there are any new changes).

**Comment by calixteman** [comment]
@timvandermeij done.

**Pull request closed without merging**
