### PR TITLE
For images that include SMask/Mask entries, ignore an SMask defined in the current graphics state (bug 986450)

### LINKED ISSUE #6967: Image in PDF doesn't load
Tested in both Chrome and Firefox. Image in page 10 of the attached PDF (labeled page 8 in the document) doesn't load.

The Chrome native viewer and Adobe Reader both load the image properly.

[temp_portfolio658660046914130129 (1).pdf](https://github.com/mozilla/pdf.js/files/124118/temp_portfolio658660046914130129.1.pdf)

### LINKED ISSUE #7992: Image not shown in some pages on MANGA contents
Link to PDF file (or attach file here):
[AN_1000126_p100.pdf](https://github.com/mozilla/pdf.js/files/728428/AN_1000126_p100.pdf)

Configuration:
- Web browser and its version: doesn't seem browser specific
- Operating system and its version: any
- PDF.js version: current
- Is an extension:

Steps to reproduce the problem:
1.  Open the attached PDF
2.

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image
Even it's MANGA contents, images aren't shown.
(Most pages are OK, but it happens with this page only.)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### LINKED ISSUE #8136: Multi-layered PDF is not displayed properly
Link to PDF file : [17_BY400_PURL_working.pdf](https://github.com/mozilla/pdf.js/files/824905/17_BY400_PURL_working.pdf)

Configuration:
- Chrome 56.0.2924.87 (64-bit) (also confirmed on Safari 10, FF 51.0.1 (64-bit))
- Ubuntu 16.10 (also confirmed on Mac Os Sierra)
- PDF.js version: any (confirmed on 1.7.348, 1.5.188)

Steps to reproduce the problem:
1. Open attached file in demo viewer at https://mozilla.github.io/pdf.js/web/viewer.html
2. Scroll to page 3 (important!)

What is the expected behavior?
Note that there is a layer with the gradient (diagonal stripes) at the top-right part of the page:
image

What went wrong?
No gradient layer is rendered
image

### LINKED ISSUE #11666: pdf with backgroun image not shoing
Link to PDF file here: [test.pdf](https://github.com/mozilla/pdf.js/files/7492723/test.pdf)

Configuration:
- I tried in chrome , edge and firefox
- Windows 10 latest version
- PDF.js version latest I tried via the demo link :
- Is a browser extension:no

Steps to reproduce the problem:
1. open the file from the link above the background not showing 
2.

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### LINKED ISSUE #14200: Image not shown
Attach (recommended) or Link to PDF file here:
[PDFBOX-5307-reduced.pdf](https://github.com/mozilla/pdf.js/files/7425315/PDFBOX-5307-reduced.pdf)

This is reduced from [here](https://issues.apache.org/jira/browse/PDFBOX-5307). The problem is somehow related to softmask / transparency group.

Configuration:
- Web browser and its version: FF 93.0
- Operating system and its version: W10.0.19042.1288
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. open the file
2.

What is the expected behavior? (tried with Adobe Reader and Ghostscript)
grafik

What went wrong?
all white

### LINKED ISSUE #14296: Background image does not load for some PDFs
Attach (recommended) or Link to PDF file here:
[welzRkYrNV6JRO8q.pdf](https://github.com/wojtekmaj/react-pdf/files/7023899/welzRkYrNV6JRO8q.pdf)

Configuration:
- Web browser and its version: Any
- Operating system and its version: macOS Monterey
- PDF.js version: Tested on 2.12.69 (Firefox 95b7) and 2.12.201 ([standalone viewer](https://mozilla.github.io/pdf.js/web/viewer.html))
- Is a browser extension: n/a

Steps to reproduce the problem:
* Render this PDF using PDF.js
* Alternatively, you can also open in the 6 viewers mentioned above to see the difference.

What is the expected behavior? (add screenshot)

PDF should look like this:
yes

What went wrong? (add screenshot)
It displays a white background and this seems to be an issue in certain viewers. Here's are some other viewers I tested with,
where it works and where it fails:

Instead it renders like this:
no

_Originally raised by @anniebombanie in https://github.com/wojtekmaj/react-pdf/issues/832_

### LINKED ISSUE #14830: Missing image in PDF
Attach (recommended) or Link to PDF file here: [extracted_page.pdf](https://github.com/mozilla/pdf.js/files/8546955/extracted_page.pdf)

Configuration:
- Web browser and its version: Firefox Nightly 101.0a1
- Operating system and its version: Windows 11 Build 22000.613
- PDF.js version: v2.13.216
- Is a browser extension: No?

Steps to reproduce the problem:
1. Open the PDF with the built-in pdf.js in Firefox
   OR
   Open the PDF at https://mozilla.github.io/pdf.js/web/viewer.html in Edge
2. The trees image is missing.

What is the expected behavior? (add screenshot)
Adobe Acrobat:
Acrobat

What went wrong? (add screenshot)
PDF.js in both Firefox and Edge:
PDF.js

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### LINKED ISSUE #19240: [Bug]: Image in FormXObject with SMask is not rendered correctly
### Attach (recommended) or Link to PDF file

[test.pdf](https://github.com/user-attachments/files/18193476/test.pdf)

### Web browser and its version

Firefox 133.0.3

### Operating system and its version

Windows 11

### PDF.js version

Firefox built-in, pdfjs-dist@4.9.155

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the PDF in Firefox

### What is the expected behavior?

The PDF file has 4 pages.
Each page has a QR code image on top right corner.
When opened in Adobe Acrobat or Google Chrome, it appears well like:
image

### What went wrong?

When opened with Firefox, it looks like:
(only page 1 and 2 have the issue)
image

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Snuffleupagus**
From section [11.6.4.3 Mask Shape and Opacity](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#G10.4848628) in the PDF specification:
 - An image XObject may contain its own *soft-mask image* in the form of a subsidiary image XObject in the `SMask` entry of the image dictionary (see "Image Dictionaries"). This mask, if present, shall override any explicit or colour key mask specified by the image dictionary's `Mask` entry. Either form of mask in the image dictionary shall override the current soft mask in the graphics state.

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by THausherr** [comment]
Wow thank you @SehoAhn and @Snuffleupagus, I used this to fix https://issues.apache.org/jira/browse/PDFBOX-5307 .

**Pull request merged**
