### PR TITLE
[api-minor] Simplify how the list of points are structured

### PR DESCRIPTION
**Pull request by calixteman**
Instead of sending to the main thread an array of Objects for a list of points (or quadpoints), we'll send just a basic float buffer.
It should slightly improve performances (especially when cloning the data) and use slightly less memory.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Two questions:
 - Are the ref-test "failures" actually expected?
 - If so, what's the explanation for the changes?

**Comment by calixteman** [comment]
> Two questions:
> 
>     * Are the ref-test "failures" actually expected?
> 
>     * If so, what's the explanation for the changes?

I didn't expect the changes and their are due to the fact I chose to set the data in some `Float32Array` which makes the check failing:
https://github.com/mozilla/pdf.js/blob/17e09e54785ed09dd3417983c3ed4085e8ee1fa4/src/display/annotation_layer.js#L535-L539

So in last version of the patch I changed for `Float64Array`.
I think we don't need to have 64-bits precision here and 32-bits is enough but it can be done in a follow-up.
And it'll require to make few other changes especially when we test the equality of two numbers with different precisions or we could just try to pass every floating data  into `Float32Array` (which could make sense for `data.rect`).

**Comment by Snuffleupagus** [comment]
> I didn't expect the changes and their are due to the fact I chose to set the data in some `Float32Array` which makes the check failing:

Interesting, thank you!
*This leads me to a, potentially stupid, question:* Could we use `Float32Array` and utilize `Math.fround(...)` in that check?

**Comment by calixteman** [comment]
> > I didn't expect the changes and their are due to the fact I chose to set the data in some `Float32Array` which makes the check failing:
> 
> Interesting, thank you! _This leads me to a, potentially stupid, question:_ Could we use `Float32Array` and utilize `Math.fround(...)` in that check?

Yes (thx for the tip: I didn't know `fround`) or just use a `Float32Array` for the `data.rect`, but as said I think it's worth doing that in follow-up, or do you prefer we switch to 32-bits precision in this patch ?

**Comment by Snuffleupagus** [comment]
> [...] or just use a `Float32Array` for the `data.rect`,

Off the top of my head I cannot tell how much else that'd affect, so perhaps we shouldn't do that here.

My *untested* idea was that we'd use `Float32Array` as originally in this patch, and simply change https://github.com/mozilla/pdf.js/blob/95a7de9f986c449cb949d39af948dbe97f60948e/src/display/annotation_layer.js#L531 into
```javascript
const [rectBlX, rectBlY, rectTrX, rectTrY] = this.data.rect.map(e => Math.fround(e));
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Comment by timvandermeij** [comment]
Given that this is the first `[api-minor]` patch for the new release, could you create a patch to bump the library version to 4.4 with a reference to the merge commit of this patch, similar to https://github.com/mozilla/pdf.js/commit/3ff93ede07d3813244fef83097c88411dd2dec2a? Thanks!

**Pull request merged**
