### PR TITLE
Replace some ternary operators with optional chaining, and nullish coalescing, in the `src/display/`-folder

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This way, we can further reduce unnecessary code-repetition in some cases.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Given that PR #12874 has the *same exact* integration-test failure, and that PR only touches README-files, I don't think the failure is relevant here either.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thanks!

**Pull request merged**
