### PR TITLE
XFA - Layout correctly a subform with row layout (bug 1718740)

### PR DESCRIPTION
**Pull request by calixteman**
- Fix issues with subformSet elements which are not a real container.

### CODE REVIEW

**Comment by marco-c** [comment]
`firefox-xfa_issue13213-page2` and other pages of the same PDF lost the border on the right.

**Comment by calixteman** [comment]
Some lines are pretty small so sometimes depending on the zoom level and rounding errors the lines are drawn or not.
I checked for the one above and it's the case.

**Review by marco-c — APPROVED** [review]

**Pull request merged**
