### PR TITLE
Adds more characters to the PUA range

### PR DESCRIPTION
**Pull request by yurydelendik**
Trying to move more characters to the PUA range, adding chars from https://bugzilla.mozilla.org/attachment.cgi?id=8412717&action=diff#a/gfx/thebes/gfxPlatformFontList.cpp_sec1.

Total count of problematic codes now is 2718 (PUA can hold 6400)

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Looks good, thank you for the patch!

@yurydelendik Since I don't have a Mac; can you please go through and close the relevant bugs (if they were fixed by this patch)?
- [ ] #5540.
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1151216.
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1175943.

**Comment by CodingFabian** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1026437 looks fixed now for me using preview

**Comment by CodingFabian** [comment]
https://bug1151216.bugzilla.mozilla.org/attachment.cgi?id=8588312 is fixed

**Comment by CodingFabian** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1175943 fixed as well.

good work @yurydelendik

**Pull request merged**
