### PR TITLE
XFA - Add support for overflow element

### PR DESCRIPTION
**Pull request by calixteman**
- and fix few bugs:
    - avoid infinite loop when layout the document;
    - avoid confusion between break and layout failure;
    - don't add margin width in tb layout when getting available space.

### CODE REVIEW

**Comment by brendandahl** [comment]
@calixteman looks like some ref tests failed with this PR

**Comment by brendandahl** [comment]
Wiped out the bad cached file, let's try this again.
/botio-windows test

**Comment by Snuffleupagus** [comment]
@brendandahl It looks like this regressed *at least* `xfa_imm1344e-page1` in all browsers/platforms, and possibly the rest of that file as well, why was this landed as-is?

**Comment by brendandahl** [comment]
I mixed up the refs for that one (thought it was improving). Calixte has a fix in progress, so we'll just re-run with the fix.

**Pull request merged**
