### PR TITLE
Remove `waitForTimeout` usage from the helper functions

### PR DESCRIPTION
**Pull request by timvandermeij**
The commit messages contain more details about the individual changes.

Fixes a part of #17656.

### CODE REVIEW

**Comment by timvandermeij** [comment]
(The Linux failure above is unrelated to this patch because it doesn't use any of the touched helper functions, and is therefore one of the remaining intermittents to be fixed in a later scope.)

/botio integrationtest

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Review by calixteman — APPROVED** [review]
LGTM. Thank  you.

**Pull request merged**
