### PR TITLE
XFA - Fix the way to select page on breaking

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1716838.
  - some fonts in the pdf in the bug where bold when they shouldn't so write the font properties in the html to avoid to use some wrong inherited ones.

### CODE REVIEW

**Comment by brendandahl** [comment]
Looks like there's regressions on imm1344e and imm1295e.

**Comment by calixteman** [comment]
The diffs on `imm1344e` and `imm1295e` are expected: the first pageArea has a max set to 1 so the other pageArea must be used for other pages.

**Comment by marco-c** [comment]
> The diffs on imm1344e and imm1295e are expected: the first pageArea has a max set to 1 so the other pageArea must be used for other pages.

In page 2 and 4 of imm1295e there seems to be a regression. The header and footer of page 2 and page 4 should be like on page 5.

**Comment by calixteman** [comment]
There are some diff with `xfa_bug1716816.pdf` but it seems that this pdf is wrongly displayed (even before the patch).
I'll fix this pdf later.

**Review by marco-c — APPROVED** [review]

**Comment by Snuffleupagus** [comment]
Sorry, but why was this landed with a bunch of breaking error (which is also why `makeref` failed) such as e.g. the following in multiple tests!? 
```
TEST-UNEXPECTED-FAIL | test failed xfa_candidate_petitions | in chrome | page1 round 1 | Loading PDF document: UnknownErrorException: Cannot read property 'length' of undefined
```

This should probably be backed out, and then re-landed once fixed, to prevent testing being completely busted in the meantime!
(I'd suggest looking at not just the reference images, but *also* the actual test output when e.g. reviewing :-P)

**Comment by calixteman** [comment]
> (I'd suggest looking at not just the reference images, but _also_ at the actual test output when e.g. reviewing :-P)
It's the reason why I missed the failures... sorry for that.

**Comment by Snuffleupagus** [comment]
Since it's currently way too easy to *accidentally* overlook breaking errors in the test-output, we might want to include more information directly in the botio output; in case it's deemed helpful, I've just submitted https://github.com/mozilla/botio-files-pdfjs/pull/30

**Comment by marco-c** [comment]
> Since it's currently way too easy to accidentally overlook breaking errors in the test-output, we might want to include more information directly in the botio output

Totally agree!

**Pull request merged**
