### PR TITLE
Ensure that `test/driver.js` actually takes the same `Annotation` code-path as the viewer when running `forms` tests (PR 7633 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
_Please refer to the commit messages._

/cc @timvandermeij

### CODE REVIEW

**Review by timvandermeij — CHANGES_REQUESTED** [review]
I managed to track down why the input and textarea elements are not showing the text in the reference images. Take a look at the fiddle at https://jsfiddle.net/g13hLcha/1. It turns out that using `input.value = "foo";` only sets the value internally, but does not expose the `value` DOM attribute that the rasterizer needs for rasterization. What does work is `input.setAttribute("value", "foo");`. Could you try to change that and see if the reference images improve? If so, please incorporate it in this PR so we don't have a broken intermediate state. You can choose to use `setAttribute` everywhere in `annotation.js` or use it only for `value` as it's not directly required in the other places. In the latter case, please add a comment explaining why we need to do this and squash it into for example the second commit. In the former case, it might be better to create a new commit for that.

**Comment by Snuffleupagus** [comment]
> [...] Could you try to change that and see if the reference images improve?

That only seems to work for `<input>`, but unfortunately it's breaking for `<textarea>` in *both* the viewer and the tests  :-(
I'm not sure how we can fix this, and I don't really have time right now to attempt to fix/workaround it.
Could we just land this as, with a bullet point in the tracking issue about fixing the tests, since it seems to me that we've stumbled upon an pre-existing issue?

**Comment by Snuffleupagus** [comment]
@timvandermeij Thank you for the help in https://github.com/mozilla/pdf.js/pull/7647#issuecomment-248016670, it seems to do the trick both in the viewer/tests!

/botio-linux preview

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice work!

**Pull request merged**
