### PR TITLE
Ensure that `ChunkedStream` won't attempt to request data *beyond* the document size (issue 14303)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This bug was surprisingly difficult to track down, since it didn't just depend on range-requests being used but also on how quickly the document was loaded. To even be able to reproduce this locally, I had to use a very small `rangeChunkSize`-value (note the unit-test).

The cause of this bug is a bogus entry in the XRef-table, causing us to attempt to request data from *beyond* the actual document size and thus getting into an infinite loop.

Fixes *one* of the issues listed in issue #14303, namely the `PDFBOX-4352-0.pdf` document.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Based on https://github.com/mozilla/pdf.js/pull/14233#issuecomment-978149680 I believe that the Linux failures aren't caused by this patch.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for fixing this!

**Pull request merged**
