### PR TITLE
Update puppeteer to 22.3.0

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
As far as I can tell, the latest version is `22.3.0` as of this writing so please update to that one rather than doing an "intermediate" update.
(If there's a reason for not doing a "full" update then please amend the commit message to explain why.)

**Comment by calixteman** [comment]
My bad, I just update to the version mentioned here by @timvandermeij:
https://github.com/mozilla/pdf.js/pull/17685#issuecomment-1950279164

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks.

**Pull request merged**
