### PR TITLE
Overwrite maxSizeOfInstructions in maxp with computed value.

### LINKED ISSUE #7507: Some of the Devnagri Fonts not being rendered properly
Link to PDF file:  [2007-01-SB_CMYK.pdf](https://github.com/mozilla/pdf.js/files/382169/2007-01-SB_CMYK.pdf)

**Configuration:**
- Web browser and its version: Chrome (Version 51.0.2704.103 m) and Mozilla Firefox 47.0
- Operating system and its version: Windows 10 Pro
- PDF.js version: 1.5.355
- Is an extension: N/A

**Steps to reproduce the problem:**
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the attached PDF (2007-01-SB_CMYK.pdf) file to reproduce the error.

**What is the expected behavior?**
I have attached correct display of the PDF file below which is showing up the text without any issue before being rendered by pdf.js
before-being-rendered

**What went wrong?**
Some of the text are not being rendered properly. We are using SHREE-DEV Devnagri Fonts which are freely available at http://www.abstractfonts.com/search/shree-dev-0714%20download for download. I have included the screenshot of the PDF file which is being rendered incorrectly.
fonts-issue-01

**Chrome Error Console Output:**

```
Warning: Failed to load font "g_d0_f2": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
Warning: Failed to load font "g_d0_f4": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
Warning: Failed to load font "g_d0_f6": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
Warning: Failed to load font "g_d0_f10": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
Warning: Failed to load font "g_d0_f11": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
```

### PR DESCRIPTION
**Pull request by brendandahl**
In issue #7507 the value is less than the actuall max size
of the glyph instructions causing OTS to fail the font.

Fixes #7507

### CODE REVIEW

**Comment by brendandahl** [comment]
Forgot the pdf file :( 
/botio test

**Review by Snuffleupagus — APPROVED** [review]
Looks good to me, thank you for fixing this!

**Pull request merged**
