### PR TITLE
Re-factor the `arraysToBytes` helper function (PR 16032 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
- Change `WorkerTasks`, in `WorkerMessageHandler.createDocumentHandler`, to a use a Set

   This is a tiny bit more compact, thanks to the `Set.prototype.delete` method.

 - Re-factor the `arraysToBytes` helper function (PR 16032 follow-up)

   Currently this helper function only has two call-sites, and both of them only pass in `ArrayBuffer` data. Given how it's implemented there's a couple of code-paths that are completely unused (e.g. the "string" one), and in particular the intended fast-paths don't actually work.
   This patch re-factors and simplifies the helper function, and it'll no longer accept anything except `ArrayBuffer` data (hence why it's also re-named).

   Note that at the time when `arraysToBytes` was added we still supported browsers without TypedArray functionality, and we'd then simulate them using regular Arrays.

 - Move the `arrayBuffersToBytes` helper function into the worker-thread

   Given that this helper function is only used on the worker-thread, there's no reason to duplicate it in both of the *built* `pdf.js` and `pdf.worker.js` files.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
For the MOZCENTRAL build, this PR saves about `1.3 kB` in bundle size (which isn't a lot but still can't hurt).

**Review by timvandermeij — COMMENTED** [review]
While the changes themselves look good, seeing where this function is used it would be good to have some (simple) unit tests for this function given that it's currently uncovered in https://github.com/mozilla/pdf.js/blob/master/test/unit/util_spec.js, just to make sure we handle the regular and fasts paths correctly.

**Comment by Snuffleupagus** [comment]
> [...] seeing where this function is used it would be good to have some (simple) unit tests for this function given that it's currently uncovered

That's a fair comment; I've added a couple of basic unit-tests :-)

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice work!

**Pull request merged**
