### PR TITLE
Improve compression of PNG images embedded in generated SVG files

### PR DESCRIPTION
**Pull request by Rob--W**
Fixes issue #8560 for Node.js.

The first four commits are refactorings, the last one contains the actual fix (read its commit message for the motivation for the fix, test steps and suggestions for future improvements).

### CODE REVIEW

**Review by yurydelendik — APPROVED** [review]
Thank you for the patch.

**Comment by Rob--W** [comment]
FYI, I rebased the branch to account for the change from #8630.
@yurydelendik You approved the changes. Is it good to merge?

**Comment by yurydelendik** [comment]
> You've approved the changes. Is it good to merge?

Yes. (it was kind of r+)

**Comment by timvandermeij** [comment]
Awesome work!

**Comment by Snuffleupagus** [comment]
When running the unit-tests locally (in Firefox), either with `gulp unittest` or directly in the browser with http://localhost:8888/test/unit/unit_test.html, one of the newly added unit-tests isn't working as expected with `SPEC HAS NO EXPECTATIONS should produce a svg:image even if zlib is unavailable` displayed in the results.

My first guess was that it was simply a problem with the unit-tests being asynchronous, but missing the required `done` calls to make sure that we wait for each unit-test to complete properly; i.e. like so:
```diff
diff --git a/test/unit/display_svg_spec.js b/test/unit/display_svg_spec.js
index 515e59fe..ccd89f79 100644
--- a/test/unit/display_svg_spec.js
+++ b/test/unit/display_svg_spec.js
@@ -101,7 +101,7 @@ describe('SVGGraphics', function () {
       });
     }
 
-    it('should produce a reasonably small svg:image', function() {
+    it('should produce a reasonably small svg:image', function(done) {
       if (!isNodeJS()) {
         pending('zlib.deflateSync is not supported in non-Node environments.');
       }
@@ -117,10 +117,12 @@ describe('SVGGraphics', function () {
         // Without zlib (uncompressed), the size of the data URL was excessive
         // (80247).
         expect(imgUrl.length).toBeLessThan(367);
-      });
+        done();
+      }).catch(done.fail);
     });
 
-    it('should produce a svg:image even if zlib is unavailable', function() {
+    it('should produce a svg:image even if zlib is unavailable',
+        function(done) {
       withZlib(false, getSVGImage).then(function(svgImg) {
         expect(svgImg.nodeName).toBe('svg:image');
         expect(svgImg.getAttribute('width')).toBe('200px');
@@ -129,7 +131,8 @@ describe('SVGGraphics', function () {
         expect(imgUrl).toMatch(/^data:image\/png;base64,/);
         // The size of our naively generated PNG file is excessive :(
         expect(imgUrl.length).toBe(80247);
-      });
+        done();
+      }).catch(done.fail);
     });
   });
 });
```
Having made the above changes locally, which are necessary to ensure that the tests work correctly, the same test now fail consistently with `Failed: Requesting object that isn't resolved yet [object Object]`.

@Rob--W I don't really have time to delve deeper into this right now, so I'd appreciate if you could take a look!

**Pull request merged**
