### PR TITLE
Remove glyph id's outside the range of valid glyphs.

### LINKED ISSUE #5564: Stray squares are displayed
This is a regression. Squares are displayed where there should be empty space.

URL: http://www.love-to-dance.dk/stepsheets/A%20touch%20of%20Rumba.pdf
1.0.1017: http://i.imgur.com/hrjYRD0.png
0.8.990: http://i.imgur.com/64NnupX.png

b5b94a4af389ef387570cf22662d9fc6bd41417a is the first bad commit
commit b5b94a4af389ef387570cf22662d9fc6bd41417a
Author: Brendan Dahl
Date:   Tue Feb 11 10:27:09 2014 -0800

    Use built in CMaps and unify the glyph mapping.

Console log:
> downloadable font: cmap: Range glyph reference too high (2 > 1) (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIGlmNpAAAACcAAAA1k9T (...)

### PR DESCRIPTION
**Pull request by brendandahl**
OTS does not like invalid glyph ids in a camp table.
Fixes issues with warning "Range glyph reference too high"

Fixes #5564, #6648, #3483, #5702, #6343, #5690. Maybe more, we should look for people talking about boxes appearing.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Really nice patch!

r=me, provided that the tests pass, and with the PDF file added to [.gitignore](https://github.com/mozilla/pdf.js/blob/master/test/pdfs/.gitignore).

**Comment by timvandermeij** [comment]
Nice indeed! It also fixes #6312.

**Comment by timvandermeij** [comment]
Awesome work, thank you!

**Comment by dangquang1020** [comment]
I use the latest version and this issue still there.

**Pull request merged**
