### PR TITLE
[Editor] Avoid to darken the current editor when opening the alt-text dialog

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
We should disable zooming with the mouse when the dialog is displayed because it leads to some inconsistencies.

**Comment by Snuffleupagus** [comment]
This looks *much* nicer/better, since it clearly focuses on the active image!

*One small question, although I'd guess that it's a wontfix since it's an edge-case that might be annoying to fix in general:*
If you add a fairly large image, I used [this one](https://github.com/mozilla/pdf.js/blob/master/test/images/firefox_logo.png), such that the entire image won't fit on screen at once, when opening the altText dialog the mask may also "include" part of the viewer toolbar.

toolbar-overlay

**Comment by calixteman** [comment]
> This looks _much_ nicer/better, since it clearly focuses on the active image!
> 
> _One small question, although I'd guess that it's a wontfix since it's an edge-case that might be annoying to fix in general:_ If you add a fairly large image, I used [this one](https://github.com/mozilla/pdf.js/blob/master/test/images/firefox_logo.png), such that the entire image won't fit on screen at once, when opening the altText dialog the mask may also "include" part of the viewer toolbar.
> 
Yep I thought about this case. A way to solve it, would be to take into account only the really visible part of the editor which should be possible but probably more work (we should take into account the toolbar, margins, ...) or maybe there's a smart trick we could use.

**Review by Snuffleupagus — APPROVED** [review]
r=me, this looks great; thank you!

**Pull request merged**
