### PR TITLE
Split underline, strikeout, squiggly annotions div into multiple divs

### PR DESCRIPTION
**Pull request by calixteman**
* Follow up of #12505
 * Fix bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1679696

### CODE REVIEW

**Comment by calixteman** [comment]
The user (in bug 1679696) shared privately the PDF and this patch fix the issue.
The div for strikeout is over the div for some highlights, so splitting them fix the issue.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice work! I actually had this exact same patch stashed locally, but got distracted with another edge case that we need to fix. I'll make a patch for that later which will also include a minimal reference test case for all these annotations, but I can confirm that this patch indeed also fixes the normal cases in that file.

/botio makeref

**Pull request merged**
