### PR TITLE
Added the data-page-number dom attribute to the page rendered in the browser

### PR DESCRIPTION
**Pull request by mbbaig**
Added data-page-id attribute to page container divs

Updated the attribute with a better label

### CODE REVIEW

**Comment by timvandermeij** [comment]
Looks good. Fixes #5766. I do wonder though: now that we have this, do we still need the ID for every container (i.e., `pageContainer1`, `pageContainer2`, et cetera)? It seems like this `data` attribute is much better for querying and for the display styles we have the class, so is the ID even used?

**Comment by yurydelendik** [comment]
@timvandermeij we don't need it... unless somebody already started using/parsing it

**Comment by mbbaig** [comment]
is that not used anywhere within the library itself?

**Comment by yurydelendik** [comment]
I don't think so, it was just carried from demo viewer created at https://github.com/mozilla/pdf.js/commit/c828fdd2cab6c4b71246c35f5c47aaf10b816c97

**Comment by timvandermeij** [comment]
Personally I think it is best to encourage developers to start using `data-page-number` instead of parsing the ID (which is a bit ugly anyway in my opinion), but I can also imagine that you do not want to get rid of it immediately. Shall we remove it or keep it for now?

**Comment by yurydelendik** [comment]
Let's remove

**Comment by mbbaig** [comment]
Okay good. Cause I already removed it and pushing the code.

**Comment by yurydelendik** [comment]
Found pageContainer usage at http://mxr.mozilla.org/mozilla-central/source/browser/extensions/pdfjs/test/browser_pdfjs_zoom.js , if we going to land this we need to change the test in m-c too

**Comment by mbbaig** [comment]
@yurydelendik So that is curruntly located here https://github.com/mozilla/gecko-dev/blob/master/browser/extensions/pdfjs/test/browser_pdfjs_zoom.js#L112 on GitHub. It that the repo that I should change?

**Comment by yurydelendik** [comment]
let's remove the latter change from this pr and open different issue to fix test first

**Comment by timvandermeij** [comment]
@mbbaig Could you change the commit such that only https://github.com/mbbaig/pdf.js/commit/9643750f02770ff6dbff0e0d8e13140fa7dc5a40#diff-c880b70cf7d6b97863eeb665a736c4baR82 remains? Maybe it's easiest to add back https://github.com/mbbaig/pdf.js/commit/9643750f02770ff6dbff0e0d8e13140fa7dc5a40#diff-c880b70cf7d6b97863eeb665a736c4baL79 and then squash the commits. With only the `data-page-number` addition this PR should be good to go; we can fix the ID removal with tests in a follow-up issue/PR.

**Comment by mbbaig** [comment]
I added the 'id' tag back so it can associated with a different issue. The commits have also been cleaned up to only show the required addition.

**Comment by timvandermeij** [comment]
Thank you for the patch!

**Pull request merged**
