### PR TITLE
Replace the test-case for issue 8798 with a reduced one (PR 8800 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Re: issue #8798 and PR #8800.*

Big thanks to @THausherr for providing the test-case.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Since we're *replacing* a linked test-case with a reduced one, the "failures" are to be expected :-)

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you!

**Pull request merged**
