### PR TITLE
Remove gloss on zoom dropdown in Safari

### PR DESCRIPTION
**Pull request by MichielDG**
Screenshot-pdf js-Safari

### CODE REVIEW

**Comment by timvandermeij** [comment]
Looks good, but could you amend the commit message to `Remove gloss on zoom dropdown in Safari` to make it more specific and a bit more neutral?

**Comment by Snuffleupagus** [comment]
Besides https://github.com/mozilla/pdf.js/pull/11517#issuecomment-575801291, there's also the question if this is actually a desirable change given that it looks worse in Google Chrome now (given that there's a Chrome extension built from the PDF.js project):

zoom

**Comment by timvandermeij** [comment]
I didn't check in Google Chrome, but that is indeed a regression. Chrome has a lot more users and we also build an extension for Chrome, so a fix for the gloss in Safari should also only apply to Safari. If you can make this patch only apply to Safari, we can accept it, but otherwise we need to close it unfortunately.

**Comment by timvandermeij** [comment]
I looked at this again and found that a solution for this can only be accepted if it only applies to Safari, hence it's unfortunately not mergeable in its current state. Closing because of that, but we'll be happy to look at a new PR if there is a way to only make this work for Safari. Thanks.

**Pull request closed without merging**
