### PR TITLE
Adds transfer function support for SMask.

### LINKED ISSUE #5044: PDF rendering issue (incorrect in FF30; correct in FF24)
I have an example PDF which renders correctly in FF24, but incorrectly in FF30.

http://hochhaus.us/HeadBodyFoot.pdf (attached [HeadBodyFoot.pdf](https://github.com/mozilla/pdf.js/files/52162/HeadBodyFoot.pdf) )

This PDF contains three logical entities (a header, a body and a footer). When rendered in Adobe Reader, Chrome's built in reader, PDF.js in FF24 and Apple Preview all three entities are visible. For example:

correct

However, when rendered from PDF.js in FF30 only the footer is visible. For example:

incorrect

Without knowing anything about PDF.js my guess would be that this has something to do with how different "regions" of the PDF are cropped. Is this the type of issue that the PDF.js team is interested in resolving? If so, what can I do to provide more helpful debugging information?

### PR DESCRIPTION
**Pull request by yurydelendik**
Fixes #5044 

TODO:
- [x] ask for permission to include the PDF file as a test

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Nicely done!

Also fixes #5118 and https://bugzilla.mozilla.org/show_bug.cgi?id=960462.

**Comment by Snuffleupagus** [comment]
Hopefully the test failure was just some kind of weird intermittent issue.

/botio-linux test

**Comment by yurydelendik** [comment]
very strange (after restarting botio-linux)

/botio-linux test

**Comment by Snuffleupagus** [comment]
Looks good, thank you for fixing this!

/botio makeref

**Pull request merged**
