### PR TITLE
Add different code-paths to `{CMap, ToUnicodeMap}.charCodeOf` depending on length, since `Array.prototype.indexOf` can be extremely inefficient for very large arrays (issue 8372)

### LINKED ISSUE #8372: Cannot open certain PDF file
Link to PDF file (or attach file here):
[扶摇政纲·年度计划.pdf](https://github.com/mozilla/pdf.js/files/975072/default.pdf)

Configuration:
- Web browser and its version: Chrome 58.0.3029.96
- Operating system and its version: Windows 15063.250
- PDF.js version: 1.7.225
- Is an extension: no

What went wrong? (add screenshot)
Cannot display pages other the first page

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #8372.

### CODE REVIEW

**Review by yurydelendik — APPROVED** [review]
Looks good

**Comment by Snuffleupagus** [comment]
@yurydelendik Thank you for the review!

I realized that I made a stupid mistake: Since `for...in` stringifies the indices, we need to convert the result back to integers in order for the method to have consistent return types; please see the interdiff:
```diff
diff --git a/src/core/cmap.js b/src/core/cmap.js
index abe2756b..0c9faa4e 100644
--- a/src/core/cmap.js
+++ b/src/core/cmap.js
@@ -307,7 +307,7 @@ var CMap = (function CMapClosure() {
       }
       for (let charCode in map) {
         if (map[charCode] === value) {
-          return charCode;
+          return (charCode | 0);
         }
       }
       return -1;
diff --git a/src/core/fonts.js b/src/core/fonts.js
index 4ed6f90f..3a2d361b 100644
--- a/src/core/fonts.js
+++ b/src/core/fonts.js
@@ -292,7 +292,7 @@ var ToUnicodeMap = (function ToUnicodeMapClosure() {
       }
       for (let charCode in map) {
         if (map[charCode] === value) {
-          return charCode;
+          return (charCode | 0);
         }
       }
       return -1;
```

**Pull request merged**
