### PR TITLE
Update .gitattributes

### LINKED ISSUE #2332: JavaScript files incorrectly reported as Java
Take a look at the language statistics for https://github.com/mozilla/pdf.js. It says "Java 85.9%", but in fact there is not a single line of Java in the repository: it's all JavaScript. Interestingly, if you click that percentage, you end up at https://github.com/mozilla/pdf.js/search?l=java, which shows only six files: not by far 85.9%.

This bug is new and occurred approx. a few weeks ago. A friendly GitHub staff member asked me to create an issue for this here and pointed out that Linguist might be confused by Mozilla's way of tagging files for various editors. See https://github.com/mozilla/pdf.js/blob/ba8a4f2b3e2ac3f0eb9c4ab59eedb9e0072ad52b/test/driver.js#L1 for example: the first line of all our JavaScript files starts with 'Mode: Java'.

### PR DESCRIPTION
**Pull request by arfon**
Fixes https://github.com/github/linguist/issues/2332

### CODE REVIEW

**Comment by CodingFabian** [comment]
LGTM +1

**Comment by Snuffleupagus** [comment]
We've got a number of `.jsm` files in the repo, and those need to be recognised as JavaScript too.
@arfon Could you please *amend* the commit to also cover the `*.jsm` case; and also please update the commit message to something a little more descriptive, e.g.
`Update .gitattributes to fix GitHub file type detection for JavaScript`.

**Comment by arfon** [comment]
@Snuffleupagus done.

**Comment by Snuffleupagus** [comment]
Thank you for the patch!

**Comment by CodingFabian** [comment]
works :-)

**Pull request merged**
