### PR TITLE
Use Array.isArray in the LoopbackPort.

### PR DESCRIPTION
**Pull request by yurydelendik**
For better serialization of Arrays that belong to different sandboxes.

See also http://logs.glob.uno/?c=mozilla%23pdfjs#c66373

/cc @tobytailor

### CODE REVIEW

**Comment by timvandermeij** [comment]
Indeed, wouldn't just changing https://github.com/mozilla/pdf.js/blob/master/src/shared/util.js#L1097 suffice here? For the polyfill we can use `core-js` since we already use it for clamped arrays.

**Comment by yurydelendik** [comment]
> Can we use Array.isArray everywhere?

Maybe. There are too many places to check if they will work as expected when changed. For now I'm just addressing regression (and hope will not add another one :).

**Comment by yurydelendik** [comment]
> For IE9, a polyfill can be added to compatibility.js.

Per MDN, Array.isArray is implemented in IE9

**Comment by Rob--W** [comment]
Even better. Then we don't need a polyfill at all.

**Review by Snuffleupagus — APPROVED** [review]
This seems fine, but it now needs a rebase :-)

r=me, with passing tests.

**Pull request merged**
