### PR TITLE
[Editor] Avoid to have duplicated entries in the Annot array when saving an existing and modified annotation

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
I'm assuming that there's no easy way to test this?

r=me, thank you!

**Comment by calixteman** [comment]
> I'm assuming that there's no easy way to test this?

I was ready to write "Yes" and then I thought "I already did something like that"...
Here's a test in the last version of this patch.

**Pull request merged**
