### PR TITLE
Add a parameter to the `isName` function that enables checking not just that something is a `Name`, but also that the actual `name` properties matches

### PR DESCRIPTION
**Pull request by Snuffleupagus**
_Please refer to the individual commit messages._

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
It seems that all the test failures are either intermittent (and thus tracked in #7542), and/or issues that should be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1292870 (which isn't uplifted to Firefox 50 yet).

**Comment by timvandermeij** [comment]
Looks good to me too. The test failures are not caused by the PR and are tracked in the mentioned issues. Thanks!

**Pull request merged**
