### PR TITLE
XFA - Avoid to have containers not pushed in the html

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix issue #13668.

### CODE REVIEW

**Review by marco-c — APPROVED** [review]

**Comment by Snuffleupagus** [comment]
Hmm; given that *both* browsers timed-out on *both* of the bots during the tests above, see https://github.com/mozilla/pdf.js/pull/13716#issuecomment-877836304 and https://github.com/mozilla/pdf.js/pull/13716#issuecomment-877836572, how do we know that this doesn't cause a bunch of breakage/regressions!?

**Comment by calixteman** [comment]
My bad, I missed that... I checked locally that everything was good and it was.
Anyway, do you prefer I revert and then push again, test, ... ?

**Comment by marco-c** [comment]
> Hmm; given that both browsers timed-out on both of the bots during the tests above, see #13716 (comment) and #13716 (comment), how do we know that this doesn't cause a bunch of breakage/regressions!?

Where can I see an indication that they timed out?

**Comment by Snuffleupagus** [comment]
> I checked locally that everything was good and it was.

Strange, for me this patch actually times-out locally as well.

> Where can I see an indication that they timed out?

There's a `errors: 1238` respectively `errors: 1226` printed in https://github.com/mozilla/pdf.js/pull/13716#issuecomment-877836304 respectively https://github.com/mozilla/pdf.js/pull/13716#issuecomment-877836572, and those kind of (general) errors should never appear when testing a working patch. After that, following the "Full output at..." links, the reference tests end with:
```
TEST-UNEXPECTED-FAIL | test failed firefox has not responded in 120s
TEST-UNEXPECTED-FAIL | test failed chrome has not responded in 120s
```

**Comment by marco-c** [comment]
> There's errors: 1238 respectively errors: 1226 printed in #13716 (comment) respectively #13716 (comment), and those kind of (general) errors should never appear when testing a working patch. After that, following the "Full output at..." links, the reference tests end with:

Could the bot surface the "has not responded" errors in the comment or the HTML output?

**Comment by Snuffleupagus** [comment]
@calixteman I've tested this patch locally, in the viewer (with `enableXfa = true` set), and `xfa_bug1717668_2` causes the browser (or tab rather) to hang (with full CPU utilization of one core) and the document doesn't render.

---

> Could the bot surface the "has not responded" errors in the comment or the HTML output?

But as mentioned this is already indirectly visible, via the `errors: {number here}` lines, since those should *never* appear and that's thus a clear indication to look at the full logs.

**Comment by calixteman** [comment]
The same for me locally... I was sure I tested (and I'm still sure) but obviously I didn't.

**Pull request merged**
