### PR TITLE
Complete romanian translation

### PR DESCRIPTION
**Pull request by totpero**
add missing translation

### CODE REVIEW

**Comment by flodolo** [comment]
Thanks for the contribution, unfortunately this is not the way to provide localization for this project.

We should update the README to explain that localization is only possible via Pontoon (this is a file within Firefox)
https://pontoon.mozilla.org/ro/firefox/toolkit/toolkit/pdfviewer/viewer.ftl/?status=missing&string=286363

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Thanks for the patch, however we unfortunately cannot accept this as outlined in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md:
> Note that the translations for PDF.js in the l10n folder are imported from the Nightly channel of Mozilla Firefox, such that we don't have to maintain them ourselves. This means that we will not accept pull requests that add new languages and/or modify existing translations, unless the corresponding changes have been made in Mozilla Firefox first.

**Comment by marco-c** [comment]
@flodolo could you point to the docs so @totpero can submit his changes in the right way?

**Comment by flodolo** [comment]
There is no document at the moment, but:
* You log in to Pontoon with a Mozilla account.
* Submit suggestions with the link I provided above.
* Wait for a translator or manager (for Romanian) to approve the suggestions.

If that doesn't happen within a couple of weeks, ping the project manager (see [header at the top of the page](https://pontoon.mozilla.org/projects/firefox/)) and we'll look into it (looks like Romanian is not very active).

**Comment by totpero** [comment]
Hi @flodolo , @Snuffleupagus and @marco-c ,
Thanks for your prompt replay.
I submit this pull request because after last major update v4.0 I notice that in Mozilla browser I get this error:
image
and after some investigations I found that the missing of localization texts this error appear many time in console.
I think that this error is in other languages/localization.

**Comment by totpero** [comment]
> Thanks for the contribution, unfortunately this is not the way to provide localization for this project.
> 
> We should update the README to explain that localization is only possible via Pontoon (this is a file within Firefox) https://pontoon.mozilla.org/ro/firefox/toolkit/toolkit/pdfviewer/viewer.ftl/?status=missing&string=286363

Hi @flodolo I compleate this also... Thanks 👍

**Pull request closed without merging**
