### PR TITLE
shading-pattern: Decreased `Shadings.SMALL_NUMBER`

### LINKED ISSUE #6298: Axial shading (type 2) too small
https://issues.apache.org/jira/secure/attachment/12690132/Shading2Function2text.pdf

The vertical size is too small.

### PR DESCRIPTION
**Pull request by dsprenkels**
Fixes #6298.

### CODE REVIEW

**Comment by dsprenkels** [comment]
By the way: this change breaks test `issue1133-page4`, but I think this is intentional.

**Comment by timvandermeij** [comment]
Is there documentation about this "small number" somewhere, i.e., in a specification or other document? If this also works in Chrome, I think we can remove that from the comment right above this variable.

**Comment by Snuffleupagus** [comment]
> Is there documentation about this "small number" somewhere, i.e., in a specification or other document? If this also works in Chrome, I think we can remove that from the comment right above this variable.

It was introduced by PR #1809, so I'd suggest asking @brendandahl if he remembers more about the context.

**Comment by yurydelendik** [comment]
I'm thinking will we go for it. I'm sure Chrome improved graphics backend to not trip on this. (if it still does we will handle it as a regression and we will see how to make this number below 1e-4 - possible amount of rows/columns on modern displays). That said, the comment above needs to be changed to reflect that.

**Comment by brendandahl** [comment]
As the comment suggests, I found the number by just testing what works. If it's working fine in chrome now, I'm fine with changing it.

**Comment by timvandermeij** [comment]
Landed in #6843. Thank you for the patch, @dsprenkels!

**Comment by gsampath127** [comment]
Can anyone please answer this questions
 Can you please describe the issue in detail?
 Do we know if there was anything unique about the PDF, that PDF.js could not resolve or is it something related to the zoom in level or any known issue?

**Comment by dsprenkels** [comment]
@gsampath127 
> Do we know if there was anything unique about the PDF, that PDF.js could not resolve or is it something related to the zoom in level or any known issue?

#6298 was about a PDF file containing a large shading pattern (gradient). The glitch was in [pattern.js](https://github.com/timvandermeij/pdf.js/blob/90ec2c9294409b19b983c1988f89bc5f385d108d/src/core/pattern.js), the code that evaluates the PDF file to drawing instructions, so it was not related to the zoom level.

> Can you please describe the issue in detail?

When we translate a PDF shading pattern to canvasGradient colorStops, [we build to a list of ten colorsStops from the beginning of the shading to the end](https://github.com/timvandermeij/pdf.js/blob/90ec2c9294409b19b983c1988f89bc5f385d108d/src/core/pattern.js#L175-L181).
When the PDF file says `extendStart: false` (or `extendEnd: false`) for the shadingPattern, we must always make sure the pattern is transparent at the beginning. This is done by [adding a transparent `colorStop` right at the start of the shading](https://github.com/timvandermeij/pdf.js/blob/90ec2c9294409b19b983c1988f89bc5f385d108d/src/core/pattern.js#L192), and [correcting the offset of the colorStop that was originally at the start](https://github.com/timvandermeij/pdf.js/blob/90ec2c9294409b19b983c1988f89bc5f385d108d/src/core/pattern.js#L193). Note that this transition from transparent to colour should be too small to notice. However, the first colorStop was moved 0.01 (=1%) (this is the `Shadings.SMALL_NUMBER` we are talking about) of the pattern space. This does not seem like a lot, but for a pattern that is 1000px wide, the user can clearly see a transition:

screenshot from 2016-01-07 11 01 25

So we changed `Shadings.SMALL_NUMBER` to 0.000001 (=0.0001% of the space). This transition is so small, that even if we have huge shading patterns, we won't see a transition (which is what we want). :smiley:

**Pull request closed without merging**
