### PR TITLE
Use cursor:move for draggable texts and drawings (Bug 1804252)

### LINKED ISSUE #16194: Simplify our css in using :is or :where
For reference:
 - https://developer.mozilla.org/en-US/docs/Web/CSS/:is
 - https://developer.mozilla.org/en-US/docs/Web/CSS/:where

### PR DESCRIPTION
**Pull request by nchevobbe**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Will this simply be ignored in browsers that doesn't support it, or do we need to increase the minimum supported Google Chrome version (for the general PDF.js library)?

 - https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
 - https://developer.mozilla.org/en-US/docs/Web/CSS/:is#browser_compatibility

**Comment by calixteman** [comment]
In considering that safari 14.1 and node.js 16 are from 2021 and Chrome 87 is from Nov 2020, I suppose we could consider increasing to 88 (which is from Jan 2021). 
It's just my opinion, I have absolutely no idea on how the Chrome users are using pdf.js and with which version...

**Comment by Snuffleupagus** [comment]
> In considering that safari 14.1 and node.js 16 are from 2021 and Chrome 87 is from Nov 2020, I suppose we could consider increasing to 88 (which is from Jan 2021). It's just my opinion, I have absolutely no idea on how the Chrome users are using pdf.js and with which version...

Given what part of the CSS *this patch* touches, we can probably ignore these things for now (and defer until we start using `:is()` and `:where()` generally in the viewer).

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Pull request merged**
