### PR TITLE
work around webkit bug that coalesces multiple spaces

### PR DESCRIPTION
**Pull request by AaronSherwoodForest**
https://bugs.webkit.org/show_bug.cgi?id=112032
https://github.com/mozilla/pdf.js/issues/8935

I ran lint and the tests locally, but 1/465 unit tests is failing whether I use "master" or my feature branch.

### CODE REVIEW

**Review by Snuffleupagus — COMMENTED** [review]
Generally we do not add browser/environment specific compatibility hacks in core code. The reason is first of all that this would often have a negative impact on performance, even in browsers where the bug isn't present. Secondly, it often also hurts readability/maintainability of the code in question.

In a custom implementation of PDF.js you can obviously do this, but personally I'm not convinced that the patch would be a good idea in the PDF.js repo (at least not in its current form).

**Comment by yurydelendik** [comment]
Is this solution complete? Are we sure that safari only removes double spaces and not touching leading spaces?

**Comment by SnailCoil** [comment]
Thanks yury, I think your concern was spot on. I updated the logic.

Snuffleupagus, I completely understand that reasoning. I'm content to close the PR and linked issue, and people will be able to follow the issue to see this specific workaround, since this should be fixed in webkit. However, you mentioned "(at least not in its current form)"--is there a reasonable way to rework this PR to make it optional for people who need to work around the webkit bug?

**Comment by timvandermeij** [comment]
I'm going to close this pull request, but we can keep the issue open for tracking purposes. Indeed we do not wish to have browser-specific hacks in the core code. Custom deployments may add this, but I don't think we should add it in PDF.js repository.

**Pull request closed without merging**
