### PR TITLE
Update dependencies and translations to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**
The Puppeteer update should unblock #17962; see https://github.com/mozilla/pdf.js/issues/17961#issuecomment-2160492481 and the comment below it. It also comes with newer Chrome and Firefox versions; this might lead to reference image differences.

### CODE REVIEW

**Comment by timvandermeij** [comment]
The Firefox update on Linux caused a lot of reference image "failures", but I went over most of them and couldn't spot any meaningful differences with the naked eye. All of them appear to be (sub)pixel differences in rendering.

**Comment by calixteman** [comment]
> The Firefox update on Linux caused a lot of reference image "failures", but I went over most of them and couldn't spot any meaningful differences with the naked eye. All of them appear to be (sub)pixel differences in rendering.

Yep it's my impress to.

**Review by calixteman — APPROVED** [review]
Thank you.

**Pull request merged**
