### PR TITLE
Use CMap in Type0 fonts when CFF is not a CID font

### LINKED ISSUE #9534: PDF.js does not render correctly
Attach (recommended) or Link to PDF file here: 
[tmp1520327772592644.pdf](https://github.com/mozilla/pdf.js/files/1784252/tmp1520327772592644.pdf)

Configuration:
- Web browser and its version: Firefox Quantum 58.0.2 (64 bits)
- Operating system and its version: Windows 10 Home
- PDF.js version: 119
- Is a browser extension: no

Steps to reproduce the problem:
1. viewer.html?file=tmp1520327127416893.pdf
2.

What is the expected behavior? (add screenshot)
ok

What went wrong? (add screenshot)
ko

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://81.184.7.209/v_119/web/viewer.html?file=tmp1520327127416893.pdf

### PR DESCRIPTION
**Pull request by janpe2**
Fixes #9534
in which the PDF uses composite Type0 fonts and the embedded CFF data is not in CID font format. The problems are caused by the `Encoding` entry whose value is an embedded CMap stream. The existing implementation ignores the CMap, so wrong glyphs are rendered. 

Most PDFs like this use `/Encoding /Identity-H` instead. They have no problems and their rendering is not affected by this PR.

### CODE REVIEW

**Comment by janpe2** [comment]
Actually the PDF isn't broken. The spec mentions that CFF data can be used like this. Because the CFF doesn't support CIDs, glyph indexes are used as CID values.

**Review by Snuffleupagus — APPROVED** [review]

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice find, thanks!

**Pull request merged**
