### PR TITLE
Use the `cidToGidMap`, if it exists, when building the glyph mapping for non-embedded composite fonts (issue 12418)

### LINKED ISSUE #12418: The context of the document is not rendered properly in the document,Garbled text in two text boxes
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
All browsers.
- Operating system and its version:
Windows 10
- PDF.js version:
Tested 2.0/2.1.266/2.3.200/2.4.456/2.5.207/2.6.347
- Is a browser extension:
Yes and viewer and embeded in our product, same issue

Steps to reproduce the problem:
1. open document

What is the expected behaviour?
Compare to Acrobat or Chrome PDF viewer

What went wrong? (add screenshot)
Garbled text in two text boxes

Document to be supplied by client rep.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #12418

### CODE REVIEW

**Comment by timvandermeij** [comment]
@brendandahl Do you have time to review this patch?

**Review by brendandahl — APPROVED** [review]
Nice, now we do better than pdfium and preview and match acrobat.

**Comment by timvandermeij** [comment]
Thanks!

**Pull request merged**
