### PR TITLE
Move compatibility code to the shared/compatibility.js.

### PR DESCRIPTION
**Pull request by yurydelendik**
Trying to address "Dependency on Promise for legacy browsers" item from #8050 with attempt to provide centralized compatibility file for window and worker files.

The web/compatiblity.js file is not really needed, but will be helpful for people to avoid 404 in nearest future and not break their build scripts. We can remove that later with major version.

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
It's really great to see this happening, since it gets rid of so much stuff from `shared/util.js`!

r=me, with passing tests.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Awesome work!

**Pull request merged**
