### PR TITLE
Handle CSS-comments better in the preprocess-function (PR 14963 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This fixes another oversight, please see the updated tests.

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM.

**Comment by calixteman** [comment]
Out of curiosity, did you build and run on m-c in order to be sure that everything is ok ?

**Comment by Snuffleupagus** [comment]
> Out of curiosity, did you build and run on m-c in order to be sure that everything is ok ?

Yes, I diffed the output of `gulp mozcentral` with/without this patch for the *built* `web/viewer.css` and `web/viewer.html` files.
As expected, there were ***no changes*** caused by this patch.

**Pull request merged**
