### PR TITLE
Update linux bot to chrome 58

### PR DESCRIPTION
**Pull request by brendandahl**

### CODE REVIEW

**Comment by brendandahl** [comment]
@timvandermeij or @Snuffleupagus I did a first run through and most things look fine, there were some new boxes in chrome-issue1049-page2, but I didn't notice much else. Do either of you have some time to run through and double check chrome didn't regress?

**Comment by timvandermeij** [comment]
I'm going to check them now.

**Comment by timvandermeij** [comment]
The problems I found are:

- chrome-thuluthfont-pdf-page1 (boxes)
- chrome-ShowText-ShadingPattern-page1 (cut-offs, but is now the same as in Firefox)
- chrome-issue1049 (boxes)

However, there are also many improvements, so I would propose to create an issue to track the three items above and continue with creating the reference images.

**Comment by brendandahl** [comment]
/botio-linux makeref

> However, there are also many improvements, so I would propose to create an issue to track the three items above and continue with creating the reference images.

sgtm

**Comment by timvandermeij** [comment]
Thanks!

**Pull request closed without merging**
