### PR TITLE
Ensure that the necessary src/* dependencies are loaded before the viewer, when it's run with `gulp server` (issue 7448)

### LINKED ISSUE #7448: Promise is undefined when running web/viewer.html in Internet Explorer 10 and 11
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Internet Explorer 10 and 11
- Operating system and its version: Windows Server 2012 R2
- PDF.js version: Latest
- Is an extension: No

Steps to reproduce the problem:
1. Followed the steps (from https://github.com/mozilla/pdf.js) to build and run server with gulp
2. Navigate to http://localhost:8888/web/viewer.html

What is the expected behavior? Default compressed.tracemonkey-pldi-09.pdf file should be coming up. (see chrome.jpg)

What went wrong? Instead, nothing displays and an javascript error saying "Promise is undefined" at preferences.js, line 34 character 3. (see ie.jpg)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #7448.

### CODE REVIEW

**Comment by yurydelendik** [comment]
I wonder if we can just add dependency on pdfjs-web/pdfjs for modules that use polyfilled stuff (and provide comments why we do that).

**Comment by Snuffleupagus** [comment]
> I wonder if we can just add dependency on pdfjs-web/pdfjs for modules that use polyfilled stuff (and provide comments why we do that).

I did consider doing that, but then I figured that since we use `Promise` in a lot of files, we'd technically need to require the `pdfjs-web/pdfjs` module in lots of places. Currently there's just one breaking issue (in `preferences.js`), but that seems more like a happy coincidence, so I figured why not solve this in one place such this issue won't come up somewhere else in the future.

**Comment by yurydelendik** [comment]
Okay, let's go for your original solution. I'm afraid it might bite us we start using different bundler. I'm thinking we shall have something like polyfill module that will export Promise and URL and use these.

**Comment by yurydelendik** [comment]
Thank you for the patch

**Pull request merged**
