### PR TITLE
Fix the "must check that an infinite loop is not triggered" integration test

### PR DESCRIPTION
**Pull request by timvandermeij**
This integration test fails intermittently, locally at least in Chrome with Puppeteer 23.4.0+, with the following errors:

```
In chrome: Expected '123Hello' to equal 'Hello123'.
In chrome: Expected '123Hello' to equal '123'.
```

This happens because the test before it left queued sandbox events behind. We don't close the document between tests, so those get run when we click the textbox in this test and that interferes with our selection/typing actions. This commit fixes the issue by flushing the queued sandbox events in the first test, which makes sure that state no longer leaks through to the next test and thus improves isolation.

Morever, similar to commit 3adf8b6 we use safer assertions to avoid further intermittent failures, and we replace the `page.$eval` call with a simpler Home button push like we already do in e.g. the test helpers. This combined makes the code shorter and simpler.

Fixes a part of #18773 (the scripting tests now all pass for me locally with the new Puppeteer version).

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
> This happens because the test before it left queued sandbox events behind. We don't close the document between tests, so those get run when we click the textbox in this test and that interferes with our selection/typing actions.

Possibly a stupid question, but could/should we just close the document between tests instead?

**Comment by timvandermeij** [comment]
I did consider that, but because we don't seem to do that anywhere else yet I figured I'd go for consistency here. I think it was done that way to reduce runtime of the (already lengthy) integration tests, and for most tests it also isn't an issue.

However, I do agree that we might want to consider doing that in follow-up work. Isolation issues are currently not visible because we run the integration tests in a fixed order (in contrast to e.g. the unit tests which already run in a random order to make dependencies between tests visible), and I think fixing that (by removing https://github.com/mozilla/pdf.js/blob/3219d4905df61516e7097fdc7211de569d90584e/test/integration-boot.mjs#L24) will bring any remaining isolation issues to the surface, and fixing them will then probably result in having the close the document between tests. For now though the objective is to unblock Puppeteer updates, so I therefore kept this patch small, but I will make a follow-up issue to track this because I do think that this is a good idea.

**Comment by calixteman** [comment]
> > This happens because the test before it left queued sandbox events behind. We don't close the document between tests, so those get run when we click the textbox in this test and that interferes with our selection/typing actions.
> 
> Possibly a stupid question, but could/should we just close the document between tests instead?

Yes we should make all the tests independent of each other, mainly because it's super painful to have to run all test before the one you want to debug...
It's on my todo list (but its rank isn't very high...)

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.

**Pull request merged**
