### PR TITLE
Add support for bold/italic styled outline items in the viewer

### LINKED ISSUE #3214: Unsupported bookmark features
The bookmarks in this PDF (download+rename to ".pdf") - [bookmark-unsupported-features pdf](https://f.cloud.github.com/assets/2175324/467817/fc5d9218-b683-11e2-8bad-3d02692e3e04.png) - should be self-explanatory of what the problem is.

So far, the only reader I've found that supports this is Adobe. Okular gets the link to Google right, but not the rest. Xpdf and ViewPDF crash when attempting to open the file. Evince, ApVLV, and gv don't show it right either.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #3214 (since we won't fix the colour part).

### CODE REVIEW

**Comment by timvandermeij** [comment]
Funny, I thought about this some days ago and this is also exactly how I would have implemented it. I was also concerned about the colors in the sidebar. It seems that most (all?) other PDF readers use a white background and thus the colors are visible. However, they must have the same kind of issue: what if the color of the outline item is white? Would it not be visible or would the readers just ignore it? I therefore think ignoring the black color is a good thing to do here.

**Comment by Snuffleupagus** [comment]
> [...] I don't know if you can really set all kinds of colors, I did not check the spec for that yet

According to the specification[1], any RGB colour is possible. Given that most readers seem to use a light background, the "darker" colours appear more commonly used for outline items. I've checked e.g. `basicapi.pdf` this patch, and there the outline items suffer from readability issues against the background we use in the viewer.

One option could be to only add support for bold/italic, which works fine, and perhaps let the support for colours be controlled by a preference!?

---
[1] http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=377

**Comment by timvandermeij** [comment]
Given how rare outline colors are, I think for this patch it would be better to leave out the color handling part and just focus on implementing bold/italic. That way we can at least land that and keep color handling for a later PR as that might require discussion about whether we want to support it at all. I'm fine with landing the bold/italic part (i.e., the first two points of your PR message).

**Comment by Snuffleupagus** [comment]
> I'm fine with landing the bold/italic part

@timvandermeij Does this imply that you are willing to sign off on this, or should we ask Brendan/Yury if they think the viewer ought to support this?
I'm thinking to split the `core` and `test` parts out into a separate PR, to at least get them landed now.

**Comment by timvandermeij** [comment]
I can sign off everything except for the colors in the viewer, as I think we should discuss whether or not we actually want to support that, given the issues that may arise from a UX point of view. For now, perhaps splitting this PR into the core/test and web parts is easier. I can review the core/test parts and then we can ask Yury/Brendan about the web part.

**Comment by timvandermeij** [comment]
This PR needs a rebase now that your previous patch landed.

**Comment by timvandermeij** [comment]
@yurydelendik @brendandahl Do you think that we should support this? My opinion is that bold/italic support should be fine as most other readers support this too and it's not a big change from a UX perspective. I think that we should no the colors as that is very likely to cause issues since we have a gray-ish background for the outline view (and yellow, red or blue text for example looks really bad on that).

**Comment by timvandermeij** [comment]
@Snuffleupagus Yury and I had some discussion on this (see http://logs.glob.uno/?c=mozilla%23pdfjs#c46798). Let's update this PR to only add support for bold/italic styles and remove the support for colors (which we won't fix because of the rare usage and UX problems).

**Comment by timvandermeij** [comment]
Thank you for the patch!

**Pull request merged**
