### PR TITLE
Also update the width/unicode data when replacing missing glyphs in non-embedded Type1 fonts (issue 18059)

### LINKED ISSUE #18059: No spacing between characters
Attach (recommended) or Link to PDF file here: [example.pdf](https://github.com/mozilla/pdf.js/files/15260162/example.pdf)

Configuration:
- Web browser and its version: Chrome Version 124.0.6367.119
- Operating system and its version: macOS Sonoma 14.4.1
- PDF.js version: 4.3.21 [b6765403a]
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF.
2. Scroll to the bottom left where the text is.

**What is the expected behavior? (add screenshot)**

The characters in the PDF are separated.

Chrome

image

macOS Preview

image

GhostScript PDF to image

image

**What went wrong? (add screenshot)**

PDF.js does not render the characters with spaces between them

image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please note:* This causes a little bit of movement in the `issue2770` test-case, however this matches the rendering in both Adobe Reader and PDFium.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@calixteman Gentle review ping?

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
