### PR TITLE
Ensure that Type0, i.e. composite, OpenType fonts with `CFF ` tables are *not* treated as CFF fonts if their glyph mapping is non-default (issue 9915)

### LINKED ISSUE #9915: Some fonts cannot display on PDF js correctly
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browsers: Google Chrome 67.0.3396.99 (Official Build) (64-bit) / Internet Explorer 11.492.16299.0
- Operating system: Windows 10
- PDF.js version: Tested with 2.0.550 and almost the tagged versions.

Steps to reproduce the problem:
1. Open Demo page at: https://mozilla.github.io/pdf.js/web/viewer.html
2. Browse the specific PDF from me ,see the link: 
 [demo document](https://drive.google.com/file/d/1i5UiyUD1A64WRjP3D4MJS9HTQBPu0R9W/view)
3. We expect the content should display correct what my PDF file have.
But it have some content in the footer was not display correctly
+ Here is expected content of pdf footer
[expected content.PNG](https://drive.google.com/file/d/1htanQsDeIUZpd1mk5NTDvbEQa4xnbF99/view?usp=sharing)
+ Here is unexpected result when open on demo page
[Unexpected content.PNG](https://drive.google.com/file/d/1qYHc7UBorSHmgXqMIwiTPvAr1ID9G_rS/view?usp=sharing)
+ When check the content property via Foxit Reader:
[Data property.PNG](https://drive.google.com/file/d/1yTr5jI4c1tmkcUziIZxXWQLmDo-Fwuz3/view?usp=sharing)

Thank you for any contribution to solve the issue.
Cheers.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*I've been hanging around, waiting for PDF.js `2.0` to be officially released, and fixing a few regressions/smaller issues during that time. This PR is a continuation on that theme.*

This particular code-path has been the source of *numerous* regressions to date, so hopefully this patch won't cause any more of those. (All those regressions were, unfortunately, my "fault" as well.)

Fixes #9915.

### CODE REVIEW

**Review by brendandahl — APPROVED** [review]
Looks good. We don't need to change any thing, but out of curiosity, have you looked into how PDFium handles this?

**Comment by timvandermeij** [comment]
Thank you!

**Comment by timvandermeij** [comment]
/botio makeref

(also for the other PR that landed before without this)

**Comment by Snuffleupagus** [comment]
> Looks good. We don't need to change any thing, but out of curiosity, have you looked into how PDFium handles this?

I attempt to look into this, and it appears that PDFium is basically passing all the font data to FreeType. Unfortunately, I'm getting lost in the FreeType code and cannot really tell where/how it's being handled.

**Pull request merged**
