### PR TITLE
Implement a Two Page View Mode

### LINKED ISSUE #590: Feature: Two-page view
Feature request: add buttons for two-page view
also, it would be nice to have a button for 100%, and "Page Fit" in the toolbar.

### LINKED ISSUE #1475: Two-Up?
I have a client that is asking for Page displays as found in Adobe Reader (Two-Up, Two-Up Continuous, Show Gaps Between Pages and Show Cover Pages During Two-Up)

Would this be possible? Either now or sometime in the future?

Thanks

### LINKED ISSUE #2376: Two page spread view
Hi, is it possible to view the pdf as a two page spread and add a left-right sliding functionality on top? I picture this to work on touch screen devices too but not sure if this is feasible?

Thanks in advance.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This PR is the continuation of the work that @Moistly and @waddlesplash started in PRs #2395 and #2660.
_Please note that I got permission from @waddlesplash on IRC to take over the implementation of this feature._

Given that the last actual coding in #2660 was done six months ago, it was easier for me to start fresh rather that trying to patch the old code. Compared to the old implementation, this PR tries to add as much of the code as possible in separate files to avoid cluttering viewer.js too much.

**_Based on a recent IRC discussion, this PR is on hold until we have implemented testing that covers the viewer._**

**Things left to do in this PR:**
- [ ] Once we have a testing framework in place: Implement the necessary tests for this feature.
- [ ] Ask Stephen Horlander for icons that fit the new style.
- [ ] Revert to the initial horizontal scrolling behaviour. (From working on e.g. #4188, I've found that there are lots of issues with horizontal scrolling in a cross-browser environment.)

Fixes #590.
Fixes #1475.
Fixes #2376.
Fixes #3658.
Fixes [bug 786602](https://bugzilla.mozilla.org/show_bug.cgi?id=786602).
Fixes [bug 864440](https://bugzilla.mozilla.org/show_bug.cgi?id=864440).

[Review on Reviewable](https://reviewable.io/reviews/mozilla/pdf.js/3723)

### CODE REVIEW

**Comment by avih** [comment]
Is there still a plan to add two-pages display?

It's quite an important feature of a PDF viewer IMO, and content which was meant to be displayed as two-pages, like magazines, really suffers if it can't.

**Comment by toerb** [comment]
The PR is now open for over 600 days. What is holding it back?

**Comment by timvandermeij** [comment]
The main problem is that pages can be of different sizes and that the current implementation might not deal with that properly. There is also the problem of testing this: it has to be done manually as there are no browser tests for this yet.

**Comment by micsan13br** [comment]
Is there a document that explains how to implement the changes from @Snuffleupagus (a few posts above this) in the latest release of pdf.js ?
Is this feature still going to be implemented in the future ?

**Comment by timvandermeij** [comment]
@micsan13br You would have to clone the branch and rebase it onto the current master branch. After that you should be able to work with it using `node make server`.

**Comment by thomasflad** [comment]
I've tried to rebase the changes from @Snuffleupagus but the changes are complexer then I thought. Maybe someone can help here?

**Comment by brendandahl** [comment]
I'd be more comfortable with landing this feature with more tests. In the mean time I'll close it until we have done something about #6505.

**Comment by avih** [comment]
> In the mean time I'll close it until we have done something about #6505.

TBH this doesn't sounds like a great reason to close this PR.

Admittedly the patch is very bitrotted, but it's probably the place where most discussions of this feature happened, and closing it would hide this discussion (e.g. while searching within open issues).

**Comment by timvandermeij** [comment]
Discussions about the issue should take place in #590. Discussions here should only concern this particular implementation. Since this patch is needs a lot of work and there are no tests yet, it is better to close it and to revisit it later on with a fresh implementation rather than leaving it open and keeping it in the queue for several years.

By the way, I think that this patch can be simplified quite a bit given the current code base, so revisiting this is not only a good idea for the tests, but also for the code quality. Keep in mind that this patch was written two years ago.

**Comment by Snuffleupagus** [comment]
> By the way, I think that this patch can be simplified quite a bit given the current code base, so revisiting this is not only a good idea for the tests, but also for the code quality. Keep in mind that this patch was written two years ago.

I completely agree with the above!

(One of the reasons that I stopped working on it, is that it wasn't clear to me if we really wanted to introduce all this complexity in the viewer.)

**Comment by brendandahl** [comment]
> TBH this doesn't sound like a great reason to close this PR.

Yes, sorry there's a bit more context. We're are trying to clean up the pull request queue and only have actively worked on(within the last month) things there. This will hopefully leave less pulls in an unresolved limbo like we currently have.

**Comment by avih** [comment]
> Yes, sorry there's a bit more context

Thanks. Appreciate the info.

**Comment by jepz88** [comment]
@Snuffleupagus i know this has been discussed, but will this be implemented in the soon future? :) Saw the demo of this by you, is it possible to use that solution until the official release? :)
/Jesper

**Comment by Snuffleupagus** [comment]
> I know this has been discussed, but will this be implemented in the soon future?

As outlined in https://github.com/mozilla/pdf.js/pull/3723#issuecomment-145628420, further work on this is blocked on test coverage for the viewer. Hence it's currently not possible to provide any time-line for this.
Once the necessary testing framework is in place, the functionality in this PR would have to be (at least partially) re-implemented from scratch, since the default viewer has changed *significantly* since this code was written.

> [...] is it possible to use that solution until the official release?

I suppose that it's technically possible. However, in its current state, the PR will most likely *not* work with an up-to-date version of PDF.js. (Please note that it doesn't make sense for me to continue work on this, *until* such a time as it's actually possible for this feature to land.)

**Comment by michal-drozd** [comment]
@Snuffleupagus: Is there any chance, that Your PR d81c30b would be working on actual version of pdf.js ? Disregarding tests my team is desperately need this feature.

**Comment by prohtex** [comment]
@Snuffleupagus @michal-drozd I also have a need for this feature. Is there any hope of getting the code working on a current version of pdfjs?

**Comment by timvandermeij** [comment]
This is already answered in https://github.com/mozilla/pdf.js/pull/3723#issuecomment-155388936.

**Comment by prohtex** [comment]
@timvandermeij Its too bad development of such a crucial feature is hinged on #6505 which seems to be stuck. Until then, I guess I am using 0.8.852 on a production site. Aside from performance drawbacks, the 2 page view implemented in this PR by @Snuffleupagus is excellent.

**Comment by nikhilweee** [comment]
Any chances of this being accepted anytime soon?

**Comment by timvandermeij** [comment]
Another pull request is currently in the review queue that implements this in an easier way.

**Pull request closed without merging**
