### PR TITLE
Slightly refactor the `fontRef` handling in `PartialEvaluator_loadFont` (issue 7403 and issue 7402)

### LINKED ISSUE #7403: Text glyphs are scrambled
### Link to PDF file (or attach file here): 
[garbled78910.pdf](https://github.com/mozilla/pdf.js/files/309967/garbled78910.pdf)

### Configuration:
- Web browser and its version: **Firefox 47.0**
- Operating system and its version: **Ubuntu 16.04**
- PDF.js version: **1.4.121**
- Is an extension: **no**

### Steps to reproduce the problem:
1. Open the PDF
2. Scroll to page 3, 4, or 5

### What is the expected behavior?

screenshot from 2016-06-10 16-16-20

### What went wrong?

screenshot from 2016-06-10 16-16-44

(Text is corrupt all over the last three pages; the screenshots only compare one section.)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Originally, I was just going to change this code to use `Ref_toString` in a couple more places. When I started reading the code, I figured that it wouldn't hurt to clean up a couple of comments. While doing this, I noticed that the logic for the (rare) `isDict(fontRef)` case could do with a few improvements.

There should be no functional changes with this patch, but given the added reference checks, we will now avoid bogus `Ref`s when resolving font aliases. ~~In practice, I don't think the current code has caused issues, but it seems good to clean this up to prevent any future problems.~~ _As issue #7403 shows, there're issues with the current code._

Note that the only thing that this patch will change, is the `font.loadedName` in the case where a `fontRef` is a reference _and_ the font doesn't have a descriptor. Previously for `fontRef = Ref(4, 0)` we'd get `font.loadedName = 'g_d0_f4_0'`, and with this patch `font.loadedName = g_d0_f4R`, which is actually one character shorted in most cases. (Given that `Ref_toString` contains an optimization for the `gen === 0` case, which is by far the most common `gen` value.)

In the already existing fallback case, where the `fontName` is used to when creating the `font.loadedName`, we allow any alphanumeric character. Hence I don't see how (as mentioned above) e.g. `font.loadedName = g_d0_f4R` would be an issue here.

**Edit:** This also fixes #7403 and #7402.

### CODE REVIEW

**Comment by timvandermeij** [comment]
@brendandahl Do you have time to review this PR?

**Comment by Snuffleupagus** [comment]
> @brendandahl Do you have time to review this PR?

I'd guess that both Brendan and Yury are currently at https://wiki.mozilla.org/All_Hands/2016_London, so if anyone else wants to review this, feel free to :-)

**Comment by Snuffleupagus** [comment]
*The PR was rebased to fix a merge conflict in `test/pdfs/.gitignore`.*

**Comment by Snuffleupagus** [comment]
*The PR was rebased to fix a merge conflict in `test/pdfs/.gitignore`*.

**Pull request merged**
