### PR TITLE
Update packages and translations

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
While I've looked at all of them, the Chrome-specific failures on the Linux-bot appears to be nothing but fallout from a new Chromium-version as part of the updated Puppeteer package.

**Comment by Snuffleupagus** [comment]
While I've not looked at all of them, the Chrome-specific failures on the Linux-bot appears to be nothing but fallout from a new Chromium-version as part of the updated Puppeteer package.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
> While I've not looked at all of them, the Chrome-specific failures on the Linux-bot appears to be nothing but fallout from a new Chromium-version as part of the updated Puppeteer package.

I agree; I've clicked through quite a number of them and haven't noticed any breakage. Thanks!

/botio makeref

**Pull request merged**
