### PR TITLE
[api-minor] Support custom `offsetX`/`offsetY` values in `PDFPageProxy.getViewport` and `PageViewport.clone`

### PR DESCRIPTION
**Pull request by Snuffleupagus**
There's no good reason, as far as I can tell, to not also support `offsetX`/`offsetY` in addition to e.g. `dontFlip`.

Fixes #11239.

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good to me; thank you for picking this up!

**Comment by soadzoor** [comment]
When does this become available for the npm package?

**Comment by timvandermeij** [comment]
In the next release. The date for that is not yet determined.

**Pull request merged**
