### PR TITLE
Try to not omit some values when printing a choice list with several selected items

### LINKED ISSUE #16500: Not showing all items including selected values in list box
Attach (recommended) or Link to PDF file here:
[InputForm_1.pdf](https://github.com/mozilla/pdf.js/files/11615814/InputForm_1.pdf)

Configuration:
- Web browser and its version:
Chrome latest version
- Operating system and its version:
Windows 10
- PDF.js version:
Latest
- Is a browser extension:

Steps to reproduce the problem:
1. Open InputForm_1.pdf attached in https://mozilla.github.io/pdf.js/web/viewer.html
2. Select "three" and "Five" from the input multi select list box
3. use download feature from the https://mozilla.github.io/pdf.js/web/viewer.html
4. open in adobe or any pdf viewer
5. Observe default values visible are "Three", "Four" and "Five, selected "Three" and "Five" but missing "One" and "Two"

as per the fix: https://github.com/mozilla/pdf.js/pull/14720/commits/ad3fb71a02508a7a8f28fe2ca0bcd16441bd3fe4#diff-a7e409abd3d3209d32d3adc8457c5e23feb4c06113a2e065b0c6a9322a3a3369
I think line 2577, first index should always be start with 0, instead of selected value calculation.

What is the expected behavior? (add screenshot)
It should show all elements and highlight selected values.
What went wrong? (add screenshot)
[InputForm_1_Filled1.pdf](https://github.com/mozilla/pdf.js/files/11615871/InputForm_1_Filled1.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
The changes in `annotation-choice-widget-print-page1` are probably just fine as-is, but how does it compare with the behaviour in e.g. Adobe Reader?

**Comment by calixteman** [comment]
In Chrome, it takes into account the position of the scroll knob and in Acrobat it's just impossible to make it working correctly (the selection is stuck on the initial values).

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Pull request merged**
