### PR TITLE
Add a `recoveryMode` that suppresses errors from the `Parser`, and utilize it when searching for the main trailer in `XRef_indexObjects` (bug 1250079)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Instead of having `Parser_getObj` fail unconditionally for the referenced PDF file, this patch attempts to let searching for the main trailer continue even if there are errors.

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1250079.

_Given that the PDF file is broken enough that even Adobe Reader refuses to open it, I'd understand if we decide to close the bug (and this PR) as WONTFIX. However, if we do want to try and fix it, this patch contains a suggested way of doing so._

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@yurydelendik, @brendandahl Can we make a decision about whether or not we want this PR?
As I said above, I'd totally understand if we close this and WONTFIX the bug, but I do think that we should decide either way!

**Comment by yurydelendik** [comment]
Looks good. However let's inline `_throwError` method because this name is misleading. How about:

             if (isEOF(this.buf1)) {
                if (!this.recoveryMode) {
                  error('End of file inside dictionary');
                }
                return dict;
             }

r+ with the change above (I think we don't need any warnings for the recoveryMode)

**Comment by Snuffleupagus** [comment]
> Looks good. However let's inline _throwError method because this name is misleading. How about:
> 
>          if (isEOF(this.buf1)) {
>             if (!this.recoveryMode) {
>               error('End of file inside dictionary');
>             }
>             return dict;
>          }
> 
> r+ with the change above (I think we don't need any warnings for the recoveryMode)

@yurydelendik Thank you for the review; I've pushed a new version which address your comments!
Since the latest round of testing only showed the intermittent issues that are already tracked elsewhere, this should be good to go now.

**Comment by timvandermeij** [comment]
Nice work!

**Pull request merged**
