### PR TITLE
[DO NOT MERGE] Reference testing

### PR DESCRIPTION
**Pull request by brendandahl**

### CODE REVIEW

**Comment by Rob--W** [comment]
Why?

**Comment by timvandermeij** [comment]
Some context: a few days ago the Linux bot broke down with all kinds of errors when we would run a test on it. @brendandahl started looking into it and suspects that it might have something to do with Chrome, but it's not sure yet.

**Comment by brendandahl** [comment]
I originally thought the issue was with chrome updating and tried to manually update it.  The issue was firefox was stuck. I'm going to try and roll back chrome, then do the chrome update.

**Comment by brendandahl** [comment]
The firefox changes all seem to be good. It was bit hard to verify all of the chrome ones, so it'd be great if someone else also did a quick pass through.

**Comment by brendandahl** [comment]
> I'm going to try and roll back chrome, then do the chrome update.

On second thought let's just makeref after one more person does a little verification.

**Pull request closed without merging**
