### PR TITLE
Add support for TrueType format 12 `cmap`s (issue 14881)

### LINKED ISSUE #14881: Text is not rendered
Attach (recommended) or Link to PDF file here: [Zu_MR_INF_2223.pdf](https://github.com/mozilla/pdf.js/files/8638426/Zu_MR_INF_2223.pdf)

Configuration:
- Web browser and its version: Firefox 102.0a1 (2022-05-05) (64-bit)
- Operating system and its version: Windows 10 Pro x64 19044.1682
- PDF.js version: 2.14.224
- Is a browser extension: No, the built-in version in Firefox

Steps to reproduce the problem:
1. Open the attached PDF file
2. Go to page 3 and see that all the text is missing.
3. Open the PDF file in Adobe Reader DC and see how it should look like

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

Console log:
Warning: Unknown field name, falling back to empty field name.
PDF 59d44a749e1b8c6b0b32d0ab3dc4eff0 [1.6 Apache FOP Version 2.6 / FOP] (PDF.js: 2.14.224)
Warning: cmap table has unsupported format: 12
downloadable font: OS/2: Adjusting head.macStyle (italic) to match fsSelection (font-family: "g_d0_f7" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This is, as far as I can tell, the first case we've seen of a format 12 `cmap`.
Please see https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for implementing this!

/botio makeref

**Comment by Snuffleupagus** [comment]
@timvandermeij Thanks a lot for reviewing/merging my patches!

---

A possible follow-up here could be to add support for format 13 `cmap`s as well, since according to the specification those are nothing more than a special-case of format 12; see https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html

Based on the specification text it seems to me that format 13 might be quite rare, and I'd not be able to supply a test-case, but do you think that it'd make sense to add support for those `cmap`s as well to prevent a possible future bug report?

**Comment by timvandermeij** [comment]
Given the "[...] used internally by Apple for its last resort font and by Unicode's last resort font. It would, in general, not be appropriate for any font other than a last resort font" part of the specification, I don't really think we'll see it in practice. Moreover, I think it's good to only implement this if we actually have a file that uses it, otherwise it will be hard to verify the correctness of the implementation and we won't have a regression test. For now I'd say we don't implement this until we actually find/make a file with format 13 `cmap`s.

**Pull request merged**
