### PR TITLE
Allow over-writing entries, in `XRef.indexObjects`, only when the generation number matches (issues 11230, 11139, 9552, 9129, 7303)

### LINKED ISSUE #7303: dict.get is not a function
There is a problem rendering this PDF: 
[ws_protectyourwork_e.pdf](https://github.com/mozilla/pdf.js/files/254710/ws_protectyourwork_e.pdf)

Using the standard web viewer example (build/generic/web/viewer.html) it runs into an exception, showing the error:

PDF.js v1.5.232 (build: a682cce)
Message: dict.get is not a function

screen shot 2016-05-09 at 11 06 41

This happens in Chrome, Firefox, Safari on the Mac - haven't tried any others. Message on Safari is: dict.get is not a function. (In 'dict.get('Filter')', 'dict.get' is undefined)

I hope this helps. Not sure if there is a problem with the PDF but I guess it would ideally catch the error anyway. PDF seems to display OK in other software.

Thanks,

Dan

### LINKED ISSUE #9129: Edited pages rendered as if not changed
Attach (recommended) or Link to PDF file here:
https://zenodo.org/record/1048152#.WgrUmd9fjeQ
or
https://waset.org/publications/10006645/red

Configuration:
- Web browser and its version:
mozilla ( under linux/windows), 
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
0. Our editors format papers, and our system using zend php, adding necessary information to header, footer, side notes.
1. Open the document, there is no header, footer, side notes 

What is the expected behavior? (add screenshot)
screencapture-waset-org-publications-10006645-r-1510672765952

What went wrong? (add screenshot)
screenshot-2017-11-14 microsoft word - 17ae030135 3 - red

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
expected:
https://waset.org/publication/Red/10006645
not working  :
https://zenodo.org/record/1048152#.WgrUmd9fjeQ

### LINKED ISSUE #9552: pdf.js seems to be ignoring annotations added using Preview.app
Attach (recommended) or Link to PDF file here:
https://github.com/Napoleon-BlownApart/Firefox_pdf.js_Problem

Configuration:
- Web browser and its version:
Nightly 49.0.1  (Last version that does not require signed addons)
- Operating system and its version:
MacOS 10.13.3
- PDF.js version:
*Standard version shipped with the build mentioned above.*
- Is a browser extension:

Steps to reproduce the problem:
1. Open PDF using Firefox (Nightly in my case) and two yellow annotations will be visible in the 2nd column of text on page 1.
2. Open PDF using Safari, or preview, (possibly other readers including Adobe), and four (4) other additional annotations will now be visible, also on the 1st page;
2a)  A "Note" in the top left,
2b) A comment "This is from Preview" near the top left,
2c) The first five (5) words of the Abstract will be highlighted in red, and
2d) The first five (5) words of the Introduction will be highlighed in orange.

What is the expected behavior? (add screenshot)
All annotations are rendered.
screen shot 2018-03-13 at 1 00 05 am

What went wrong? (add screenshot)
Some annotations are not visible.
screen shot 2018-03-13 at 12 59 55 am

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### LINKED ISSUE #11139: Missing first page
Attach (recommended) or Link to PDF file here:
[FR Cekada SedesUnCum.pdf](https://github.com/mozilla/pdf.js/files/3602024/FR.Cekada.SedesUnCum.pdf)

Configuration:
- Web browser and its version: Firefox 69 & Chrome 77
- Operating system and its version: Ubuntu 16.04.6 LTS
- PDF.js version: 2.3.160
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached PDF.
2. The first page is missing. The page displayed as first is actually the second one.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

### LINKED ISSUE #11230: Majority of Document is Cut Off
Attach (recommended) or Link to PDF file here: 
[Y._Tsividis_A_First_Lab_in_Circuits_and_Electronics.pdf](https://github.com/mozilla/pdf.js/files/3717821/Y._Tsividis_A_First_Lab_in_Circuits_and_Electronics.pdf)

Configuration:
- Web browser and its version: Google Chrome 77.0.3865.120
- Operating system and its version: Windows 10 1903 (Build 18362.418)
- PDF.js version: 2.3.164
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open attached document
2. Scroll to bottom

What is the expected behavior?
In all other PDF readers, such as the one in Microsoft Edge, 139 pages are rendered
image

What went wrong? (add screenshot)
Only 15 pages are rendered
image

JS Console Messages:
```
pdf.worker.js:1710 Warning: Indexing all PDF objects
viewer.js:1502 PDF d216c1e858407c419356a28ea6096b93 [1.6 Acrobat Distiller 7.0 (Windows) / PScript5.dll Version 5.2] (PDF.js: 2.3.164 [WebGL])
pdf.worker.js:1710 Warning: Invalid absolute docBaseUrl: "file:///C:/Users/nkizz/Desktop/Textbooks/Y._Tsividis_A_First_Lab_in_Circuits_and_Electronics.pdf".
```

### PR DESCRIPTION
**Pull request by Snuffleupagus**
**TODO:**
 - [x] Manually check open/closed issues tagged with `4-corrupted-pdf` such that there's no obvious regressions.
*I've done a quick pass already, but additional help would be very much appreciated here.*
 - [x] Convert (relevant) pre-existing `load` tests to `eq` tests instead, to help avoid unnecessary regressions. Note that some files will render, but not as intended when compared with e.g. Adobe Reader, depending on which objects are chosen (see e.g. issues with incorrect total number of pages).
 - [x] Add as many new `eq` tests as possible, based on the list above.

---

This patch is making me somewhat worried about future regressions, since it's certainly easy to imagine this completely breaking certain kinds of corrupt/edited PDF documents while fixing others.[1]

Obviously it passes all existing reference tests (and even improves one), however compared to many other patches there's no telling how much it could break. *Edit:* Obviously any breakage would be limited to *corrupt* PDF documents, since valid ones does not enter this method at all. *Edit2:* Also, this patch should mostly affect the "multiple documents in one PDF file" case, but not necessarily PDF documents with just a broken XRef table.
The only reason that I'm even submitting this patch, is because of the number of open issues that it would address.

Generally speaking though, the best course of action would probably be if `XRef.indexObjects` was re-written to be much more robust (since it currently feels somewhat hand-wavy in parts). E.g. by actually checking/validating more of the objects before committing to them.

Fixes #11230
Fixes #11139
Fixes #9552
Fixes #9129
Fixes #7303

Also partially improves #6243, however parts of it regresses as well. (A couple of pages now renders "better", but one page no longer renders and an image looks worse.)
Generally though it seems that none of the PDF viewers I've tried agree completely on how the document should look, and this might be a case where the document is just too damaged to "fix".

---
[1] Especially given that it's reverting part of PR #5910, however in the case of issue #5909 it seems that other (more recent) changes have actually made that PR redundant.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
*Temporarily dumping some PDF files here, to have a (slightly) better place to point linked test-cases to.*
[issue5909_original.pdf](https://github.com/mozilla/pdf.js/files/3720894/issue5909_original.pdf)

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
I think this is a very nice improvement. Even though you're absolutely right about other breakage that may still occur, given that those PDF files are usually quite broken, we have a lot more test coverage now than we had before, so future changes will be less risky. Thanks!

**Pull request merged**
