### PR TITLE
Replace the unavailable linked test-case for issue 2128 with a reduced test-case

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Re: issue #2128 and PR #2628.

### CODE REVIEW

**Comment by timvandermeij** [comment]
There appears to be something wrong with the test on Linux. The characters are all replaced with squares. @Snuffleupagus Do you have an idea why that is happening only on Linux?

**Comment by Snuffleupagus** [comment]
> Do you have an idea why that is happening only on Linux?

Not really, since it works as expected on Windows. My only idea is that this might be a pre-existing issue on Linux, so I've just submitted a temporary patch to test that idea.

/botio test

**Comment by Snuffleupagus** [comment]
> My only idea is that this might be a pre-existing issue on Linux, so I've just submitted a temporary patch to test that idea.

The last round of testing seem to confirm this theory.
@timvandermeij Since this is an existing issue, would you agree that the PR is good to go (once the temporary test commit is removed)?

**Comment by timvandermeij** [comment]
I have opened the issue above to track the Linux problem. Otherwise this patch seems fine to me and Yury confirmed on IRC that we can go ahead and merge this.

/botio makeref

**Comment by timvandermeij** [comment]
Thank you for this patch!

**Pull request merged**
