### PR TITLE
Fetch parameters if they are a |Ref| in CalGray/CalRGB color spaces (issue 5747)

### LINKED ISSUE #5747: Error with PDF containing CCITTFaxStream Image
I've a problem to view a PDF which contains a CCITTFaxStream image.

I get an error in pdf.worker.js in method ColorSpace.parseToIR at: 
switch(mode) {
..
  case 'CalGray':
          params = cs[1].getAll();  <-- undefined is no function
          return ['CalGrayCS', params];
}

Error message of pdf.worker.js:
Warning: Unable to decode image: TypeError: undefined is not a function
Warning: Dependent image isn't ready yet

pdf to test: https://drive.google.com/file/d/0BzOCthVk1FvqMmc4WUVjdkI0N1U/view?usp=sharing

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #5747.

### CODE REVIEW

**Comment by CodingFabian** [comment]
looks good to merge, thanks Jonas

**Comment by yurydelendik** [comment]
Thank you for the patch!

**Pull request merged**
