### PR TITLE
Change 'Current View' to 'Current Page' in the secondary toolbar

### PR DESCRIPTION
**Pull request by calixteman**
Content Design team (UX) proposed this change.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
If we're going to change this, is there any update regarding https://github.com/mozilla/pdf.js/pull/15391#issuecomment-1340834742 since the button is more difficult to find now?

**Review by Snuffleupagus — APPROVED** [review]

**Comment by flodolo** [comment]
Could someone explain what `(View URL from Current Page)` means here? 

As someone outside of the team: `Content Design team (UX) proposed this change.`, with no link to this proposal, or issue linked to explain it, it's all but transparent what's being changed and why.

**Comment by calixteman** [comment]
Sorry, I forgot to mention the ticket:
https://mozilla-hub.atlassian.net/browse/FXCD-291

**Comment by flodolo** [comment]
Thanks, that helps (although we should have some comment to explain it to localizers).

Is it worth mentioning that the PDF viewer and specs linked in that ticket don't really match? I'm seeing the label of the command and explanation between parentheses, while the Figma file only shows the explanation as title/tooltip?

Figma
Schermata 2023-01-22 alle 16 17 06

My browser (Italian)
Schermata 2023-01-22 alle 16 17 49

**Comment by calixteman** [comment]
Here's the link I got on slack:
https://www.figma.com/file/elSBKpUxHCZe6yTqoohUu9/PDF.js-Designs?node-id=2249%3A17574&t=69VouyRyK4M2lywB-0

and I provide the https://github.com/mozilla/pdf.js/pull/15941#issuecomment-1396643862 to UX to check that everything is ok.

Anyway we must do something better here.

**Pull request merged**
