### PR TITLE
Remove `Util.appendToArray` and `Util.prependToArray`

### PR DESCRIPTION
**Pull request by timvandermeij**
The former may be replaced by regular JavaScript array concatenation and the latter is unused. This avoids unnecessary function calls/imports.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
> This avoids unnecessary function calls/imports.

While that's certainly correct, it will however result in more allocations since the existing array won't be re-used; please refer to [this MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat):
> The concat() method is used to merge two or more arrays. This method does not change the existing arrays, but instead returns a new array.

**Comment by Snuffleupagus** [comment]
> This avoids unnecessary function calls/imports.

While that's certainly correct, it will however result in more allocations[1] since the existing array won't be re-used; please refer to [this MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat):
> The concat() method is used to merge two or more arrays. This method does not change the existing arrays, but instead returns a new array.

---
[1] Whether or not this would be a problem, I don't know. Using `push` instead of `concat` might work!?

**Comment by timvandermeij** [comment]
Good point! With the spread syntax, it's now possible to use the regular `push` operation instead of `concat`, so this both avoids additional method calls and reuses the original array. I have pushed the new version. Could you check if it's what you had in mind?

**Comment by Snuffleupagus** [comment]
> Could you check if it's what you had in mind?

That looks great; and it's nice that more (old) code can be removed now!

---

A good follow-up might be to try and replace `Util.extendObj` with (the native) `Object.assign` too. It'd basically just be a search-and-replace exercise, but you'd probably need to add a (core-js) polyfill though.

**Comment by timvandermeij** [comment]
Thank you for checking this!

**Pull request merged**
