### PR TITLE
Add support for TrueType (0, 0) cmap tables (issue 5501, issue 5574, and bug 1037973)

### LINKED ISSUE #5501: PDF fonts misrendered
On (for example) page 12 of this PDF file:

http://andreask.cs.illinois.edu/cs357-f14/public/notes/09-function-spaces.pdf

pdf.js misrenders the fonts for me, as shown in the following screen shot (comparing with Chrome's renderer):

pdf-misrender

I'm using pdf.js version 1.0.907+dfsg-1 as distributed by Debian, on Firefox 33.0. (Debian's Iceweasel 33.0-2)

FWIW, the PDF was generated by [Xournal](http://xournal.sourceforge.net/).

### LINKED ISSUE #5574: Fully scrambled output
http://www.icsharpcode.net/TechNotes/SharpDevelopCodingStyle03.pdf

In the console:
```
"PDF ec26a249de38ee06ff2ca4ad26631042 [1.4 - / -] (PDF.js: 1.0.1021)" viewer.js:5393
"Warning: Could not find a preferred cmap table." pdf.worker.js:235
```

[FF 35b5; Win7]

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This is a tentative patch that adds support for (0, 0) cmap tables. References available [here](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6name.html) and [here](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html).
Since those tables use "standard" Unicode, I hope that my assumption to just use the charCodes as is, is a reasonable one!

Fixes #5501.
Fixes #5574.
Fixes [bug 1037973](https://bugzilla.mozilla.org/show_bug.cgi?id=1037973).

### CODE REVIEW

**Comment by timvandermeij** [comment]
Looks really good to me and I can confirm that this fixes the referenced issues. Nice work!

**Comment by brendandahl** [comment]
Nice work!

**Pull request merged**
