### PR TITLE
Slightly modify the max width of a tracking space

### LINKED ISSUE #16119: Space inserted between each letter in textLayer
Exactly the same issue as I reported in (Space inserted between each letter in textLayer)[https://github.com/mozilla/pdf.js/issues/6705].

Tested in the current PDF.js demo at https://mozilla.github.io/pdf.js/web/viewer.html:

image

- Correct text: `Engang var der i Samvirke en opskrift`
- Rendered text: `E n g a n g v a r d e r i Samvirke en opsk `

PDF in question:

[Fiskelagkagen_2016v2 1.pdf](https://github.com/mozilla/pdf.js/files/10907776/Fiskelagkagen_2016v2.1.pdf)

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
r=me, assuming it passes all tests (since it seems like tweaking these constants could easily break something else).

**Comment by calixteman** [comment]
There is a small difference with issue14415.pdf but from my pov it's acceptable: a space was alone in a span and now it belongs to the next span so from a text selection point of view it isn't a problem.

**Comment by Snuffleupagus** [comment]
> There is a small difference with issue14415.pdf but from my pov it's acceptable: a space was alone in a span and now it belongs to the next span so from a text selection point of view it isn't a problem.

Agreed, that seems OK to me too.

**Pull request merged**
