### PR TITLE
Check availability of canvas & PDF before printing

### LINKED ISSUE #6083: Print document before it loaded throws exception and completely disabled the print functionality
Any PDF document, with demo viewer, Chrome 43.0.2357.81 (64-bit), OS X 10.10.3

Click the print button before the document load completely, these errors shows on console:

```
viewer.js:6232 Uncaught TypeError: Cannot read property 'numPages' of null
viewer.js:684 Uncaught TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.
```

Then wait until the document loaded and click print will give this error

```
viewer.js:628 Ignored window.print() because of a pending print job.
```

### PR DESCRIPTION
**Pull request by Rob--W**
Fixes #6083

### CODE REVIEW

**Comment by timvandermeij** [comment]
@Snuffleupagus #6086 appears to fix the same issue, but this patch also addresses the polyfill. Can we go with this patch instead?

**Comment by Snuffleupagus** [comment]
> Can we go with this patch instead?

Sure. (I can address the indentation issue some other time.)

/botio-linux preview

**Comment by Snuffleupagus** [comment]
Thanks for the patch.

**Comment by pengliheng** [comment]
image
this issue hasn't fixed.

**Pull request merged**
