### PR TITLE
XFA - Avoid to have containers not pushed in the html

### LINKED ISSUE #13668: Large amount of text missing
Attach (recommended) or Link to PDF file here:
https://www.placementsmondiauxsunlife.com/content/dam/sunlife/regional/canada/documents/slgi/4839-I-F.pdf

Configuration:

- Web browser and its version: 91.0a1 (2021-07-03) (64-bit)
- Operating system and its version: Windows 10

Steps to reproduce the problem:
1. enableXfa = true
2. Open form

What is the expected behavior? (add screenshot)

image

What went wrong? (add screenshot)

image

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix issue #13668.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Compared with Adobe Reader, the `issue13611` test-case seems to regress a little bit.

**Comment by calixteman** [comment]
The issue fixed by this patch is a way worse than the regression.
So if you're ok, we can merge this PR and then we could update the m-c version (once https://bugzilla.mozilla.org/show_bug.cgi?id=1720159 is fixed too) and I'll fix the regression in a follow-up.
@marco-c, are you ok ?

**Comment by calixteman** [comment]
Finally the fix was pretty easy.

/botio test

**Review by marco-c — APPROVED** [review]

**Pull request merged**
