### PR TITLE
Update dependencies and translations to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks!

**Comment by timvandermeij** [comment]
@Snuffleupagus Thank you for the reviews!

For your information, there is a bug in Puppeteer 22.1.0 that was released today. I have bisected it and created https://github.com/puppeteer/puppeteer/issues/11938 so it can be fixed, hopefully before the next dependency update round. Just a heads-up in case you want to update dependencies later so you don't run into the same issue :-)

**Pull request merged**
