### PR TITLE
Tighten the `vars`-argument for the ESLint `no-unused-vars` rule

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Please see https://eslint.org/docs/latest/rules/no-unused-vars#vars

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
*Slightly off-topic here:* I've also been looking into possibly enabling the [`args: after-used`](https://eslint.org/docs/latest/rules/no-unused-vars#args-after-used) option, however that's less straightforward unfortunately.
The reason is that we have loads of interface definitions, base classes, and placeholder methods where arguments are "unused" by design. Hence we'd likely have to add `// eslint-disable-next-line no-unused-vars` comments all over the code-base, which doesn't feel great, but the rule could possible still be useful in order to find *truly* unused arguments!?

**Review by calixteman — APPROVED** [review]
LGTM.

**Pull request merged**
