### PR TITLE
Update the link location for 'intelisa.pdf' to point to the Internet Archive

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Given the the file changes every now and then, this patch should ensure that we test the _intended_ version.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@timvandermeij Do you have time to test/review this?
To confirm that the patch doesn't change anything, test this locally by moving the already downloaded `intelisa.pdf` file from `test/pdfs`. When you then run the tests, a "new" `intelisa.pdf` should be downloaded, without warning about a MD5 mismatch and (obviously) without causing any test failures.

**Comment by timvandermeij** [comment]
Thank you for the fix!

**Pull request merged**
