### PR TITLE
Support spaces and semicolons in filename (Content-Disposition)

### PR DESCRIPTION
**Pull request by Rob--W**
This PR is a follow-up to https://github.com/mozilla/pdf.js/pull/9383#issuecomment-362203603 and adds support for spaces and quoted strings in the filename of a `Content-Disposition` header.

It imports the following changes:
https://github.com/Rob--W/open-in-browser/commit/5b1afa7c29339627a7ed230473ab715d1364a740 (an insignificant one-character deletion).
https://github.com/Rob--W/open-in-browser/commit/7e2e35a38b8b4e981b11da7b2f01df0149049e92 (supports ; and " in quoted strings).

The changes are covered by unit tests at https://github.com/Rob--W/open-in-browser/blob/7e2e35a38b8b4e981b11da7b2f01df0149049e92/test/test-content-disposition.js#L268-L274 (and there are no regressions on previous tests)

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
> The changes are covered by unit tests at https://github.com/Rob--W/open-in-browser/blob/7e2e35a38b8b4e981b11da7b2f01df0149049e92/test/test-content-disposition.js#L268-L274 (and there are no regressions on previous tests)

Unless it's too much trouble, can we include a unit-test (or two) for these changes in the PDF.js repo as well?

r=me; thanks for improving this!

**Comment by Rob--W** [comment]
Done. The tests completed locally (and if Travis agrees too, you can merge it).

**Comment by timvandermeij** [comment]
Thank you for fixing this!

**Pull request merged**
