### PR TITLE
XFA - Add margins if needed after having layout some text

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix the text misplacement found in https://bugzilla.mozilla.org/show_bug.cgi?id=1716380.

### CODE REVIEW

**Review by marco-c — APPROVED** [review]
Can you run the reftests and ensure all changes are OK?

**Comment by calixteman** [comment]
> Can you run the reftests and ensure all changes are OK?

My bad, I thought we already have the file in the bug in the suite.

**Review by brendandahl — APPROVED** [review]
r+ if you're fine with the changes in `xfa_issue13500`. They seem mostly better, but I'm not sure if you're expecting that.

**Comment by calixteman** [comment]
I think the diff is correct but this pdf has other errors I need to fix.

**Pull request merged**
