### PR TITLE
Update dependencies and translations to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**
The Puppeteer update should in particular be helpful for us because it contains improved WebDriver BiDi compatibility, a newer Chrome version (both might help for #17962) and an official deprecation of CDP for Firefox. Note that the latter change requires no changes on our end because we already use WebDriver BiDi unconditionally for Firefox since https://github.com/mozilla/pdf.js/commit/4db01746d8e7dc2c5aa86d584db285b4f28e1c50. The full release notes can be found at https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v22.8.0.

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks!

**Comment by timvandermeij** [comment]
Closing since I'll redo this today with the most recent updates given the time that has passed since the Windows bot issue.

**Pull request closed without merging**
