### PR TITLE
Avoid re-parsing global images that failed decoding (issue 18042, PR 17428 follow-up)

### LINKED ISSUE #18042: Rendering crashes if PDF contains images which cannot be decoded
Attach (recommended) or Link to PDF file here: I cannot provide the PDF file due to NDA.

Configuration:
- Web browser and its version: all browsers, all versions
- Operating system and its version: all operating systems
- PDF.js version: 4.0.379 and newer, the bug was introduced in PR #17428.

If the PDF file contains an image which cannot be decoded, rendering fails trying to dereference a
`null` object.

Unfortunately, I cannot attach the PDF file due to NDA but I did some debugging and here are my
findings:

When `PartialEvaluator#buildPaintImageXObject()` fails to decode an image it sends `null` as
`imgData` to the main thread `this._sendImgData(objId, /* imgData = */ null, cacheGlobally);`.

The `WorkerTransport` object receives `null` in the `imageData` parameter in the `"obj"` handler and
calls `this.objs.resolve(id, imageData);` where `imageData == null` in the `case "Image"`
branch.

The `PDFObjects#resolve()` method replaces `INITIAL_DATA` in `obj.data` with `null`.

The `PDFObjects#*[Symbol.iterator]()` method filters out only `data === INITIAL_DATA` but not `data
== null`.

The `case "CopyLocalImage"` branch in the  `"commonobj"` handler iterates over `pageProxy.objs`:

```javascript
for (const [, data] of pageProxy.objs) {
  if (data.ref !== imageRef) {               // `data` can be `null` here.
    continue;
  }
  ...
}
```

and because `data` can be `null` the code crashes trying to access the `ref` property with an error
message in the console:

```plaintext
Warning: getOperatorList - ignoring XObject: "UnknownErrorException: Cannot read properties of null (reading 'ref')".
```

A simple fix `data.ref !== imageRef` -> `data?.ref !== imageRef` makes the PDF renderable again but
probably it just fixes the symptom, not the cause of the issue.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
For images that failed to decode once we want to avoid a pointless round-trip to the main-thread, which could otherwise happen for globally cached images.

---

~~*Please note:* Submitted as a "draft", since I'm not keen on making these changes without test-coverage.~~

Given the lack of a real-world PDF document, since none was provided, I've tried to manually create a broken one. However, I obviously cannot tell if it properly covers the original issue.

### CODE REVIEW

**Comment by plantago** [comment]
I tested the changes in this PR with the pdf files I was having problems with.
Everything works fine now.

**Review by timvandermeij — APPROVED** [review]
Looks good to me; the included PDF file seems to cover the problem well, also given that the original reporter shared that this patch solved the issue. Thanks!

**Review by calixteman — APPROVED** [review]
LGTM for me either. Thank you for doing this.

**Pull request merged**
