### PR TITLE
Ensure that dependencies are added to the operatorList for locally cached images (issue 18259)

### LINKED ISSUE #18259: Fix reference test "pr12564"
In PR #18257 we have seen the following intermittent failure in the reference tests:

```
TEST-UNEXPECTED-FAIL | test failed pr12564 | in chrome | page1 round 1 | render : Error: Requesting object that isn't resolved yet img_p0_15.
```

It looks like this happened only once before, in PR #18167, which may or may not be where this problem started. We should try to reproduce the issue locally. One idea is to repeatedly open/close the file until it happens so we can hopefully extract some debugging information to find out what goes wrong here.

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by Snuffleupagus** [comment]
Missed one case...

/botio test

**Comment by Snuffleupagus** [comment]
Locally I get less "severe" movement when testing on Windows, perhaps this is worse with `devicePixelRatio === 1` since I believe the bots use that?
Perhaps the `QueueOptimizer` logic is also affecting things, now that we're correctly handling cached imageMask-data as well?

In any case, given that this patch ought to *correct* are we OK with the ref-test movement in the latest round of testing?

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
I have checked locally that this indeed solves the issue. I have also checked the last round of reference tests and didn't find anything that was either noticeable with the naked eye or that was unexpected movement, and given that I agree that this patch should be correct I think we can do this. Thanks!

**Pull request merged**
