### PR TITLE
Fix PDFs that loop through "showSpacedText" with a whitespace first

### LINKED ISSUE #5687: Some text chunks misaligned
On second page of this [PDF file](https://dl.dropboxusercontent.com/u/7246095/IFAD_Enabling_Poor_Rural_People_concept_e.pdf) the `agriculture:`'s last part of the word is aligned elsewhere.

### PR DESCRIPTION
**Pull request by Hengjie**
Fixes https://github.com/mozilla/pdf.js/issues/5687

### CODE REVIEW

**Comment by Hengjie** [comment]
So still see places where this happens and I suspect it's because of the multiplication of `textState.textMatrix[0]` within `buildTextGeometry()` in evaluator.js. Do you guys have any idea of how to fix that? For example this [PDF](https://dl.dropboxusercontent.com/u/7246095/tori_6_tk_webre.pdf_150.pdf) has the same problem but isn't fixed with my PR.

**Comment by Hengjie** [comment]
So can we merge it? @yurydelendik @Snuffleupagus

**Comment by Hengjie** [comment]
Ok, I've finally figured out what was causing text to be misaligned and it's because of https://github.com/mozilla/pdf.js/pull/4633 @yurydelendik at the time introduced [`textState.textMatrix[0];`](https://github.com/mozilla/pdf.js/pull/4633/files#diff-0b94c2e77a5259f7a728122fdbf9f46aR894) but it didn't actually improve issue https://github.com/mozilla/pdf.js/issues/4631

Latest commit reverts that regression and puts it inline with how `display/canvas.js` and `display/svg.js` works with their `showText` op

**Comment by timvandermeij** [comment]
Closing as superseded by #5813.

**Pull request closed without merging**
