### PR TITLE
Don't duplicate the first entry in the `charCodeToGlyphId` map for CIDFontType2 fonts with a `CIDToGIDMap` that already mapped the first entry to a non-zero `glyphId` (issue 7544)

### LINKED ISSUE #7544: Embedded fonts do not render correctly.
Link to PDF file (or attach file here): [document.pdf ](https://github.com/mozilla/pdf.js/files/419419/document.pdf)

Configuration:
- Web browser and its version: Both Chrome `52.0.2743.116` and Firefox `47.0.1`
- Operating system and its version: OSX `10.11.4`
- PDF.js version: `1.5.376`

Steps to reproduce the problem:
1.  Download this document: [document.pdf ](https://github.com/mozilla/pdf.js/files/419419/document.pdf)
2. Load up in the viewer here: https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior?

We should see the document text displayed as `Testing PDF Conversion`:

chrome-native

What went wrong? (add screenshot)

We see that the `T` is missing:
firefox

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #7544.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
All the remaining intermittent test failures should be caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1292870, which hasn't yet been uplifted to Firefox 50.

**Comment by timvandermeij** [comment]
Should we bump the upstream issue for the uplift? They wanted to wait a few days, but it has been almost two weeks now.

**Comment by yurydelendik** [comment]
r+ with comment in the if-branch (probably similar to the pr title)

**Comment by yurydelendik** [comment]
(related issue #3427)

**Comment by Snuffleupagus** [comment]
> r+ with comment in the if-branch (probably similar to the pr title)

A comment has been added; thank you for the review here, and in the other recent font PR :-)

/botio test

**Comment by timvandermeij** [comment]
Thank you for working on this!

**Comment by cetra3** [comment]
Awesome work!  Has there been a version number allocated to PDFjs that includes this fix?

**Comment by Snuffleupagus** [comment]
> Awesome work! Has there been a version number allocated to PDFjs that includes this fix?

Given that this landed less than a day ago, it's not part of any [official release](https://github.com/mozilla/pdf.js/releases) just yet.
However, this patch is included in PDF.js version `1.5.446` (or above). For information about obtaining the latest version of PDF.js, please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#is-there-a-pre-built-version-pdfjs-available.

**Pull request merged**
