### PR TITLE
Remove the |el| property in PDFPageView and PDFThumbnailView

### PR DESCRIPTION
**Pull request by Snuffleupagus**
~~Obviously it would have been nicer to just remove it all together, but in the event that some third-party implementation depends on it, I figured that we might want to keep it around for `GENERIC` builds for now.~~

### CODE REVIEW

**Comment by CodingFabian** [comment]
how will a developer know that this has been deprecated?
right now i would even prefer to remove this (its not really public api). Developers building on the code would quickly see that el no longer exist and could easily rewrite to use the div element.

**Comment by timvandermeij** [comment]
I agree with @CodingFabian. I'm fairly sure no-one is using this, and if so they will notice soon enough that it has been deprecated if we remove it. If we keep enabling it for generic builds, most people wouldn't notice that it's deprecated I think.

**Comment by Snuffleupagus** [comment]
I only left `el` for `GENERIC` builds as a matter of consistency, since we've done similar things with other code, e.g. [this](https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L1371-L1373) and also [this](https://github.com/mozilla/pdf.js/blob/master/web/pdf_page_view.js#L417-L425). But in this particular case, I don't have a strong opinion either way.

**Comment by brendandahl** [comment]
We're not currently versioning the viewer API and we warn about this in the getting started code.  Let's just wipe this out.

**Comment by Snuffleupagus** [comment]
It's gone now!

/botio-windows preview

**Comment by yurydelendik** [comment]
Thank you

**Pull request merged**
