### PR TITLE
[api-minor] Remove the default factories, used to initialize various layers, in the viewer

### PR DESCRIPTION
**Pull request by Snuffleupagus**
The purpose of this patch series is to reduce indirection, and the amount of code that we need to maintain, related to the various layers used in the viewer. *Please refer to the individual commit messages for additional details.*

### CODE REVIEW

**Comment by timvandermeij** [comment]
I'm happy about getting rid of this what I also experienced as unnecessary indirection. 'll try my best to review this during the weekend. Am I correct that third-party users should now simply set the relevant `TextLayerMode`/`AnnotationMode` settings in order to toggle text/annotation (and therefore struct tree/XFA/editor) layers?

**Comment by Snuffleupagus** [comment]
> I'm happy about getting rid of this what I also experienced as unnecessary indirection. I'll do my best to review this during the weekend.

Thank you!

> Am I correct that third-party users should now simply set the relevant `TextLayerMode`/`AnnotationMode` settings in order to toggle text/annotation (and therefore struct tree/XFA/editor) layers since it cannot be toggled via the component constructor anymore?

Correct, but please note that it *only* applies to [the "pageviewer" example](https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js) and that the "simpleviewer"/"singlepageviewer" examples are completely unaffected here.
Furthermore, note how `PDFPageView` currently needs both options *and* factories specified in order for things to work; see https://github.com/mozilla/pdf.js/blob/1ab711e2ac5c2c4b9ae873d9f1e3454df9a9f899/web/pdf_page_view.js#L70-L83

> I'm a little bit concerned about if this will break third party usage since we also had to edit the component examples here, so I'll have to think about if `[api-minor]` is appropriate here since the components were intended to be more stable than the regular viewer.

That's a fair comment; although it (as mentioned above) only applies to the "pageviewer" example.

> I would feel much better about this patch if we could replace the factory endpoints with dummies that only issue a deprecation warning for let's say a release or two and simply do nothing else. That way at least current usages don't outright break.

OK, how about if I just add dummy factories in [the `pdf_viewer.component.js` file](https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.component.js) where we simply throw when they're invoked (since that can't be missed and forces users to adjust)?

**Comment by timvandermeij** [comment]
> OK, how about if I just add dummy factories in [the pdf_viewer.component.js file](https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.component.js) where we simply throw when they're invoked (since that can't be missed and forces users to adjust)?

Let's do that so that _if_ this is being used (and fortunately that should be very limited given that only one of the examples is affected by this, and I therefore agree that this is `[api-minor]`) that we at least give out a useful error message that suggests how users should adapt their code. This can then be removed after a couple of releases, but it does give users a bit more pointers on how to adapt their code.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks really good to me; thank you for simplifying this!

**Comment by Snuffleupagus** [comment]
> Looks really good to me; thank you for simplifying this!

Thanks for the review!

**Pull request merged**
