### PR TITLE
Prevent mouse-wheel zooming *outside* of the viewer from being interpreted as a pinch-gesture (bug 1810800, PR 15907 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This is essentially a slightly hacky work-around, to prevent the pinch-gesture handling added in PR #15907 from being invoked when mouse-wheel zooming starts *outside* of the viewer.
Note that since we don't focus the viewer, upon PDF document load, when it's embedded we need to use different initial values for the `PDFViewerApplication._isCtrlKeyDown` property.

### CODE REVIEW

**Comment by calixteman** [comment]
I just tested on a laptop with windows 11 and the problem is that pinch-to-zoom is disabled when the window is left and there is no way to get it back except in hitting ctrl in the focused window.
I tried to play with `mouseenter` in checking if ctrlKey is true but at least in Firefox it doesn't work as I expected. And when the viewer isn't focused key events are not caught and then we don't know if ctrl is pressed....
Having those pinch-to-zoom events backed on a wheel+ctrl is really a terrible thing... :(

**Comment by calixteman** [comment]
Maybe I've an idea to avoid to have all those events/workarounds.
Let me try a PR and we can iterate.

**Comment by Snuffleupagus** [comment]
> Having those pinch-to-zoom events backed on a wheel+ctrl is really a terrible thing... :(

Completely agreed; there really should be *some* way, e.g. a property on the event, to determine if this "special" kind of zooming is happening.

> Maybe I've an idea to avoid to have all those events/workarounds.
> Let me try a PR and we can iterate.

Given that this is a regression, and the next PDF.js release is probably this weekend, I wonder if we should take this PR for now (since a larger PR could take longer to review/land)?

**Pull request closed without merging**
