### PR TITLE
Support running the tests headlessly.

### PR DESCRIPTION
**Pull request by brendandahl**
Now you can add "headless: true" to the browser_manifest.json. I can't get headless to work on Chrome with MacOS though.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Nice work! I was thinking about this some time ago because I hoped that we could eventually run the reference tests on Travis CI too, and not requiring a display would make that a bit easier.

**Comment by Rob--W** [comment]
@brendandahl Can you provide log files (maybe via IRC?)

**Comment by brendandahl** [comment]
I was getting:
```
ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.
```
I ended up finding https://github.com/testem/testem/issues/1117#issuecomment-356534997 and it now seems to work locally.

**Comment by timvandermeij** [comment]
@brendandahl Could you fix up this PR so we can merge it?

I'm thinking that we could use this to perhaps run more tests on Travis CI instead of on the bots. The only problem is that we need a place to store reference images and PDFs, but according to Travis CI documentation a simple Amazon S3 bucket can be used for persistent storage.

**Comment by brendandahl** [comment]
Note: with chrome I'm currently running into https://bugs.chromium.org/p/chromium/issues/detail?id=848210 on MacOS.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
I tried this locally and it worked just fine. Thank you for implementing this!

**Pull request merged**
