### PR TITLE
Added enter key functionality for presentation mode

### LINKED ISSUE #9116: enter key in presentation slide mode
<Steps to reproduce the problem:>
1. opening the pdf file using pdf.js
2. switch it to the presentation slide mode
3. 

> upon entering the enter key, it doesn't work

<What is the expected behavior? (add screenshot)>
upon entering the enter key, I do hope it occurs the same result as entering the space bar or the end key

<What went wrong? (add screenshot)>
nothing happens after the enter key behavior

> **_requesting PR_**

 for modifying the code 
(inserting enter key for diversifying in terms of entering keys upon switching to the next slide)

(e.g; this is the example opening the slide version)
image

### PR DESCRIPTION
**Pull request by bansalnitish**
Fixes #9116

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
If we decide to do this, then <kbd>Shift</kbd>+<kbd>Enter</kbd> (compare with the `Spacebar` case) must be implemented as well.

**Comment by bansalnitish** [comment]
I have made the requested changes !

**Comment by timvandermeij** [comment]
Could you squash the two commits into one commit? Refer to https://github.com/mozilla/pdf.js/wiki/Squashing-Commits for how to do this easily if you're not familiar with the process. We ask contributors to do this because it keeps the commit history clean, i.e., one specific feature is located in one specific commit then.

**Comment by bansalnitish** [comment]
@timvandermeij I have squashed the commits !

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you!

**Pull request merged**
