### PR TITLE
[api-minor] Use a CSS transform to update the progress bar instead of changing the width (bug 1768481)

### PR DESCRIPTION
**Pull request by calixteman**
- it isn't a fix for bug 1768481 but just a tiny improvement to refresh the progress bar on the compositor thread.

### CODE REVIEW

**Comment by marco-c** [comment]
> First of all, given that there appeared to be a suggestion in the bug about never using the viewer-loadingBar and instead only use the existing browser loading-indicator (in the tab); is this something that's being seriously considered here?
> 
> Because if we end up doing that, which based on looking through the relevant code just now might not actually be that difficult to implement, these sort of changes feels mostly moot to me.

I think we should ask an opinion to some UX expert.

**Comment by marco-c** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1769023 to take into consideration removing the progress bar or reducing the cases where it is shown.
Moving the animation to the compositor thread would be good for perf and power usage.

**Comment by Snuffleupagus** [comment]
Given the second point mentioned in https://github.com/mozilla/pdf.js/pull/14898#issuecomment-1122624581, if we need to change the CSS used to update the loadingBar it'd probably make sense to *explicitly* remove support for any options in the `ProgressBar`-constructor *first* (since that'd probably simplify things).

**Comment by calixteman** [comment]
Thanks to this change the animation can run on the compositor thread:
image

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Did you forget to test the `indeterminate` ProgressBar, since that one no longer works :-P

(When I want to manually test that one, I usually [change this line](https://github.com/mozilla/pdf.js/blob/63441e8f1e0535bec938b34e2bc564cbd0dd0ad7/web/app.js#L1128) to `const percent = NaN;` instead.)

To fix that, it seems that just replacing https://github.com/mozilla/pdf.js/blob/63441e8f1e0535bec938b34e2bc564cbd0dd0ad7/web/viewer.css#L382 with `transform: none;` is sufficient.

Finally, please remember to make the same exact changes in https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer as well.

**Comment by calixteman** [comment]
I didn't know about `indeterminate` state, thank you for pointing that out.
I slightly changed the animation to have it on the compositor thread:
image

**Comment by Snuffleupagus** [comment]
> I didn't know about `indeterminate` state, thank you for pointing that out.

Note that in practice it's pretty rare to see that one, since it only happens if a server doesn't provide a (valid) `contentLength` which means that it's impossible to tell how much of the PDF document is loaded; see e.g.
 - https://searchfox.org/mozilla-central/rev/6d396b2abda4371f54251e9de8dc790deab706fc/toolkit/components/pdfjs/content/PdfStreamConverter.jsm#197
 - https://searchfox.org/mozilla-central/rev/6d396b2abda4371f54251e9de8dc790deab706fc/toolkit/components/pdfjs/content/PdfStreamConverter.jsm#208-211

**Pull request merged**
