### PR TITLE
Use the `waitForEvent` helper function in the text layer integration tests

### PR DESCRIPTION
**Pull request by timvandermeij**
The `waitForClick` helper function is functionality-wise mostly a reduced copy of the more generic `waitForEvent` helper function that we use for other integration tests, so we can safely replace it to reduce the amount of code.

Moreover, the `waitForClick` code is prone to intermittent failures given recent assertion failures we have seen on the bots (one of them is linked in #18396) while `waitForEvent` has recently been fixed to avoid intermittent failures, so usiong it should also get rid of the flakiness for these integration tests.

Fixes a part of #18396.

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks for cleaning this up, and sorry for having introduced the flake! The reason I originally introduced a new helper was that I didn't realize I could use the "validator" to call `e.preventDefault()`.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by timvandermeij** [comment]
@nicolo-ribaudo No worries; I also didn't catch this during review, and such intermittent issues unfortunately often only tend to show up after a number of runs, and on the slower bot which makes it hard to reproduce locally.

**Pull request merged**
