### PR TITLE
Better errors capturing at the core and stop rendering on error.

### PR DESCRIPTION
**Pull request by yurydelendik**
It shall better capture errors during PDF parsing (as in #6707 case).

### CODE REVIEW

**Comment by brendandahl** [comment]
What about instead of wrapping with a next/promiseBody doing https://github.com/brendandahl/pdf.js/commit/e63cd5ce9ca8965839f6e8d0e9aa9c02c99ce7b4 ?

**Comment by yurydelendik** [comment]
This was an issue in the past https://bugzilla.mozilla.org/show_bug.cgi?id=1008467

**Comment by yurydelendik** [comment]
> What about instead of wrapping with a next/promiseBody doing brendandahl@e63cd5c ?

So difference is that we have to keep in memory all promises vs just only very top one.

**Comment by brendandahl** [comment]
> So difference is that we have to keep in memory all promises vs just only very top one.

Yes, one of the differences. Alternative looks cleaner to me. 

What tripped me up on your approach for a bit were the calls where there's `return next(...` I had originally thought this was my alternative approach. Seems strange to return a function call that returns nothing. How about use your approach but move the returns to there own line e.g. `next(...); return;`

**Comment by timvandermeij** [comment]
What is the status of this patch? Does it only need the fix above or do we need more to land this?

**Comment by timvandermeij** [comment]
@yurydelendik @brendandahl Do you have time to fix this up so it can be merged?

**Comment by Snuffleupagus** [comment]
Great, it seems that the Firefox 45 -> 46 update made the Linux bot even more unstable than before :-(

/botio-linux test

**Pull request merged**
