### PR TITLE
Restore broken functionality and simplify the implementation in `src/display/text_layer.js`

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please refer to the individual commit messages for additional information.*

### CODE REVIEW

**Comment by marco-c** [comment]
I wonder if the limit will help with https://bugzilla.mozilla.org/show_bug.cgi?id=1890537 and/or https://bugzilla.mozilla.org/show_bug.cgi?id=1838865.

**Comment by Snuffleupagus** [comment]
> I wonder if the limit will help with https://bugzilla.mozilla.org/show_bug.cgi?id=1890537

I don't *think* so, since the number of textLayer elements are quite low there with < 400 per page.

> or https://bugzilla.mozilla.org/show_bug.cgi?id=1838865.

The PDF link in the bug seems dead, but a version of the file is available through the Internet Archive. Even in that case we're *below* the limit, with approximately 28000 respectively 66000 textLayer elements for the two pages.

**Review by timvandermeij — APPROVED** [review]
Looks good; thank you for simplifying this! (Initially I was a bit confused about the `render` method not doing much anymore after the first commit, but luckily the third commit got rid of the indirection altogether.)

r=me, with passing Windows tests once the bot is working again.

**Pull request merged**
