### PR TITLE
Update dependencies and translations to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**
Note that this is another step towards #17928 because `eslint-plugin-no-unsanitized` (see https://github.com/mozilla/eslint-plugin-no-unsanitized/releases/tag/4.1.0) now supports ESLint 9 and `eslint-plugin-import` (see https://github.com/import-js/eslint-plugin-import/releases/tag/v2.30.0) now has support for flat configuration, which is a prerequisite for supporting ESLint 9 later on.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
> [...] and `eslint-plugin-import` (see https://github.com/import-js/eslint-plugin-import/releases/tag/v2.30.0, the "add support for Flat Config" item) are now compatible with ESLint 9.

Does that plugin actually support ESLint 9 now though, given that https://github.com/import-js/eslint-plugin-import/issues/2948 is still open?
While support for the Flat Config format is a pre-requisite for ESLint 9 compatibility, it may not be the only thing required.

**Comment by timvandermeij** [comment]
You're right; looking at https://github.com/import-js/eslint-plugin-import/pull/3018 confirms that this mainly lays the foundation for supporting ESLint 9, but that's indeed a separate issue. I have amended the PR description to reflect that.

**Comment by timvandermeij** [comment]
It looks like the Puppeteer 23.3.0 update causes some integration tests to fail due to suddenly different expectations. I have change the update to Puppeteer 23.2.2 instead to find out if that is the last working version, and if so this PR becomes unblocked and I'll make a follow-up issue to update Puppeteer to version 23.3.0 and above since that'll require more debugging for what's going on on Windows and I don't have a Windows machine at the moment to do that (see https://github.com/mozilla/pdf.js/pull/18708#issuecomment-2336715567).

**Comment by timvandermeij** [comment]
I have removed the Puppeteer update due to a couple of sudden integration test failures on Windows only (see http://54.193.163.58:8877/562f5aeb62a0629/output.txt). I'll create a follow-up issue to investigate that later.

/botio test

**Comment by timvandermeij** [comment]
Hm, it failed again, even without the Puppeteer update. It might then be caused by a browser update on the bots. I'll retry on a clean PR without any other changes to confirm.

**Comment by timvandermeij** [comment]
It turns out that the Windows failures are not caused by this PR, but are a regression from #18698 where they showed up in https://github.com/mozilla/pdf.js/pull/18698#issuecomment-2336406803 already. I have reverted this PR to the original state with the Puppeteer update again so this is now unblocked.

/botio test

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.

**Review by Thompson1985 — APPROVED** [review]

**Pull request merged**
