### PR TITLE
Feature add - Find match count (issue #4805)

### PR DESCRIPTION
**Pull request by andyparisi**
Hi all!

This is my first contribution to the project (and first time looking at this codebase)–so I apologize ahead of time if I have missed anything obvious. What I've done here is try to implement a simple match count for the find bar.

Please let me know if there's something I have misplaced or just done wrong. I'm open to feedback and look forward to contributing more to this project.

### CODE REVIEW

**Comment by heavensrevenge** [comment]
Any progress on this?  I'm glad there has been others interested in a such a simple but extremely useful piece of information about a document.

**Comment by Inversion-des** [comment]
Applied this patch manually for some older version. 
Works for me. Thank you!

**Comment by brendandahl** [comment]
@andyparisi Could you rebase your branch I think this is good to go.

> To make this perform better, we should probably do what the native find bar does in Firefox and stop counting matches above some reasonable threshold. In Firefox, the default value is 100.

The calculation of the number of matches shouldn't be an issue here, but yes we should probably limit matches somewhere else in the code. This can be in a different PR though.

**Comment by yurydelendik** [comment]
Merged by c2e70ea7268222ffc48039f6c613269ee0e3f6d4

Thank you for the patch

**Pull request closed without merging**
