### PR TITLE
Remove unneeded awaits for events from input actions

### PR DESCRIPTION
**Pull request by lutien**
This logic is problematic to run with WebDriver BiDi, because if we don't await on the script evaluation, we have no guarantee that the script was fully run before the code goes to the next step. In this case, for example, the event listener is set up after the input actions are triggered, so the event is never caught and promise is never resolved.
It looks like it's not really needed here, neither for WebDriver BiDi nor for CDP.

### CODE REVIEW

**Comment by calixteman** [comment]
We use a similar pattern at different places in the tests for example:
https://github.com/mozilla/pdf.js/blob/319e85449ea6b49bb89a5542def5f88894c812ee/test/integration/ink_editor_spec.mjs#L28
https://github.com/mozilla/pdf.js/blob/319e85449ea6b49bb89a5542def5f88894c812ee/test/integration/ink_editor_spec.mjs#L81-L86

**Comment by whimboo** [comment]
> We use a similar pattern at different places in the tests for example:
> 
> https://github.com/mozilla/pdf.js/blob/319e85449ea6b49bb89a5542def5f88894c812ee/test/integration/ink_editor_spec.mjs#L28
> 
> https://github.com/mozilla/pdf.js/blob/319e85449ea6b49bb89a5542def5f88894c812ee/test/integration/ink_editor_spec.mjs#L81-L86

Yes, we wanted to get these tests running in CI first for this particular case with CDP to see if that makes a difference. While this is fine other tests are failing. Not sure if that is a known issue with reference images or not?

Also please note that when I checked the puppeteer unit tests none of the input tests actually checked for events, so whenever such a related command has been awaited for we probably can assume that the event has been dispatched on the page. CC @orkon for proper feedback from the Puppeteer team.

**Comment by calixteman** [comment]
> Yes, we wanted to get these tests running in CI first for this particular case with CDP to see if that makes a difference. While this is fine other tests are failing. Not sure if that is a known issue with reference images or not?

Yes, those failures in ref tests are known (due to small invisible pixel differences because of antialiasing most of the time).

**Comment by OrKoN** [comment]
> This logic is problematic to run with WebDriver BiDi, because if we don't await on the script evaluation, we have no guarantee that the script was fully run before the code goes to the next step. In this case, for example, the event listener is set up after the input actions are triggered, so the event is never caught and promise is never resolved.
It looks like it's not really needed here, neither for WebDriver BiDi nor for CDP.

I wonder if we should address this in the BiDi spec. The pattern is relatively common in CDP/Puppeteer and I know that it used often in tests. In Chrome, the script is guaranteed to run first because both commands run on the page's main thread eventually. Is it not the case for Firefox?

**Comment by OrKoN** [comment]
So to correct myself above: the dispatch of the evaluate was happening synchronously at some point but it has [regressed](https://github.com/puppeteer/puppeteer/issues/11507). I'd recommend using the following pattern which would be more reliable:

```
          let promise = await page.evaluateHandle(
            () =>
              [new Promise(resolve => {
                document.addEventListener("selectionchange", resolve, {
                  once: true,
                });
              })]
          );
          await page.click("#pageNumber");
          await promise.evaluate(promise => promise[0]);
```

**Comment by calixteman** [comment]
@whimboo, @lutien,  I made this PR:
https://github.com/mozilla/pdf.js/pull/17387
so I guess this one is useless now.

**Pull request closed without merging**
