### PR TITLE
[WIP]Can display PDF without indirect references to fonts

### PR DESCRIPTION
**Pull request by HirokiTamura1**
I want to display PDF characters that do not exist in the table used for character code mapping processing.

### CODE REVIEW

**Comment by HirokiTamura1** [comment]
Publishing a PDF is difficult because the problem arises from the customer's PDF data used in the project.
The wording of the error is "Warning: loadFont --translateFont failed:" XRefEntryException: Bad (uncompressed) XRef entry: 28R ".
pdf.js: 1895 Warning: Error during font loading: Bad (uncompressed) XRef entry: 28R, Warning: loadFont --translateFont failed: "XRefEntryException: Bad (uncompressed) XRef entry: 31R".
pdf.js: 1895 Warning: Error during font loading: Bad (uncompressed) XRef entry: 31R ,,,, ".

**Comment by marco-c** [comment]
Could you generate a PDF with fake data that reproduces the problem?

**Comment by HirokiTamura1** [comment]
> Could you generate a PDF with fake data that reproduces the problem?
Please give me some time. I making PDF without secret information. I have PDF that looks better with this patch in my hands, and the PDF can`t show you.

**Comment by HirokiTamura1** [comment]
[sample3c.pdf](https://github.com/mozilla/pdf.js/files/9099487/sample3c.pdf)I have created a PDF that can be published by editing customer information, so I will attach it.

The character part is displayed in other PDF viewers, but the character part is not displayed when using the viewer attached to PDF.js.

**Pull request closed without merging**
