### PR TITLE
Replacing custom bundling with webpack 2

### PR DESCRIPTION
**Pull request by yurydelendik**

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
*I've not reviewed all the builder changes in minute detail, however everything looks OK as far as I can tell!*

Besides testing this locally, I've also built the Firefox addon with this patch and used it during the day without encountering any issues, so everything appears to work as it should!

I've got one small question though: In the `webpackBootstrap` blocks added at the top of the built files there's a lot of `tabs` used, is there some configuration parameter we can utilize to have `spaces` instead?

r=me, with passing tests.
Really nice effort here, thank you for doing this!

**Comment by MSchip** [comment]
This seems to have broken the pdf.combined.js build: https://github.com/mozilla/pdfjs-dist/commits/master/build/pdf.combined.js.

console error:
```
pdf.combined.js:20815 Uncaught ReferenceError: pdfjsLibs is not defined
    at e (pdf.combined.js:20815)
```

**Pull request merged**
