### PR TITLE
fix(browser): zlib is not available in browser

### PR DESCRIPTION
**Pull request by ErikNijland**
Solves #9923

### CODE REVIEW

**Comment by gabrielalan** [comment]
@Snuffleupagus @yurydelendik @timvandermeij  That would be a nice think to have!!!!

**Comment by yurydelendik** [comment]
Thank you

**Comment by ErikNijland** [comment]
You're welcome!

Can you give some insight into the pdfjs-dist releases? Now that this is fixed I'd like to use it in our project. But that requires a new pdfjs-dist release.

**Comment by timvandermeij** [comment]
The `pdfjs-dist` library is updated when the next release is made, which will be the final 2.0 version.

**Comment by jlberrocal** [comment]
Any updates on when is this going to be released???

**Comment by thinhbuzz** [comment]
please update for v1

**Comment by jlberrocal** [comment]
@thinhbuzz what you mean by v1?

**Comment by thinhbuzz** [comment]
@jlberrocal 
sorry, i mean `pdfjs-dist` version 1.*

**Comment by jlberrocal** [comment]
i tested using latest v1 release and problem is there too, BTW there was a release 4 days ago which says that fix this issue, i haven't tested yet

**Comment by timvandermeij** [comment]
The stable 2.0 release is now made, so this should be fixed if you upgrade.

**Comment by dotNetAthlete** [comment]
I get this problem using Angular 7.

This is from my package.json:
"private": true,
  "dependencies": {
    "@angular/animations": "^7.0.2",
    "@angular/cdk": "^6.4.3",
    "@angular/common": "^7.0.2",
    "@angular/compiler": "^7.0.2",
    "@angular/core": "^7.0.2",
    "@angular/forms": "^7.0.2",
    "@angular/http": "^6.1.0",
    "@angular/material": "^6.4.3",
    "@angular/platform-browser": "^7.0.2",
    "@angular/platform-browser-dynamic": "^7.0.2",
    "@angular/router": "^6.1.0",
    "@ng-bootstrap/ng-bootstrap": "^4.0.0",
    "@ng-select/ng-select": "^2.12.0",
    "@ngx-pwa/local-storage": "^6.0.0-rc.1",
    "angular-font-awesome": "^3.1.2",
    "blob-util": "^2.0.2",
    "bootstrap": "^4.1.3",
    "buffer": "^5.2.1",
    "compass-mixins": "^0.12.10",
    "core-js": "^2.5.4",
    "cors": "^2.8.4",
    "events": "^3.0.0",
    "font-awesome": "^4.7.0",
    "formidable": "^1.2.1",
    "guid-typescript": "^1.0.9",
    "js-xlsx": "^0.8.22",
    "ng2-file-upload": "^1.3.0",
    "ng2-pdf-viewer": "^5.2.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "stream": "0.0.2",
    "timers": "^0.1.1",
    "websocket-extensions": "^0.1.3",
    "ws": "^3.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "^7.0.4",
    "@angular/compiler-cli": "^7.0.2",
    "@angular/language-service": "^7.0.2",
    "@types/jasmine": "^2.8.9",
    "@types/jasminewd2": "^2.0.5",
    "@types/node": "^10.12.2",
    "codelyzer": "^4.5.0",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngx-typeahead": "^6.2.0",
    "protractor": "^5.4.1",
    "ts-node": "~5.0.1",
    "tslint": "^5.11.0",
    "typescript": "^3.1.6",
    "webpack-dev-server": "^3.1.10"

**Pull request merged**
