### PR TITLE
Add a reduced test-case for issue 6113

### PR DESCRIPTION
**Pull request by Snuffleupagus**
As promised in PR #6125, here's a reduced test-case that should (hopefully) avoid the intermittent failure of the previous one.

### CODE REVIEW

**Comment by timvandermeij** [comment]
@yurydelendik @brendandahl Any idea what's wrong with the Windows bot? I have never seen this error before. It seems like it could not download a resource tarball before and is now locking the other modules.

**Comment by Snuffleupagus** [comment]
While we wait for the Windows bot to be fixed; let's check that this test-case doesn't cause any intermittent failures on Linux, as the previous one did.

/botio-linux test

**Comment by timvandermeij** [comment]
Nice work!

**Pull request merged**
