### PR TITLE
Update eslint-plugin-mozilla to ^1.0.1

### PR DESCRIPTION
**Pull request by wojtekmaj**

### CODE REVIEW

**Comment by timvandermeij** [comment]
This requires an update of `npm` on the bots, at least on the Linux bot. I asked on IRC if that can be done.

**Comment by timvandermeij** [comment]
In the meantime, could you rebase this now that the other patches have been merged?

**Comment by timvandermeij** [comment]
@wojtekmaj Could you rebase this again? We should be good now since Node.js/NPM/Gulp got updated on the bots.

**Comment by wojtekmaj** [comment]
@timvandermeij Done :)

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for helping out with this!

**Pull request merged**
