### PR TITLE
Disable the "copy all text" feature when `enablePermissions` is set (PR 16286 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
When permissions are enabled and the PDF document doesn't have the COPY-flag set, it shouldn't be possible for the user to trigger the "copy all text" feature.

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM.

**Comment by calixteman** [comment]
Oh I missed the draft status.

**Comment by Snuffleupagus** [comment]
> Oh I missed the draft status.

The GENERIC viewer can open more than one document, which I obviously forgot about initially; please check the updated patch.

**Review by calixteman — APPROVED** [review]

**Comment by Snuffleupagus** [comment]
> Do you plane to disable copy here too:
> https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js#L217 ?

I don't believe that we need to, since we have CSS rules that prevent user-selection.
https://github.com/mozilla/pdf.js/blob/3e292dc2228ce957a912f6e52b211a59edb55bcd/web/pdf_viewer.css#L196-L199

**Comment by calixteman** [comment]
> > Do you plane to disable copy here too:
> > https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js#L217 ?
> 
> I don't believe that we need to, since we have CSS rules that prevent user-selection.
> 
> https://github.com/mozilla/pdf.js/blob/3e292dc2228ce957a912f6e52b211a59edb55bcd/web/pdf_viewer.css#L196-L199

After having thinking about that, I think it could be useful to be able to select the text (for example when the user wants to show something to someone else) even if the copy is disabled (I personally already have been in such a situation and it was a bit painful). So I'd inclined to remove the CSS rule and disable the copy in the copy listener. Wdyt ?
When the pdf doesn't have the full permissions, maybe we should display an icon in the toolbar (like a lock or something like that) with a tooltip indication what the permissions are. And when the user try to copy when he isn't allowed to, then we could highlight this icon... or something like that.

**Comment by Snuffleupagus** [comment]
> After having thinking about that, I think it could be useful to be able to select the text (for example when the user wants to show something to someone else) even if the copy is disabled (I personally already have been in such a situation and it was a bit painful). So I'd inclined to remove the CSS rule and disable the copy in the copy listener. Wdyt ?

Sure, we could implement it like that without too much trouble I think; I'll submit a patch for this later.

> When the pdf doesn't have the full permissions, maybe we should display an icon in the toolbar (like a lock or something like that) with a tooltip indication what the permissions are. And when the user try to copy when he isn't allowed to, then we could highlight this icon... or something like that.

In Adobe Reader there's an additional sidebar-view in protected documents, but given that we ignore permissions by default that feels like a slightly too "heavy" solution in the PDF.js viewer. Your idea about an additional toolbarButton with a tooltip sounds simpler, although we'd probably need a couple of new l10n-strings for that.
Also, this part definitely feels like something where having UX input *before* we start coding would help.

**Pull request merged**
