### PR TITLE
XFA - Page can be too small when printing (bug 1723705)

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by marco-c** [comment]
Can you add a test?

**Comment by calixteman** [comment]
Unfortunately, I think we don't have such tests for now.
I filed a bug: https://github.com/mozilla/pdf.js/issues/13853

**Comment by marco-c** [comment]
> Unfortunately, I think we don't have such tests for now.

What does setting "print: true" in test_manifest.json do then?

**Comment by calixteman** [comment]
Some data are picked up in the annotation storage in order to be used as values for some text fields, checkboxes, ... (depending on the id).

**Comment by Snuffleupagus** [comment]
> What does setting "print: true" in test_manifest.json do then?

It tests only the *rendering* pipeline of the PDF.js library, by using the correct intent and placing Annotation-data on the canvas itself, but doesn't actually cover *complete* printing process as it happens in the browser.

**Review by marco-c — APPROVED** [review]

**Pull request merged**
