### PR TITLE
Dummy test PR: do not merge!

### PR DESCRIPTION
**Pull request by brendandahl**

### CODE REVIEW

**Comment by timvandermeij** [comment]
@yurydelendik Firefox has been updates to version 48, causing the test failures above. Most can be resolved with a simple makeref, but for instance "firefox-bug946506-page1" is notably worse. Should we just makeref here and file a bug report upstream for this somehow? Maybe there are more, I did not check all of them yet.

**Comment by yurydelendik** [comment]
Let's makeref but create an issue for the thing above

**Comment by timvandermeij** [comment]
Funny that for example "firefox-tracemonkey-eq-page11" improved in comparison to the reference. I'll go through all of them now and create an issue for broken ones.

**Pull request closed without merging**
