### PR TITLE
Use UglifyJS to minify files in minified target

### PR DESCRIPTION
**Pull request by TimothyGu**
It is written in JavaScript, is less buggy, and compresses better.

### CODE REVIEW

**Comment by timvandermeij** [comment]
I like the idea of this. In addition to what you mention, less code is required and it can be downloaded automatically as it is an NPM dependency. We do need to make sure that this uglifier does not break the final build. Did you verify that already?

**Comment by TimothyGu** [comment]
@timvandermeij Yes. I've been using UglifyJS in [production](http://lilybin.com) and no bugs have been reported or observed because of the minifier.

**Comment by TimothyGu** [comment]
Seems like I spoke too soon. Google Chrome chokes on minified files after 2edf2792dcb6adbfffed242cc5c02b412157e45c (committed 4 days ago) because of long sequences generated by UglifyJS. It only affects pdf.worker.js, so I have added a workaround for that file specifically. The workaround increases the output size by less than 1KB, which is less than 0.2% of the total file size.

On the other hand, I did some benchmarking, and found that Closure Compiler compiles all three files marginally better (difference <1%), at the cost of 8 times more CPU time. The fact that after gzipping one of the files compiled by UglifyJS is smaller than the counterpart produced by Closure doesn't help Closure's case either.

So all in all, even though some Chrome bug makes UglifyJS's output look "buggy," its sheer performance and good-enoughness makes it a lot better choice.

**Comment by timvandermeij** [comment]
@yurydelendik What do you think about this patch?

**Comment by yurydelendik** [comment]
target.minified is not used on the botio. @timvandermeij if it works as advertised than we can accept it. (I saw somewhere messages about UglifyJS has some problem with our new code base).

**Comment by timvandermeij** [comment]
I did more testing with this and found no further issues. Thank you for the patch!

**Comment by timvandermeij** [comment]
I have just updated the frequently asked questions wiki page to mention what has been changed in this update.

**Comment by TimothyGu** [comment]
+1

**Pull request merged**
