### PR TITLE
A couple of small tweaks of the `PDFCursorTools` class

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please refer to the individual commit messages.*

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice clean-up!

**Comment by Snuffleupagus** [comment]
@timvandermeij As always, thanks for the reviews :-)

Do you have time to create a new release this weekend, since there's new editing-feature in progress (adding of Stamp-annotations, i.e. allowing users to insert images) that we don't want to land just before a release?

**Comment by timvandermeij** [comment]
Definitely; I'll get it done today.

**Pull request merged**
