### PR TITLE
Don't map glyphs to certain problematic General Punctuation Unicode locations (bug 911034)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes the remaining missing characters in https://bugzilla.mozilla.org/show_bug.cgi?id=911034.

For reference, see http://www.unicode.org/charts/PDF/U2000.pdf (and also http://en.wikipedia.org/wiki/General_Punctuation_%28Unicode_block%29).

_Note:_ With all the existing special cases for problematic character locations in `adjustMapping`, and given that we're most likely going to need to add even more in the future, I felt that readability was starting to become an issue. Hence the first patch, which extracts that code into a separate function.

### CODE REVIEW

**Comment by CodingFabian** [comment]
Thanks Jonas for your tireless work on those issues. I think the refactoring is fine, But as somebody who is not involved as you are, could you maybe add a comment line saying WHY these codes are "problematic", maybe linking the Wikipedia page?

**Comment by timvandermeij** [comment]
Nice work! I like the separate function too.

**Comment by rohithns** [comment]
Which version of firefox can i expect this change be updated?

**Comment by timvandermeij** [comment]
I think Firefox 39 or 40 since that has to go through the Aurora and Beta branches before it gets to the Release branch.

**Comment by rohithns** [comment]
I there way i can test these changes using some build.

**Comment by Snuffleupagus** [comment]
> I think Firefox 39 or 40 since that has to go through the Aurora and Beta branches before it gets to the Release branch.

The PDF.js updates lands on `mozilla-central` first<sup>1</sup>, hence Firefox 40 is the first version that will contain these changes.
*Please note:* This is under the assumption that we do an uplift during the current development cycle, and that these changes are not backed-out for causing regressions.

[1] Virtually all changes to Mozilla source code follows the pattern:
`mozilla-central -> aurora -> beta -> release`, with each period usually lasting six weeks. Please see the scheduled here: https://wiki.mozilla.org/RapidRelease/Calendar.

___

> I there way i can test these changes using some build.

@rohithns The simplest way is to open your file(s) with the web viewer (by clicking on the `Open file` button on the toolbar): http://mozilla.github.io/pdf.js/web/viewer.html.

**Pull request merged**
