### PR TITLE
Improve glyph mapping for non-embedded composite standard fonts with a /CIDToGIDMap (issue 11915)

### LINKED ISSUE #11915: Garbled Display of Fonts
Viewer:  https://mozilla.github.io/pdf.js/web/viewer.html
Chrome on Windows 10
When the attached PDF file is viewed, some of the fonts display as garbled text. 
[Arial, Courier, Times New Roman]
The file views correctly in Adobe Reader.
[fff.pdf](https://github.com/mozilla/pdf.js/files/4652174/fff.pdf)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please note:* All of this feels very handwavy, but at least it passes all tests locally. Hopefully we have enough tests for this part of the font code.

For non-embedded composite standard fonts with an "incomplete" /CIDToGIDMap, we'll now fallback to an *explicitly defined* /ToUnicode map even when that one happens to be an /Identity-H or /Identity-V map.

The `Font.fallbackToSystemFont` method is unfortunately getting more and more special-cases, however that might be unavoidable given all the weird non-embedded fonts found in the wild :-(

Fixes #11915

### CODE REVIEW

**Comment by brendandahl** [comment]
Does this fix #14015 too?

**Comment by Snuffleupagus** [comment]
> Does this fix #14015 too?

Yes, it does.

**Pull request merged**
