### PR TITLE
Add a basic `gasp` table to improve font rendering (bug 1769884)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
See https://docs.microsoft.com/en-us/typography/opentype/spec/gasp

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
*I mostly want to see what sort of effect, if any, this has across the test-suite.*

/botio browsertest

**Comment by calixteman** [comment]
Maybe we could use this gasp table only when hinting is missing. Do we have a way to detect such a situation ?

**Comment by calixteman** [comment]
I played with the behavior flag and `issue13130.pdf`.
I see some real differences on my old DELL screen (U2415).
Here is what I see:
With your patch
image
Without
image
The same pdf but in Edge
image
and in Acrobat
image

So with your patch some curves are very thin (see the bottom, in the round part, e,p or c).
And I checked the pdf in https://bugzilla.mozilla.org/show_bug.cgi?id=1769884 and there is a real improvement.

I wonder if we should have different flags for different ranges.

I noticed that the gasp table isn't in the list:
https://github.com/mozilla/pdf.js/blob/master/src/core/fonts.js#L1220
and I was wondering if we correctly add it when it's present in the font.

**Pull request closed without merging**
