### PR TITLE
Crypt filter EFF key should have StmF value as default, not StrF

### LINKED ISSUE #5935: Potential problem when encountering encrypted file streams
The fallback at https://github.com/mozilla/pdf.js/blob/master/src/core/crypto.js#L1970 should not be `this.strf` but `this.stmf` according to the PDF1.7 spec section 7.6.1 page 57 (EFF key description).

### PR DESCRIPTION
**Pull request by gettalong**
This fixes #5935.

### CODE REVIEW

**Comment by timvandermeij** [comment]
For verification, this is the exact location in the specification: https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=65&zoom=auto,-274,714

**Comment by CodingFabian** [comment]
well done, just for curiosity: how does one find such a bug without a document? Or do you have such doc, but you cannot share it?

**Comment by gettalong** [comment]
I'm currently studing the PDF1.7 spec and comparing various implementations. The Adobe PDF1.7 spec as well as the ISO-32000-1:2008 spec (more or less equivalent to the Adobe PDF1.7 spec) are available online from Adobe, see @timvandermeij comment.

**Comment by Snuffleupagus** [comment]
Thanks for the patch!

**Pull request merged**
