### PR TITLE
Take the mask-offset into account when rendering repeated image masks (bug 1799927)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please note:* As usual when I'm working with the `src/display/canvas.js` code I don't really know what I'm doing, but it at least *appears* to work.

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
I think it's correct, so r=me.

**Review by LOHAYBOY999 — CHANGES_REQUESTED** [review]
@jokerlohayboy999

**Comment by LOHAYBOY999** [comment]
> *Please note:* As usual when I'm working with the `src/display/canvas.js` code I don't really know what I'm doing, but it at least *appears* to work.

3e4caf2e13be802797f3a6a180f16102914d5060

**Pull request merged**
