### PR TITLE
Initialize the `ExternalServices`-instance lazily in the viewer (PR 17588 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Strangely enough this doesn't reproduce in the GENERIC viewer.

Unfortunately I've not (yet) had time to test this in a local `mozilla-central` build, but *hopefully* delaying the initialization is enough to fix the failures in https://bugzilla.mozilla.org/show_bug.cgi?id=1877789#c1

**Comment by Snuffleupagus** [comment]
I've successfully ran `./mach test toolkit/components/pdfjs/` locally with this patch applied.

**Review by calixteman — APPROVED** [review]
Is it possible to add a test ?
That said, it looks good to me, thank you.
I'll update the m-c patch tomorrow.

**Comment by Snuffleupagus** [comment]
> Is it possible to add a test ?

Given that I cannot reproduce this in the GENERIC viewer, I unfortunately don't have any ideas how we could test this here.

(The underlying issue seems to be somehow related to the include-order in the built viewer, and that's always subject to change given that Webpack controls it.)

**Pull request merged**
