### PR TITLE
Update packages and translations

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

**Comment by timvandermeij** [comment]
Hm, it looks like `TEST-UNEXPECTED-FAIL | should correctly render PDFs in parallel | in firefox` permafails now :(

**Comment by Snuffleupagus** [comment]
All of the Firefox- and Linux-specific failures described in https://github.com/mozilla/pdf.js/pull/14967#issuecomment-1140429886 is fallout from [bug 1770088](https://bugzilla.mozilla.org/show_bug.cgi?id=1770088), so I believe that those problems should already be *indirectly* tracked and thus in the process of getting fixed.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you!

**Pull request merged**
