### PR TITLE
Ignore some *scripting* events which don't make sense in PresentationMode

### PR DESCRIPTION
**Pull request by Snuffleupagus**
A number of the currently supported *scripting* events only make sense in the "normal" viewer mode, and not when PresentationMode is active. For example:
 - Changing the zoom-level will outright break rendering in PresentationMode, since it relies on "page-fit" being used.
 - Focusing a particular (AcroForm) element won't work, and could break keyboard navigation, since forms should not be editable in PresentationMode (see issue 12232).

### CODE REVIEW

**Comment by calixteman** [comment]
Maybe we should disable scripting when in presentation mode, wdyt ?

**Comment by Snuffleupagus** [comment]
> Maybe we should disable scripting when in presentation mode, wdyt ?

My initial though was exactly the same, but there *may* be some cases where scripting actually make sense even in PresentationMode.

See e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1100769, which is currently not working because of an error being thrown in the sandbox, but is probably something that users would expect to work *also* in PresentationMode.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good to me; thanks!

**Pull request merged**
