### PR TITLE
Split the font_spec.js unit-tests into cff_parser_spec.js and type1_parser_spec.js

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Re: issue #7261.

Given the we have `gulp fonttest`, which tests the `fonts.js` functionality at a higher level, and that we have _a lot_ of font specific reference tests, I'm not convinced that we _also_ need unit-tests for it.

_Note:_ I'm setting the [WIP] label, pending agreement on the above.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Sounds reasonable to me. @yurydelendik, what do you think?

**Comment by brendandahl** [comment]
> Given the we have gulp fonttest, which tests the fonts.js functionality at a higher level, and that we have a lot of font specific reference tests, I'm not convinced that we also need unit-tests for it.

I highly prefer unit test over the higher level tests. Debugging the higher level ref tests when broken is often very painful, where as a unit test the issue is usually immediately obvious. In hindsight, I think we should have made much more of our ref tests into font unit tests. You've probably also run into the situation where a reftest breaks and you have no idea why without some pretty deep digging.

**Comment by timvandermeij** [comment]
You're right. Let's keep on tracking the addition of more unit tests in #7261, but I think this patch is nevertheless good to have because the two parsers are now also in separate files in `src/core`.

**Comment by Snuffleupagus** [comment]
> Debugging the higher level ref tests when broken is often very painful, where as a unit test the issue is usually immediately obvious. In hindsight, I think we should have made much more of our ref tests into font unit tests.

That is certainly a very valid point, that I didn't really consider!
One thing that makes creating small/self-contained unit-tests a bit difficult though, is that for e.g. `TrueType` fonts (which is what most of *my* font patches have touched), it might not be that easy to do.
For example: Most of the helper functions in [`Font_checkAndRepair`](https://github.com/mozilla/pdf.js/blob/master/src/core/fonts.js#L1223) are local, and you'd probably want a way to test only parts of that functionality in an issue/bug specific unit-test. Should we perhaps split some of those local functions out into "class" methods instead?

> You've probably also run into the situation where a reftest breaks and you have no idea why without some pretty deep digging.

I have, on more than one occasion, and I agree that it's no fun at all.

> [...] but I think this patch is nevertheless good to have because the two parsers are also in separate files in src/core.

Yes, as Tim points out, this patch is more of a bookkeeping one, moving existing unit-tests to the correct files. Please note that it *does not* remove any existing tests.

@brendandahl So in summary: If we block this PR on adding unit-tests for `fonts.js`, I'm not sure when it'll land, so can we take this and track adding unit-tests for `fonts.js` in e.g. #7261 instead?

**Comment by brendandahl** [comment]
> Should we perhaps split some of those local functions out into "class" methods instead?

I'm not sure it's worth retroactively adding unit tests for these, for new bugs though unit tests would be preferable.



> If we block this PR

No need to block.

**Pull request merged**
