### PR TITLE
XFA - Fix indentation for justified paragraph

### PR DESCRIPTION
**Pull request by calixteman**
- and ceil the reserve for a caption to avoid to split it;
  - both issues are present in the pdf in issue #13633.

### CODE REVIEW

**Comment by marco-c** [comment]
Is the change in `firefox-xfa_dhl_shipment-page5` expected?

**Comment by calixteman** [comment]
I finally managed to display this page in masterpdfeditor (it's a dynamic form) and the changes in page 5 in are correct.

**Review by marco-c — APPROVED** [review]

**Pull request merged**
