### PR TITLE
XFA - Default background in rectangle is white

### PR DESCRIPTION
**Pull request by calixteman**
- Fix a typo in order to open the pdf in issue #13679
  - After fixing the fill default color there wer some regressions because of z-index
    and when fixing z-index there were some regressions because of borders
  - So fix the borders rendering.

### CODE REVIEW

**Comment by calixteman** [comment]
It's expected to have a lot of regressions in reftests but overall borders are a way better rendered thanks to this patch.

/botio test

**Review by marco-c — APPROVED** [review]

**Comment by marco-c** [comment]
The PDF from https://github.com/mozilla/pdf.js/issues/13634 is better than before (more rectangles are white), but there are still some rectangles that should be white but aren't.

**Comment by brendandahl** [comment]
It looks like  `xfa_issue13213` has some content that is now missing. Is this expected?

**Comment by marco-c** [comment]
> It looks like xfa_issue13213 has some content that is now missing. Is this expected?

Ooh, I had missed that, too many pages!

**Comment by calixteman** [comment]
There is an error on page 4 of `xfa_issue13213` but for the others it is expected: depending of the value of a checkbox theses white rectangle on top of form elements are hidden or not.

**Comment by brendandahl** [comment]
I noticed one more `xfa_bug1718740-page13`. Though the button is in the wrong place to start, so I'm not sure that's a regression.

**Pull request merged**
