### PR TITLE
For embedded Type1 fonts without included `ToUnicode`/`Encoding` data, attempt to improve text selection by using the `builtInEncoding` to amend the `toUnicode` map (issue 6901, issue 7182, issue 7217, bug 917796, bug 1242142)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Note that in order to prevent any possible issues, this patch does _not_ try to amend the `toUnicode` data for Type1 fonts that contain either `ToUnicode` or `Encoding` entries in the font dictionary.

Fixes, or at least improves, issues/bugs such as e.g. #6658, #6901, #7182, #7217, [bug 917796](https://bugzilla.mozilla.org/show_bug.cgi?id=917796), [bug 1242142](https://bugzilla.mozilla.org/show_bug.cgi?id=1242142).

### CODE REVIEW

**Comment by timvandermeij** [comment]
Looks good to me. The code is actually quite understandable even though I'm not too familiar with the font code. It's really good to notice that the test now cover this well and show clear improvements. It's a big issue closer, so nice work!

/cc @brendandahl or @yurydelendik for review

**Review by brendandahl — APPROVED** [review]

**Comment by Snuffleupagus** [comment]
@brendandahl Thank you for the review!

**Pull request merged**
