### PR TITLE
Don't map glyphs to the HANGUL FILLER (0x3164) Unicode location (issue 8424)

### LINKED ISSUE #8424: Missing glyph in Unicode code charts, Hangul Filler U+3164
Link to PDF file (or attach file here): http://www.unicode.org/charts/PDF/U3130.pdf

Configuration:
- Web browser and its version: Firefox Nightly: 55.0a1 (2017-05-12) (64-bit)
- Operating system and its version: Arch Linux: Linux kaydel-ko 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux
- PDF.js version: whatever is built-in to Firefox
- Is an extension: no

Steps to reproduce the problem:
1. Go to page 3, under Special characters, for U+3164

What is the expected behavior? (add screenshot)

Dotted square with initials HF. Rendered here with Google Drive PDF viewer in Android.

What went wrong? (add screenshot)

PDF.js shows just a blank space.

screenshot from 2017-05-19 13-29-07

Issue found through this twitter thread: https://twitter.com/passcod/status/865366170169257985

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*This patch follows a similar pattern as previous ones, by skipping certain problematic Unicode locations.*

According to http://searchfox.org/mozilla-central/rev/6c2dbacbba1d58b8679cee700fd0a54189e0cf1b/gfx/harfbuzz/src/hb-unicode-private.hh#136, it seems that the HANGUL FILLER (0x3164) location is "special".

Fixes #8424.

### CODE REVIEW

**Comment by yurydelendik** [comment]
/botio makeref

Thank you for the patch.

**Comment by khaledhosny** [comment]
Ignore my ignorance about the code, but why not map the glyphs to one of the private use areas which are guaranteed not to have any special properties? Each of [Supplemental Private Use Area-A and B](https://en.wikipedia.org/wiki/Private_Use_Areas#PUA-A) is big enough to cover all glyphs in a given font file.

**Comment by yurydelendik** [comment]
> Excuse my ignorance about the code, but why not map the glyphs to one of the private use areas 

That's right -- we move such characters to Private Use Area.

**Pull request merged**
