### PR TITLE
[api-minor] Load Node.js packages/polyfills with `process.getBuiltinModule`

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Note:* Unless this functionality is uplifted to the current Node.js LTS versions it'll unfortunately be several years before we can actually make this change.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Fyi, `process.getBuiltinModule` has just been backported to Node.js 20 LTS.

It still not available in Node.js 18 LTS, which will reach end of life in April 2025.

**Comment by Snuffleupagus** [comment]
In the latest Node.js 20 version (i.e. the current LTS) this seems to work fine now, however the `typestest` still fail which considering how much trouble the type-definitions have caused previously doesn't really surprise me.

**Comment by timvandermeij** [comment]
It looks like that can be fixed by changing https://github.com/mozilla/pdf.js/blob/master/test/types/tsconfig.json#L13 to `"types": ["node"]`. I found that in https://github.com/oozcitak/xmlbuilder-js/issues/223 and confirmed that works locally by checking out your PR and checking that `npx gulp typestest` no longer fails after adding that (while it did fail before).

**Comment by Snuffleupagus** [comment]
> It looks like that can be fixed by changing https://github.com/mozilla/pdf.js/blob/master/test/types/tsconfig.json#L13 to `"types": ["node"]`.

Thank you, that did the trick!

---

The only thing preventing this from landing is Node.js 18, where `process.getBuiltinModule` isn't available yet.

**Comment by nicolo-ribaudo** [comment]
@Snuffleupagus I was thinking about this PR.

Using https://nodejs.org/api/packages.html#conditional-exports we could have an entry point just for Node.js (using the `"node"` and `"default"` conditions) that polyfills `process.getBuiltinModule` on Node.js 18, and then loads the real pdf.js entry point.

**Comment by Snuffleupagus** [comment]
> Using https://nodejs.org/api/packages.html#conditional-exports we could have an entry point just for Node.js (using the `"node"` and `"default"` conditions) that polyfills `process.getBuiltinModule` on Node.js 18, and then loads the real pdf.js entry point.

I'm still hoping that it'll be back-ported to Node.js 18, but I obviously have no idea if or when that'll actually happen.

We might need a few different entry points, if we attempt that work-around, since normally in Node.js you'd need to use the files in the `legacy/` folder. There's also the `image_decoders/` builds that should keep working, and we want `gulp unittestcli` (which is used in GitHub Actions) to work in Node.js 18 as well.

Since I don't have much experience with conditional exports in Node.js, and generally not enough time to figure it out either I probably won't look into that any time soon (or even at all sadly).
That said, if you have time and want to try and figure something out here that's obviously welcome. (In that case this PR could simply include *another commit*, with you credited as the author, for the polyfill- and exports-parts.)

**Comment by Snuffleupagus** [comment]
Superseded by PR #18959.

**Pull request closed without merging**
