### PR TITLE
Add a (linked) test-case for issue 4914

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Re: issue #4914 and PR #4915.

### CODE REVIEW

**Comment by timvandermeij** [comment]
@brendandahl Could you check Firefox on the Linux bot again? It has not responded in 120 seconds according to the logs. Probably it's stuck again. Not sure why that is happening after multiple months of no failures whatsoever: maybe an update?

**Comment by brendandahl** [comment]
Seemed to be another hung update. We may have to disable auto-update if this keeps happening.

/botio-linux test

**Comment by timvandermeij** [comment]
Nice work!

**Pull request merged**
