### PR TITLE
[api-minor] Add an `IsLinearized` property to the `PDFDocument.documentInfo` getter, to allow accessing the linearization status through the API (via `PDFDocumentProxy.getMetadata`)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please refer to the individual commit messages for additional details.*

### CODE REVIEW

**Comment by timvandermeij** [comment]
Should we label this as `[api-minor]` because it's an addition?

**Comment by timvandermeij** [comment]
For completeness I'm also providing the Dutch translations. If you would like to include them in this patch, please feel free to; otherwise we can make a follow-up. Here they are:

```
document_properties_linearized=Snelle webweergave:
document_properties_linearized_yes=Ja
document_properties_linearized_no=Nee
```

**Comment by Snuffleupagus** [comment]
> Should we label this as [api-minor] because it's an addition?

You're obviously correct (the change may be really small, but it's still adding "new" API functionality).

> For completeness I'm also providing the Dutch translations.

Nice, thank you! I'll add those as well soon (and probably some kind of localization comment as well).

**Review by timvandermeij — APPROVED** [review]

**Pull request merged**
