### PR TITLE
[api-minor] Deprecate the SVG back-end

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

**Comment by timvandermeij** [comment]
Hm, do you know why the Linux bot is not triggered here?

**Comment by Snuffleupagus** [comment]
> Hm, do you know why the Linux bot is not triggered here?

It might be unrelated but the bots were updated the other day since their Node.js versions were old, so they should now be using the current LTS release, and it seems that (anecdotally) the Linux bot has been a little bit flaky since then.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thanks!

**Pull request merged**
