### PR TITLE
Ensure that the clipping path is reset when the state is restored (issue 6413)

### LINKED ISSUE #6413: PDF is missing content
Hi,

[this](https://traffiq.synology.me/owncloud/index.php/s/4VvpixNjAWiqp1d) PDF does not correctly show in firefox version 40. It does show correct in chrome or any other tool.

Is this a Bug of PDF.js or is the PDF itself corrupt ?

### PR DESCRIPTION
**Pull request by Snuffleupagus**
According to the specification, see `NOTE 2` in http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G7.3882161, it appears that we should ensure that the clipping path is reset when the restore (`Q`) operator is encountered.

Fixes #6413.

~~_Note: I'm currently trying to create a reduced test-case, hence the WIP label._~~

### CODE REVIEW

**Comment by timvandermeij** [comment]
Nice work!

**Comment by nbenitez** [comment]
Spec link is broken, here it's an updated one:
https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#G7.3882161

**Pull request merged**
