### PR TITLE
Implement support for StrikeOut annotations

### PR DESCRIPTION
**Pull request by timvandermeij**
Notice that the reduced test case provided with this patch now renders just like Adobe Reader/Acrobat and without any warnings in the console.

### CODE REVIEW

**Comment by timvandermeij** [comment]
@Snuffleupagus Would you be interested in reviewing this one? It's almost completely the same as the patch for Underline annotations.

**Comment by Snuffleupagus** [comment]
> Would you be interested in reviewing this one?

I was just about to do that :-)
Looks good, thank you!

/botio makeref

**Pull request merged**
