### PR TITLE
Fix various corrupt PDF files (issue 9252, issue 9418)

### LINKED ISSUE #9252: PDF not rendering at all: getOperatorList - ignoring errors during task: RenderPageRequest
This can be reproduced either with a simple app using PDFJS or a newer version of Firefox. I'll give details for the latter.

**Attach (recommended) or Link to PDF file here:**
[not-shown-pdfjs.pdf](https://github.com/mozilla/pdf.js/files/1542926/not-shown-pdfjs.pdf)

Configuration:
---
**- Web browser and its version:**
Firefox 57.0.1 (64-bit)
**- Operating system and its version:**
OS X EI Capitan 10.11.6
**- PDF.js version:**
1.9.583 (shipped with Firefox)
**- Is a browser extension:**
No (built into Firefox out of the box)

Steps to reproduce the problem:
---
1. Open the related PDF

**What is the expected behavior? (add screenshot)**
One page with the text 'Test' is rendered. Works with any other viewer I tried.
screen shot 2017-12-08 at 4 43 22 pm

**What went wrong? (add screenshot)**
Nothing renders.

screen shot 2017-12-08 at 4 43 40 pm

Related warning in the console:
```javascript
Warning: getOperatorList - ignoring errors during task: RenderPageRequest: page 0
```

### LINKED ISSUE #9418: bad XRef entry
hello

I have problems with rendering of the attached PDF file. When I open it using the official viewer at http://mozilla.github.io/pdf.js/web/viewer.html I get the following error:

`PDF.js v2.0.303 (build: 55e3f97a)
Message: bad XRef entry`

this file is generated from an application and I can open that  in adobe reader.
I hope pdf.js can open this file.

[Drawing2.pdf](https://github.com/mozilla/pdf.js/files/1676637/Drawing2.pdf)

thank's

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*While waiting for a reviewer to have time to look at PR #9729, I happened to glance at the `4-corrupted-pdf` category; hence this PR which fixes a few simple issues.*

Please refer to the individual commit messages for additional details.

Fixes #9252.
Fixes #9418.

### CODE REVIEW

**Review by Rob--W — COMMENTED** [review]
How about adding a unit test for the new parser logic to `test/unit/parser_spec.js`, preferably with a reference to the motivation behind the parser logic?

**Review by Rob--W — APPROVED** [review]
r=me with passing tests

**Comment by Snuffleupagus** [comment]
> r=me with passing tests

Thanks for the review!

The Linux-only test "failures" look like the usual fallout from a browser upgrage on the bots (Firefox 61 -> 62), so I don't think it's a problem here.

**Comment by timvandermeij** [comment]
Thank you for fixing this, and @Rob--W for the review!

**Comment by kdleijer** [comment]
many thanks for this fix/review/merge!

**Pull request merged**
