### PR TITLE
Update dependencies and translations to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**

### CODE REVIEW

**Comment by timvandermeij** [comment]
@calixteman Hm, it looks like the Linux bot does receive commands, but the logs are not visible. Could you check why that is?

**Comment by timvandermeij** [comment]
Well, `tar` errors that keep the bot busy for 2 hours is a first... Let's try that again:

/botio-linux test

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks.

**Pull request merged**
