### PR TITLE
Apply gradient when stroking text

### LINKED ISSUE #19022: [Bug]: Gradient is not applied when stroking text
### Attach (recommended) or Link to PDF file

[linear-gradient-on-rect_text.pdf](https://github.com/user-attachments/files/17703776/linear-gradient-on-rect_text.pdf)

### Web browser and its version

Firefox nightly

### Operating system and its version

Windows 11

### PDF.js version

built-in

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open the pdf.

### What is the expected behavior?

image

### What went wrong?

image

### Link to a viewer

_No response_

### Additional context

For reference:
https://gitlab.freedesktop.org/poppler/poppler/-/issues/1532

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #19022.

I noticed that the glyph contours weren't correct (for T and x) and because we forgot to close the contour.

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.

**Comment by calixteman** [comment]
The test issue18896.pdf is taking too much time with Chrome on linux.

**Pull request merged**
