### PR TITLE
Allow to set up a hook at the end of the initialization (bug 1881319)

### PR DESCRIPTION
**Pull request by calixteman**
With this patch it's now possible to be sure to add a listener (for example for the "pagerendered" event) before the pdf is set.

### CODE REVIEW

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Is it really not possible utilize an existing event, or perhaps even the `PDFViewerApplication.initializedPromise` promise, rather than having to add all of this new complexity here?
Also, in case it's helpful, please keep in mind that you can determine if tests are running in `mozilla-central` via the `isInAutomation`-property which is already available in the viewer through `AppOptions`.

All-in-all this code unfortunately does *not* feel all that readable/maintainable, and looking at the description here and in Bugzilla it still feels a bit like the "bigger picture" isn't entirely clear to me!?

**Comment by calixteman** [comment]
The goal is to have some tests for the snap package of Firefox and they're using [Selenium](https://www.selenium.dev/).
The test takes an image from the canvas and then compare it to a reference: the problem is to know when the canvas is ready.
So the idea is to set a listener for `pagerendered` but afaik there is no guarantee that the listener will be set before the event is triggered, hence this patch.
That said, if you've a better/simpler idea to achieve the same, please share it.

**Comment by Snuffleupagus** [comment]
> The goal is to have some tests for the snap package of Firefox and they're using [Selenium](https://www.selenium.dev/).

How is the PDF viewer being loaded in this case, because it might be possible to work-around that?

Anyway, could we *at least* avoid adding a new Preference for this and keep it as "just" an option?
If we [change this event](https://github.com/mozilla/pdf.js/blob/72b8b29147c3a19ccacc9db111df4925efcbe1bf/web/viewer.js#L184-L206) to be dispatched in all builds, could the test-runner listen for "webviewerloaded"[1] and then call e.g. `window.PDFViewerApplicationOptions.set("hasInitializationHook", true)` from that event listener instead?

---
[1] Since that event is dispatched *before* the viewer-initialization runs.

**Comment by timvandermeij** [comment]
Closing in favor of #18617 which only requires changing test code and overall seems safer/simpler.

**Pull request closed without merging**
