### PR TITLE
[api-minor] Use the Fetch API, when supported, to load PDF documents in Node.js environments

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Given that modern Node.js versions now implement support for a fair number of "browser" APIs, we can utilize the standard Fetch API to load PDF documents that are specified via http/https URLs.

Please find compatibility information at:
 - https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#browser_compatibility
 - https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch
 - https://developer.mozilla.org/en-US/docs/Web/API/Response#browser_compatibility
 - https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#response

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Given that in `package.json` you require Node.js 18+ (https://github.com/mozilla/pdf.js/blob/72b8b29147c3a19ccacc9db111df4925efcbe1bf/package.json#L74-L76), are there still cases in which `fetch` is not supported?

**Comment by Snuffleupagus** [comment]
> are there still cases in which `fetch` is not supported?

Yes, according to the Node.js documentation it can still be manually disabled in even the *latest* version; see https://nodejs.org/docs/latest-v21.x/api/cli.html#--no-experimental-fetch

**Comment by Snuffleupagus** [comment]
@calixteman Gentle review ping here (and for #17691).

(Normally I'd ask Tim to review these sort of patches, but he's unfortunately not been around for awhile.)

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by timvandermeij** [comment]
> (Normally I'd ask Tim to review these sort of patches, but he's unfortunately not been around for awhile.)

Yes, I had quite a bit of time off last weeks, but I'm back again :-)

This also looks really good to me; thanks for doing this!

**Pull request merged**
