### PR TITLE
[api-minor] Improve handling of links that are using explicit destination arrays

### PR DESCRIPTION
**Pull request by Snuffleupagus**
_Please refer to the individual commit messages._

@timvandermeij Since you asked in https://github.com/mozilla/pdf.js/pull/6272#issuecomment-189018446 if the second commit could be submitted in a separate PR, I've done that here. Would you be willing to try and review this?
Since it's been awhile since I wrote that patch, when getting back to it I found that there were actually a number of (existing) issues present, which I've tried to account for. Unfortunately, that means this is now quite a bit larger than originally, but I've tried to add unit-tests for all API/core changes.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Nice work! This looks much better to me than the current situation.

By the way, I'm sorry that this took a bit long to review. I was quite busy the last two weeks and I wanted to make sure to review and test this thoroughly before landing it.

**Comment by Snuffleupagus** [comment]
@timvandermeij Thanks so much for reviewing not only this one, but the `move-isSpace` PR as well :-)

**Pull request merged**
