### PR TITLE
Slightly improved Crypto unit tests

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Currently in the tests which check that incorrect passwords are rejected, we don't ensure that the exceptions thrown are the ones we expect. This patch improves the current situation, so that we actually can be sure that the code "fails" in the correct way.

_Note:_ This patch also fixes some cases of weird indentation in the file.

**Edit:** Easier reviewing with https://github.com/mozilla/pdf.js/pull/6093/files?w=1.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Aside from the comment above this looks really good!

**Comment by Snuffleupagus** [comment]
The function name was shortened.

/botio unittest

**Comment by timvandermeij** [comment]
Looks good, thanks!

**Pull request merged**
