### PR TITLE
Ignore reserved commands when parsing operands in `CFFParser_parseDict`, instead of just rejecting the entire font (bug 1308536)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
According to the CFF specification, see http://partners.adobe.com/public/developer/en/font/5176.CFF.pdf#page=11, certain commands are currently reserved.

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1308536.

### CODE REVIEW

**Comment by brendandahl** [comment]
Could we do a unit test for this instead?

**Comment by Snuffleupagus** [comment]
> Could we do a unit test for this instead?

I've tried to (very quickly) put together a simple unit-test for this, but considering that its scope is perhaps a bit limited, I still want to keep the reference test as well to ensure proper test coverage here.

/botio test

**Review by brendandahl — APPROVED** [review]

**Comment by Snuffleupagus** [comment]
Landing with r=bdahl on IRC.

**Pull request merged**
