### PR TITLE
Cleanup code to drop support for Chrome < 49 in the Chrome extension

### PR DESCRIPTION
**Pull request by Rob--W**
This finalizes the work for #9397 .

@Snuffleupagus In particular, this commit removes a snippet that referenced `PDFJS.disableWorker`, so you don't need to account for it any more in #9385.

### CODE REVIEW

**Review by Snuffleupagus — COMMENTED** [review]
I believe that the following line needs to removed to fix the linting failure: https://github.com/mozilla/pdf.js/blob/28c87ce9c61fecbdbfe56edb982a6a5cd9a0ed64/extensions/chromium/pdfHandler.js#L16

**Comment by Rob--W** [comment]
Done.

**Review by Snuffleupagus — APPROVED** [review]
I've successfully tested the Chrome extension locally, using Google Chrome `Version 64.0.3282.119 (Official Build) beta (64-bit)`.

According to https://github.com/mozilla/pdf.js/issues/9397#issue-290812728:
> We need to evaluate whether there are commonly used versions that we wish to support, and maybe set a minmum_chrome_version in manifest.json to explicitly drop support for older versions.

Should that be done in the current PR as well?
If the answer is "no", you can land this PR as-is.
Otherwise, please feel free to land once the mentioned `manifest.json` entry has been added. 

Thanks for removing all this old code!

**Comment by Rob--W** [comment]
Among the logged user agents are also custom browsers. I'm not sure about the impact of setting a minimum version in the manifest on these forks, so I'll just omit the field.

**Comment by Rob--W** [comment]
Thanks for the quick review @Snuffleupagus

**Pull request merged**
