### PR TITLE
Differential cmap compression

### PR DESCRIPTION
**Pull request by fkaelberer**
When I compressed cmap files with winrar, I noticed that they compress 2x better when put in a _solid_ archive, which means that the file contents are very similar.

This PR makes use of this fact by storing cmap files differentially, that is, a cmap file A is either stored normally, or it is stored as a patch that contains the necessary data to recover A from a similar file B.
This reduces the combined size of the cmaps to ~~608k~~ 620k (54% of 1150k) and the size of pdf.js.xpi from 2MB to 1.5MB.

The patches are computed using a third party diff tool ([cemerick/jsdifflib](https://github.com/cemerick/jsdifflib)) which is a partial port of python's difflib.

The dependencies are chosen ~~optimally with respect to the output size~~ so that the number of dependencies, the overhead and total file size is minimized. This takes over an hour to compute (because each pair of files is diff'ed), but because that has to be done only if the cmap files change, I didn't care much about performance optimization.

The reconstruction of the original files is very simple. Each file starts with a `filename`  string. If `filename` is empty, the rest of the file is stored normally. Otherwise, it `filename` points to a basefile from which the cmap is to be reconstructed. Reconstrucion commands are either 
-  `copy`, followed by a `start` and `length` number, which means that the respective data has to be fetched from the base file, or
- `insert` followed by a `length` number and the corresponding number of bytes to insert.

(Since the `copy` and `insert` commands are always alternating, the commands themselves do not have to be stored.) Strings and numbers are stored and restored using the existing functions in [cmapscompress/compress.js](https://github.com/mozilla/pdf.js/blob/master/external/cmapscompress/compress.js) and [cmaps.js](https://github.com/mozilla/pdf.js/blob/master/src/core/cmap.js).

I marked this as work in progress, because I have still some questions / TODOs that I wanted to check before polishing this.
- [x] Does the license of jsdifflib allow usage in pdf.js? [Yury says yes, if only for compression]
- [x] Are there any drawbacks I didn't think of? 
- [x] ~~Do we need more test for this? Can somebody provide them?~~ Update file verification.
- [x] Reduce number of dependencies to ~1-3 ~~(currently, each file depends recursively on ~10 other files)~~ [At the cost of 1% compression ratio, average dependency length can be reduced to 1.1.]
- [x] Avoid that small cmap files depend on big cmap files.
- [x] ~~update~~ fix formatting in [cmapscompress/Readme.md](https://github.com/mozilla/pdf.js/blob/master/external/cmapscompress/README.md)
- [x] cleanup ~~code /~~ commits

### CODE REVIEW

**Comment by akkatracker** [comment]
Any updates on this?

**Comment by timvandermeij** [comment]
Ping @brendandahl for reviewing this. As far as I know @yurydelendik agreed on this change.

**Comment by Snuffleupagus** [comment]
Are we still interested in implementing this in some form, or should we close the PR?

Note that since this was originally submitted, the loading/fetching of CMap files has been re-factored and now runs on the main-thread instead. Furthermore, we also cache (compressed) CMap files in the worker, which should help improve amount of (font related) data that needs to be loaded.

**Comment by timvandermeij** [comment]
Closing since this is not a problem in practice anymore due to the outlined refactoring steps. If this becomes a concern later on, we can always revisit this.

**Pull request closed without merging**
