### PR TITLE
Map missing glyphs to the `notdef` glyph for TrueType (3, 1) fonts regardless if the 'post' table is defined or not (issue 6889)

### LINKED ISSUE #6889: Embedded font displayed as random characters
I made a document using Scribus 1.5.0svn with only the text "This should be readable" in it using the embedded Arial Regular font. While it displays fine in Adobe Acrobat Reader DC, PDF.js displays random characters when using Windows 10 x64 and Firefox 43.0.4.

Initially I thought my issues with the Scribus PDF exports were fixed by #6068. That issue is still fixed, so this is not a regression, but something must have changed in the meantime (either in Scribus or in my system fonts) because, as far as I can remember, this new PDF is generated in the *exact* same way as the one in that issue, yet this one is broken and the other one is not.

Here is a reduced test case for inclusion in the PR that fixes this issue:
[example.pdf](https://github.com/mozilla/pdf.js/files/93576/example.pdf)

Using Brendan's PDF browser I see that this font also has names of the form `uniXXX` in the `differences` array, which might indicate a similarity with #6090. @Snuffleupagus Do you perhaps have an idea if the fix for this issue is similar to the one in #6090, but for a different code path?

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #6889.

**Edit:** I pushed a new commit _only_ to fix a typo in the commit message, no functional changes were made!

### CODE REVIEW

**Comment by timvandermeij** [comment]
Awesome, thank you for working on this so quickly! I can confirm that this fixes the issue.

**Comment by yurydelendik** [comment]
/botio makeref

Looks good. Thank you.

**Pull request merged**
