### PR TITLE
Skip mapping of glyphs to Unicode "Ideographic space" (issue 7416)

### LINKED ISSUE #7416: Boxed X symbol shown instead of Japanese multibyte space (but not always) only on IE
Link to PDF file (or attach file here):
[boxed_x_symbol.pdf](https://github.com/mozilla/pdf.js/files/317616/boxed_x_symbol.pdf)

Configuration:
- Web browser and its version: **IE only** (Firefox/Chrome are OK)
- Operating system and its version: Windows 7
- PDF.js version: any version up to 1.5.188
- Is an extension:

Steps to reproduce the problem:
1. Open the attached PDF on IE.
2. You will see boxed X symbol as attached screen shot below. (I indicated) The problematic location is Japanese multi-byte space character exist, but the boxed X symbol doesn't always show with the multi-byte space character, in many cases showing properly.
Below screen shots are my own tool implemented on local web server, so that it's not accessible in internet, but the tool is just a collection of several versions of PDF.js. (nothing changed)

What is the expected behavior? (add screenshot)
boxed_x_symbol_firefox

What went wrong? (add screenshot)
boxed_x_symbol_ie11

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Please look into and investigate it.
Thanks in advance,
Best Regards

Futoshi Tanuma

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #7416, which is an IE specific issue.

@brendandahl I think this should do it. Since I cannot reproduce the issue in neither Firefox nor Chrome, but only in IE, I'm not sure how meaningful it would be to add a test-case.
But please let me know if you think that we need one anyway!

### CODE REVIEW

**Comment by timvandermeij** [comment]
This patch indeed seems to fix the issue, as reported by two users in the issue above. Nice work!

**Comment by yurydelendik** [comment]
Thank you for the patch.

**Pull request merged**
