### PR TITLE
[GeckoView] Bundle the Firefox printing code in the viewer (bug 1810111)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This may not be enough, on its own, to completely fix [bug 1810111](https://bugzilla.mozilla.org/show_bug.cgi?id=1810111) however it's impossible for printing to work in GeckoView without this patch.

### CODE REVIEW

**Review by calixteman — CHANGES_REQUESTED** [review]
I tested locally and it doesn't work.
The `printerContainer` is missing in `viewer-geckoview.html` and in `viewer-geckoview.js`.
I can share with you how I setup an android dev environment on windows 11 if you need.

**Comment by calixteman** [comment]
When printing, Fenix is generating a pdf and then it's sent to whatever app to print it.
So we probably don't need to really "print" it but we could just run the beforeprint callbacks, save it, send it to fenix and use the result as the print result.
It should be a way faster like this which means that we don't consume too much resources (especially power).

**Comment by Snuffleupagus** [comment]
> I tested locally and it doesn't work.
> The `printerContainer` is missing in `viewer-geckoview.html` and in `viewer-geckoview.js`.

D'oh, that's of course obvious in hindsight; didn't think about that :-)

> When printing, Fenix is generating a pdf and then it's sent to whatever app to print it.
> So we probably don't need to really "print" it but we could just run the beforeprint callbacks, save it, send it to fenix and use the result as the print result.
> It should be a way faster like this which means that we don't consume too much resources (especially power).

Ah, that makes total sense! In that case this PR obviously isn't even in the correct direction, since none of this is necessary if we just call `PDFDocumentProxy.saveDocument()` and send its result to some native API.

Given that I don't know anything about the Fenix platform-code, and it seemingly being written in Java (which I've not used for many years), I'm unfortunately not sure if I'll be able to fix this bug anytime soon.

**Comment by calixteman** [comment]
My plan was to merge this patch and try to be smarter later.

**Comment by Snuffleupagus** [comment]
> My plan was to merge this patch and try to be smarter later.

Sorry, I figured we should go directly for the "proper" solution.

I've update the patch to address https://github.com/mozilla/pdf.js/pull/16163#pullrequestreview-1373414665, so now the DOM element should be found correctly.

**Comment by Snuffleupagus** [comment]
@calixteman Ping, do we want to move forward with these changes?

Should we perhaps also add a GeckoView toolbar-button for this, and if so could you please help find a suitable one?

**Comment by calixteman** [comment]
It was on my today todo-list :).
IIRC, I need to write something in m-c to have it working correctly.

**Comment by calixteman** [comment]
So for now the `window.print` is plugged on the save to pdf stuff:
 - https://searchfox.org/mozilla-central/rev/85b4f7363292b272eb9b606e00de2c37a6be73f0/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#750
 - https://searchfox.org/mozilla-central/rev/85b4f7363292b272eb9b606e00de2c37a6be73f0/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#6836
 - https://searchfox.org/mozilla-central/rev/85b4f7363292b272eb9b606e00de2c37a6be73f0/toolkit/components/pdfjs/content/GeckoViewPdfjsParent.sys.mjs#209

which isn't what we want when we've for example a filled form and especially if we've something to execute before printing.
For now, the only way to trigger a window.print is to have an embedded script calling it (or call it from a devtools console connected to the device/emulator).
As far as I can tell there is no UI to print something in Fenix, so I'll see with Android UI/UX people what we want and then they'll provide us an icon.

So for the moment, I'm waiting for Fenix people to know what we want to do.
Could you add a pref (off by default), something like `pdfjs.enablePrinting` ? and then I'll land your patch or we can keep it in the oven until we've more info. What do you prefer ?

**Comment by Snuffleupagus** [comment]
Landing something that doesn't work anyway seems kind of pointless. at least to me, so let's just wait until we actually know exactly how this should be integrated on the platform side.

**Comment by calixteman** [comment]
@Snuffleupagus, I want to merge this patch asap to fix pdf form printing on Android (bug 1842685).
Would you mind to have a look on it to see if everything is ok for you ?

**Review by calixteman — APPROVED** [review]
LGTM.
Thank you.

**Pull request merged**
