### PR TITLE
Issue #6569 document_colors_disabled shouldn't escape quotes (compare-locales warning)

### PR DESCRIPTION
**Pull request by Archaeopteryx**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
First of all, please rebase the patch onto the current `master`, since there are merge conflicts.
(It appears that the patch is based on a fairly old PDF.js version.)

Second of all, I'm wondering if it's actually necessary to update the `id` of the string?
According to https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Changing_existing_strings:
> [...] If your changes are relevant only for English — for example, to correct a typographical error or to make letter case consistent — then there is generally no need to update the entity name.

**Comment by timvandermeij** [comment]
@Archaeopteryx Do you have time to fix up this PR? All it needs is a rebase and a revert of the ID change. Then it should be good to go.

**Comment by timvandermeij** [comment]
From the discussions on IRC the following should be changed before we can land this PR:

- Rebase onto the current master (keep it as one commit by squashing if necessary: https://github.com/mozilla/pdf.js/wiki/Squashing-Commits)
- Make the ID change more descriptive: `document_colors_disabled2` could become `document_colors_not_allowed` or something else that has the same meaning.

The reason for this change are the warnings at https://l10n.mozilla.org/dashboard/compare?run=551090.

**Comment by Archaeopteryx** [comment]
Sorry for the delay. I have [pushed an updated commit](https://github.com/Archaeopteryx/pdf.js/commit/27577a714f6403441b0e1c92879399e40e46ae5e), but lost the previous 'pdf.js' repository, so it seems impossible to update this pull request. Should I open a new one?

The reason why the [string gets updated](https://groups.google.com/d/msg/mozilla.dev.l10n/tIjyUTV36a0/vZBjawscSjkJ) is that unnecessary escaping creates warnings in Mozilla's l10n validator compare-locales like mentioned in the previous comment. If the string id would remain unchanged, locales wouldn't pick it up.

**Comment by timvandermeij** [comment]
I have made a new pull request with your updated commit in it (#6676), so we can close this PR.

**Pull request closed without merging**
