### PR TITLE
Don't map glyphs to Unicode "Dotted circle" combining mark (bug 1108301)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
It seems that `0x25CC` is another bad spot for charCodes.
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1108301.

**Edit:** Fixes one of the bugs in #5647.

### CODE REVIEW

**Comment by brendandahl** [comment]
Any idea why this character is special? BTW seems to be a windows only problem.

**Comment by Snuffleupagus** [comment]
> Any idea why this character is special? BTW seems to be a windows only problem.

No, unfortunately not. I'm actually leaning towards closing the PR, since I have a hard time rationalizing why this patch the "correct" solution.

**Comment by Snuffleupagus** [comment]
Actually, doing a code search against the Mozilla source gives interesting results: https://dxr.mozilla.org/mozilla-central/search?q=0x25CC&case=false.
I'm not pretending to understand anything about that code, or if it's even *remotely* relevant in this context, but it does appear to be some special casing of the `0x25CC` charCode.

**Comment by Snuffleupagus** [comment]
Rebased to fix merge conflicts in the test files, no functional code changes were made.

**Pull request merged**
