### PR TITLE
Make use of textAdvanceScale consistent during combineTextItems. Fix for #7878.

### PR DESCRIPTION
**Pull request by rossj**
Currently, while generating the text content of a page, multiple text draw operations may be combined into a single `textContentItem`. The running size of this `textContentItem` is kept as text is added and as the text transformation is changed; however, the summing of this size inconsistently applies the `textAdvanceScale` factor.

This pull request fixes the discrepancy by only using the `textAdvanceScale` upon completion / flushing of the `textContentItem`. The result is that the `textContentItem`'s size is calculated correctly, improving text highlighting in cases like #7878.

More details:

Currently, `textAdvanceScale` is applied when adding the width / height of actual text content [here](https://github.com/mozilla/pdf.js/blob/c5b06cb40d032e782f5afa3a0ed73d4ee80f160a/src/core/evaluator.js#L1369). The `textAdvanceScale` is not applied when accounting for size changes due to text advance transformation changes, such as [here](https://github.com/mozilla/pdf.js/blob/c5b06cb40d032e782f5afa3a0ed73d4ee80f160a/src/core/evaluator.js#L1468).

I believe this issue might not appear often as it requires there to be a non-zero difference between the text advance distance and the previously calculated `lastAdvanceWidth` in order for the non-application of the scaling factor to have an effect.

### CODE REVIEW

**Comment by timvandermeij** [comment]
The tests reveal some unexpected changes. In particular, `firefox-issue1936-text-page1` seems bad. Could you check why that is the case?

**Comment by rossj** [comment]
You are right about the issues with some files -- sorry for not noticing these.

I tracked the issue down to the fact that `textMatrix` scaling was already being applied to `TJ` offsets during processing of the `showSpacedText` op, which I was then re-applying when "flushing" the `textContentItem`. Removing these first scaling operations fixes the problem files.

screen shot 2016-12-14 at 1 42 43 am

I should mention that I do find the scaling operations that I removed a bit odd, and I don't quite understand mathematically what they were trying to accomplish or how they correspond with the equations in section 9.4.4 "Text Space Details" of the PDF spec. Regardless, I believe my new updates are in line with the provided text matrix equations.

**Comment by timvandermeij** [comment]
Looks good. Could you add the file from #7878 as a regression test? Check https://github.com/mozilla/pdf.js/pull/7714/files as an example of how to add a test case. You have to do three things: update `.gitignore` to ignore the PDF file, add the PDF file itself and add an entry to `test_manifest.json` like the one over there. This helps us to prevent any regressions in the future.

When that is done, please squash the commits into one commit. See https://github.com/mozilla/pdf.js/wiki/Squashing-Commits for how to do that easily. Thanks!

**Comment by rossj** [comment]
Sure, I'll make those changes. Is it best to name the new test file after the issue or to give it a more descriptive name?

I've also just noticed that `evaluator.js` isn't properly detecting the font in the #7878 file as monospace, despite the `FixedPitch` font flag being set and the `Font` providing a single `W` width. This results in the default glyph width of 1000 being used instead of the correct width of 600. This doesn't effect highlighting the #7878 PDF very much because each glyph is essentially positioned explicitly, but I can imagine for longer string draws the calculated text/highlight width would be much to large.

Do you suggest I look into the monospace detection as part of this PR or should I make a new issue?

**Comment by brendandahl** [comment]
> Is it best to name the new test file after the issue or to give it a more descriptive name?

Issue number is preferred for referencing it later.

> Do you suggest I look into the monospace detection as part of this PR or should I make a new issue?

New PR would be best.

**Comment by rossj** [comment]
Squashed. Please let me know if anything else should be changed. Thanks!

**Comment by yurydelendik** [comment]
/botio makeref

Thank you for the patch!

**Pull request merged**
