### PR TITLE
optimize png images using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use Google's zopflipng to re-compress png images losslessly as below:

```
 extensions/b2g/images/div_line_left.png           | Bin 174 -> 169 bytes
 extensions/b2g/images/div_line_left@1.5x.png      | Bin 196 -> 185 bytes
 extensions/b2g/images/div_line_left@2x.png        | Bin 319 -> 295 bytes
 extensions/b2g/images/div_line_right.png          | Bin 173 -> 166 bytes
 extensions/b2g/images/div_line_right@1.5x.png     | Bin 193 -> 184 bytes
 extensions/b2g/images/div_line_right@2x.png       | Bin 319 -> 295 bytes
 extensions/b2g/images/document_bg.png             | Bin 609 -> 560 bytes
 extensions/b2g/images/icon_next_page.png          | Bin 325 -> 310 bytes
 extensions/b2g/images/icon_next_page@1.5x.png     | Bin 343 -> 338 bytes
 extensions/b2g/images/icon_previous_page.png      | Bin 384 -> 372 bytes
 extensions/b2g/images/icon_previous_page@1.5x.png | Bin 396 -> 395 bytes
 extensions/b2g/images/icon_zoom_in@1.5x.png       | Bin 1229 -> 1170 bytes
 extensions/b2g/images/icon_zoom_out@1.5x.png      | Bin 1090 -> 1051 bytes
 extensions/b2g/images/spinner.png                 | Bin 3225 -> 2759 bytes
 extensions/b2g/images/toolbar_background.png      | Bin 4695 -> 4657 bytes
 extensions/chromium/icon128.png                   | Bin 3463 -> 2989 bytes
 extensions/chromium/icon16.png                    | Bin 622 -> 594 bytes
 extensions/chromium/icon19.png                    | Bin 712 -> 679 bytes
 extensions/chromium/icon38.png                    | Bin 1330 -> 1300 bytes
 extensions/chromium/icon48.png                    | Bin 1691 -> 1671 bytes
 extensions/firefox/icon.png                       | Bin 1612 -> 1597 bytes
 extensions/firefox/icon64.png                     | Bin 2089 -> 2003 bytes
 web/images/texture.png                            | Bin 2418 -> 2417 bytes
 web/images/toolbarButton-menuArrows.png           | Bin 108 -> 107 bytes
 web/images/toolbarButton-viewAttachments@2x.png   | Bin 871 -> 859 bytes
 web/images/toolbarButton-viewThumbnail@2x.png     | Bin 220 -> 219 bytes
 web/images/treeitem-collapsed-rtl.png             | Bin 183 -> 143 bytes
 web/images/treeitem-collapsed-rtl@2x.png          | Bin 205 -> 167 bytes
```

### CODE REVIEW

**Comment by timvandermeij** [comment]
There is a problem with `web/images/loading-small.png` and `web/images/loading-small@2x.png`. Those are animated PNGs, but this patch removed the animation. We might need to exclude these two or somehow let `zopflipng` know that it is an animated PNG. Could you look into that?

**Comment by PeterDaveHello** [comment]
Okay, I'll take a look at this problem.

**Comment by PeterDaveHello** [comment]
Problem confirmed, reported to zopflipng upstream here: https://github.com/google/zopfli/issues/118, rollback those two images to origin. Thanks @timvandermeij.

**Comment by timvandermeij** [comment]
Thank you!

**Pull request merged**
