### PR TITLE
Fix wrong order of arguments when calling the CipherTransform ctor (bug 1782186)

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
I guess that virtually all encrypted PDF documents use *the same* stream/string filters, which is probably why this bug has gone unnoticed ever since PR #275 (eleven years ago).

However, this *really* needs a test-case. Please add a new `eq` test for this, and looking at the PDF document it seems fine to include that one directly in the repository.

**Comment by calixteman** [comment]
I didn't know we can make ref test with a password: TIL.

**Pull request merged**
