### PR TITLE
Use a `ResizeObserver` to update the layout of `PDFFindBar`

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please note:* In the Firefox PDF Viewer this findbar is only used for PDF documents placed in e.g. `<iframe>` elements.

By registering a `ResizeObserver` when the `PDFFindBar` is open we slightly unify and simplify how the findbar layout (row vs column) is handled.
This will be especially helpful with upcoming changes, where we'll make use of "data-l10n-id"/"data-l10n-args" to trigger translation in the viewer.

### CODE REVIEW

**Comment by calixteman** [comment]
Can't we achieve the same layout change with [flex-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap) ?

**Comment by Snuffleupagus** [comment]
> Can't we achieve the same layout change with [flex-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap) ?

Unfortunately I don't believe that this helps, since the findbar then becomes too wide once wrapping occurs; please note
https://github.com/mozilla/pdf.js/blob/a4cd2ef1db506d175c0ae768488596085a6511c9/web/pdf_find_bar.js#L195-L198

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
