### PR TITLE
Improve jpx decoding by around 20% in enabling simd support when compiling OpenJPEG

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Have you tested that the image decoder still works in Node.js environments with this change?

**Comment by calixteman** [comment]
No I didn't.
I just ran: `gulp image_decoders`.
In `node`, I ran:
```
const { JpxImage } = await import("./build/image_decoders/pdf.image_decoders.mjs");
JpxImage.decode(new Uint8Array([0]));
```
and it complains because of the wrong format but the wasm loaded, so it should be ok.
My node version is `18.19.1`.
If there's a risk to break something, shouldn't we have some tests ?

**Comment by Snuffleupagus** [comment]
> If there's a risk to break something, shouldn't we have some tests ?

I just wanted to check that the SIMD-part didn't break anything (we probably don't need specific Node.js tests here).

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Pull request merged**
