### PR TITLE
Actually skip pages included in the `skipPages` array when running tests, rather than creating empty 1x1 canvases (issue 8241)

### LINKED ISSUE #8241: Skipped pages show up in reftests
I noticed a number of blank pages in http://107.21.233.14:8877/aec1bf6261c835c/reftest-analyzer.html for chrome-issue1658, turns out 1-10 are skipped pages. Not sure why they're showing up in the tests.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Considering how extremely simple this patch turned out to be, I'm almost worried that I completely misunderstood why the current code looks like it does...

Fixes #8241.

### CODE REVIEW

**Comment by timvandermeij** [comment]
I share the confusion about the current code. I really don't see why creating 1x1 empty canvases would be useful. If @brendandahl agrees with this patch, you have my blessing for this as well.

**Comment by Snuffleupagus** [comment]
Hmm, I'm not sure what's up with the one "failure" in Chrome on Linux, since everything looks fine...

/botio-linux test

**Comment by Snuffleupagus** [comment]
Based on test-run in https://github.com/mozilla/pdf.js/pull/3891#issuecomment-292478504, it seems that there are intermittent failures in Chrome `master` as well, so at least it doesn't look like the failures are caused by this PR.

**Comment by Snuffleupagus** [comment]
Based on the test-run in https://github.com/mozilla/pdf.js/pull/3891#issuecomment-292478504, it seems that there are intermittent failures in Chrome on `master` as well, so at least it doesn't look like the failures are caused by *this* PR.

**Pull request merged**
