### PR TITLE
Make sure the canvas is always the first child of its wrapper

### PR DESCRIPTION
**Pull request by calixteman**
While drawing, in zooming fast enough, it's possible, intermittently, to have the canvas after the svg which makes the svg invisible.
So this patch makes sure to have the canvas at the right position.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
> to have the canvas after the svg which makes the svg invisible.

Sorry, but what SVG is this referring to since I don't believe that the `canvasWrapper` has any SVG elements?

**Comment by calixteman** [comment]
> > it's possible, intermittently, to have the canvas after the svg which makes the svg invisible.
> 
> Sorry, but what SVG is this referring to since I don't believe that the `canvasWrapper` has any SVG elements?

The drawings (highlights and inks) are under the canvasWrapper:
image
The goal of having highlights there was to make sure the blend operation was applied with the canvas as the backdrop.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.

**Pull request merged**
