### PR TITLE
[Editor] Take all the viewBox into account when computing the coordinates of an annotation in the page (fixes #15789)

### LINKED ISSUE #15789: Annotations are on Wrong Position after Saving/Downloading
Attach (recommended) or Link to PDF file here: [sample_pdf.pdf](https://github.com/mozilla/pdf.js/files/10175112/sample_pdf.pdf)

Configuration:
- Web browser and its version: Chrome 108 (Firefox too)
- Operating system and its version: Windows
- PDF.js version: 3.1.81
- Is a browser extension: no

Steps to reproduce the problem:
1. open viewer https://mozilla.github.io/pdf.js/web/viewer.html
2. Open attached PDF
3. Use ink editor or add annotations
4. Save/Download PDF
5. Open Again

What is the expected behavior? (add screenshot)

After saving (and opening the document again), all annotations should be on the same position as before.

Before

What went wrong? (add screenshot)

After

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
I was expecting this failure but I had the secret hope that it could work.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Pull request merged**
