### PR TITLE
Extract & use createHeaders helper

### PR DESCRIPTION
**Pull request by wojtekmaj**
Prevents code duplication by implementing createHeaders enclosing duplicated pieces of code

### CODE REVIEW

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Nit: It would be nice if the *commit message* actually mentioned where these changes are being made, e.g. something like `Extract & use createHeaders helper in src/display/fetch_stream.js`, since otherwise it's not really possible to understand the changes without looking at the code.

**Comment by wojtekmaj** [comment]
@Snuffleupagus Sure thing, done!

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Good clean-up!

**Pull request merged**
