### PR TITLE
Abort, with a small delay, `getOperatorList` on the worker-thread when rendering is cancelled (PR 11069 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
With this patch we're finally able to abort worker-thread parsing of the `OperatorList`, rather than *only* aborting the main-thread rendering itself, when the `RenderTask.cancel` method is being called.
This will help improve perceived performance in the default viewer, especially when reading longer and more complex documents, since pages that've been scrolled out-of-view (and thus evicted from the cache) will no longer compete for parsing resources on the worker-thread.

*Please note:* With the implementation in this patch we're *not* aborting worker-thread parsing immediately on `RenderTask.cancel`, since that would lead to *worse* performance in many cases. For example: When zoom/rotation occurs in the viewer, while parsing/rendering is still ongoing, a `cancel` call will usually be (almost) immediately folled by a new `PDFPageProxy.render` call. In that case you obviously don't want to abort parsing on the worker-thread, since that would risk throwing away a partially parsed `OperatorList` and thus force unnecessary re-parsing which will regress perceived performance (especially for more complex documents).

When choosing a reasonable delay, before cancelling `getOperatorList` on the worker-thread when `RenderTask.cancel` is called, two different positions need to be considered:
 1. The delay needs to be short enough, since a timeout in the multiple seconds range would essentially make this entire functionality meaningless (by always allowing most/all pages enough time to finish parsing).

 2. The delay cannot be *too* short, since that would actually *reduce* performance in the zoom/rotation case outlined above. Furthermore, the time between `RenderTask.cancel` and `PDFPageProxy.render` calls will obviously be affected by both general computer performance and current CPU load.

It's certainly possible that the timeout may require some further tweaks, however the value settled on in this patch was easily *one order* of magnitude larger than the delta between cancel/render in my tests.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
PR #11069 has now landed in `mozilla-central`, courtesy of [bug 1576613](https://bugzilla.mozilla.org/show_bug.cgi?id=1576613), but I'd like to delay landing of this PR a little while to make it easier to pin-point any issues (hopefully there won't be any :-).
Additionally, since there's been a couple of recent `MessageHandler` patches it probably won't hurt to wait for those to land in `mozilla-central` first as well.

**Comment by Snuffleupagus** [comment]
This will also address (a significant) part of issue #1887, since we're now aborting parsing of both `OperatorList` and `TextContent` on the worker-thread when rendering is cancelled.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks like a really good approach to me!

**Comment by Snuffleupagus** [comment]
> Looks like a really good approach to me!

@timvandermeij Thanks a lot for reviewing and landing this; this should hopefully help performance a fair bit with long documents.

I tried to keep the implementation as simple I possibly could and the key, as far as I'm concerned, was to remove the entire `intentState` on abort rather than trying to resetting only some of its parameters.

**Pull request merged**
