### PR TITLE
Enables source maps for webpack generated files.

### PR DESCRIPTION
**Pull request by yurydelendik**
screen shot 2017-05-03 at 12 40 05 pm

### CODE REVIEW

**Review by Snuffleupagus — COMMENTED** [review]
While this seem to work just fine in my testing, I've got a couple of questions:
- First of all, the generated `.map` files seem to be approximately *two* times larger than their corresponding `.js` files. Am I missing something here, or are they supposed to be *that* big?
Are there any settings to compact them somewhat? For example, there seem to be *a lot* of (unnecessary?) white-space in the `.map` files.
- Second of all, the `.map` files are being bundled into the output of *all* of the built targets by defaults.
For e.g. the `FIREFOX`/`MOZCENTRAL` builds[1], I'm assuming that may not be what we want (at least not right now), given the point above regarding the size of the `.map` files?

---
[1] I recall that there was some initial resistance about file sizes when the Adobe CMaps where originally added. However, they were less than 1 MB, so I'd assume that people would really object if the size of the `pdfjs` directory in mozilla-central went from 3 to 6 MB overnight :-)

**Comment by yurydelendik** [comment]
> First of all, the generated .map files seem to be approximately two times larger than their corresponding .js files.

It's expected. I also configured map to include original files content, so we don't have to ship ton of separate files.

> Second of all, the .map files are being bundled into the output of all of the built targets by defaults. For e.g. the FIREFOX/MOZCENTRAL builds...

Yes, now I think, we need to disable maps for FIREFOX/MOZCENTRAL/CHROME

**Review by Snuffleupagus — APPROVED** [review]
Thank you for answering my questions, that helped to clear things up!

With this now being excluded from the extensions, I don't have any reservations.
r=me, since this works just fine; thank you!

**Pull request merged**
