### PR TITLE
Fix font for the 'current view' entry in the secondary toolbar (bug 1797310)

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by marco-c** [comment]
The bug is fixed: immagine

**Comment by marco-c** [comment]
The text is not vertically centered though.

**Comment by Snuffleupagus** [comment]
> The text is not vertically centered though.

Testing quickly, it seems that reducing the following value with one pixel works better:
https://github.com/mozilla/pdf.js/blob/098ca670d0f290fbc3f70c66080708a5e4b67155/web/viewer.css#L938

**Review by Snuffleupagus — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
