### PR TITLE
Use standard `import` statements more when running the unit-tests

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please refer to the individual commit messages for additional information.*

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks much better. Thanks!

**Comment by Snuffleupagus** [comment]
> Looks much better. Thanks!

Thank you for reviewing/landing this, and the other recent test-related patches.

It's really fascinating how code sort of "ages", like in the font-tests, when you don't touch it for a couple of years.

**Pull request merged**
