### PR TITLE
Test new linux bot.

### PR DESCRIPTION
**Pull request by brendandahl**
Migrating linux bot to m4 instance.

### CODE REVIEW

**Comment by brendandahl** [comment]
Open those ports!
/botio-linux-new lint

**Comment by brendandahl** [comment]
Use the right ip!
/botio-linux-new lint

**Comment by brendandahl** [comment]
Install gulp!
/botio-linux-new lint

**Comment by brendandahl** [comment]
Comparing against old linux bot.
/botio-linux-new test

**Comment by timvandermeij** [comment]
Just a quick note that some files failed to download, as it may get a bit lost in the large log.

**Comment by brendandahl** [comment]
> Just a quick note that some files failed to download, as it may get a bit lost in the large log.

Hmm...it shouldn't have downloaded the files at all.

**Comment by brendandahl** [comment]
/botio-linux-new makeref
Looks like I didn't update the bot files there.

**Comment by timvandermeij** [comment]
@brendandahl How is this work going? Will we be able to use the new Linux bot soon or are there open issues with it?

**Comment by brendandahl** [comment]
> @brendandahl How is this work going? Will we be able to use the new Linux bot soon or are there open issues with it?

No issues, the new bot isn't really faster and I haven't had time to finish the migration. If we need to upgrade chrome, maybe it time to switch bots too.

**Comment by brendandahl** [comment]
looks like ff updated
/botio-linux-new makeref

**Comment by timvandermeij** [comment]
Closing since the Linux bot is ready now and will be in use shortly.

**Pull request closed without merging**
