### PR TITLE
[TrueType] Recover from a missing "glyf" table by replacing it with dummy data, utilizing the existing code in `sanitizeGlyphLocations`

### LINKED ISSUE #4684: Missing glyf and loca errors prevent invisible font from showing
PDF.js shows a search button and accurately searches and allows selection of text for many types of PDFs.  For the PDF files created by our tools below (the vast majority of our large collection), however, we see no search box and are unable to select text.  Opening these same PDFs is Adobe Reader, Apple Preview, and Foxit Reader. None of those readers show error messages or any other signs that the PDF is malformed.

Our theory is that the relatively antique and simpe invisible font we are using for our text layer is missing some TrueType elements (glyf and loca tables) that the OpenType font sanitizer wants to see.  When it does not see them, it drops the font which in our case renders the PDF unsearchable becuase everything from the HDOC processing by Tesseract has been rendered in this one font.

Any advice or help you can provide would be great.  Thanks so much for this work on PDF.js -- it is a beautiful reader!

Error Message:

In Firefox console (debug turned on) we see:

"Warning: Error during font loading: Required "glyf" or "loca" tables are not found"

FontInspector on Firefox native PDF.js shows no fonts in the sidebar.

Document samples: 

http://pucdocket.s3.amazonaws.com/MA/12-42/121912dpuaprv_ocr.pdf
http://pucdocket.s3.amazonaws.com/MA/11-07/123112dpugrmt_ocr.pdf

Tools Used for PDF Creation:

Font: http://www.angelfire.com/pr/pgpf/if.html
ReportLab: https://bitbucket.org/rptlab/reportlab/overview
PyPDF2: https://github.com/mstamy2/PyPDF2

Possibly Related Issues:

https://github.com/mozilla/pdf.js/issues/3483
https://github.com/mozilla/pdf.js/pull/495
https://github.com/mozilla/pdf.js/issues/3522
screen_shot_2014-04-25_at_10 58 38_am

### LINKED ISSUE #6007: pdf rendered with errors: "Error: Required "glyf" or "loca" tables are not found"
http://www.tp-link.com/resources/document/Archer_C7_V2_User_Guide_1910010809.pdf

tested with ff 37.0.2 on linux.

on page 3/4:
```
"PDF 81db909953679b4aa345f95eb9537722 [1.6 Adobe PDF Library 10.0 / Acrobat PDFMaker 10.1 Word 版] (PDF.js: 1.1.124)" viewer.js:6397:0
"Error: Required "glyf" or "loca" tables are not found" pdf.worker.js:243:4
"Font_checkAndRepair@resource://pdf.js/build/pdf.worker.js:17896:11
Font@resource://pdf.js/build/pdf.worker.js:16462:16
PartialEvaluator_translateFont@resource://pdf.js/build/pdf.worker.js:12002:14
PartialEvaluator_loadFont@resource://pdf.js/build/pdf.worker.js:10775:1
PartialEvaluator_handleSetFont@resource://pdf.js/build/pdf.worker.js:10547:14
next@resource://pdf.js/build/pdf.worker.js:10936:22
next/<@resource://pdf.js/build/pdf.worker.js:10941:19
" pdf.worker.js:244:0
"Warning: Unsupported feature "unknown"" pdf.worker.js:235:4
"Warning: Unsupported feature "unknown"" pdf.js:235:4
"Warning: Unsupported feature "font"" pdf.worker.js:235:4
"Warning: Unsupported feature "font"" pdf.js:235:4
"Warning: Error during font loading: Required "glyf" or "loca" tables are not found" pdf.js:235:4
```

### LINKED ISSUE #6829: Cannot select text for PDF generated by hocr-pdf
I used hocr-pdf (https://github.com/tmbdev/hocr-tools/blob/master/hocr-pdf) to generate a PDF (attached). hocr-pdf can merge a hocr file with an image file to generate a PDF.  The hocr file is generated by Tesseract.  Adobe Reader and Chrome default PDF viewer both have no problem to let me select and copy text from the PDF.  But PDF.js does not allow me to select the text.  

Anyone knows why? Is it an issue with hocr-pdf or PDF.js?  Any suggestion on how to resolve the issue?

[tesseract_hocr.pdf](https://github.com/mozilla/pdf.js/files/76606/tesseract_hocr.pdf)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
It seems to be fairly common for OCR software to include incomplete TrueType fonts, notable missing the "glyf" table, in PDF files. Since we currently reject such fonts, the result is that text-selection/copying is broken.

This patch contains a suggested approach to try and use these kind of broken fonts, by using existing code in `sanitizeGlyphLocations` to replace a missing "glyf" table with dummy data.

~~_Please note:_ Given that I'm not sure if we actually want to do this, I didn't want to waste time creating a reduced test-case. If this patch is deemed acceptable, I'll be happy to add a test.~~

Fixes #4684.
Fixes #6007.
Fixes #6829.

### CODE REVIEW

**Comment by timvandermeij** [comment]
This looks like a good solution to me. I can confirm that the three mentioned issues are resolved with this PR. I think that if we are able to recover from bad data that we certainly should make an effort to do so. I'll leave the final decision for @yurydelendik or @brendandahl, but with a reduced test case added you have my blessing for this!

**Comment by brendandahl** [comment]
This fix seems good to me. A reduced text selection test case would be nice.

**Comment by Snuffleupagus** [comment]
A reduced `text` test-case has been added, thanks for the review!

/botio test

**Comment by timvandermeij** [comment]
Thank you for patching this!

**Pull request merged**
