### PR TITLE
Fix copying of the reduced Planck constant

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Please see https://en.wikipedia.org/wiki/H_with_stroke

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
I stumbled upon this in https://github.com/py-pdf/pypdf/issues/2009#issue-1818191533 and as far as I can tell the reduced Planck constant is the only one, of the listed characters, that we don't already handle correctly when copy-pasting.

**Review by calixteman — COMMENTED** [review]
What a nice PR title :)
LGTM. Thank you.

**Comment by pubpub-zz** [comment]
@Snuffleupagus 
I've completed the list of  Glyphs names to Unicode  in https://github.com/py-pdf/pypdf/pull/2016 if you are interesting

**Pull request merged**
