### PR TITLE
Additional Scroll/Spread mode clean-up (PR 9832 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please refer to the individual commit messages for additional details.*

Since I had some free time yesterday, this is the additional clean-up mentioned in PR #9832.

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Good changes; thanks!

**Comment by Snuffleupagus** [comment]
@timvandermeij As always, thanks for reviewing/merging this!

Given that the current pre-release needs to be replaced anyway (given the regressions fixed by PR #9832), would it make sense to include these changes here as well?

Rather than cherry-picking certain change sets, it seems that me that it's perhaps easiest to simply mark e.g. the current version (`2.0.659` as of this writing) as the new pre-release. Especially considering that a number of fixes for corrupt/broken PDF files landed recently, and these could be good to include as well.

**Comment by timvandermeij** [comment]
Yes, I think when we make a new (pre)release, it should include all changes up to that date.

**Comment by Snuffleupagus** [comment]
*For future reference:* Once this PR has been included in at least *one* official release, remove the deprecated code as outlined in the diff below.

```diff
diff --git a/web/base_viewer.js b/web/base_viewer.js
index c904a448..1d9ac59f 100644
--- a/web/base_viewer.js
+++ b/web/base_viewer.js
@@ -171,18 +171,6 @@ class BaseViewer {
     if (this.removePageBorders) {
       this.viewer.classList.add('removePageBorders');
     }
-
-    if ((typeof PDFJSDev === 'undefined' || PDFJSDev.test('GENERIC')) &&
-        ('scrollMode' in options || 'spreadMode' in options)) {
-      console.error(`The ${this._name} constructor options ` +
-        '`scrollMode`/`spreadMode` are deprecated, use the setters instead.');
-      if (options.scrollMode !== undefined) {
-        this.scrollMode = options.scrollMode;
-      }
-      if (options.spreadMode !== undefined) {
-        this.spreadMode = options.spreadMode;
-      }
-    }
   }
 
   get pagesCount() {
@@ -1078,14 +1066,6 @@ class BaseViewer {
     this.update();
   }
 
-  setScrollMode(mode) {
-    if (typeof PDFJSDev === 'undefined' || PDFJSDev.test('GENERIC')) {
-      console.error(`${this._name}.setScrollMode() is deprecated, ` +
-                    `use the ${this._name}.scrollMode setter instead.`);
-      this.scrollMode = mode;
-    }
-  }
-
   /**
    * @return {number} One of the values in {SpreadMode}.
    */
@@ -1145,14 +1125,6 @@ class BaseViewer {
     this.scrollPageIntoView({ pageNumber, });
     this.update();
   }
-
-  setSpreadMode(mode) {
-    if (typeof PDFJSDev === 'undefined' || PDFJSDev.test('GENERIC')) {
-      console.error(`${this._name}.setSpreadMode() is deprecated, ` +
-                    `use the ${this._name}.spreadMode setter instead.`);
-      this.spreadMode = mode;
-    }
-  }
 }
 
 export {

```

**Comment by timvandermeij** [comment]
Yes, it's good that they all have the word "deprecated" in the text so it easily comes up when using `grep`.

**Pull request merged**
