### PR TITLE
Split the existing `WebGLUtils` in two classes, a private `WebGLUtils` and a public `WebGLContext`, and utilize the latter in the API to allow various code to access the methods of `WebGLUtils`

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This patch is one (small) step on the way to reduce the general dependency on a global `PDFJS` object, for PDF.js version `2.0`.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@yurydelendik Review ping; can you please check if the interface of the new `WebGLFactory` looks OK?

**Comment by Snuffleupagus** [comment]
It looks like the "usual" intermittent errors on Windows, but let's check once more...

/botio-windows test

**Review by yurydelendik — APPROVED** [review]
Overall looks good, thanks for refactoring. IMHO "Factory" is not appropriate name, e.g. "ZZZFactory" have to create "ZZZ" object. Will `WebGLContext` be a better name choice here?

**Comment by Snuffleupagus** [comment]
> IMHO "Factory" is not appropriate name, e.g. "ZZZFactory" have to create "ZZZ" object. Will WebGLContext be a better name choice here?

Good point, I've change the name as suggested; thanks for the review!

**Pull request merged**
