### PR TITLE
Fixes insertion of blank pages during print if page sizes differ

### PR DESCRIPTION
**Pull request by tbtlr**
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1020878, https://bugzilla.mozilla.org/show_bug.cgi?id=972677 and probably more.

### CODE REVIEW

**Comment by yurydelendik** [comment]
I wonder if we can just get away with   #printContainer and #printContainer > div `height:100%` attribute. 

Not sure what kind of affect setting of the canvas'es style width/height will have on mozPrintCallback polyfill for other browsers. I wish we could set real size of the paper here in inches or mm.

**Comment by tobytailor** [comment]
We probably can once https://bugzilla.mozilla.org/show_bug.cgi?id=851937 is fixed. On my plate.

**Comment by timvandermeij** [comment]
I confirm that this fixes the mentioned Bugzilla issues. On top of that it fixes #4041 too. However, it regressed #6461 as it stretches it to match 100% height.

@tobytailor Could you look into what is causing this?

**Comment by tobytailor** [comment]
@timvandermeij fixed via 708895ffbacdb468d14906d5ae5e49c287910102.

**Comment by timvandermeij** [comment]
Thank you for the patch!

(I have tested this with IE, Edge, Firefox and Chrome and found no regressions for all problematic PDF files from older/current issues, only improvements in terms of no more blank pages and improved scaling.)

**Pull request merged**
