### PR TITLE
Clear the |getSinglePixelWidth| cache when rendering Type3 fonts (issue 6117)

### LINKED ISSUE #6117: Letter too bold
This is a regression from PR #4615. The letter "F" on page 6 is unreadable.

URL: http://chrishecker.com/images/3/33/Gdmogl.pdf
1.1.209: https://i.imgur.com/IobYdDE.png
0.8.990: https://i.imgur.com/s188qBb.png

fc1e2483b433134a538cce0acd0ccc76e335cf5f is the first bad commit
commit fc1e2483b433134a538cce0acd0ccc76e335cf5f
Author: Jonas Jenwald
Date:   Fri Apr 11 20:19:39 2014 +0200

    Enforce minimum line widths

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #6117.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
The test "failure" on Linux is extremely weird, since using `Circle differences` doesn't actually highlight any differences what so ever!
Even more strange is the fact that the line added in this patch isn't actually reached during rendering of `issue6113.pdf`, which was confirmed locally by placing an `error()` statement just before it.

**Comment by Snuffleupagus** [comment]
Even without this patch, that test "fails" in exactly the same way in Firefox on Linux, see https://github.com/mozilla/pdf.js/pull/3891#issuecomment-112401582.
Since that file is unfortunately fairly large, and also takes quite a while to render, I'm wondering if we are perhaps somehow comparing the images before they are ready!?

*Ninja edit:* I'm starting to wonder if we need to remove that test-case, since having a test which fails intermittently for no good reason isn't very practical.

**Comment by timvandermeij** [comment]
We can try the Windows bot first to see if it fails there too. Then we could try re-running "makeref" to see if that helps (maybe something went wrong there). If both do not help, then we might need to consider removing it.

**Comment by timvandermeij** [comment]
Looks good to me, but I would like @yurydelendik or @brendandahl to look into this too and merge it.

**Comment by yurydelendik** [comment]
Looks good

**Comment by timvandermeij** [comment]
Thanks!

**Pull request merged**
