### PR TITLE
Revert "Fix rendering problem when zooming on Safari" for causing bug 1895909

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Reverts mozilla/pdf.js#18019

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
r=me; as mentioned in the original PR, if there would be a regression we'd revert this.

**Comment by calixteman** [comment]
From my pov, the real problem isn't the original PR which just revealed an other problem: our CSS isn't perfect.

**Comment by timvandermeij** [comment]
Yes, but I also agree with @Snuffleupagus that it's best to first get back to the original working state before we do additional work in this area. Now that we know what regressed that gives us time, and a good opportunity, to e.g. introduce more tests and refactor the CSS first to avoid future regressions, which I do think is a really good idea indeed.

**Pull request merged**
