### PR TITLE
Fix integration test "Interaction in issue14307.pdf (1) must check input for US zip format"

### LINKED ISSUE #16929: Fix integration test "Interaction in issue14307.pdf (1) must check input for US zip format"
Introduction date: January 23, 2022
Introduction PR: https://github.com/mozilla/pdf.js/commit/6ac296e48e52a8940f6a869c44f768edb4674a7b (/cc @calixteman)
Type: intermittent (sometimes it works, indicating a possible timing/waiting issue)
OS: Windows
Logs: http://54.193.163.58:8877/248efa3bf526b9a/output.txt
Traceback:

```
Failures:
3) Interaction in issue14307.pdf (1) must check input for US zip format
  Message:
[31m    Error: Timeout - Async function did not complete within 30000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)[0m
  Stack:
        at <Jasmine>
        at listOnTimeout (node:internal/timers:569:17)
        at process.processTimers (node:internal/timers:512:7)
```

### PR DESCRIPTION
**Pull request by timvandermeij**
_This is part 6 of the work to create tickets for and on a case-by-case basis fix intermittently failing integration tests._

The commit messages contain more information about the individual changes.

Fixes #16929.

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
It's too bad that we can't remove the arbitrary timeouts, but anything that gets rid of intermittent failures is great to see.

r=me, thank you!

---

Also would today be a good time for a new release, if you have time?
(There's been about a month since the last one, and the Stamp-editing should be pretty much complete now.)

**Comment by timvandermeij** [comment]
> Also would today be a good time for a new release, if you have time?
(There's been about a month since the last one, and the Stamp-editing should be pretty much complete now.

Yes, I can do that. Given that there were some release blockers I thought I'd wait until next week, but if those are all settled now I can also do it today.

**Comment by Snuffleupagus** [comment]
> but if those are all settled now I can also do it today.

Yes, I think that we should be good to go now. (The upcoming release should also, hopefully, unbreak the type-definitions so it's probably a good idea to get it out as soon as possible.)

**Pull request merged**
