### PR TITLE
Add a couple more, mostly `text`, reference tests for non-embedded symbolic fonts without included encoding information

### PR DESCRIPTION
**Pull request by Snuffleupagus**
I've started to look into how we can fix issue #7580, but quickly became worried that fixing it could easily mean that we'd trade one fixed PDF file for a multitude of broken ones.

Hence I started going through the history of the code that choose the fallback encoding, and noticed that it has been changed a number of times over the years to deal with various cases of weirdness/errors in non-embedded fonts.
To my relief it turned out that almost all the PRs, please see a possibly incomplete [list here](https://gist.github.com/Snuffleupagus/a01105336950d876c18c8bd61f30c1e8), that changed this code actually included `eq` test-cases.

However, in one case it appears that a PR missed to add a test-case. Furthermore since the fallback encoding may also be the only source for creating a `toUnicode` map, changing the encoding could possibly regress only the text-selection despite a PDF file still rendering correctly.
Therefore, this PR adds one new `eq` test, and also a number of additional `text` tests for PDF files already present in the test-suite.

Note that it's obviously possible that there's a certain overlap between the added tests, but I'd be _a whole lot_ more concerned with causing regressions.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
It seems that the Linux bot wasn't able to correctly download the new file :-(
```
Downloading http://web.archive.org/web/20160910104607/http://www6.inra.fr/productions-animales_eng/content/download/4803/45520/version/1/file/Prod_Anim_1997_10_2_04.pdf to pdfs/issue2017.pdf...
Error during downloading of http://web.archive.org/web/20160910104607/http://www6.inra.fr/productions-animales_eng/content/download/4803/45520/version/1/file/Prod_Anim_1997_10_2_04.pdf: HTTP 503
Downloading http://web.archive.org/web/20160910104607/http://www6.inra.fr/productions-animales_eng/content/download/4803/45520/version/1/file/Prod_Anim_1997_10_2_04.pdf to pdfs/issue2017.pdf...
WARNING: File was not downloaded. See "pdfs/issue2017.pdf.error" file.
WARNING: File was not downloaded. See "pdfs/issue2017.pdf.error" file.
Unable to verify the checksum for the files that are used for testing.
Please re-download the files, or adjust the MD5 checksum in the manifest for the files listed above.
```

**Comment by timvandermeij** [comment]
I'll trigger a retry after the reference images are created in the other PR. The Windows bot did succeed and I noticed previously that the Web Archive intermittently returns 503 responses, so this can happen.

**Comment by timvandermeij** [comment]
It does not retry the download, which is not particularly useful... @yurydelendik Could you download this file and put it on the Linux bot manually?

**Comment by timvandermeij** [comment]
It's probably because of https://github.com/mozilla/pdf.js/blob/122d4732398ca67381cc469dc2f49696b824c98d/test/downloadutils.js#L96, which creates an empty file so that we do not retry. Why is that even there?

**Comment by Snuffleupagus** [comment]
Instead of waiting for someone to have time to manually fix the PDF file that failed to download, I just went ahead and replaced it with a reduced test-case instead :-)

/botio test

**Comment by timvandermeij** [comment]
Awesome! Good to have more test coverage and to even have a reduced test case.

**Pull request merged**
