### PR TITLE
Allow `getOperatorList`/`getTextContent` to skip errors when parsing broken XObjects (issue 8702, issue 8704)

### LINKED ISSUE #8702: pdf converted powerpoint (.ppt) files with hidden layer shows as blank on PDFjs viewer
Link to PDF file (or attach file [here):]([url])
[2_Test.pdf](https://github.com/mozilla/pdf.js/files/1175758/2_Test.pdf)

Configuration: 
- Web browser and its version: All Modern browsers
- Operating system and its version: winXX / latest
- PDF.js version: latest
- Is an extension:

Steps to reproduce the problem:
1. take a powerpoint (.ppt) files with hidden layer 
2. convert that ppt to pdf via acrobat
3. then try to view through pdfjs viewer

What is the expected behavior? (add screenshot)
should show exact contents
What went wrong? (add screenshot)
shows blank page

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### LINKED ISSUE #8704: referring: #8702
Link to PDF file (or attach file here):
[2_Test_latest.pdf](https://github.com/mozilla/pdf.js/files/1176873/2_Test_latest.pdf)

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This patch makes use of the existing `ignoreErrors` property in `src/core/evaluator.js`, see PRs #8240 and #8441, thus allowing us to attempt to recovery as much as possible of a page even when it contains broken XObjects.

Fixes #8702.
Fixes #8704.

*Edit:* More manageable diff with https://github.com/mozilla/pdf.js/pull/8922/files?w=1.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@timvandermeij In an effort to reduced Yury's review load a bit, is this something that you'd, time permitting, be comfortable reviewing? Please keep in mind that "no" is a perfectly valid answer :-)

*Just to clarify the intent of this PR:*
After PR #8240 we'll no longer fail immediately when encountering corrupt PDF operators, but will instead attempt to recover what's possible of a file.

The idea behind *this* PR is to ensure that any error present in an XObject will be limited to *only that particular* XObject, such that it will no longer negatively impact parsing/rendering of the rest of page (which, as the issue shows, can happen currently).

**Comment by timvandermeij** [comment]
Yes, I'm planning to dive into the details of some of the pull requests in the queue during the weekend, including this one. Thank you for the ping; hopefully we can split the work a bit this way.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice work!

**Pull request merged**
