### PR TITLE
Check that Type1C fonts does not actually contain OpenType font files (issue 7598)

### LINKED ISSUE #7598: Text not rendering in some generated PDFs
Link to PDF file (or attach file here): [TIDAUS161164634.pdf](https://github.com/mozilla/pdf.js/files/455873/TIDAUS161164634.pdf)

Configuration:
- Web browser and its version: Chrome 53.0.2785.89 (64-bit)
- Operating system and its version: OSX Yosemite 10.10.5 (14F1909)
- PDF.js version: PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 1.5.432)
- Is an extension: No

Steps to reproduce the problem:
1. Open the PDF in Preview on OSX, or in Gmail. The text will render.
2. Open the PDF in pdf.js: https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)

screen shot 2016-09-06 at 1 21 39 pm

What went wrong? (add screenshot)

screen shot 2016-09-06 at 1 22 51 pm

Notes:

The PDF was encoded using Aspose.Words for .NET 9.4.0.0.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This patch is yet another instalment in the (never ending) series of patches for PDF files that specify completely incorrect Type/Subtype for its fonts. In this case Type1/Type1C, when in fact OpenType would have been correct.

Fixes #7598.

**Edit:** Perhaps marginally easier reviewing with https://github.com/mozilla/pdf.js/pull/7600/files?w=1.

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/pdf.js/7600)

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Given that this isn't the first, and probably won't be the last, time that we've had to adjust the Font/Subtype because the PDF generator lies, we might want to consider simply ignoring that information and always check the font file itself instead.

I've got a [WIP patch](https://github.com/Snuffleupagus/pdf.js/tree/fonts-ignore-type-subtype-and-check-font-file-contents) that does this, and provided that it actually passes all tests locally I'd be happy to submit that one as a follow-up after the current PR lands.

**Comment by yurydelendik** [comment]
r+

**Comment by timvandermeij** [comment]
Nice work!

**Comment by timvandermeij** [comment]
(Feel free to make a PR for the follow-up patch you mentioned if you think it helps to prevent further issues.)

**Pull request merged**
