### PR TITLE
Use correct matrix for patterns with showText.

### LINKED ISSUE #8111: incorrect shading of text
Link to PDF file (or attach file here):
https://issues.apache.org/jira/secure/attachment/12650283/000004_ShadingPatternTextPDF.pdf

Configuration:
- Web browser and its version: FF 51.0.1 32bit
- Operating system and its version: W7
- PDF.js version: latest

Steps to reproduce the problem:
display file

What is the expected behavior? (add screenshot)
ok

What went wrong? (add screenshot)
nok

possibly similar problem:
https://www.pdflib.com/fileadmin/pdflib/Cookbook/pdf/color_gradient.pdf (shaded text completely missing)
https://issues.apache.org/jira/secure/attachment/12630566/pslib-shading.pdf (page 4, part of text missing)
https://issues.apache.org/jira/secure/attachment/12652009/pattern-shading-2-4-idMatrix.pdf (some text missing)
https://issues.apache.org/jira/secure/attachment/12652010/pattern-shading-2-4-noMatrix.pdf (some text missing)

### LINKED ISSUE #9243: Displaced shading pattern
Attach (recommended) or Link to PDF file here:
[shading_pattern.pdf](https://github.com/mozilla/pdf.js/files/1532598/shading_pattern.pdf)

Configuration:
- Web browser and its version: Firefox 57.0
- Operating system and its version: Debian GNU/Linux 9 64-bit
- PDF.js version: tried with Firefox's 1.9.583 and with online viewer 2.0.185
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached file with the online viewer https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
image
(Image captured from Adobe Reader CS.) The shading needs to be inside the letters.

What went wrong? (add screenshot)
image
The shading seems to be displaced and upside-down, for it does not cover all the characters of the word.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by brendandahl**
We were incorrectly using the transform in the pattern before it had been
adjusted causing the pattern to be misplaced relative to the page.

Fixes: ShowText-ShadingPattern.pdf (already in corpus)
Fixes: #8111
Fixes: #9243

### CODE REVIEW

**Comment by brendandahl** [comment]
I should mention the two test issues added are slightly different problems, so I've added them both.

**Comment by brendandahl** [comment]
Let's try that again after ref fixes...
/botio test

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks for fixing these long-standing issues!

**Pull request merged**
