### PR TITLE
Extracts OperatorList class and prepares for streaming

### PR DESCRIPTION
**Pull request by yurydelendik**
Now OperatorList will be optimized all the time and no need to optimize it before we decide to send with large chunk, it can be send in smaller portions (e.g. based on time slice).

### CODE REVIEW

**Comment by yurydelendik** [comment]
Somewhat expected this type of failures -- different operator list painting for e.g. paintInlineImageXObjectGroup . We need to check if we can avoid intermittent failures when streaming will be used.

**Comment by brendandahl** [comment]
/botio test

Checking to see if test failures stay the same...

**Comment by brendandahl** [comment]
Looks like there was some flakyness on windows:

! | chrome-issue4926-page1
! | chrome-issue4926-built-in-jpg-page1

**Review by brendandahl — APPROVED** [review]

**Pull request merged**
