### PR TITLE
Enable some Stylelint color-related rules to slightly reduce file sizes

### PR DESCRIPTION
**Pull request by Snuffleupagus**
- Use a consistent format for all alpha-values (this rule didn't require any code changes); see https://stylelint.io/user-guide/rules/alpha-value-notation
 - Use modern and slightly shorter color notation, since [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb#browser_compatibility) that should be supported "everywhere" nowadays; see https://stylelint.io/user-guide/rules/color-function-notation/
 - Use "short" hexadecimal colors whenever possible; see https://stylelint.io/user-guide/rules/color-hex-length/
 - Help avoid adding broken hexadecimal colors (this rule didn't require any code changes); see https://stylelint.io/user-guide/rules/color-no-invalid-hex/

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by Snuffleupagus** [comment]
*Running makeref here, since it recently failed in PR #17075 because the branch was removed too soon.*

/botio makeref

**Comment by calixteman** [comment]
arff... my bad, sorry about that.

**Pull request merged**
