### PR TITLE
Enable the `unicorn/prefer-dom-node-append` ESLint plugin rule

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This rule will help enforce slightly shorter code, especially since you can insert multiple elements at once, and according to MDN `Element.append()` is available in all browsers that we currently support.

Please find additional information here:
 - https://developer.mozilla.org/en-US/docs/Web/API/Element/append
 - https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-dom-node-append.md

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
This mostly mechanical change reduces the size of the `gulp mozcentral` output by just over 1 kB.

**Review by calixteman — APPROVED** [review]
Thank you.

**Pull request merged**
