### PR TITLE
Update dependencies to the most recent versions and upgrade `eslint-plugin-unicorn` to version 54.0.0

### PR DESCRIPTION
**Pull request by timvandermeij**
The commit messages contain more details about the individual changes. Notes for the reviewer:

- The `eslint-plugin-jasmine` update contains support for ESLint 9 (see https://github.com/tlvince/eslint-plugin-jasmine/releases/tag/v4.2.0), which brings us another step closer for #17928.
- The `@metalsmith/markdown` update is interesting because that one _should_ already have been part of #18248. I don't know what happened exactly, but I somehow managed to mess up the version number there and probably copy/pasted the older one.
- The `puppeteer` update contains some bugfixes and Chrome updates that could benefit us (see https://github.com/puppeteer/puppeteer/releases), but note that this version does _not_ yet contain the fix for https://github.com/GoogleChromeLabs/chromium-bidi/issues/2317 because even though it's released the `chromium-bidi` bump has not been done in the Puppeteer repository yet. (This one was identified in https://github.com/mozilla/pdf.js/issues/17961#issuecomment-2167844445 and could help us get more details as to what's going wrong in the Chrome-on-BiDi PR.)
- I didn't forget to include the translation updates; there just weren't any ;-)
- This brings us back to 0 vulnerabilities reported by NPM again (it was 3 before this patch). There is also a slight reduction in the size of the dependency tree: 1166 packages now versus 1201 before this patch.

### CODE REVIEW

**Comment by timvandermeij** [comment]
I'm not really sure what's wrong with Chrome here: it looks like it just... stopped halfway the integration tests? I'll try this again locally to find out if it's intermittent (I do somewhat recall having seen such weird high number of errors before, and usually a retry resolved it) or if it's caused by the Puppeteer upgrade.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.

**Pull request merged**
