### PR TITLE
[Firefox] Parse all JPEG images in the addon

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Workaround for:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1164199.
- https://github.com/mozilla/pdf.js/issues/6017.

### CODE REVIEW

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by samlh** [comment]
This also fixes (or works around) issue #6012

**Comment by yurydelendik** [comment]
Let's land it until upstream will be fixed.

**Comment by yurydelendik** [comment]
Thanks

**Pull request merged**
