### PR TITLE
Fix inverted calculation of RTL text percentage in bidi

### PR DESCRIPTION
**Pull request by Skaty**
While I was doing up unit tests for the Unicode bi-directional function, I realised that the fraction to calculate the percentage of RTL text in the document is swapped (i.e. it was calculating the inverse of the percentage).

Due to this bug, all bidi strings passed will be tagged as predominantly RTL, despite meeting the requirements listed.

### CODE REVIEW

**Comment by brendandahl** [comment]
Looks good, but do you have a unit test you can add so we don't regress this?

**Comment by Skaty** [comment]
Do you want me to add the unit test just for this first?

I have been doing up the basic unit tests for bidi, but I feel that this needs to be address as it's a breaking bug.

**Comment by yurydelendik** [comment]
> Do you want me to add the unit test just for this first?

> I have been doing up the basic unit tests for bidi, but I feel that this needs to be address as it's a breaking bug.

Having tests will help to avoid breaking your fix in the future. Unit tests will be great to have.

**Comment by yurydelendik** [comment]
btw, bidi.js is one of the two core files that don't have unit tests (see #7261).

**Comment by Skaty** [comment]
@yurydelendik 

I agree with that. I'm sorry if the question was not clear. I was resolving #7261 for bidi.js, but I found this particular issue that seems to break.

So, should I add the full suite of unit tests that was meant to resolve #7261, or as an interim, just tests to ensure that this particular logic (percentage of RTL text) doesn't regress?

**Comment by brendandahl** [comment]
> So, should I add the full suite of unit tests that was meant to resolve #7261, or as an interim, just tests to ensure that this particular logic (percentage of RTL text) doesn't regress?

The single test is fine as a starting point. Besides regressions, it helps prove the validity of the patch.

**Comment by Skaty** [comment]
Unit test for this patch has been added.

**Review by yurydelendik — APPROVED** [review]
The tests looks good. Can you check if you can add bidi.js to the test/unit/clitools.js list?

**Comment by Skaty** [comment]
@yurydelendik Do you mean test/unit/clitests.json?

**Comment by yurydelendik** [comment]
> Do you mean test/unit/clitests.json?

Yes.

**Comment by Skaty** [comment]
@yurydelendik Done.

**Comment by yurydelendik** [comment]
Thank you for the patch

**Pull request merged**
