### PR TITLE
Ensure same origin in ?file= parameter

### PR DESCRIPTION
**Pull request by avivkeller**
This PR prevents a `history.replaceState` error that occurs with a query like `?file=/test`, by ensuring the origin will always be for the extension.

### CODE REVIEW

**Review by Snuffleupagus — COMMENTED** [review]
Please remember to write a proper *commit message*, since `Update chromecom.js` is fairly non-descriptive; please note https://github.com/mozilla/pdf.js/wiki/Squashing-Commits when updating the patch.

**Comment by RedYetiDev** [comment]
I amended the commit with a new name: "Update chromecom.js to ensure same origin, preventing history.replaceState from throwing an error"

**Comment by RedYetiDev** [comment]
Hi Team, any update from @Rob--W on this? Take your time, but I'm just checking in

**Comment by Rob--W** [comment]
I missed the previous notification, thanks for the ping.

**Comment by Rob--W** [comment]
Do you have an example or test case that demonstrates the necessity of this change?

The URL starts with `/` so I would expect it to resolve to the current origin.

Are you using `<base href>` anywhere?

**Comment by RedYetiDev** [comment]
In the code, when a user-provided `<filepath>` is used, it undergoes concatenation as follows: `/<filepath>`. If `<filepath>` is `/www.google.com`, the concatenation results in `//www.google.com`. This `//` triggers a protocol resolution, transforming the URL into `chrome://www.google.com`. While this doesn't present a security threat, it does lead to the failure of the `history.replaceState` function, thereby preventing the extension from properly loading the URL.

**Comment by Rob--W** [comment]
> In the code, when a user-provided `<filepath>` is used, it undergoes concatenation as follows: `/<filepath>`. If `<filepath>` is `/www.google.com`, the concatenation results in `//www.google.com`.

In the extension use case, `<filepath>` cannot be `/www.google.com`, because the extension only routes prefixes that look like `/scheme:`, such as `/https://example.com/file.pdf`. This is due to https://github.com/mozilla/pdf.js/blob/master/extensions/chromium/manifest.json#L60-L68

Of course, the user or web page could directly try to navigate to the html. That is not a supported use case. I would not mind throwing an error in that case.

> This `//` triggers a protocol resolution, transforming the URL into `chrome://www.google.com`.

How did you get a `chrome:` scheme? Extensions ordinarily have a `chrome-extension:` scheme in Chrome.

> While this doesn't present a security threat, it does lead to the failure of the `history.replaceState` function, thereby preventing the extension from properly loading the URL.

The described scenario is unsupported. Even if `history.replaceState` were to succeed, the viewer would still fail to load the URL because the browser would not allow it.

**Comment by RedYetiDev** [comment]
Yes, right, sorry, `chrome-extension://`. I figured this PR would help by allowing this edge case through, but maybe that isn't the best solution, we can close this if you'd like?

**Comment by Rob--W** [comment]
> Yes, right, sorry, `chrome-extension://`. I figured this PR would help by allowing this edge case through, but maybe that isn't the best solution, we can close this if you'd like?

The PDF viewer extension does not bundle a pdf file, so there is no point in allowing relative URLs through.

Let's close this PR.

**Pull request closed without merging**
