### PR TITLE
Re-implement `PDFHistory`

### PR DESCRIPTION
**Pull request by Snuffleupagus**
_Please refer to the individual commit messages._

@timvandermeij I know that this is a large PR, but would you be willing to try and review it?
I'd suggest that you completely ignore the combined diff, and instead look at each patch on its own.

Also, we should make sure this is landed at beginning of a development-cycle ([see future dates](https://wiki.mozilla.org/RapidRelease/Calendar#Future_branch_dates)), to allow more time for follow-ups.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Two things I'm wondering:

1. Does this also address the concerns in #6200, as that PR also seems to work on the PDF history code?
2. Maybe this is a long shot, but would it be possible to write unit tests for this PR? We do not need complete coverage, but some unit tests on the basic functionality would be nice to have. What I was thinking about is opening a PDF, changing the page programmatically and checking the history state to make sure that it is updated. Do you think that that would be possible, or would that be very hard and should we keep that for later?

**Comment by Snuffleupagus** [comment]
> Does this also address the concerns in #6200, as that PR also works on the PDF history code?

Yes, I believe that it does (it works in my testing).

> Maybe this is a long shot, but would it be possible to write unit tests for this PR?

I though about that, but it seemed quite difficult to add meaningful tests without a UI testing framework in place.

**Comment by timvandermeij** [comment]
@Rob--W Could you check if this PR solves the issue you adress with #6200 ? If so, we can probably close that PR and continue here as this is a more complete rewrite of the history code.

@Snuffleupagus Good, let's keep that for later then. I had hoped it would be easy, but indeed it can be hard without such a framework.

**Comment by Rob--W** [comment]
@timvandermeij I haven't tested this code yet, but I looked through it.

The current history logic (insofar relevant for #6200) is 1) going back in history, 2) rewriting the history state and 3) going forward in history. Step 1, 2 and 3 are currently exected right after each other, while in Chrome it is necessary to wait a little bit between each step. This was fixed by #6200.
I could be mistaken, but at the first sight it seems that this PR does not use navigate-back-rewrite-and-navigate-forwards logic, and instead just keeps replacing / pushing new items in the history. If that is true, and this PR gets merged, then #6200 becomes obsolete.

@Snuffleupagus Could you confirm whether my assessment is correct?

**Comment by Rob--W** [comment]
What's the status of this PR? https://github.com/mozilla/pdf.js/pull/6200#issuecomment-121197353

> @Snuffleupagus 
> Actually, if you're willing to live with this issue for just a little while longer, it might actually be fixed "for free" by the PDFHistory rewrite that I'm working on.

This "a little while longer" is already taking over 2 months, and I'd like to publish the Chrome extension with a fix to the problem. If you expect this to take much more time, could #6200 be merged in the meanwhole, to improve the usability of the location bar in Chrome/Opera/Safari?

**Comment by Snuffleupagus** [comment]
@Rob--W Apparently I forgot to answer your question, my apologies!

> [From https://github.com/mozilla/pdf.js/pull/6272#issuecomment-124991481] Could you confirm whether my assessment is correct?

Yes, that would be correct!
The current code is not actually working as intended, and the implementation is also fairly complicated. Since changing the hash of a loaded document could be considered somewhat of an edge-case, this PR simplifies the implementation to *not* try to go back (and forward) and modify the previous history entry when the hash is changed by the user.

> This "a little while longer" is already taking over 2 months, [...]

I agree that is unfortunate; but given that this is a pretty large PR, I don't think @timvandermeij has had time to review it yet.

> If you expect this to take much more time, could #6200 be merged in the meanwhole, to improve the usability of the location bar in Chrome/Opera/Safari?

In my testing, PR #6200 unfortunately seem to introduce other issues; hence I'm not willing to merge it into `master` in its current form. (And I'd rather not spend a whole lot more time testing it, since I still hope that we'll get rid of the code in question.)

**Comment by Rob--W** [comment]
> In my testing, PR #6200 unfortunately seem to introduce other issues; hence I'm not willing to merge it into master in its current form. (And I'd rather not spend a whole lot more time testing it, since I still hope that we'll get rid of the code in question.)

I'm not aware of any regressions in #6200. What are those?

**Comment by timvandermeij** [comment]
I currently do not have any time to properly review this patch, unfortunately. Perhaps @brendandahl can review this?

**Comment by timvandermeij** [comment]
@Snuffleupagus Could you rebase this patch? Unfortunately I'm still lacking enough time to properly review this, but given the current wave of reviews, probably either Yury or Brendan can take a look at this. I think the patch is too good to leave it laying around!

**Comment by fbender** [comment]
@yurydelendik Do you have time to review this?

**Comment by timvandermeij** [comment]
@Snuffleupagus Is there any way in which we can split this PR into multiple smaller PRs? I'm willing to review this, but it would be much easier (and less error-prone) if it were split in smaller chunks? For example create a PR for the second commit about `getDestinationHash` (as it seems that that is rather independent of the `PDFHistory` rewrite) and instead of ripping everything out and rewriting it all, incrementally improve the current situation, for example by first creating a PR to streamline the event listener binding from https://github.com/Snuffleupagus/pdf.js/commit/8704aa60fc4ef177bca2bbbfdd6315c10f108804#diff-3b4ebbe223f93c9123a754b4845844e7R456.

It could be somewhat similar to what I did for the initial annotation layer rewrite. I tried to do everything at once, but soon came to the conclusion that is was easier and less error-prone when doing it in smaller parts. It will help to get this functionality landed sooner. What do you think?

**Comment by Snuffleupagus** [comment]
> Is there any way in which we can split this PR into multiple smaller PRs?

I really tried that when writing the code, but in the end I didn't do so because of the *very* high risk of introducing severely broken intermediate states. (Note that the current implementation suffers from many issues.)

> For example create a PR for the second commit about getDestinationHash (as it seems that that is rather independent of the PDFHistory rewrite)

I'm not totally confident that that wouldn't break the current `PDFhistory` (even more than it currently is), but I'll try to look into that since it should be an easy win if it's possible.

> It will help to get this functionality landed sooner. What do you think?

I totally understand this, but I just don't know how I'd be able to re-factor `PDFHistory` in steps :-(
The new implementation makes fever assumptions about the state, in order to prevent many of the issues with the current code, so I'm simply not sure if/how this would work.

I'll make another attempt to see if this can be split into multiple PRs, but I cannot promise that it will work!

**Comment by timvandermeij** [comment]
Fortunately PR #7341 has been merged, so if we can rebase this PR onto the current master it should be more manageable in terms of size and complexity.

**Comment by Snuffleupagus** [comment]
Note that I closed this PR, since it's very badly bit-rotten by now. I'm currently testing https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:rewrite-pdf-history, and if all goes will submit that soon.

**Pull request closed without merging**
