### PR TITLE
Increase color stop index for transparent edges.

### LINKED ISSUE #9664: Specific pdf file is not rendered correctly in Chrome
Attach (recommended) or Link to PDF file here:
[AMS2921833.pdf](https://github.com/mozilla/pdf.js/files/1907470/AMS2921833.pdf)

Configuration:
- Web browser and its version: Google Chrome Version 65.0.3325.181 (Official Build) (64-bit);
- Operating system and its version: Windows 10 x64 1709;
- PDF.js version: pdfjs-dist 2.0.491;
- Is a browser extension: no;

Steps to reproduce the problem:
1. Upload attached file.
2. Data in grid on first page is not rendered.

What is the expected behavior?
expected

What went wrong?
actual

### PR DESCRIPTION
**Pull request by brendandahl**
The current number is too small for chrome and causes issues.

Fixes #9664

### CODE REVIEW

**Comment by brendandahl** [comment]
If anyone wants to play with this further...try out https://codepen.io/anon/pen/xJQXRJ and adjust the 2nd and 2nd to last color stops.

**Comment by brendandahl** [comment]
I was talking with Patrick and he mentioned the values are probably getting packed into a byte hence 254/255 = 0.996 so above .996 gets rounded to 1.

**Comment by brendandahl** [comment]
We should also test if this is actually an issue on the bots since they may not be using skia gl.

**Comment by timvandermeij** [comment]
@brendandahl I notice some small regressions in the reference test results. Do you want to continue this PR or should it be revisited?

**Comment by timvandermeij** [comment]
Closing since the underlying ticket is resolved by an upstream fix.

**Pull request closed without merging**
