### PR TITLE
Add --testfilter and -t flags

### PR DESCRIPTION
**Pull request by Rob--W**
- Add a `--testfilter` (`-t`) flag to run a specific test.
- Resolve the browser path to a full path before trying to launch the browser.
- Add an example to the help message, to quickly get started with running tests.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Perhaps the bot failures are related to the first commit and the actual web browsers are not found anymore?

**Comment by Rob--W** [comment]
@timvandermeij

I forgot to test without the `-t` flag. When this was omitted, the driver passed `undefined` to the test runner, which causes a runtime error because this value cannot be parsed as JSON. I've fixed the issue, try again.

**Comment by timvandermeij** [comment]
@Rob--W This patch needs a rebase. Could you rebase it onto the current master?

**Comment by Rob--W** [comment]
@timvandermeij Rebased.

**Comment by timvandermeij** [comment]
Looks good with the comments above addressed.

**Comment by timvandermeij** [comment]
Nice work!

**Pull request merged**
