### PR TITLE
Pdfjs fix

### PR DESCRIPTION
**Pull request by arnaudschlupp**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
It appears that this PR just contains various test and customization commits, so I'm assuming that it was opened against the `mozilla/pdf.js` repo by mistake. Hence I'm closing this as invalid.

**Comment by Shahbaz1990** [comment]
how can i edit the viewer.js is there any possiblity to change the js what
i want to.
i have change some things in the pdf text highlighting.
can u plz tell me.









*Regards,*

*Shahebazuddin Khan*
*PHP/Wordpress Web developer*
*Email:- shahbazuddinkha@gmail.com <shahbazuddinkha@gmail.com>*

**Comment by Shahbaz1990** [comment]
when i find the keyword or text in pdf file how to edit the font size and
anything in pdf text.
plz let me know if u anything else about it.









*Regards,*

*Shahebazuddin Khan*
*PHP/Wordpress Web developer*
*Email:- shahbazuddinkha@gmail.com <shahbazuddinkha@gmail.com>*

**Comment by Shahbaz1990** [comment]
when i highlight the searchable text it will highlight only the background
color.but, i want to highlight the text it's font size padding.is there any
possible to do this plz let me knw..









*Regards,*

*Shahebazuddin Khan*
*PHP/Wordpress Web developer*
*Email:- shahbazuddinkha@gmail.com <shahbazuddinkha@gmail.com>*

**Pull request closed without merging**
