### PR TITLE
parser: dereference stream 'Length' field

### PR DESCRIPTION
**Pull request by mcorb**
Check indirect values as we do elsewhere in the parser for internal
consistency.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/pdf.js/6045)

### CODE REVIEW

**Comment by timvandermeij** [comment]
Do you have a PDF that particularly benefits from this change, or is it just a general improvement?

**Comment by mcorb** [comment]
It's purely a cleanup from visual inspection that's been in our internal branch for a while, but it seems "correct" so I went ahead and submitted this pull request.

In practice the fix will just return a NullStream more consistently in all cases where a zero length is known, which likely has no perceptible impact whatsoever AFAICT but I figure we might as well do the check right to avoid developer confusion.

**Comment by yurydelendik** [comment]
Could you add a simple test case?

**Comment by timvandermeij** [comment]
Should be good when a simple (unit) test is added.

**Comment by timvandermeij** [comment]
This patch became obsolete by #6411, so I'm closing this one.

**Pull request closed without merging**
