### PR TITLE
Fix tiling pattern with smask.

### LINKED ISSUE #8565: Missing gradient
Link to PDF file (or attach file here):
[gradient invisible pdfjs.pdf](https://github.com/mozilla/pdf.js/files/1096729/gradient.invisible.pdfjs.pdf)

Configuration:
- Web browser and its version: 59.0.3071.109
- Operating system and its version: Windows 10
- PDF.js version: 1.8.480
- Is an extension: No

Steps to reproduce the problem:
1. Open the file in Adobe Reader or Google Chrome
2. Open the file in PDFjs online viewer
3. Compare

What is the expected behavior? (add screenshot)
- There is an orange radial gradient, from opacity 0 at the center to opacity 1 at the page bound

image

What went wrong? (add screenshot)
- The gradient is completely missing

image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://mozilla.github.io/pdf.js/web/viewer.html

Description of the file:
An opaque orange gradient is masked with a mask. The mask's group contains a rectangle filled with a pattern. The pattern contains an other rectangle filled with a greyscale gradient from black to white. All the rectangles, patterns & groups have the same size as the page (400x400pt).

### PR DESCRIPTION
**Pull request by brendandahl**
After drawing a tiling pattern we were not calling
endDrawing, which handles compositing any
active smasks.

Fixes #8565.

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
r=me with passing tests, thank you!

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thanks!

/botio makeref

**Pull request merged**
