### PR TITLE
An option is missing for last versions of worker-loader to use pdf.js with webpack

### LINKED ISSUE #12813: webpack instructions can't work with last worker-loader versions
I followed the recommendations [given here](https://github.com/mozilla/pdf.js/blob/master/examples/webpack/README.md) to use pdf.js `2.6.347` with webpack.

It mention that:
> ...(configuring worker-loader is not necessary; just installing it is sufficient).

It's no longer the case with the last version of `worker-loader` (`v3.0.7`), and since the version [v3.0.0](https://github.com/webpack-contrib/worker-loader/releases/tag/v3.0.0) I believe, due to a breaking change in this package:

image

The `filename` option now [default to [name].worker.js](https://github.com/webpack-contrib/worker-loader#filename), which cause webpack to generate a `pdf.worker.worker.js` file instead of the expected `pdf.worker.js`.

To make webpack generate the proper file, I had to update [a line inside /external/dist/webpack.js](https://github.com/mozilla/pdf.js/blob/master/external/dist/webpack.js#L19) as mention bellow:

```javascript
var PdfjsWorker = require("worker-loader?esModule=false&filename=[name].js!pdfjs-dist/build/pdf.worker.js");
```
(I added `&filename=[name].js` option, for `worker-loader` not to add its new suffix)

### PR DESCRIPTION
**Pull request by fdaveine**
Fix #12813

### CODE REVIEW

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
These changes are small enough, and sufficiently connected, that a *single* commit will suffice here; please see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits

**Comment by fdaveine** [comment]
@Snuffleupagus fixed

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
The commit message contains "work-loader" (more than once), which looks like a typo; please fix that as well.

**Comment by fdaveine** [comment]
@Snuffleupagus fixed too :+1:

**Comment by Snuffleupagus** [comment]
> fixed too +1

Not quite, since you *still* have the incorrect package name in your commit message :-)

**Comment by fdaveine** [comment]
> Not quite, since you _still_ have the incorrect package name in your commit message :-)

Sorry I misread your previous comment, should be fixed now...

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for your contribution!

**Pull request merged**
