### PR TITLE
Fix regressions affecting both the 'pagemode' hash parameter and certain 'namedaction' types (PR 5971)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
_Please refer to the individual commit messages._

Both these regressions are from PR #5971.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Looks good to me with the nit addressed. I'm leaving the final review for @yurydelendik as he was the author of the PR that caused the regressions.

**Comment by Snuffleupagus** [comment]
I removed the unnecessary newline; I also made a couple of small improvements in the first commit (e.g. better comments for the `bookmarks`/`outline` case).

/botio-windows preview

**Comment by timvandermeij** [comment]
Nice patch, thank you!

**Pull request merged**
