### PR TITLE
Update dependencies and translations to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**
The major version bumps don't seem to contain any breaking changes for us; please refer to:

- `eslint-plugin-unicorn`: https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v44.0.0
- `jstransformer-markdown-it`: https://github.com/jstransformers/jstransformer-markdown-it/compare/2.1.0...v3.0.0
- `puppeteer`: https://github.com/puppeteer/puppeteer/releases
- `vinyl`: https://github.com/gulpjs/vinyl/releases/tag/v3.0.0

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
In addition to existing intermittent integration-test failures, it seems that this PR introduces one *new* problem on both bots (see excerpt below). I'd guess that the Puppeteer update might be somehow responsible, and thus require the test(s) to be tweaked.
```
1) Interaction in 160F-2019.pdf must check that first text field has focus
  Message:
[31m    In firefox: Expected null to equal '401R'.[0m
  Stack:
        at <Jasmine>
        at C:\pdfjs\botio-files-pdfjs\private\f58403b5abb3898\test\integration\scripting_spec.js:60:55
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Promise.all (index 0)
```

**Comment by timvandermeij** [comment]
I'll have a look at that. Sadly the integration tests are quite flaky lately :-/

**Comment by Snuffleupagus** [comment]
It might be too simplistic, and possibly not robust enough, but would it work if we simply delayed trying to find the active element a little bit? Basically change https://github.com/mozilla/pdf.js/blob/a93c01ae6a455c879603c69be7f888eea334c916/test/integration/scripting_spec.js#L56-L59 to something like:
```javascript
const id = await page.evaluate(async () => {
  await new Promise(resolve => setTimeout(resolve, 0));

  const element = window.document.activeElement; 
  return element.getAttribute("data-element-id");
}); 
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with passing tests; thank you!

**Pull request merged**
