### PR TITLE
Update Puppeteer to version 7

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Please see:
 - https://github.com/puppeteer/puppeteer/releases/tag/v7.0.1
 - https://github.com/puppeteer/puppeteer/releases/tag/v7.0.0

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you!

/botio makeref

**Comment by Snuffleupagus** [comment]
Let's see if that reduced the intermittent failures...

/botio tset

**Comment by timvandermeij** [comment]
Nice, that does look _a lot_ better on Linux!

**Pull request merged**
