### PR TITLE
Disables Font Loading API for Firefox.

### PR DESCRIPTION
**Pull request by yurydelendik**
Too many bugs opened. Let's introduce a workaround while waiting on proper fix:
- [x] create upstream issue minimal example that demonstrates the problem
- [x] disable only for printing?

### CODE REVIEW

**Comment by yurydelendik** [comment]
@timvandermeij can you verify on ff (and if we didn't regress it for other browsers)?

/botio-linux preview

**Comment by yurydelendik** [comment]
> create upstream issue minimal example that demonstrate the problem

mozPrintCallback never fully worked. Plus filed https://bugzilla.mozilla.org/show_bug.cgi?id=1308259 (it also contains the [https://bug1308259.bmoattachments.org/attachment.cgi?id=8798493](test case))
 
> disable only for printing?

We are caching fonts and (per test case above) we need to cache fonts, so keeping it disabled for canvas as well.

**Comment by timvandermeij** [comment]
Thank you for fixing this!

**Pull request merged**
