### PR TITLE
Update quickjs to revision 2788d71e823b522b178db3b3660ce93689534e6d

### PR DESCRIPTION
**Pull request by calixteman**
- The date parser in quickjs is not optimal so use the navigator one.

### CODE REVIEW

**Comment by calixteman** [comment]
I noticed some errors with date parsing so I patched our quickjs built to use the navigator date parser:
https://github.com/mozilla/pdf.js.quickjs/commit/de3bf958065e654f6defd601f3cb0cc78d8d2515

**Review by Snuffleupagus — APPROVED** [review]
r=me (essentially rubber-stamping the changes).

However, there's a couple of alerts here: https://github.com/mozilla/pdf.js/pull/14863/checks?check_run_id=6247493331
Are some of those possible to fix, perhaps by patching/updating the build-process in https://github.com/mozilla/pdf.js.quickjs, or should we simply just ignore them?

**Comment by calixteman** [comment]
I don't know what to do to remove this warnings.
The compilation command is:
https://github.com/mozilla/pdf.js.quickjs/blob/main/compile.sh

If you've any ideas, then I take, else I think we should ignore them.
If you're interested to hack on this file, if I remember correctly I didn't manage to run that stuff in a windows shell.
But in installing docker on Windows and an Ubuntu in using WSL, then it works nice (just run `node build.js --compile --output /tmp/foo` in an Ubuntu shell).

**Comment by Snuffleupagus** [comment]
Given that the alerts don't suggest any security problems, but rather just mention unused code and missing semicolons, it's likely not meaningful to spend a lot of time/effort on "fixing" this (especially when none of this code is being used in Firefox).

**Pull request merged**
