### PR TITLE
Extend `getNonStdFontMap` for non-embedded versions of the ItcSymbol font (issue 11532)

### LINKED ISSUE #11532: Incorrect font rendering
Attach (recommended) or Link to PDF file here: [ar99.pdf](https://github.com/mozilla/pdf.js/files/7086733/ar99.pdf)
https://www.dallasfed.org/fed/~/media/documents/fed/annual/1999/ar99.pdf 

Configuration:
- Web browser and its version: Firefox Browser 72.0.2 (64-bit)
- Operating system and its version: Windows 10 Enterprise version 1809
- PDF.js version: 2.4.152
- Is a browser extension:

Steps to reproduce the problem:
1. Open URL
2. Observe

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Despite its name, the fonts in ItcSymbol-family are "regular" fonts and not Symbol ones. However, given that the font name contains the word "Symbol" we ended up picking the wrong code-path in the `Font.fallbackToSystemFont`-method.

*Please note:* While this patch ensures that the text becomes readable, by falling back a standard font, the rendering will obviously not be perfect. However, that's the PDF generators "fault" since non-embedded fonts cannot be guaranteed to render correctly in all environments.

Fixes #11532

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
*I didn't really have time to create a reduced test-case right now, but figured that submitting the patch with a linked test-case was better than the issue remaining open even longer; sorry about that!*

/botio-linux preview

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good! I did find the old rendering amusing though ;-)

**Pull request merged**
