### PR TITLE
Update highlight.js fix deserialize typo error

### PR DESCRIPTION
**Pull request by jarklee**

### CODE REVIEW

**Comment by timvandermeij** [comment]
Given that commit https://github.com/mozilla/pdf.js/commit/a62ceedb692f33bf9d7b25e2ca1a9fe9d25f3c84 contains test cases, do you know why this didn't fail those test cases if the code is in fact incorrect? In that case it'd be great to add an extra test case here because that might indicate missing test coverage.

**Comment by jarklee** [comment]
> Given that commit [a62ceed](https://github.com/mozilla/pdf.js/commit/a62ceedb692f33bf9d7b25e2ca1a9fe9d25f3c84) contains test cases, do you know why this didn't fail those test cases if the code is in fact incorrect? In that case it'd be great to add an extra test case here because that might indicate missing test coverage.

@timvandermeij Thank you for your consideration. I checked the commit you mentioned and found that the test case does not cover the deserialize function. Therefore, there is no issue report at that time.
If you wish, I'll create the extra test for the deserialize function.

**Comment by timvandermeij** [comment]
Yes, if you could include a test for the deserialization logic in this commit that'd ensure that it can't accidentally regress in the future; thank you.

**Comment by jarklee** [comment]
> Yes, if you could include a test for the deserialization logic in this commit that'd ensure that it can't accidentally regress in the future; thank you.

I added the test case to coverage for quadPoints deserialize, please check.

**Review by calixteman — CHANGES_REQUESTED** [review]
You must explain why there is a bug.
So you can provide either a pdf or a clear explanation on why it's a bug, but we need to have something to just consider this patch.

**Comment by jarklee** [comment]
> You must explain why there is a bug. So you can provide either a pdf or a clear explanation on why it's a bug, but we need to have something to just consider this patch.

@calixteman yeah, I see. I tested with both before and after my fixes. It works just fine with exporting and printing the PDF. 
The case I face here is using the serialized logic to store only the annotation outside of PDF (I have some reason to do that) and because lack of synchronization between serialized and deserialized logic within the highlight annotation editor, the annotation failed to show.

Here is my proof of steps
```javascript
const { map } = PDFViewerApplication.pdfDocument.annotationStorage.serializable;
const vals = Array.from(map.values());

const layer =  PDFViewerApplication.pdfViewer.getPageView(0).annotationEditorLayer.annotationEditorLayer;
const editor = await layer.deserialize(vals[0]);
layer.add(editor); 
// Highlight will not show, if you check the #boxes field, you will see that the height value gets a negative value.
// The y position will not correct either
```

**Pull request closed without merging**
