### PR TITLE
Move symbolic font glyphs to private use area if they don't have unicode mappings (issue 2594, bug 789074, bug 865644)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This is a tentative patch, which builds upon PR #7482 (that commit is included here with the correct author), that attempts to address issue #2594, [bug 789074](https://bugzilla.mozilla.org/show_bug.cgi?id=789074), [bug 865644](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=865644).

According to https://github.com/mozilla/pdf.js/issues/2594#issuecomment-247970930 and https://github.com/mozilla/pdf.js/issues/2594#issuecomment-253557318 it seems like this kind of simple hack might actually work, and I'm opening the PR to be able to run tests on (especially) the Linux bot.

### CODE REVIEW

**Comment by timvandermeij** [comment]
I checked most of the test failures (not all of them), but those looked like improvements to me. It has been reported that this patch fixes the original issue.

/cc @yurydelendik or @brendandahl for review

**Comment by brendandahl** [comment]
It looks like we're moving a lot of glyphs to the private use area, even ones that probably shouldn't be.
Some random pdf's I looked at:
issue5501.pdf
before patch
```
fonts.js:920 originalCharCode=65 (A)
fonts.js:931 unicode=         65 (A)
fonts.js:920 originalCharCode=69 (E)
fonts.js:931 unicode=         69 (E)
```
after patch

```
fonts.js:920 originalCharCode=65 (A)
fonts.js:932 unicode=         65 (A)
fonts.js:958 remapping to=    57380 ()
fonts.js:920 originalCharCode=69 (E)
fonts.js:932 unicode=         69 (E)
fonts.js:958 remapping to=    57381 ()
```

artofwar.pdf

```
originalCharCode=65 (A)
fonts.js:933 unicode=         65 (A)
fonts.js:921 originalCharCode=66 (B)
fonts.js:933 unicode=         66 (B)
```

after

```
originalCharCode=65 (A)
fonts.js:933 unicode=         65 (A)
fonts.js:959 remapping to=    57359 ()
fonts.js:921 originalCharCode=66 (B)
fonts.js:933 unicode=         66 (B)
fonts.js:959 remapping to=    57360 ()
```

Also, see my comment in https://github.com/mozilla/pdf.js/issues/2594#issuecomment-254289210

**Comment by yurydelendik** [comment]
my 2¢: we don't have complete charCode->glyphNames mapping (based on encoding and differences). I'm thinking we shall address this first and after that adjustMapping will use glyphNames/unicode to determine if char code is at right location and will build FreeType2 autofit-friendly toFontChar?

**Comment by Snuffleupagus** [comment]
*The last version of this PR is in all likelihood my last attempt at fixing #2594, since it's an issue that I'm personally not affected by.*

Now, besides the original patch by @brendandahl which already fixes the majority of the problem, I'm also amending `src/core/glyphlist.js` with the (common) names used in AMSmath Type1 (La)TeX fonts.
This is based on lists of TeX glyph names, and reasonable Unicode values, that I found while searching the web. Hopefully this should be enough to avoid mapping these math symbols to regular characters, thus preventing FreeType from using the wrong glyphs when computing hint values, and should also improve text-selection at the same time.

If this is a reasonable approach, we probably need a couple of Linux users (currently affected by the issue) to test this to ensure that it's in fact a sufficient solution.

**Comment by brendandahl** [comment]
r+ pending confirmation of fix

**Comment by timvandermeij** [comment]
The fix has been confirmed, so I'll take care of landing this.

**Comment by timvandermeij** [comment]
Thank you for the patch!

**Pull request merged**
