### PR TITLE
XFA - Remove empty pages

### LINKED ISSUE #13583: XFA DHL Form contains extra, blank pages
Attach (recommended) or Link to PDF file here:
https://www.dhl.com/content/dam/downloads/g0/express/emailship_page/globalpage/dhl_emailship_pdfclient_my_en.pdf

- Web browser and its version: Firefox 89.0.1
- Operating system and its version: Windows 10 10.0.19043.1052
- PDF.js version: commit 5d251a3a3e7bfaa8fbfa07f0b7f9901eb3f999d9
- Is a browser extension: No

Steps to reproduce the problem:
1. Enable XFA support
2. Open form

What is the expected behavior? (add screenshot)
First page loads 
image

What went wrong? (add screenshot)
Extra blank pages load (pages 1, 3, 4, 7, 8)

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix #13583;
  - because hidden subform and breakBefore some pages can be empty so remove them;
  - don't fail when there is horizontal overflow (except in lr-tb);
  - fix a typo in radial gradient first argument.

### CODE REVIEW

**Review by marco-c — DISMISSED** [review]
Can you ensure the reftests are good?

**Comment by calixteman** [comment]
There is a regression with `imm1344e.pdf`.

**Comment by calixteman** [comment]
The differences for `xfa_bug1716816` are expected.

**Review by marco-c — DISMISSED** [review]

**Review by marco-c — APPROVED** [review]

**Pull request merged**
