### PR TITLE
Enable the `no-unsafe-finally`/`no-octal`/`no-useless-call` ESLint rules

### PR DESCRIPTION
**Pull request by Snuffleupagus**
http://eslint.org/docs/rules/no-unsafe-finally, there's just one violation which in this case can actually be ignored since there's nothing `return`ed there.
http://eslint.org/docs/rules/no-octal, there're no violations in the code-base.
http://eslint.org/docs/rules/no-useless-call, there's just one violation that needs to be fixed.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Thank you for your continuous efforts to improve linting!

**Comment by Snuffleupagus** [comment]
@timvandermeij Thanks for reviewing/merging all of these ESLint PRs!

**Pull request merged**
