### PR TITLE
[api-minor] Decode all JPEG images with the built-in PDF.js decoder in `src/core/jpg.js`

### LINKED ISSUE #7041: Poorly rendered image quality
Hi all,

I have tried using the latest 1.3.91 version for this. All I did was modify the viewer.js to point to my own PDF. This is the result using the fresh out of the box viewer.html :
image

The left one is the actual PDF, and the right one is rendered by viewer.html. Same thing in IE and Chrome. I did not try it in FF because my users use either IE or Chrome. 

I've tried searching everywhere I could and have been unsuccessful in finding a solution to this. Here's the PDF file from the picture. 
[.0002.pdf](https://github.com/mozilla/pdf.js/files/150290/default.0002.pdf)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please refer to the individual commit messages.*

Fixes https://github.com/mozilla/pdf.js/pull/6984#issuecomment-184778220
Fixes #7041

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Sign; oh great, since Firefox was update to the Nightly branch (during the switch to Puppeteer) the Windows bot is now seems to be affected by https://bugzilla.mozilla.org/show_bug.cgi?id=1607630

**Comment by Snuffleupagus** [comment]
Sigh; oh great, since Firefox was update to the Nightly branch (during the switch to Puppeteer) the Windows bot is now seems to be affected by https://bugzilla.mozilla.org/show_bug.cgi?id=1607630

**Comment by Snuffleupagus** [comment]
Sigh; oh great, since Firefox was update to the Nightly branch (during the switch to Puppeteer) the Windows bot now seem to be affected by https://bugzilla.mozilla.org/show_bug.cgi?id=1607630

**Comment by timvandermeij** [comment]
Oof, that's a nasty bug. I can confirm I have not seen such corruption on Linux so far. On the one hand I'm happy we're finding it now so we can bump the upstream issue so it hopefully won't reach the stable release, but on the other hand it does mess with our tests now. We should see how it goes; otherwise there are ways to tell Puppeteer to use another version than the built-in versions.

**Comment by Snuffleupagus** [comment]
> [,..] otherwise there are ways to tell Puppeteer to use another version than the built-in versions.

If all the intermittent font rendering failures, which are not related to this patch, is blocking reviewing/landing of this patch then going back to Firefox 76 for the time being would be nice!

**Comment by timvandermeij** [comment]
The bug is fixed upstream, but I'm not sure if it made it to today's Nightly yet. Let's see...

/botio test

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you! This greatly simplifies the code and should improve performance.

/botio makeref

**Pull request merged**
