### PR TITLE
Extend `getNonStdFontMap` for non-embedded Impact fonts (bug 1365930)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
According to https://en.wikipedia.org/wiki/Impact_(typeface) this font should be available on all current versions of Windows, and with the recently added font-substitution we should actually be able to render it correctly (at least on Windows).

### CODE REVIEW

**Comment by marco-c** [comment]
Do we need to do this font by font?

**Comment by Snuffleupagus** [comment]
> Do we need to do this font by font?

Not necessarily, since it depends on the exact font-type used in the PDF document itself.
In this particular case we're dealing with a non-embedded `CIDFontType2` font, and then we need to add a fallback-entry to be able to build a usable `toFontChar`-map. Had it been a "simpler" font, e.g. `Type1` or `TrueType`, I believe it'd have worked as-is.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good, and renders better than Okular now which shows a square for the 7 glyph. Thanks!

/botio makeref

**Pull request merged**
