### PR TITLE
Fix transformations when painting image masks and tiling patterns.

### LINKED ISSUE #1344: Blurred images
PDF.js displays blurry plots in PDF documents, e.g.

http://arxiv.org/pdf/1202.5344v1.pdf

When viewed in Chrome or Adobe Acrobat all the plots show sharp-edged squares. When viewed in Preview or PDF.js, all the squares show as blurry pixelated blobs.

### LINKED ISSUE #6297: Pattern not rendered
https://issues.apache.org/jira/secure/attachment/12744264/gs-bugzilla690297.pdf
Tiffany, Kelly and Doris (at the bottom) are not rendered. They are all in patterns, the other ladies (Paula, Denise and Neita) are not.

We at PDFBox do also have a problem with the same ladies, but a different one, see
https://issues.apache.org/jira/browse/PDFBOX-2864

See also
https://issues.apache.org/jira/browse/PDFBOX-1958
https://issues.apache.org/jira/secure/attachment/12632189/cinnebar.pdf
https://issues.apache.org/jira/secure/attachment/12631470/PATTYP2.pdf
The problem is to apply a stencil to a pattern color.

### LINKED ISSUE #13441: Backgroundimage is not rendered
Attach (recommended) or Link to PDF file here:
[backgroundimage_not_visible_anonymisiert.pdf](https://github.com/mozilla/pdf.js/files/6544725/backgroundimage_not_visible_anonymisiert.pdf)

Configuration:
- Web browser and its version: Chrome Version 90.0.4430.212 (Offizieller Build) (x86_64)
- Operating system and its version: Windows 10, MacOs BigSur
- PDF.js version: 2.5.207
- Is a browser extension: no

Steps to reproduce the problem:
1. open the document in demo viewer.js
2.

What is the expected behavior? (add screenshot)
The backgroundimage gets rendered like in Acrobat Reader
Bildschirmfoto 2021-05-26 um 09 44 21

What went wrong? (add screenshot)
Backgroundimage is not rendered only some  text
Bildschirmfoto 2021-05-26 um 09 43 57

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### LINKED ISSUE #13561: Image missing in PDF
Attach (recommended) or Link to PDF file here: [ICEE-B.2017.8192026.pdf](https://github.com/mozilla/pdf.js/files/6651211/ICEE-B.2017.8192026.pdf)

Configuration:
- Web browser and its version:  Firefox 89.0 (64-bit)
- Operating system and its version: Windows 10 Pro Version 21H1
- PDF.js version: I don't know, sorry
- Is a browser extension: No

Steps to reproduce the problem:
1. Open PDF
2. Figure 1 in page 2 is missing

What is the expected behavior? (add screenshot)
This is how it looks in Edge
image

What went wrong? (add screenshot)
This is how it looks in firefox
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by brendandahl**
Previously, when we filled image masks we didn't copy over the current transformation,
this caused patterns to be misaligned when painted. Now we create a temporary
canvas with the mask and have the transform copied over and offset it relative to
where the mask would be painted. We also weren't properly offsetting tiling patterns.
This isn't usually noticeable since patters repeat, but in the case of #13561 the pattern
is only drawn once and has to be in the correct position to line up with the mask image.

These fixes broke #11473, but highlighted that we were drawing that correctly by
accident and not correctly handling negative bounding boxes on tiling patterns.

Fixes #6297,  #13561, #13441

Partially fixes #1344 (still blurry but boxes are in correct position now)

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
There seem to be a number of cases, mostly involving images with "text", which now look a bit blurrier (and less sharp) than before.
Is this perhaps related e.g. to the zoom level, and thus less noticeable in the viewer, or is there something which can be done about that? (Given the overall improvements, I'd totally understand if we have to accept some smaller "regressions" here.)

**Comment by brendandahl** [comment]
I'm not quite sure why some of the images seem a bit more blurry. I thought if anything they'd be more crisp since we are now drawing at the correct scale. It could be we're now drawing at fractional x/y and the pixels are being blurred. Locally I can't tell a difference with a high-dpi screen, but I'll look into a few to see if there's anything obvious.

**Comment by brendandahl** [comment]
I did some testing and it looks like the issue was drawing the image with fractional offsetX/Y coordinates. Let's try this again...
/botio test

**Comment by marco-c** [comment]
It's looking better now.

**Review by Snuffleupagus — COMMENTED** [review]
Looks good to me, thank you!

**Pull request merged**
