### PR TITLE
Use const in viewer.js

### PR DESCRIPTION
**Pull request by wojtekmaj**

### CODE REVIEW

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Here, and in all other PRs, you'll need to add `/* eslint prefer-const: error */` *directly* after the copyright block in order for these sort of patches to meaningful (since otherwise there's no point to these changes).

**Comment by wojtekmaj** [comment]
Done.

**Comment by Snuffleupagus** [comment]
Please keep https://github.com/mozilla/pdf.js/wiki/Squashing-Commits in mind here and elsewhere.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good!

**Pull request merged**
