### PR TITLE
Complete rewrite of the annotation layer

### PR DESCRIPTION
**Pull request by timvandermeij**
_My apologies in advance for the wall of text!_

This PR aims to provide a drop-in replacement for the current annotation code. In my opinion the current code is not structured enough, incomplete, not documented enough and it lacks basic testing. My goals with this PR are to provide a solid framework to create and present annotations in which we can easily implement new annotation types. It provides the necessary abstraction to do this.

The basis of this PR is the base class `Annotation`. It contains all information a basic annotation should have. Specific annotation types, such as Link or Text, will extend this base class with their own specific methods (see `src/core/annotation_types/link_annotation.js` for example). This is not only a nice way to work with annotations, but it's also what the PDF specification recommends.

The existing `AnnotationUtils` class and `web/page_view.js` have been rewritten to work with this new framework, but they have also been simplified a lot because most logic is now where it belongs: either in the annotation object itself or in `annotation_handler.js`. I wanted to avoid having styles for example being applied in many places, which is what happens in the current code. Doing so makes sure that for example `page_view.js` only deals with printing the annotations and not also with styling them anymore.

Aside from rewriting the current annotation layer for the sake of readability, structure and maintainability, I also felt that the current implementation was incomplete at some points and almost none of it was documented. What I did was read the entire part of the PDF specification on annotations and made an exhaustive overview of all features the annotation layer should have. This has been done so we know exactly what we do and do not support currently. This can be found in the implementation overview document (see below).

After having made the abovementioned overview, I have also implemented some new features that were missing in the previous implementation layer. Examples are:
- Implemented full support for radii in a Border dictionary.
- Implemented full support for colorspaces used by annotations.
- Implemented full support for the 'underline' border style.
- Implemented partial support for the 'dashed' border style (because of CSS limitations we can also show the default dashed border style, but it's better than showing nothing).
- Improved handling of `GoToR` link types.

Finally, after rewriting everything and adding new features, I decided to fix the lack of tests. I have added unit tests for practically all features of the annotation layer that are currently implemented.

This is still a work in progress. The to do list can be found in the implementation overview document (see below).

I have prepared a ZIP file with eight test documents for the Link annotation and the implementation overview document as referenced above. This file can be downloaded from http://www39.zippyshare.com/v/28118637/file.html.
- [ ] Rendering of LinkAnnotation3.pdf seems better to me than in Reader (because we actually use the border width as per spec and Reader seems to ignore this), but is OK to do this differently?

### CODE REVIEW

**Comment by yurydelendik** [comment]
@timvandermeij can we revive this PR?

**Comment by timvandermeij** [comment]
@yurydelendik Yes, I hope to work on this again soon. The goal is to split this PR into multiple smaller PRs. Actually a lot of this PR is also merged into master by #5585, #6273, #6239, #6232, #6214 and more listed here: https://github.com/mozilla/pdf.js/pulls?utf8=%E2%9C%93&q=is%3Aclosed+is%3Apr+annotation

I hope to get the last bits of this PR into separate PRs soon such that we can close this one.

**Comment by mitar** [comment]
It would be really great if also #5283 could be addressed. :-)

**Comment by timvandermeij** [comment]
This PR is more about refactoring the current code, but it should make the implementation of such an API easier.

**Comment by timvandermeij** [comment]
Most parts of this patch are now present in the master branch. The remaining bits are either not necessary anymore due to other rewrites or need to be reconsidered in a separate PR, so I'm closing this one as completed.

**Pull request closed without merging**
