### PR TITLE
Enable collapsing/expanding of Outline Items

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This PR does a number of things:
- Moves the `DocumentOutlineView` code to it's own file.
- Changes the way that the outline is created. Instead of building it using `<div>`, it's changed to use `<ul>` and  `<li>` (unordered lists). This is necessary for the next part of this PR, and also makes it easy to fix a few visual nits in the current CSS.
- Enables the user to collapse/expand outline items. _This is a feature that I've been wanting, particularly in large documents._
  There is also a menu, that makes it easy to collapse/expand all items.
- Finally, it enables highlighting of the currently active outline item. _Another feature that I think is practical when browsing the outline in large documents._

For testing this, the following file could be used: http://mirrors.ctan.org/info/lshort/english/lshort.pdf.

**I'm submitting this PR to see if there is any interest in the above features.**
If there is, I assume it would be best to split this into a couple of different PRs!?

### CODE REVIEW

**Comment by flopes89** [comment]
I highly approve of any version of this feature - As I see, it is set to "Work in progress". Is there any chance to know when you are planning on implementing this in the main branch? I tried merging it with the current releases, but to no avail -  It seems the structure has change a little too much since the PR was posted...

**Comment by Snuffleupagus** [comment]
@flopes89 As you can see from the discussion above, there isn't consensus on either:
 1. If we actually *need* this feature at all in the standard PDF.js viewer; given that we're not sure if this would be a good UX, and that it would add a lot of code for a very minor feature.
 2. How it should be implemented, if we do decide to implement it.

Given that this code is 1.5 years old, and that we've done (and are still doing) a lot of refactoring of the viewer code, it's to be expected that this won't work in it's current form.

**Comment by flopes89** [comment]
@Snuffleupagus Thanks for the update. I can understand the disucssion, I wasn't sure if there was some progress, as it is still marked as "in progress" - Maybe this should be relabelled then?

**Comment by Snuffleupagus** [comment]
> [...] as it is still marked as "in progress" - Maybe this should be relabelled then?

No; the `4-work-in-progress` label simply means that a PR is not ready to be merged. We use it as a quick indication to reduce the risk that a core contributors accidentally merges a PR that isn't ready yet.

**Comment by timvandermeij** [comment]
Just as a status update for everyone following this PR: it is closed in favor of #6242 where we continue this feature development.

**Pull request closed without merging**
