### PR TITLE
Update the GitHub Actions workflow for the Fluent linter

### PR DESCRIPTION
**Pull request by timvandermeij**
The commit messages contain more details about the individual changes.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Thanks for doing this clean-up, since consistency is always nice!

Looking at this a bit closer, I've got two questions about potential additional improvements:
 - Would it be technically possible to "combine" the `push` and `pull_request` configurations, given what we do [in another workflow](https://github.com/mozilla/pdf.js/blob/238f3e728f1f4c0b4acc58e7a3560573816610a8/.github/workflows/ci.yml#L2), since we're currently duplicating the same configuration in both?
    https://github.com/mozilla/pdf.js/blob/238f3e728f1f4c0b4acc58e7a3560573816610a8/.github/workflows/fluent_linter.yml#L3-L16
 - Is it correct and/or meaningful to leave the following entry blank, or can the line be removed?
    https://github.com/mozilla/pdf.js/blob/238f3e728f1f4c0b4acc58e7a3560573816610a8/.github/workflows/fluent_linter.yml#L17

**Comment by timvandermeij** [comment]
> Would it be technically possible to "combine" the push and pull_request configurations, given what we do [in another workflow](https://github.com/mozilla/pdf.js/blob/238f3e728f1f4c0b4acc58e7a3560573816610a8/.github/workflows/ci.yml#L2), since we're currently duplicating the same configuration in both?

Sadly that's not possible in this case. In that workflow we trigger on the `push` and `pull_request` events using the default configuration, so only in that case can they be combined. If we need to override the default configuration, we have to do so per event type because the actual configuration can differ between the various event types. You can find more information at https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-activity-types-and-filters-with-multiple-events.

> Is it correct and/or meaningful to leave the following entry blank, or can the line be removed?

This puzzled me as well for a bit, but I found out that this actually has a purpose. What is does is allow this workflow to be ran manually over at https://github.com/mozilla/pdf.js/actions/workflows/fluent_linter.yml (note the "This workflow has a workflow_dispatch event trigger" banner and the "Run workflow" button). This is convenient because it allows e.g. running the workflow on-demand outside of a pull request. The other workflows don't have it yet because they make less sense to run outside of the scope of a PR (although technically they could have this as well, but there hasn't been a need to do so so far).

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Comment by flodolo** [comment]
The linter is not tested with Python 3.12 🤔 I suggest to stick with 3.10 or 3.11

For me, with 3.12 tests fail to even install dependencies
https://github.com/mozilla-l10n/moz-fluent-linter/actions/runs/6694472871/job/18187850055?pr=14

**Comment by timvandermeij** [comment]
That particular build seems to fail because it's fetching PyYAML 6.0 which doesn't have Python 3.12 wheels; see https://pypi.org/project/PyYAML/6.0/#files and see the `PyYAML-6.0.tar.gz` fetching part in those logs, which means the source package is fetched that then has to be built while the required build requirements are missing. However, in our build PyYAML 6.0.1 is fetch which does have Python 3.12 wheels and works just fine; see https://pypi.org/project/PyYAML/6.0.1/#files for the `cp312` wheels and https://github.com/mozilla/pdf.js/actions/runs/6678649246/job/18149912927 for our workflow run where the "Install Fluent dependencies" picks up `PyYAML-6.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`.

The difference between the builds is that we `pip install` the package directly so the version ranges from `setup.py` apply and therefore the latest PyYAML is fetched whereas the build you linked uses `pip install -r .github/requirements.txt` which pins PyYAML to a specific version for which no Python 3.12 wheels exists, thus building it from source.

**Pull request merged**
