### PR TITLE
api/getDocument: handle ArrayBuffer check for PDF binary data (byteLength)

### PR DESCRIPTION
**Pull request by castevinz**

### CODE REVIEW

**Comment by yurydelendik** [comment]
Could you add a description what this PR is fixing? Looks like it adds support for ArrayBuffer. If yes, could you add a separate if-branch that would use `pdfBytes instanceof ArrayBuffer` instead?

**Comment by castevinz** [comment]
Yes, this fix adds support for ArrayBuffer. I could add a separate if-branch, but do you prefer it before or after the "object" if-branch ? Thx

**Comment by yurydelendik** [comment]
> you prefer it before or after the "object" if-branch

after is fine

**Comment by castevinz** [comment]
It's ok for me.

**Comment by yurydelendik** [comment]
Looks good with commit message (and PR title) change to reflect the purpose of the commit

**Comment by castevinz** [comment]
The commit/PR message is modified. I hope it will suit you.

**Comment by yurydelendik** [comment]
Thank you for the patch.

**Comment by castevinz** [comment]
You're welcome ;)

**Pull request merged**
