### PR TITLE
Update the ESLint `quotes` rule to agree with mozilla-central style (issue 9633)

### LINKED ISSUE #9633: Fix pdf.js ESLint issues
If I remove all pdf.js whitelisting from the mozilla-central .eslintignore, I see some errors in pdf.js code:
https://queue.taskcluster.net/v1/task/QI9gXOQKQdqkf2iYrS-60g/runs/0/artifacts/public/logs/live_backing.log

TEST-UNEXPECTED-ERROR | content/build/pdf.js:24:2 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:24:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:24:24 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:24:54 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:25:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:25:3 | 'module' is not defined. (no-undef)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:26:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:26:7 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:26:28 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:26:42 | 'define' is not defined. (no-undef)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:27:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:27:3 | 'define' is not defined. (no-undef)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:28:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:28:7 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:28:29 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:29:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:29:3 | 'exports' is not defined. (no-undef)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:30:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:31:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:32:20 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:33:8 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:34:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:34:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:35:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:35:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:36:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:37:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:37:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:38:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:38:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:39:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:40:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:40:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:41:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:41:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:41:12 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:42:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:42:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:43:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:43:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:44:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:44:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:45:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:45:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:46:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:46:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:47:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:47:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:48:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:48:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:49:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:49:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:50:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:51:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:51:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:52:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:52:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:53:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:54:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:54:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:55:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:55:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:56:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:57:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:57:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:58:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:58:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:59:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:59:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:60:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:61:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:62:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:62:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:63:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:63:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:64:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:65:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:65:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:66:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:66:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:67:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:68:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:68:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:69:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:69:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:70:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:70:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:70:12 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:71:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:71:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:72:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:72:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:73:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:73:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:74:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:74:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:75:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:75:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:76:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:76:11 | Unexpected tab character. (no-tabs)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This *entire* patch was generated automatically, using the ESLint `--fix` option.

Please see https://eslint.org/docs/rules/quotes and https://searchfox.org/mozilla-central/rev/d302c3058330a57f238be4062fddea629311ce66/tools/lint/eslint/eslint-plugin-mozilla/lib/configs/recommended.js#339-344

This brings the PDF.js code-base (slightly) more in-line with the ` mozilla-central` coding style, assuming we actually want to do this. If not, I've only "wasted" about five minutes on this patch anyway :-)

---

Fixes #9633 (to the extent that doing so is possible, given the Webpack bundling; please see the discussion).

### CODE REVIEW

**Comment by timvandermeij** [comment]
@yurydelendik @brendandahl What is your opinion on this? I'm in favor of matching the Mozilla coding style, but it's also touching a lot of files and lines, so I'm a bit on the fence here...

**Comment by yurydelendik** [comment]
> What is your opinion on this?

We probably need to do it once. But I rather be more excited about further conversion these into template strings :)

**Comment by brendandahl** [comment]
There's talk of using an auto-formatting tool over in mozilla-central (similar to clang-format) for JS. I'm hoping that will happen soon and we can just start using that and (hopefully) end all the formatting discussions.

**Comment by Snuffleupagus** [comment]
Based on the comments I've closed this PR, and would also suggest closing issue #9633 as WONTFIX.

**Pull request closed without merging**
