### PR TITLE
Update openjpeg build (bug 1896577)

### PR DESCRIPTION
**Pull request by calixteman**
It just contains fixes for:
 - bug 1896577
 - https://github.com/mozilla/pdf.js.openjpeg/issues/1

### CODE REVIEW

**Comment by Rob--W** [comment]
The `_scriptDir` (pre patch) / `_scriptName` (post patch) variable is used to populate the `scriptDirectory` variable, which is not used anywhere (at least no references to it other than assignment). `document.currentScript` is already used inside the code to populate `scriptDirectory`, before unconditionally replacing it with the value of `_scriptDir`.

@calixteman Why did you introduce `_scriptName` instead of deleting the use of `_scriptDir`?

**Comment by calixteman** [comment]
> The `_scriptDir` (pre patch) / `_scriptName` (post patch) variable is used to populate the `scriptDirectory` variable, which is not used anywhere (at least no references to it other than assignment). `document.currentScript` is already used inside the code to populate `scriptDirectory`, before unconditionally replacing it with the value of `_scriptDir`.
> 
> @calixteman Why did you introduce `_scriptName` instead of deleting the use of `_scriptDir`?

Unfortunately, almost all the js in this file is generated by emscripten.
The only js I added is:
 - https://github.com/mozilla/pdf.js.openjpeg/blob/main/src/myjs.js
 - https://github.com/mozilla/pdf.js.openjpeg/blob/main/src/mypre.js

So it's a bug in emscripten.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for improving this!

**Pull request merged**
