### PR TITLE
Fixes Issue #8188 Missing references in internal links

### PR DESCRIPTION
**Pull request by nish17**

### CODE REVIEW

**Review by yurydelendik — CHANGES_REQUESTED** [review]
It's not what #8188 is looking for -- we need component similar to PDFViewer (not example). However additional example will be needed to show how PDFSinglePageViewer works.

**Comment by nish17** [comment]
I'm sorry, I didn't understand it fully. What exactly is the component and How do I implement the interface?

**Comment by nish17** [comment]
I still don't understand that part of building UI for PDFSinglePageViewer How to do it? and one more thing If I put the code of simpleviewer.js file into some other file by keeping rest everything same, then why it's not working? Web browser is only able to load the UI and not the pdf File. Why is it happening?

**Comment by nish17** [comment]
and I don't know why Travis build fails, I didn't change anything in the build folder.

**Comment by yurydelendik** [comment]
The [comment](https://github.com/mozilla/pdf.js/pull/8664#pullrequestreview-50716736) above still stands. I'm expecting class created at web/ that has interface similar to what implemented in web/pdf_viewer.js. This class needs to be properly included in pdfjs-dist and example in examples/compoments/ provided.

**Comment by timvandermeij** [comment]
Closing since a new PR is opened for this.

**Pull request closed without merging**
