### PR TITLE
Disable new tab page stuff in Firefox when running tests

### PR DESCRIPTION
**Pull request by calixteman**
It should help to have such a garbage in the logs:
```
console.warn: TopSitesFeed: Failed to fetch data from Contile server: NetworkError when attempting to fetch resource.
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.
```

### CODE REVIEW

**Comment by timvandermeij** [comment]
Out of curiosity, where have you seen those logs? I don't have them locally (the new tab page is empty if I manually open one in the headful test browser) and I also don't recall having seen them on the bots.

**Comment by calixteman** [comment]
I'm running the tests on Windows but from an Ubuntu within WSL2.
When I make a full run of the integration tests I can see the above line several times.
Chrome/Firefox are not super fast when ran from Linux through WSL so maybe the induced overhead makes the new tab living enough to start to trigger some network requests.

**Comment by calixteman** [comment]
That said in general it's probably not that bad to remove the small overhead due to the new tab page stuff.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks like a good idea to me; thanks!

**Pull request merged**
