### PR TITLE
making webpack aware of the change inside of the worker file and hash

### PR DESCRIPTION
**Pull request by mdrodz**
making webpack aware of the change inside of the worker file and hashing its name on build accordingly

### CODE REVIEW

**Comment by mdrodz** [comment]
The issue this PR is related to: https://github.com/mozilla/pdf.js/issues/13685#issue-938138753

**Comment by Snuffleupagus** [comment]
Please note https://github.com/mozilla/pdf.js/wiki/Squashing-Commits

**Comment by mdrodz** [comment]
Thanks! It is fixed now

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Let's do this; thank you!

**Pull request merged**
