### PR TITLE
Update dependencies to the most recent versions

### PR DESCRIPTION
**Pull request by timvandermeij**
The commit messages contain more details about the individual changes. No translation updates are available upstream this time.

### CODE REVIEW

**Comment by timvandermeij** [comment]
I'm not sure yet what's up with the Linux bot, but I'm pretty sure it can't be caused by the changes here. I deliberately left out Puppeteer and the other ones here should not cause this. We did notice with earlier patches that lots of Chrome processes were running, so the OOM issue is probably caused by browser processes being left behind by previous runs, but it's unclear why that would happen.

**Comment by timvandermeij** [comment]
This should be ready now that disabling WebDriver BiDi for Chrome seems to have fixed the timeout and OOM issues.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Pull request merged**
