### PR TITLE
Fix issues in driver.js when getting css sheets

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
In dumping svg, I saw an `undefined` which led me to write this patch.

**Review by Snuffleupagus — APPROVED** [review]
r=me, with passning tests; nice catch!

**Comment by timvandermeij** [comment]
Interesting how this seemingly didn't cause noticeable problems before; it looks like it more-or-less worked "accidentally". Anyway, nice find!

**Pull request merged**
