### PR TITLE
PDF.JS loaded more than 20,000 pages, page carton optimization.

### PR DESCRIPTION
**Pull request by tanglinhai**
PDF.JS loaded more than 20,000 pages, page carton optimization.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
It looks like this PR was opened against the main PDF.js repository by mistake, since it seems to contain various customizations/changes not at all relevant for the default viewer.

Furthermore, please keep in mind that PRs need to contain a good explanation/justification, written in proper English, of the changes being made which isn't the case here. Finally, something of this size and scope would essentially not be accepted in a single PR either.

**Comment by Snuffleupagus** [comment]
It looks like this PR was opened against the main PDF.js repository by mistake, since it seems to contain various customizations/changes (which are really difficult to follow) and which are not at all relevant for the default viewer.

Furthermore, please keep in mind that PRs need to contain a good explanation/justification, written in proper English, of the changes being made which isn't the case here. Finally, something of this size and scope would essentially not be accepted in a single PR either.

**Comment by tanglinhai** [comment]
Loading 20,000 pages of files causes performance problems. The loading policy was modified.


Example:


Before modification: https://tanglinhai.github.io/repo/test/pdfsrc/web/viewer.html? File=. /. /.. / docs/test.pdf#toolbar=0&view=FitH&page=1


After modification: https://tanglinhai.github.io/repo/test/pdfnew/web/viewer.html? File =. /.. /.. / docs/test.pdf#toolbar=0&view=FitH&page=1




------------------ 原始邮件 ------------------
发件人: "Jonas Jenwald"<notifications@github.com>; 
发送时间: 2019年6月23日(星期天) 晚上6:55
收件人: "mozilla/pdf.js"<pdf.js@noreply.github.com>; 
抄送: "汤林海"<316084714@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mozilla/pdf.js] PDF.JS loaded more than 20,000 pages, pagecarton optimization. (#10924)




It looks like this PR was opened against the main PDF.js repository by mistake, since it seems to contain various customizations/changes (which are really difficult to follow) and which are not at all relevant for the default viewer.
 
Furthermore, please keep in mind that PRs need to contain a good explanation/justification, written in proper English, of the changes being made which isn't the case here. Finally, something of this size and scope would essentially not be accepted in a single PR either.

**Comment by tanglinhai** [comment]
Loading 20,000 pages of files causes performance problems. The loading policy was modified.

Example:

Before modification: https://tanglinhai.github.io/repo/test/pdfsrc/web/viewer.html? File=. /. /.. / docs/test.pdf#toolbar=0&view=FitH&page=1

After modification: https://tanglinhai.github.io/repo/test/pdfnew/web/viewer.html? File =. /.. /.. / docs/test.pdf#toolbar=0&view=FitH&page=1

**Comment by timvandermeij** [comment]
I agree with https://github.com/mozilla/pdf.js/pull/10924#issuecomment-504740618; it's not clear at all why these modifications works and if they are all necessary. If you would like to propose improvements, please open an issue first for discussion and keep the scope limited to make it a small change, because this is way too large to review properly.

**Pull request closed without merging**
