### PR TITLE
Publish minified files to pdfjs-dist npm package #5487

### PR DESCRIPTION
**Pull request by RahulMetangale**
-Completed feature https://github.com/mozilla/pdf.js/issues/5487
-When "node make dist" command is run JavaScript and CSS files present under build/dist will be minified  and added to same folder.
-Minified files will be named  <file_name>.min.js or <file_name>.min.css
-For minifying css files YUI compressor is needed
-Review required

### CODE REVIEW

**Comment by yurydelendik** [comment]
> output of minified target is different than what is required by pdfjs-dist 

We shall make it the same then or at least reuse the same code (not by copy'n'paste). `miniifed` was created as example, we can adapt that to pdfjs-dist.

> Because i will have to move calls to 'generic','singlefile' and 'components' target from 'dist' to 'distminified'. Please confirm if that is ok?

Minification shall not be a part of the our `dist` target but be an addition (logically and be reflected in the build code) to optimize its output. So `dist` and `minified` output shall be combined to produce `distminifed` -- not all files from `minified` shall be used. Shall we add additional targets such as `componentsminified` and `genericminified`?

**Comment by RahulMetangale** [comment]
Environment Details:
1. Closure compiler version: v20141215 (Requires Java 7 or higher)
    Download link: http://dl.google.com/closure-compiler/compiler-latest.zip
2. YUI Compressor: 2.4.8
    Download link: https://github.com/yui/yuicompressor/releases
3. Node version 0.10.33
4. git 1.9.4

Steps to setup the environment on clean Windows machine:
1. Install Node.js and git
2. Download closure compiler and YUI compressor
3. Setup pdf.js
4. open git bash (Start- All Programs - git -git bash)
5. cd into pdf.js directory
6. set closure compiler variable with following command:
export CLOSURE_COMPILER=<path to closure compiler jar file) 
ex: export CLOSURE_COMPILER=/c/closure_compiler/compiler.jar
7. Set YUI_COMPRESSOR variable with following command:
export YUI_COMPRESSOR=<path to closure compiler jar file) 
ex: export YUI_COMPRESSOR=/c/yui_compressor/yui.jar
8. Now run following command to create dist 
node make dist
9. Observe the build and web directory

**Comment by yurydelendik** [comment]
> 2) Why you don't use/improve minified target output and creating your own?
> I did not use minified target because output of minified target is different than what is required by
> pdfjs-dist ex: locale, viewer.html etc are present in minnified target output. In addition minified output
> does not retain the unminified version which is required for pdfjs-dist.I hope this answers your question.

While I was playing with the output, I started agree with your answer. Let's remove the latter improvement and go with the initial way of minimizing only pdfjs-dist published files. Fix the style and squash commits and it will be ready to go. Thanks

**Comment by timvandermeij** [comment]
Superseded by #6682.

**Pull request closed without merging**
