### PR TITLE
fix URLs in learning examples

### PR DESCRIPTION
**Pull request by rfinz**
Previously submitted PR under gh-pages branch. Fixes 404 in learning examples.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
As described in https://github.com/mozilla/pdf.js/wiki/Squashing-Commits, please squash the commits.

**Comment by yurydelendik** [comment]
The files build/pdf.js and pdf.worker.js do not exist (after #8023). We need better way to place examples and/or built pdf.js files in gh-pages.

**Comment by yurydelendik** [comment]
We probably need to create similar examples at http://mozilla.github.io/pdf.js/examples/ and remove learning folder from gh-pages

**Comment by yurydelendik** [comment]
Fixed by #8039

**Pull request closed without merging**
