### PR TITLE
Avoid to run localization when inserting the text layer

### PR DESCRIPTION
**Pull request by calixteman**
The text layer contains either some spans with the page text or some accessibility structural info.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
I'll need a little bit of time to think through this, to *fully* convince myself that moving the textLayer-`append` won't cause any problems in some weird edge-case. (I think it should be safe, but just want more time to consider this.)

However, if we're doing this can/should the same be done for the `structTree` since I don't believe that it needs to be localized either? Obviously that one is less common, and generally contains fewer DOM-element, but nonetheless.

Finally, `NullL10n` also needs to be extended with these new methods to avoid issues in the *standalone* viewer-components.

**Comment by calixteman** [comment]
Yes we can include the struct layer.
And I'll update the `NullL10n` when I'll rebase this patch on top of yours. 
As you said the main difficulty is to be sure that we can move the appending: I pretty sure that it's safe but I'm not 100% sure.

**Review by timvandermeij — APPROVED** [review]
Looks good to me, with the note that the struct tree layer should probably also be taken along here, but I'd like @Snuffleupagus to also sign off on this before merging. From my side at least this change looks OK provided that all tests still pass.

**Comment by Snuffleupagus** [comment]
The thing that worried me initially is how/if this could affect canceling of rendering, more specifically here:
https://github.com/mozilla/pdf.js/blob/898cc2e399e47ae70e08624a72852954030370b0/web/pdf_page_view.js#L689-L692

However, looking at the `TextLayerBuilder` it's clear that the `div` is *created immediately* and this patch only changes where it's attached to the DOM (thus `this.textLayer.div` still *exists* just as before):
https://github.com/mozilla/pdf.js/blob/898cc2e399e47ae70e08624a72852954030370b0/web/text_layer_builder.js#L49-L67

All-in-all, it seems that moving the `append` should indeed be safe.

**Comment by Snuffleupagus** [comment]
@calixteman After having converted the xfaLayer, I *believe* that I now understand why this failed various integration-tests above.

As far as I can tell, the problem in this PR is that we're appending the textLayer *after* enabling the `highlighter` and `accessibilityManager`, which doesn't work. I've just had an idea for fixing this without, hopefully, making the code too messy; mind if I "steal" this and submit a PR for testing?

**Comment by calixteman** [comment]
Yes in the a11yManager we get the element bounds in order to sort the element belonging to the text layer.
So I thought about two things:
 - could we sort the elements in more lazy way instead of doing that unconditionally ?
 - could we just use the coordinates we've from the worker ? IIRC, at the end we just want to sort them so we don't need to have "real" coordinates.

I was thinking about that and then I had something else to work on.
For sure, you can steal this PR.

**Comment by Snuffleupagus** [comment]
> Yes in the a11yManager we get the element bounds in order to sort the element belonging to the text layer. So I thought about two things:
> 
>     * could we sort the elements in more lazy way instead of doing that unconditionally ?
> 
>     * could we just use the coordinates we've from the worker ? IIRC, at the end we just want to sort them so we don't need to have "real" coordinates.

It's likely that we could improve this, and worker-thread sorting would probably be more efficient (if possible). Given other recent changes that's perhaps not something that we want to land before releasing version `4`, so there's probably no real rush here.

Regardless of future improvements of the `TextAccessibilityManager`-implementation we still need to ensure that a pending search operation is deferred until the `textLayer` is available in the viewer; however this has now been addressed in PR #17192 and we should thus be able to close this one.

**Pull request closed without merging**
