### PR TITLE
Increase the size of the toolbar depending on the uidensity (bug 1171799)

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
*There might be other issues as well, but quick testing revealed the following.*
 
It seems that, when manually setting the `compact` density, the buttons in the secondaryToolbar will overflow the toolbar-element at the bottom; this is easily visible when zoom-in on the following screen-shot.

compact

**Comment by calixteman** [comment]
It should be fixed now. My devtools are on the right side... so I would have been enabled to see this bug.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks.

**Pull request merged**
