### PR TITLE
Add some telemetry to know how often the buttons in the secondary toolbar are used (bug 1789883)

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
While this covers buttons being *clicked*, it however ignores functionality that's available via keyboard shortcuts. Is that actually intended, if not this is probably not the correct place for this code?
(To determine if functionality is actually being *used*, ignoring it being invoked through the keyboard could skew the statistics collected here.)

**Comment by calixteman** [comment]
As far as I can tell, our main goal here is to measure how often buttons are used but your question is fair, I asked it and I'm waiting for an answer.

**Comment by Snuffleupagus** [comment]
Especially for something like PresentationMode (which is also available via <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>P</kbd>), given that https://github.com/mozilla/pdf.js/pull/15391#issuecomment-1236646441 mentioned potentially removing that, it *might* be problematical if the decision is based solely on button-telemetry since that may not provide a complete picture.

**Comment by calixteman** [comment]
In Firefox, the use of keyboard shortcuts is usually marginal compared to the use of buttons/menus, hence only adding some telemetry on buttons should likely be enough to understand how people are using these tools.

**Comment by Snuffleupagus** [comment]
> In Firefox, the use of keyboard shortcuts is usually marginal compared to the use of buttons/menus, hence only adding some telemetry on buttons should likely be enough to understand how people are using these tools.

For the PresentationMode specifically, ultimately basing a removal decision on *incomplete* data seems wrong to me (and I'd object to a future removal on those grounds).
For this specific case, could we not simply cover that by piggy-backing on this new telemetry with something like the following
```javascript

PDFViewerApplication.externalServices.reportTelemetry({
  type: "buttons",
  data: { id: "presentationMode-keyboard" },
});
```
placed just after these lines https://github.com/mozilla/pdf.js/blob/f63d584cb10ce2846f849f3bed93d4ba343d1f25/web/app.js#L2918-L2919

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Pull request merged**
