### PR TITLE
[Editing] Disable the HandTool during editing (bug 1792422)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This extends the approach used in PresentationMode to also cover the AnnotationEditor, and tries to handle the combination of both cases correctly. In order to simplify the overall implementation we simply track the *first* seen "previous" cursorTool, and don't allow it to be reset as long as either PresentationMode or an AnnotationEditor is being used.

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by Snuffleupagus** [comment]
Slightly tweaked the code, replacing `switch` with `if`, to make it a little smaller; no logical changes were made though.

/botio integrationtest

**Pull request merged**
