### PR TITLE
Test

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
@Snuffleupagus https://bugzilla.mozilla.org/show_bug.cgi?id=1865774 has been fixed, I tested locally with the last nightly and unit test are ok. Consequently, I deleted the old nightlies I set up yesterday on the bots.

**Comment by Snuffleupagus** [comment]
It seems that some integration-tests now fail *fairly* consistently on Linux, since there's similar failures in https://github.com/mozilla/pdf.js/pull/17318#issuecomment-1824697938 as well.

**Comment by Snuffleupagus** [comment]
@calixteman Would we be able to look into why some of the *integration tests* have started failing on the Linux bot?
Maybe it's connected with the Firefox 122 update, since I believe that's when it started?

**Comment by timvandermeij** [comment]
Closing this PR in favor of tracking this in issue #17336.

**Pull request closed without merging**
