### PR TITLE
Add a heuristic, for mouse wheel events, to avoid the document toggling between the min/max zoom levels (issue 8802)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This is obviously not a *proper* solution, since I've got no idea why this is even a problem (and don't have the required hardware to debug it either).
However, it seems that it should be reasonably easy to at least add a workaround for now, which surely is better than the current state.

*Submitting as a "Draft PR" for now, since we'd need people affected by this to test if this even helps before moving forward with it.*

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@staktrace Would you be able to test the preview build, see http://54.67.70.0:8877/48611426867ac14/web/viewer.html, to see if it helps with issue #8802?

**Comment by staktrace** [comment]
@Snuffleupagus I tried it, and it doesn't really help - it might be marginally better but from a user's point of view controlling the zoom via trackpad is still effectively impossible.

**Comment by Snuffleupagus** [comment]
> [...] it might be marginally better but from a user's point of view controlling the zoom via trackpad is still effectively impossible.

That's unfortunate, but not really all that surprising; thanks for taking the time to test this!

**Pull request closed without merging**
