### PR TITLE
Revert PR 5510, except in WebKit browsers, for breaking print preview in Firefox

### PR DESCRIPTION
**Pull request by Snuffleupagus**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1138993.

### CODE REVIEW

**Comment by CodingFabian** [comment]
I wanted to have a look at it, because I was so happy that the PR solved some scaling issues.
But I am now really confused, because in my Nightly FF I cannot even find the print setting to produce landscape....

**Comment by timvandermeij** [comment]
Thank you!

**Pull request merged**
