### PR TITLE
Refactor viewer code to fix issues with the "pageviewer" components example (issue 6056)

### LINKED ISSUE #6056: pageviewer.js: Cannot read property 'getDestinationHash' of undefined at bindLink
Hello,

I'm in trouble setting up the pageviewer.js-example of the src-package I "make'd" with node. When using a pdf containing a pdf-internal link (one page to another) and rendering a page containing a link, I get:

Uncaught (in promise) TypeError: Cannot read property 'getDestinationHash' of undefined
    at bindLink (http://fs.local/system/modules/pdf_viewer/assets/js/vendor/pdf.js-src/build/components/pdf_viewer.js:1540:32)
    at http://fs.local/system/modules/pdf_viewer/assets/js/vendor/pdf.js-src/build/components/pdf_viewer.js:1620:19

I'm using: https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js

The property which is missing, is linkService in 

link.href = linkService.getDestinationHash(dest);

in setupAnnotations in pdf_viewer.js.

Any help would be highly appreciated. Is it a bug or am I doing something wrong???

Bye Defcon0

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #6056.

When working of addressing the issue, it quickly became apparent that a number of (smaller) things needed to be re-factored in order for it to work. Hence the use of multiple commits (despite the total size of the PR), to make it easier to follow the reasoning.

_Please refer to the individual commit messages for a more detailed description of the patches._

### CODE REVIEW

**Comment by timvandermeij** [comment]
Can we squash the second and third commit to reduce the commit count somewhat? They seem very much related.

**Comment by Snuffleupagus** [comment]
> Can we squash the second and third commit to reduce the commit count somewhat?

Sure, I'll do that once the PR has been reviewed and is ready to land.

**Comment by Snuffleupagus** [comment]
@timvandermeij I've squashed the commits as you asked, and after talking to Yury on IRC I'm assigning the final review to you!

/botio-linux preview

**Comment by timvandermeij** [comment]
Review progress:

- [ ] Use "private" properties in PDFViewer_scrollPageIntoView
- [ ] Simplify the SimpleLinkService and use it to pass in a linkService instance in DefaultAnnotationsLayerFactory
- [ ] Move annotation related CSS rules from pdf_viewer.css to its own file

**Comment by timvandermeij** [comment]
I'm having trouble verifying this patch. If I apply this patch and run the pageviewer example with the test file provided in #6056 I get `TypeError: linkService is undefined` in `setupAnnotations` on the following line:

`link.href = linkService.getDestinationHash(dest);`

**Comment by Snuffleupagus** [comment]
Strange, it works for me. Perhaps a stupid question, but did you remember to do `node make generic components` after applying the patch?

**Comment by timvandermeij** [comment]
Well, that was a silly mistake. I had built the components before applying the patch, but forgot to rebuild them after applying the patch. Now it does work for me, so I will continue the review. Thanks!

**Comment by timvandermeij** [comment]
Review progress:

- [ ] Use "private" properties in PDFViewer_scrollPageIntoView
- [ ] Simplify the SimpleLinkService and use it to pass in a linkService instance in DefaultAnnotationsLayerFactory
- [ ] Move annotation related CSS rules from pdf_viewer.css to its own file

**Comment by timvandermeij** [comment]
Nice work! Moving the annotation-related CSS rules to a separate file is useful for my annotation layer work too.

**Pull request merged**
