### PR TITLE
Compatibility: disable range requests for iOS and refactor user agent detection

### LINKED ISSUE #7815: IOS webview APP error: Unexpected server response (206) while retrieving PDF...
Link to PDF file (or attach file here):
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version:微信WeChat 6.3.27
- Operating system and its version:IOS 10.0.3
- PDF.js version:1.6.319

Steps to reproduce the problem:
1. Open 微信WeChat
2. view: https://mozilla.github.io/pdf.js/web/viewer.html

What went wrong? (add screenshot)

pdfjs

### PR DESCRIPTION
**Pull request by timvandermeij**
Fixes #7815.
Supersedes #7822.
Supersedes #7824.

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]

**Comment by Snuffleupagus** [comment]
Thanks for the patch!

**Comment by websirnik** [comment]
@timvandermeij I had range requests working on iOS10/9 . I'm not sure it is a right approach to disable them completely for the iOS. Though I did experience the same issue as @Snuffleupagus in WeChat and the way I've fixed it was similar to https://github.com/mozilla/pdf.js/pull/7822 . Targeted conditions are better in this case.

**Comment by Snuffleupagus** [comment]
> I'm not sure it is a right approach to disable them completely for the iOS.

Perhaps not, but it's a simple one and we *really* don't want to waste a lot of development/testing time on fine-tuning `compatibility.js`. Its purpose is to make it possible to use (most) browsers that have missing/broken features together with PDF.js out of the box, but you're certainly free to not use `compatibility.js`, or to modify it to suite your needs, in custom deployments.
Generally speaking we will err on the side of caution, and disable some features perhaps unnecessarily for certain browsers (for simplicity), since more fine-grained feature testing is often difficult.

> Though I did experience the same issue as @Snuffleupagus in WeChat and the way I've fixed it was similar to #7822 .

Please note that I've never used, nor have I claimed to use, the WeChat browser (which seems to be specific to the Chinese market).

**Comment by websirnik** [comment]
Sorry, meant to mention the other user who had WeChat issue.

I see where you  stand on this issue. Being on the cautionary side makes sense. Someone might argue that fine-tuning `compatibility.js` for quite a large audience of iOS users might make more sense. 
I personally ok to locally fine-tune `compatibility.js` in my deployment.

**Pull request merged**
