### PR TITLE
Replace the linked test-case for issue 3879 with a reduced test-case

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Re: issue #3879 and PR #3880.

@timvandermeij Do you have time for reviewing/verifying this patch? If not, just un-assign yourself :-)

### CODE REVIEW

**Comment by timvandermeij** [comment]
Thanks again for doing this!

**Comment by Snuffleupagus** [comment]
@timvandermeij Thank you for promptly reviewing/merging these kind of PRs!

**Pull request merged**
