### PR TITLE
Improve the annotation code by converting to ES6 syntax and removing duplicate code

### PR DESCRIPTION
**Pull request by timvandermeij**
The annotation code is not performance-sensitive, so we may convert this code to ES6 syntax (see http://logs.glob.uno/?c=mozilla%23pdfjs&s=23+Aug+2017&e=23+Aug+2017#c66446). Refer to the individual commits for more information about each change.

*Using https://github.com/mozilla/pdf.js/pull/8828/files?w=1 helps reviewing tremendously.*

### CODE REVIEW

**Review by Snuffleupagus — COMMENTED** [review]
Really nice diff stats, that's a lot of boilerplate code being removed at once :-D

One thing though: The IRC discussion only seem to explicitly mention `src/display/`, and this PR would be the first case where we're using ES6 classes in `src/core`.
Since the annotations, if present, will be always be parsed during the `getOperatorList` call, I'm not sure if that's a cause for (theoretical) concern?

Although, looking at https://bugzilla.mozilla.org/show_bug.cgi?id=1167472, a number of performance improvements have already landed.
Given that the number of annotations present on any one page is usually not very large, I'd be surprised if these changes made any difference at all (performance wise).

So, tentatively `r=me`; but I'd like @yurydelendik to confirm that he's OK with this before we land it.

**Review by yurydelendik — APPROVED** [review]
Really good, thanks.

**Pull request merged**
