### PR TITLE
Only skip parsing a stream in `Parser_makeFilter` when we know for sure that it is empty (PR 6372 follow-up)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
For PDF files with multiple `/Filter`s, where the `/Length` entry is zero, we fail to render the file correctly. The reason is that `maybeLength` is `null` for the every filter except the first, and `!maybeLength` is thus truthy.
Hence it seems that we should completely ignore the `/Length` entry and also explicitly check `maybeLength === 0`.

Note that I've not (yet) come across a PDF file with this issue in the wild, but given all the stupid things PDF generators do I wouldn't be surprised if such a file actually exists. In order to prevent a possible future bug, I'm submitting this patch which includes a hand-edited PDF file that we currently cannot render correctly (but e.g. Adobe Reader can).

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1305963 for the regression in the `issue6165` test. Hence I believe that this PR should be good to go.

**Comment by Snuffleupagus** [comment]
> I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1305963 for the regression in the issue6165 test. Hence I believe that this PR should be good to go.

The upstream bug has now been fixed! However, it's not been uplifted to Firefox 51 yet, but again I don't think that needs to hold off landing this PR.

**Review by yurydelendik — APPROVED** [review]
Thank you for the patch.

**Pull request merged**
