### PR TITLE
Move the `ImageBitmap` clean-up into the `PDFObjects` class

### PR DESCRIPTION
**Pull request by Snuffleupagus**
With upcoming changes we'll potentially start to cache `ImageBitmap` data at the document-level, in addition to just at the page-level. Hence we need to ensure that such data is actually released on clean-up, and rather than duplicating the existing *manual* handling this code is instead moved into the `PDFObjects.clear` method. (In my opinion, this is an overall improvement even without globally cached `ImageBitmap` data.)

*Please note:* This patch is written using the GitHub UI, since I'm currently without a dev machine, so hopefully it's correct and makes sense.

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Comment by Snuffleupagus** [comment]
The Windows-bot "failures" looks like fallout from Firefox being updated, since we've seen similar before. It should be fine to just generate new ref-images.

---

Note that this PR was based on me (slowly) continuing to review PR #16062, and so far I've spotted one more *pre-existing* issue that makes sense to fix (to simplify things overall).

**Pull request merged**
