### PR TITLE
Checked checkboxes weren't printed correctly in acroforms

### PR DESCRIPTION
**Pull request by calixteman**
Is there a way to create a test to test a print issue ?

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Isn't it enough to simply test this "normally", and not worry about the printing part, using an `eq` test with the `"forms": true` parameter set (see the `test/test_manifest.json` file)?
Related, is this patch actually passing all existing tests locally (the `"forms": true` test-coverage is quite limited, but it does exists)?

See https://github.com/mozilla/pdf.js/wiki/Contributing#4-run-lint-and-testing

**Comment by calixteman** [comment]
Yep tests are ok locally except that I get:
```
### Running browser tests
tmp/ exists -- unable to proceed with testing
```
The test would require at least a "user" interaction to click on a checkbox, is it possible ?

**Comment by Snuffleupagus** [comment]
> Yep tests are ok locally except that I get:
> 
> ```
> ### Running browser tests
> tmp/ exists -- unable to proceed with testing
> ```

That does sound like none of the ref-tests actually ran, though!?
Did you follow the "Generating reference images"-section, from the link above, *before* running the tests?
(And if necessary, manually removing the `test/tmp/` directory between test-runs may be necessary.)

> The test would require at least a "user" interaction to click on a checkbox, is it possible?

No, unfortunately nothing like that is supported.

**Comment by calixteman** [comment]
Yes, I made a `gulp makeref` before... but I've this error.
Anyway I removed `tmp` dir and then test ran fine.
The goal of this patch is to fix a printing issue after a user interaction... so I guess that currently there is no way to correctly test that.

**Comment by timvandermeij** [comment]
I'm confused here because we explicitly don't support printing AcroForms yet. We don't even render the annotation layer onto the final canvas that is printed, so this must rely on browser printing then. Could you share a before/after patch screenshot for comparison?

**Comment by timvandermeij** [comment]
We merged checkbox printing and I couldn't find anything wrong with the print back then. Do we still need to do anything here? If so, please indicate what this fixes with a screenshot.

**Pull request closed without merging**
