### PR TITLE
Update Puppeteer to version 6 (issue 12945)

### LINKED ISSUE #12945: Update Puppeteer to the latest version
Puppeteer was just updated, please see https://github.com/puppeteer/puppeteer/releases/tag/v6.0.0, hence we should update to the latest version ASAP (since that *might* help get rid of some intermittent failures in Google Chrome).

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Please see https://github.com/puppeteer/puppeteer/releases/tag/v6.0.0

Fixes #12945

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
This looks like another case where the sheer number of rendering changes is breaking the tests, since the size of the log files becomes too large.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good to me. Let's see how it goes!

/botio makeref

**Pull request merged**
