### PR TITLE
Use Int32Array instead of Uint32Array in FlateStream

### PR DESCRIPTION
**Pull request by marco-c**
SpiderMonkey is able to optimize Int32Array better than Uint32Array: https://bugzilla.mozilla.org/show_bug.cgi?id=750947

We've done the same in j2me.js: https://github.com/mozilla/j2me.js/issues/730

### CODE REVIEW

**Comment by timvandermeij** [comment]
Could you make a benchmark (see https://github.com/mozilla/pdf.js/wiki/Benchmarking-your-changes) to show by how much this PR improves the current situation?

**Comment by marco-c** [comment]
I've run a benchmark with the tracemonkey.pdf file:

browser | stat         | Count | Baseline(ms) | Current(ms) | +/- |    % 
------- | ------------ | ----- | ------------ | ----------- | --- | -----
Firefox | Overall      |   100 |           85 |          84 |  -1 | -0.92
Firefox | Page Request |   100 |            2 |           2 |   0 |  3.57
Firefox | Rendering    |   100 |           83 |          82 |  -1 | -1.10

I don't expect the patch to have a really noticeable effect.

**Comment by timvandermeij** [comment]
Nice optimization, thanks!

**Comment by CodingFabian** [comment]
There are plenty of places where we use Uint32Array https://github.com/mozilla/pdf.js/search?utf8=%E2%9C%93&q=uint32Array
most notably in image decoding. any chance it can be used elsewhere?

**Comment by timvandermeij** [comment]
@CodingFabian It can probably also be applied there, but that will have to verified on a case-by-case basis.

**Comment by CodingFabian** [comment]
@timvandermeij I tried to tickle @marco-c to do that :)

**Pull request merged**
