### PR TITLE
Correctly wait for the editor mode when double clicking on an annotation in integration tests

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
It should help to fix the issue in https://github.com/mozilla/pdf.js/pull/19161#issuecomment-2516882998

**Comment by calixteman** [comment]
It doesn't fix the issue I can't reproduce locally neither on Windows nor on Linux...
That said these changes don't hurt because they're good enough to at least fix some potential intermittents.

**Comment by calixteman** [comment]
I really don't understand why it's failing... :(
That said, I notice a `JavaScript error: http://127.0.0.1:55049/build/generic/build/pdf.mjs, line 12789: TypeError: can't access property "sendWithPromise", this.messageHandler is null`, @Snuffleupagus  does that ring a bell ?

**Comment by Snuffleupagus** [comment]
> That said, I notice a `JavaScript error: http://127.0.0.1:55049/build/generic/build/pdf.mjs, line 12789: TypeError: can't access property "sendWithPromise", this.messageHandler is null`, @Snuffleupagus does that ring a bell ?

That might suggest that something is trying access an API method *after* document has already been closed.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks.

**Pull request merged**
