### PR TITLE
Fixed a small typo in the italian translation

### PR DESCRIPTION
**Pull request by emilyalbini**
In "document_properties_mb", {{size_mb}} was instead {{size_kb}}.

screenshot at 21-25-26

### CODE REVIEW

**Comment by timvandermeij** [comment]
Looks good, but this also needs to be reported upstream to prevent accidentally reverting this with the next L10n update.

@yurydelendik (or someone else): Could you file an upstream issue for the L10n team before we merge this?

**Comment by Snuffleupagus** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1151093.

**Comment by timvandermeij** [comment]
@Snuffleupagus Thank you!

/botio-linux preview

**Comment by timvandermeij** [comment]
Thank you! The issue has already been fixed upstream too, so no worries there.

**Comment by pietroalbini** [comment]
:D

**Pull request merged**
