### PR TITLE
XFA - Try to figure out what's wrong with xfa reftests

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
Considering `firefox-xfa_issue13500-page1`: we really have a new intermittent here...

/botio test

**Comment by Snuffleupagus** [comment]
I looks like maybe the bots haven't been updated since https://github.com/mozilla/botio-files-pdfjs/pull/33 landed, which would probably explain why the `botio browsertest` command doesn't work.

**Comment by Snuffleupagus** [comment]
@calixteman Do we still need to keep this PR open?

**Pull request closed without merging**
