### PR TITLE
[Editor] Add the uiManager to the window object when testing

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]

**Comment by timvandermeij** [comment]
@calixteman Does this fix #18187?

**Comment by calixteman** [comment]
I'd say yes :).
I missed the mentioned bug... sorry about that.
That said we should really find a way to set some stuff very early to avoid to have to add some TESTING checks in the code.

**Comment by timvandermeij** [comment]
Great! Yes, we'll keep #17709 open to track the better way of doing this, but for now the current version should at least eliminate this intermittent.

**Pull request merged**
