### PR TITLE
Parse query string in using URLSearchParams

### PR DESCRIPTION
**Pull request by calixteman**
- I just noticed in reading the code that we parse that stuff when something exists in the web api;
 - see https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
> I just noticed in reading the code that we parse that stuff when something exists in the web api;

*For reference:* Note that this PDF.js code actually *pre-dates* the existence of the `URLSearchParams` functionality, which is why this code looks the way it does. In particular Safari were quite slow, comparatively, to implement `URLSearchParams` support.

If we're making these changes, shouldn't the following code be updated similar to `web/ui_utils.js` code?
https://github.com/mozilla/pdf.js/blob/85c6dd59cede2ffcfb77a574ddf43c7bf70fa438/test/resources/reftest-analyzer.js#L53-L63

**Comment by calixteman** [comment]
> 
> If we're making these changes, shouldn't the following code be updated similar to the `web/ui_utils.js` code?
> 
> https://github.com/mozilla/pdf.js/blob/85c6dd59cede2ffcfb77a574ddf43c7bf70fa438/test/resources/reftest-analyzer.js#L53-L63

In this code we split on `&` and `;` when `URLSearchParams` handles only `&` as separator, it's why I didn't change it.
Is this `;` here because it has been forgotten or do we really have some urls containing it ?

**Comment by Snuffleupagus** [comment]
> Is this `;` here because it has been forgotten or do we really have some urls containing it ?

As mentioned at the top of that file, that code was originally imported from Firefox and the "special" separator pattern thus came from the original file.
As far as I can find, we only have *a single* call-site that invoke the `reftest-analyzer` code and there we're only passing one hash-parameter; see https://github.com/mozilla/pdf.js/blob/de7cfed9e392eb3bfcb761ccea2c1f09cdf869aa/test/test.js#L231

Hence, as long as all tests and the `reftest-analyzer` itself works, I believe that it's *should* be safe to change that one as well.

**Review by Snuffleupagus — APPROVED** [review]

**Pull request merged**
