### PR TITLE
Refactor the test driver

### PR DESCRIPTION
**Pull request by timvandermeij**
Some time ago I attempted to make the test suite work with the SVG back-end. I then found that the current testing code is really unmaintainable at some points and figured that it had to be corrected before we have a chance of adding new functionality (such as a back-end or WebGL switch).

This patch refactors the test driver by making it more class-like and removing quite some complexity from hacks and unneeded functions. Not only does this make the code much more readable, it also allows us to extend the code in a cleaner way because we got rid of the `window.load` dependency, `innerHTML` usages and many callbacks. Not all callbacks have been removed because the remaining ones are not too invasive and this patch can be seen as a major first step in cleaning up the test driver.

@Snuffleupagus Would you be up for reviewing this? It is not as daunting as it might look at first sight because a lot of it is just moving code around. The other changes are largely the same as the other refactoring PRs we have done. Reviewing with `?w=1` helps a bit, especially for the third commit.

### CODE REVIEW

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by Snuffleupagus** [comment]
At this point it's still anecdotal evidence, but it appears that with these patches applied (and rebased to tip) the runtime of `browsertest` **increased** with approximately 1 minute for me.

**Comment by timvandermeij** [comment]
This last run was with one PDF file (specifically `pdfkit_compress.pdf`) changed to make sure that failures get detected. I have removed that commit now as it was only meant for a test.

**Comment by Snuffleupagus** [comment]
Review progress:
 - [ ] Refactor test slave
 - [ ] Clean up the test driver
 - [ ] Refactor test driver to be more class-like
 - [ ] Improve driver code structure
 - [ ] Implement an option to disable automatic scrolling

**Comment by timvandermeij** [comment]
@Snuffleupagus Thank you for the review! You made some good points and I have addressed all of them. I have also moved some changed from the fourth commit to the third commit, where they indeed belonged in the first place. I have run the tests locally and verified that the results are the same as before today's changes and I have run the tests here again too.

**Comment by Snuffleupagus** [comment]
Let's check that makeref-ing still works correctly before merging.

/botio makeref

**Comment by Snuffleupagus** [comment]
Since everything still appears to work, both on the bots and locally, let's do this!
Thank you for the patch!

**Pull request merged**
