### PR TITLE
[JS] Format all the fields if any when the document is open (bug 1766987)

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1766987.

### CODE REVIEW

**Review by Snuffleupagus — COMMENTED** [review]
Can we (easily) add a test-case for this behaviour?
E.g. would it work with an integration-test that just loads the affected document, and then checks that one of the affected fields is formatted correctly?

**Comment by calixteman** [comment]
I'll add an integration test.

**Review by Snuffleupagus — APPROVED** [review]
Thanks for fixing this, and for adding tests!

**Pull request merged**
