### PR TITLE
Convert the files in the `/src/core` folder to ES6 modules

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Depends on PR #8364.*

Please note that the `glyphlist.js` and `unicode.js` files are converted to CommonJS modules instead, since Babel cannot handle files that large and they are thus excluded from transpilation.

Much smaller diff with https://github.com/mozilla/pdf.js/pull/8284/files?w=1.

### CODE REVIEW

**Comment by yurydelendik** [comment]
Sorry, I did not catch this before but we need to use cjs paths e.g. '../shared/util.js'

**Comment by yurydelendik** [comment]
Blocked by #8285

**Review by yurydelendik — APPROVED** [review]
Looks good with fixing export section formatting at src/core/cff_parser.js

**Comment by yurydelendik** [comment]
I'm thinking we a hitting some performance issue on botio-linux/chrome with the patch. Let's try convert src/shared files in the separate PR.

**Comment by yurydelendik** [comment]
Also let's try larger timeout.

**Comment by Snuffleupagus** [comment]
> Also let's try larger timeout.

I've doubled all the timeout values, and also removed the `src/shared/` patch, let's see if that helps.

/botio test

**Comment by Snuffleupagus** [comment]
OK, once more with feeling; let's try a 10 minute timeout.

/botio-linux test

**Comment by Snuffleupagus** [comment]
I reverted the patch that increased the timeout values, since it unfortunately didn't seem help at all :-(

**Comment by Snuffleupagus** [comment]
Since Travis seem to be having problems, let's run linting once more just to check that there's no issue.

/botio-linux lint

**Comment by timvandermeij** [comment]
Hooray! 💥

**Pull request merged**
