### PR TITLE
Skip bogus `d1` operators in Type3-glyphs (issue 14953)

### LINKED ISSUE #14953: characters not displayed
Attach (recommended) or Link to PDF file here:

http://www.pragma-ade.com/general/manuals/xml-mkiv.pdf

Configuration:
- Web browser and its version: Firefox 100.
- Operating system and its version: Fedora 35.
- PDF.js version: the one that comes with web browser.
- Is a browser extension: yes.

Steps to reproduce the problem:
1. Open http://www.pragma-ade.com/general/manuals/xml-mkiv.pdf.
2. It’s on the first page, no text is displayed.

What is the expected behavior? (add screenshot)

right-fonts

What went wrong? (add screenshot)

no-fonts

### PR DESCRIPTION
**Pull request by Snuffleupagus**
In the `src/display/canvas.js` code the `d1` operator will be used to set the clipping region, and it obviously cannot be empty since that prevents the Type3-glyph from rendering.

Also, the patch removes an outdated comment; refer to PR #12718.

### CODE REVIEW

**Review by calixteman — APPROVED** [review]
LGTM.

**Comment by Snuffleupagus** [comment]
All of the font-rendering failures in Firefox on the Linux-bot should already be tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1770706, and the same applies to the `should correctly render PDFs in parallel` unit-test failure, hence those are completely unrelated to this PR.

**Pull request merged**
