### PR TITLE
Correct PostScript trigonometric operators

### PR DESCRIPTION
**Pull request by bungeman**
PDF 32000-1:2008 7.10.5.1 "Type 4 (PostScript Calculator) Functions" defers to the PostScript Language Reference for the description of these functions. The PostScript Language Reference, third edition chapter 8 "Operators" defines the `angle` type as a "number of degrees". Section 8.1 defines "angle `sin` real", "angle `cos` real", and "num den `atan` angle". The documentation for `atan` further states that it will return an angle in degrees between 0 and 360.

Handle these operators correctly in `PostScriptEvaluator.execute`. Convert the inputs to `sin` and `cos` from degrees to radians for use with `Math.sin` and `Math.cos`. Correctly pop two values from the stack for `atan`, use `Math.atan2`, and convert from radians to (positive) degrees.

### CODE REVIEW

**Comment by bungeman** [comment]
Added some reference PDFs. These PDFs contain a 256x256 bitmap with component color values of x,y,0 and a DeviceN color space with a Function which calculates the alternate color space components using the operators in question (with appropriate scaling). Before this change pdf.js draws these quite interestingly different from other PDF viewers. After this change pdf.js draws these similarly to other PDF viewers.

**Comment by bungeman** [comment]
For future reference, these PDFs were generated using a hack of Skia at https://skia-review.googlesource.com/c/skia/+/651756 .

**Comment by bungeman** [comment]
I notice that a number of test pdfs are actually `issueXXXX.pdf.link` style files. If it would make more sense, I could open an issue, attach these these reproducers to it (so they'd be uploaded as files in the issue tracker)  and then convert this change to use the link method instead of checking in the files directly. Let me know if this is preferable.

**Comment by calixteman** [comment]
I opened colorspace_atan.pdf: it looks a way better with your patch :).
But I noticed in either Acrobat or Chrome a small line in the top-right corner which is not rendered with pdf.js, do you know why ?

**Comment by calixteman** [comment]
The last computed value is `-1.4033418597069752e-14` which is very closed to 0.
It can be fixed with:
```
if (Math.abs(a) <= 1e-10) {
    a = 0;
} else if (a < 0) {
    a += 360;
}
```
Do you know what's the expected precision ?

**Comment by calixteman** [comment]
If I understand correctly the numbers should be represented 32-bit floating-point format so I suppose it could make sense to round the numbers pushed in the stack in using the float 32 precision (2 ** -23 iirc).

**Comment by bungeman** [comment]
Hmmm... even after sprinkling `Math.fround` all over it doesn't happen. The actual sampled values go from 0 to 255 which should then map to 0 to 1.0. 1.0 should have the same value as 0, so should be wrapped around. It seems most likely that we didn't get 1.0 to begin with as an input maybe? It looks like 1.0 should come in from `AlternateCS::getRgbBuffer` from the 255 value. Upon inspection it appears this does happen (I'm getting 1.0 there locally). Stepping through the function I see that we're not getting exactly 0 for `Math.sin(a * (Math.PI / 180))`. Re-arranging things to `Math.sin(a / 180 * Math.PI)` doesn't help. In the end, `Math.sin(2*Math.PI)` also isn't 0, so not much help there. However, since these are degrees and so rotations happen on an integer, changing to `Math.sin(a % 360 / 180 * Math.PI)` seems to work, since it keep everything perfectly regular. Have to make sure JavaScript's remainder is the right operator (do we want remainder or mod?).

**Comment by bungeman** [comment]
After a careful re-reading of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder#description it looks like the remainder operator does the right thing here.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
