### PR TITLE
Check that CIDFontType0 fonts does not actually contain OpenType font files (issue 6782)

### LINKED ISSUE #6782: Problems rendering the "Fedra Serif A Std Medium" font
I am using viewer.js (which in turn uses pdf.js) to render pdf documents in the browser. These documents are showing up fine with all fonts except the "Fedra Serif A Std Medium". While the uppercase characters for this font are showing fine, the lowercase characters are either missing or showing up as boxes depending on the browser used. Attached are the screenshots from chrome (Version 47.0.2526.106 m), IE 11 (v 11.0.9600.17031) & that showing the original text. 
invalidtext

Following is the console log from Chrome:
pdf.worker.js:224 Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
pdf.worker.js:232 Error: Not tracking location of CharStrings
pdf.worker.js:233     at error (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:233:17)
    at Object.CFFOffsetTracker_setEntryLocation [as setEntryLocation] (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21256:9)
    at Object.CFFCompiler_compile [as compile] (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21371:22)
    at Object.CFFFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:20224:28)
    at Object.Font (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:16998:11)
    at Object.PartialEvaluator_translateFont [as translateFont] (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:12514:14)
    at Object.PartialEvaluator_loadFont [as loadFont] (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11264:16)
    at handleSetFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11670:21)
    at next (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11809:22)
pdf.worker.js:224 Warning: Unsupported feature "unknown"
pdf.worker.js:224 Warning: Failed to compile font g_font_3
pdf.js:224 Warning: Unsupported feature "unknown"
pdf.js:224 Warning: Failed to load font "g_font_3": SyntaxError: Invalid font data in ArrayBuffer.
.
Following is the Console Log from IE:
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: viewerjs
HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
File: about:blank, Line: 1, Column: 1
HTML1405: Invalid character: U+0000 NULL. Null characters should not be used.
File: about:blank, Line: 1, Column: 14
HTML1507: Unexpected character: U+0000 NULL. Null characters should not be used.
File: about:blank, Line: 1, Column: 14
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: about:blank
SCRIPT1003: Expected ':'
File: compatibility.js, Line: 119, Column: 30
SCRIPT5007: Unable to get property 'namespaceURI' of undefined or null reference
File: viewerjs, Line: 75, Column: 283
SCRIPT438: Object doesn't support property or method 'forEach'
File: viewerjs, Line: 73, Column: 174
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Error: Not tracking location of CharStrings
   at error (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:233:5)
   at CFFOffsetTracker_setEntryLocation (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21256:9)
   at CFFCompiler_compile (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21371:7)
   at CFFFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:20224:7)
   at Font (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:16997:9)
   at PartialEvaluator_translateFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:12514:7)
   at PartialEvaluator_loadFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11263:9)
   at handleSetFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11670:9)
   at next (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11809:15)
Warning: Unsupported feature "unknown"
Warning: Unsupported feature "unknown"
Warning: Failed to compile font g_font_3
CSS3111: @font-face encountered unknown error.
File: wAAAAAAAALDAAAAAAAAAAAAAAAAAAABRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAFGAAAAAAAUAPYAAQAAAAAAAAAQAAAAAQAAAAAAAQAbABAAAQAAAAAAAgAHACsAAQAAAAAAAwAIADIAAQAAAAAABAAbADoAAQAAAAAABQAMAFUAAQAAAAAABgAAAGEAAQAAAAAABwAHAGEAAQAAAAAACAAHAGgAAQAAAAAACQAHAG8AAwABBAkAAAAgAHYAAwABBAkAAQA2AJYAAwABBAkAAgAOAMwAAwABBAkAAwAQANoAAwABBAkABAA2AOoAAwABBAkABQAYASAAAwABBAkABgAAATgAAwABBAkABwAOATgAAwABBAkACAAOAUYAAwABBAkACQAOAVRPcmlnaW5hbCBsaWNlbmNlRkFBQUNCK0ZlZHJhU2VyaWZBU3RkTWVkaXVtVW5rbm93bnVuaXF1ZUlERkFBQUNCK0ZlZHJhU2VyaWZBU3RkTWVkaXVtVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUARgBBAEEAQQBDAEIAKwBGAGUAZAByAGEAUwBlAHIAaQBmAEEAUwB0AGQATQBlAGQAaQB1AG0AVQBuAGsAbgBvAHcAbgB1AG4AaQBxAHUAZQBJAEQARgBBAEEAQQBDAEIAKwBGAGUAZAByAGEAUwBlAHIAaQBmAEEAUwB0AGQATQBlAGQAaQB1AG0AVgBlAHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Error: Not tracking location of CharStrings
   at error (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:233:5)
   at CFFOffsetTracker_setEntryLocation (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21256:9)
   at CFFCompiler_compile (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21371:7)
   at CFFFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:20224:7)
   at Font (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:16997:9)
   at PartialEvaluator_translateFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:12514:7)
   at PartialEvaluator_loadFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11263:9)
   at handleSetFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11670:9)
   at next (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11809:15)
Warning: Unsupported feature "unknown"
Warning: Failed to compile font g_font_3
Warning: Unsupported feature "unknown"
CSS3111: @font-face encountered unknown error.
File: wAAAAAAAALDAAAAAAAAAAAAAAAAAAABRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAFGAAAAAAAUAPYAAQAAAAAAAAAQAAAAAQAAAAAAAQAbABAAAQAAAAAAAgAHACsAAQAAAAAAAwAIADIAAQAAAAAABAAbADoAAQAAAAAABQAMAFUAAQAAAAAABgAAAGEAAQAAAAAABwAHAGEAAQAAAAAACAAHAGgAAQAAAAAACQAHAG8AAwABBAkAAAAgAHYAAwABBAkAAQA2AJYAAwABBAkAAgAOAMwAAwABBAkAAwAQANoAAwABBAkABAA2AOoAAwABBAkABQAYASAAAwABBAkABgAAATgAAwABBAkABwAOATgAAwABBAkACAAOAUYAAwABBAkACQAOAVRPcmlnaW5hbCBsaWNlbmNlRkFBQUNCK0ZlZHJhU2VyaWZBU3RkTWVkaXVtVW5rbm93bnVuaXF1ZUlERkFBQUNCK0ZlZHJhU2VyaWZBU3RkTWVkaXVtVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUARgBBAEEAQQBDAEIAKwBGAGUAZAByAGEAUwBlAHIAaQBmAEEAUwB0AGQATQBlAGQAaQB1AG0AVQBuAGsAbgBvAHcAbgB1AG4AaQBxAHUAZQBJAEQARgBBAEEAQQBDAEIAKwBGAGUAZAByAGEAUwBlAHIAaQBmAEEAUwB0AGQATQBlAGQAaQB1AG0AVgBlAHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

Urgent help will be greatly appreciated!
Thanks in advance!

### PR DESCRIPTION
**Pull request by Snuffleupagus**
_This patch follows a similar idea as PR #5756._

The patch is based on the nice debugging done by Brendan in the referenced issue https://github.com/mozilla/pdf.js/issues/6782#issuecomment-169111439.
A better way to handle this, and similar issues, would probably be to completely ignore what the PDF file claims about font type/subtype, and just check the actual data. But until that kind of rewrite happens, this patch should help.

Fixes #6782.

### CODE REVIEW

**Comment by timvandermeij** [comment]
r+ from me. I'll leave it to @brendandahl to merge this.

**Comment by brendandahl** [comment]
Thx!

**Pull request merged**
