### PR TITLE
Let `finishPaintTask` in pdf_page_view.js return a promise instead, to avoid having to throw in the `paintTask.promise` rejection handler, and don't reject the `PDFPageView_draw` promise when rendering is `cancelled`

### PR DESCRIPTION
**Pull request by Snuffleupagus**
As mentioned on IRC yesterday, we currently throw even when rendering is `cancelled`, which is annoying when the devtools are active. Furthermore, since `cancelled` isn't really an error, rejecting the `PDFPageView_draw` promise seems somewhat strange in that case.

*Perhaps marginally easier reviewing with https://github.com/mozilla/pdf.js/pull/7829/files?w=1.*

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/pdf.js/7829)

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@yurydelendik I realize that you're probably at (or travelling to) https://wiki.mozilla.org/All_Hands/2016_Hawaii right now. So if you don't have time to review this, would you mind if I redirect the review request to @timvandermeij instead?

**Comment by Snuffleupagus** [comment]
@yurydelendik Gentle review ping?

**Comment by Snuffleupagus** [comment]
@timvandermeij Since I'm not sure how much time Yury has for PDF.js, is this something that you feel comfortable reviewing? Please note that "no" is a perfectly valid answered here!

For some more context, the IRC discussion mentioned above: http://logs.glob.uno/?c=mozilla%23pdfjs&s=18+Nov+2016&e=18+Nov+2016#c54305.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for the patch!

**Comment by Snuffleupagus** [comment]
@timvandermeij Thanks so much for landing this; the throwing on `cancelled` was really annoying me!

**Pull request merged**
